### ISSUE TITLE
Error in gcc doc, arc builtins

### ISSUE THREAD

**Issue by calandoa** [foss-for-synopsys-dwc-arc-processors/toolchain#100]
There is a small error in the doc for builtin __builtin_arc_sr()

file: gcc/gcc/doc/extend.texi

> 
> __builtin_arc_sr (unsigned int auxr, unsigned int val)
> The first argument, auxv, is the address of an auxiliary register, the second argument, val, is a compile time constant to be written to the register. Generates:
> 
>           sr  auxr, [val]
> 

There is a mismatch between first and second argument. Correct doc should be: 

> __builtin_arc_sr (unsigned int val, unsigned int auxr)

**Comment by claziss** [comment]
Documentation [updated and corrected](https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/4aff2b8aae1c6a4a888eb5e2f0a7c6434a3ec472)

Thank you,
Claudiu
