### ISSUE TITLE
Compiling  __attribute__((naked)) functions automatically adds jump

### ISSUE THREAD

**Issue by DanielAW** [foss-for-synopsys-dwc-arc-processors/toolchain#104]
Hi,

I'm using the prebuild toolchain 2006.03 with the gcc 4.8.5. I want to compile a single instruction without any additional instructions added by the compiler. Every instruction I try to compile is followed by a `nop` and `j_s [blink]` instruction, see the following example:

* original source code
```
__attribute__((naked)) void 
test(void) { asm("mov r0, r1 \n"); }
```

* disassembly of the resulting object file using `objdump`
```
   0:	200a 0040           	mov	r0,r1
   4:	78e0                	nop_s
   6:	7ee0                	j_s	[blink]
```
How can I compile the instruction above without the "additional" `nop` and `j_s` instruction?

**Comment by claziss** [comment]
Hi,

The `nop_s` can be removed by passing an optimization level greater than zero to the compiler (e.g. `-O1`). As for the return, the compiler will always issue the return instruction.
If your intention is to write an ISR, then please use `interrupt` attribute, if your function never returns, then use `noreturn` attribute.

**Comment by DanielAW** [comment]
Hi, thanks for the quick reply. I already used `-O2` but additionally using `-msize-level=3` did the trick for me to remove the `nop`. 
But I still got the problem with the additional return. Adding `__attribute__((noreturn))` does still add the return instruction.

**Comment by claziss** [comment]
Hi, attribute `noreturn` will just improve your overall code [see](https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#Common-Function-Attributes). 

The `naked` behavior will always includes the return instruction. You cannot remove it.

**Comment by claziss** [comment]
On the other side, I see the Synopsys compiler does omit the return instruction. Mark it as a bug.

Thank you for bringing it up.

**Comment by DanielAW** [comment]
Ok, I also know that it works on ARM with the "naked" attribute.

On January 10, 2017 5:54:11 PM GMT+01:00, Claudiu Zissulescu <notifications@github.com> wrote:
>On the other side, I see the Synopsys compiler does omit the return
>instruction. Mark it as a bug.
>
>Thank you for bringing it up.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/issues/104#issuecomment-271630756

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by claziss** [comment]
Various tools are having different understanding of the `naked` attribute. Some of them are omitting the return value others not.

**Comment by DanielAW** [comment]
ok, good to know 👍

**Comment by DanielAW** [comment]
@claziss 
Can you show me in the compiler code code where this return instruction gets added? This should allow me to build a compiler without this behaviour as a workaround :-)

**Comment by claziss** [comment]
Fixed by this [commit](https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/e18f1496a2f405188c3a0ab64bc593a7e0c422ab).

**Comment by DanielAW** [comment]
I have to use gcc 4.8.5 for now, but it was no problem to adapt your patch to the older version of gcc. It works perfekt, thanks 👍
