### ISSUE TITLE
2016.09 linker error on previously working makefiles

### ISSUE THREAD

**Issue by coco21** [foss-for-synopsys-dwc-arc-processors/toolchain#105]
Hello,

Just installed latest 2016.09 toolchain and tried to build some of my tests files again (they're very simple).
Whatever I do I all the time get this error back

...
c:/arc_gnu/bin/../lib/gcc/arc-elf32/6.2.1/../../../../arc-elf32/lib/arcem/crt0.o: In function `__start':
crt0.s:(.text.__startup:0x34): undefined reference to `_impure_ptr'
crt0.s:(.text.__startup:0x68): undefined reference to `exit'
make: *** [D:/MyFolder/MyApp.elf] Error 1

What am I missing? Switching back to older 2016.09 RC release or even older one makes things work again.

Thanks Christophe

**Comment by coco21** [comment]
Let me add some traces here to better understand my problem.
I did two runs: once using 2014.12 and once using 2016.09 ARC GNU.
Using a very simple source file (fibonacci.c), specifying target CPU (arcem) and that's it.

I notice the gcc's configuration changed to --host=i686-w64-mingw32 whereas before it was --host=i686-pc-mingw32 but am not sure the problem is here.

Ok here we go, thanks for helping me out here, certainly something stupid I don't see here.

Christophe

**2014.12 build**

D:\TEMP>C:\_2014.12_arc_gnu\bin\arc-elf32-gcc.exe -v -mcpu=arcem fibonacci.c -o test_2014.elf
Using built-in specs.
COLLECT_GCC=C:\_2014.12_arc_gnu\bin\arc-elf32-gcc.exe
COLLECT_LTO_WRAPPER=c:/_2014.12_arc_gnu/bin/../libexec/gcc/arc-elf32/4.8.3/lto-wrapper.exe
Target: arc-elf32
Configured with: /home/akolesov/ws/arc-2014.12/unisrc-4.8/configure --target=arc-elf32 --with-cpu=arc700 --with-pkgversion='ARCompact/ARCv2 ISA elf32 toolchain 2014.12' --with-bugu
rl=http://solvnet.synopsys.com --enable-fast-install=N/A --with-endian=little --disable-werror --enable-languages=c,c++ --prefix=/home/akolesov/ws/arc-2014.12/toolchain/../release_
output/arc_gnu_2014.12_prebuilt_elf32_windows_install --with-headers=/home/akolesov/ws/arc-2014.12/unisrc-4.8/newlib/libc/include --host=i686-pc-mingw32 --build=x86_64-linux-gnu --
disable-sim --with-python=no LDFLAGS=-static
Thread model: single
gcc version 4.8.3 (ARCompact/ARCv2 ISA elf32 toolchain 2014.12)
COLLECT_GCC_OPTIONS='-v'  '-o' 'test_2014.elf' '-mcpu=ARCv2EM'
 c:/_2014.12_arc_gnu/bin/../libexec/gcc/arc-elf32/4.8.3/cc1.exe -quiet -v -imultilib em -iprefix c:\_2014.12_arc_gnu\bin\../lib/gcc/arc-elf32/4.8.3/ fibonacci.c -quiet -dumpbase fi
bonacci.c -mcpu=ARCv2EM -auxbase fibonacci -version -o D:\Users\schmid\AppData\Local\Temp\ccO7v6dT.s
GNU C (ARCompact/ARCv2 ISA elf32 toolchain 2014.12) version 4.8.3 (arc-elf32)
        compiled by GNU C version 4.4.6 20110731 (Fedora MinGW 4.4.6-4.el6), GMP version 5.1.3, MPFR version 3.1.2, MPC version 1.0.1
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
ignoring duplicate directory "c:/_2014.12_arc_gnu/lib/gcc/../../lib/gcc/arc-elf32/4.8.3/include"
ignoring duplicate directory "c:/_2014.12_arc_gnu/lib/gcc/../../lib/gcc/arc-elf32/4.8.3/include-fixed"
ignoring duplicate directory "c:/_2014.12_arc_gnu/lib/gcc/../../lib/gcc/arc-elf32/4.8.3/../../../../arc-elf32/sys-include"
ignoring duplicate directory "c:/_2014.12_arc_gnu/lib/gcc/../../lib/gcc/arc-elf32/4.8.3/../../../../arc-elf32/include"
#include "..." search starts here:
#include <...> search starts here:
 c:\_2014.12_arc_gnu\bin\../lib/gcc/arc-elf32/4.8.3/include
 c:\_2014.12_arc_gnu\bin\../lib/gcc/arc-elf32/4.8.3/include-fixed
 c:\_2014.12_arc_gnu\bin\../lib/gcc/arc-elf32/4.8.3/../../../../arc-elf32/sys-include
 c:\_2014.12_arc_gnu\bin\../lib/gcc/arc-elf32/4.8.3/../../../../arc-elf32/include
End of search list.
GNU C (ARCompact/ARCv2 ISA elf32 toolchain 2014.12) version 4.8.3 (arc-elf32)
        compiled by GNU C version 4.4.6 20110731 (Fedora MinGW 4.4.6-4.el6), GMP version 5.1.3, MPFR version 3.1.2, MPC version 1.0.1
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
Compiler executable checksum: 8d94e95993b7f1ad1ef7778822e3fd27
COLLECT_GCC_OPTIONS='-v'  '-o' 'test_2014.elf' '-mcpu=ARCv2EM'
 c:/_2014.12_arc_gnu/bin/../lib/gcc/arc-elf32/4.8.3/../../../../arc-elf32/bin/as.exe -v -mEM -o D:\Users\schmid\AppData\Local\Temp\cczO9azY.o D:\Users\schmid\AppData\Local\Temp\ccO
7v6dT.s
GNU assembler version 2.23.2 (arc-elf32) using BFD version (ARCompact/ARCv2 ISA elf32 toolchain 2014.12) 2.23.2
COMPILER_PATH=c:/_2014.12_arc_gnu/bin/../libexec/gcc/arc-elf32/4.8.3/;c:/_2014.12_arc_gnu/bin/../libexec/gcc/;c:/_2014.12_arc_gnu/bin/../lib/gcc/arc-elf32/4.8.3/../../../../arc-elf
32/bin/
LIBRARY_PATH=c:/_2014.12_arc_gnu/bin/../lib/gcc/arc-elf32/4.8.3/em/;c:/_2014.12_arc_gnu/bin/../lib/gcc/arc-elf32/4.8.3/../../../../arc-elf32/lib/em/;c:/_2014.12_arc_gnu/bin/../lib/
gcc/arc-elf32/4.8.3/;c:/_2014.12_arc_gnu/bin/../lib/gcc/;c:/_2014.12_arc_gnu/bin/../lib/gcc/arc-elf32/4.8.3/../../../../arc-elf32/lib/
COLLECT_GCC_OPTIONS='-v'  '-o' 'test_2014.elf' '-mcpu=ARCv2EM'
 c:/_2014.12_arc_gnu/bin/../libexec/gcc/arc-elf32/4.8.3/collect2.exe -o test_2014.elf c:/_2014.12_arc_gnu/bin/../lib/gcc/arc-elf32/4.8.3/../../../../arc-elf32/lib/em/crt0.o c:/_201
4.12_arc_gnu/bin/../lib/gcc/arc-elf32/4.8.3/em/crti.o c:/_2014.12_arc_gnu/bin/../lib/gcc/arc-elf32/4.8.3/em/crtbegin.o -Lc:/_2014.12_arc_gnu/bin/../lib/gcc/arc-elf32/4.8.3/em -Lc:/
_2014.12_arc_gnu/bin/../lib/gcc/arc-elf32/4.8.3/../../../../arc-elf32/lib/em -Lc:/_2014.12_arc_gnu/bin/../lib/gcc/arc-elf32/4.8.3 -Lc:/_2014.12_arc_gnu/bin/../lib/gcc -Lc:/_2014.12
_arc_gnu/bin/../lib/gcc/arc-elf32/4.8.3/../../../../arc-elf32/lib D:\Users\schmid\AppData\Local\Temp\cczO9azY.o -lgcc -lc -lgcc c:/_2014.12_arc_gnu/bin/../lib/gcc/arc-elf32/4.8.3/e
m/crtend.o c:/_2014.12_arc_gnu/bin/../lib/gcc/arc-elf32/4.8.3/em/crtn.o

D:\TEMP>

**2016.09 build**

D:\TEMP>arc-elf32-gcc.exe -v -mcpu=arcem fibonacci.c -o test_2016.elf
Using built-in specs.
COLLECT_GCC=arc-elf32-gcc.exe
COLLECT_LTO_WRAPPER=c:/arc_gnu/bin/../libexec/gcc/arc-elf32/6.2.1/lto-wrapper.exe
Target: arc-elf32
Configured with: /home/akolesov/pub/jenkins_root/akolesov-lab/workspace/gnu_release/gcc/configure --target=arc-elf32 --with-cpu=arc700 --with-pkgversion='ARCompact/ARCv2 ISA elf32
toolchain 2016.09' --with-bugurl=https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/issues --enable-fast-install=N/A --with-endian=little --disable-werror --enable-l
anguages=c,c++ --disable-shared --disable-tls --disable-threads --prefix=/home/akolesov/pub/jenkins_root/akolesov-lab/workspace/gnu_release/toolchain/../release_output/arc_gnu_2016
.09_prebuilt_elf32_le_win_install --with-gnu-as --with-gnu-ld --host=i686-w64-mingw32 --with-python=no --with-newlib --with-headers=/home/akolesov/pub/jenkins_root/akolesov-lab/wor
kspace/gnu_release/toolchain/../release_output/arc_gnu_2016.09_prebuilt_elf32_le_win_install/arc-elf32/include --with-libs=/home/akolesov/pub/jenkins_root/akolesov-lab/workspace/gn
u_release/toolchain/../release_output/arc_gnu_2016.09_prebuilt_elf32_le_win_install/arc-elf32/lib --disable-libstdcxx-pch 'CFLAGS_FOR_TARGET=-ffunction-sections -fdata-sections '
Thread model: single
gcc version 6.2.1 20160824 (ARCompact/ARCv2 ISA elf32 toolchain 2016.09)
COLLECT_GCC_OPTIONS='-v' '-mcpu=arcem' '-o' 'test_2016.elf'
 c:/arc_gnu/bin/../libexec/gcc/arc-elf32/6.2.1/cc1.exe -quiet -v -imultilib arcem -iprefix c:\arc_gnu\bin\../lib/gcc/arc-elf32/6.2.1/ fibonacci.c -quiet -dumpbase fibonacci.c -mcpu
=arcem -auxbase fibonacci -version -o D:\Users\schmid\AppData\Local\Temp\cc0FmaNB.s
GNU C11 (ARCompact/ARCv2 ISA elf32 toolchain 2016.09) version 6.2.1 20160824 (arc-elf32)
        compiled by GNU C version 4.9.2 20141030 (Fedora MinGW 4.9.2-1.el6), GMP version 6.1.1, MPFR version 3.1.4, MPC version 1.0.3, isl version none
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
ignoring duplicate directory "c:/arc_gnu/lib/gcc/../../lib/gcc/arc-elf32/6.2.1/include"
ignoring duplicate directory "c:/arc_gnu/lib/gcc/../../lib/gcc/arc-elf32/6.2.1/include-fixed"
ignoring duplicate directory "c:/arc_gnu/lib/gcc/../../lib/gcc/arc-elf32/6.2.1/../../../../arc-elf32/sys-include"
ignoring duplicate directory "c:/arc_gnu/lib/gcc/../../lib/gcc/arc-elf32/6.2.1/../../../../arc-elf32/include"
#include "..." search starts here:
#include <...> search starts here:
 c:\arc_gnu\bin\../lib/gcc/arc-elf32/6.2.1/include
 c:\arc_gnu\bin\../lib/gcc/arc-elf32/6.2.1/include-fixed
 c:\arc_gnu\bin\../lib/gcc/arc-elf32/6.2.1/../../../../arc-elf32/sys-include
 c:\arc_gnu\bin\../lib/gcc/arc-elf32/6.2.1/../../../../arc-elf32/include
End of search list.
GNU C11 (ARCompact/ARCv2 ISA elf32 toolchain 2016.09) version 6.2.1 20160824 (arc-elf32)
        compiled by GNU C version 4.9.2 20141030 (Fedora MinGW 4.9.2-1.el6), GMP version 6.1.1, MPFR version 3.1.4, MPC version 1.0.3, isl version none
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
Compiler executable checksum: a33c1ec382b3884c84fccfe51a1b2364
fibonacci.c: In function 'main':
fibonacci.c:28:29: warning: implicit declaration of function 'atoi' [-Wimplicit-function-declaration]
     int num = (argc >= 2) ? atoi(argv[1]) : 38;
                             ^~~~
COLLECT_GCC_OPTIONS='-v' '-mcpu=arcem' '-o' 'test_2016.elf'
 c:/arc_gnu/bin/../lib/gcc/arc-elf32/6.2.1/../../../../arc-elf32/bin/as.exe -v -mcpu=arcem -mcode-density -o D:\Users\schmid\AppData\Local\Temp\ccWqrzmL.o D:\Users\schmid\AppData\L
ocal\Temp\cc0FmaNB.s
GNU assembler version 2.27.51 (arc-elf32) using BFD version (ARCompact/ARCv2 ISA elf32 toolchain 2016.09) 2.27.51.20161017
COMPILER_PATH=c:/arc_gnu/bin/../libexec/gcc/arc-elf32/6.2.1/;c:/arc_gnu/bin/../libexec/gcc/;c:/arc_gnu/bin/../lib/gcc/arc-elf32/6.2.1/../../../../arc-elf32/bin/
LIBRARY_PATH=c:/arc_gnu/bin/../lib/gcc/arc-elf32/6.2.1/arcem/;c:/arc_gnu/bin/../lib/gcc/arc-elf32/6.2.1/../../../../arc-elf32/lib/arcem/;c:/arc_gnu/bin/../lib/gcc/arc-elf32/6.2.1/;
c:/arc_gnu/bin/../lib/gcc/;c:/arc_gnu/bin/../lib/gcc/arc-elf32/6.2.1/../../../../arc-elf32/lib/
COLLECT_GCC_OPTIONS='-v' '-mcpu=arcem' '-o' 'test_2016.elf'
 c:/arc_gnu/bin/../libexec/gcc/arc-elf32/6.2.1/collect2.exe -plugin c:/arc_gnu/bin/../libexec/gcc/arc-elf32/6.2.1/liblto_plugin-0.dll -plugin-opt=c:/arc_gnu/bin/../libexec/gcc/arc-
elf32/6.2.1/lto-wrapper.exe -plugin-opt=-fresolution=D:\Users\schmid\AppData\Local\Temp\ccPtQtb6.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc -o test_2016.el
f c:/arc_gnu/bin/../lib/gcc/arc-elf32/6.2.1/../../../../arc-elf32/lib/arcem/crt0.o c:/arc_gnu/bin/../lib/gcc/arc-elf32/6.2.1/arcem/crti.o c:/arc_gnu/bin/../lib/gcc/arc-elf32/6.2.1/
arcem/crttls.o c:/arc_gnu/bin/../lib/gcc/arc-elf32/6.2.1/arcem/crtbegin.o -Lc:/arc_gnu/bin/../lib/gcc/arc-elf32/6.2.1/arcem -Lc:/arc_gnu/bin/../lib/gcc/arc-elf32/6.2.1/../../../../
arc-elf32/lib/arcem -Lc:/arc_gnu/bin/../lib/gcc/arc-elf32/6.2.1 -Lc:/arc_gnu/bin/../lib/gcc -Lc:/arc_gnu/bin/../lib/gcc/arc-elf32/6.2.1/../../../../arc-elf32/lib D:\Users\schmid\Ap
pData\Local\Temp\ccWqrzmL.o -lgcc -lgcc c:/arc_gnu/bin/../lib/gcc/arc-elf32/6.2.1/arcem/crtend.o c:/arc_gnu/bin/../lib/gcc/arc-elf32/6.2.1/arcem/crtn.o
c:/arc_gnu/bin/../lib/gcc/arc-elf32/6.2.1/../../../../arc-elf32/lib/arcem/crt0.o: In function `__start':
crt0.S:(.text.__startup+0x34): undefined reference to `_impure_ptr'
crt0.S:(.text.__startup+0x68): undefined reference to `exit'
D:\Users\schmid\AppData\Local\Temp\ccWqrzmL.o: In function `main':
fibonacci.c:(.text+0x78): undefined reference to `atoi'
fibonacci.c:(.text+0x90): undefined reference to `printf'
fibonacci.c:(.text+0xb0): undefined reference to `printf'
fibonacci.c:(.text+0xd0): undefined reference to `puts'
collect2.exe: error: ld returned 1 exit status

D:\TEMP>

**Comment by anthony-kolesov** [comment]
Hi Christoper,

It seems your test case for 2016.09 doesn't use `--specs=` option, which is required in this version. You should user nsim.specs for nSIM simulation and nosys.specs for hardware targets. More info here: https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/wiki/Building-a-baremetal-application.

However it looks like that you mentioned that the same test case worked for 2016.09-RC1? Specs option was required for that RC as well.

**Comment by coco21** [comment]
Hi Anthony,

Great it helped! We can close this, best regards Christophe

**Comment by coco21** [comment]
Ok have another question. We plan to use latest ARC GNU for baremetal application dev, no underlying OS planned but more of a super-loop type.

Now using option --specs=nosys.specs, are there things I shall be aware or problems we may encounter vs. if I simply would use e.g. 2014.12 version of ARC GNU? Will try to have a look into libnosys and functions being exported there.

Thanks Christophe

**Comment by anthony-kolesov** [comment]
Hi Chris,

Strictly speaking, specs=nsim.specs is equivalent to what was default in the 2014.12 toolchain. So to have maximum compatibility you can use nsim.specs. What nosys.specs does - it removes code specific to nSIM GNU IO hostlink, so system-specific functions, like write(), open(), etc are empty dummies or not defined at all, while in nsim.specs and 2014.12 those functions to software exceptions, which should be handled by nSIM. On hardware there shouldn't be any big difference. There also shouldn't be any problem if your application doesn't use those functions.

There is one notorious issue, which might not be obvious - exit() function in 2014.12 and nsim.specs uses `flag 1` instruction so that processor actually halts. But in nosys.specs exit() is an infinite loop, therefore applications that try to use it (if main() returns, then exit() will be called as well!), will get stuck in a loop, instead of halting. This shouldn't be the problem if your main() never returns, if code doesn't call exit(). IIRC abort() might call exit(), but I'm not sure. 

In theory libnsim.a and libnosys.a (which are use by respective .specs files) contain implementation of system-specific functions of libc (as I've mentioned those are write(), read(), open(), etc). You can make your own custom implementation of this library, specific to your board, so that, for example, printf(stdout) will print to UART, scanf(stdin) would read from UART, etc.

**Comment by coco21** [comment]
Hi Anthony,

Ok that pretty well clarifies things here, understand now better.

Let me keep this request open for a while if you don't mind, maybe I come back with more questions as my investigations move forward.

Thanks much so far Chris

**Comment by coco21** [comment]
Hello Anthony,

In parallel I work on another topic that uses compile and runtime generated GCC profiling datas (.gcno and .gcna). I understand in order to get .gcna properly generated on of the prerequisites is to properly return from main() function or call the exit() function. I am wondering if using -specs=nosys.specs we may get in trouble here - so far I am able to create the compile time .gcno (easy, simply using -fprofile-arcs and -ftest-coverage options of GCC). But for the .gcna I am not able to obtain it yet - I run the compiled code on a simulator. Any advise / input from your side welcome.

Thanks Christophe

**Comment by anthony-kolesov** [comment]
Hi Christopher,

nonsys.specs will not work for profiling. .gcda file is generated by the application itself, profiling code calls write() and open(), and as I've mentioned nosys.specs has stub implementations of those. You need to compile application with nsim.specs, run it on nSIM with `nsim_emt` property set to on (aka "enable nSIM GNU IO hostlink") - application will generate .gcda files:
```
$ arc-elf32-gcc -mcpu=hs38 -coverage --specs=nsim.specs -o test test.c

$ ls -1
hs38_full.tcf
test
test.c
test.gcno

$ nsimdrv -tcf hs38_full.tcf -on nsim_emt test
hello world
func1
func2

$ ls -1
hs38_full.tcf
test
test.c
test.gcda
test.gcno

$ arc-elf32-gcov -f test.gcno
Function 'main'
Lines executed:100.00% of 4

Function 'func2'
Lines executed:100.00% of 3

Function 'func1'
Lines executed:100.00% of 4

File 'test.c'
Lines executed:100.00% of 11
Creating 'test.c.gcov'
```

**Comment by coco21** [comment]
Hi Anthony,

Ok got it and makes sense, thanks.
Question: do I absolutely need nSIM as simulator basis? We run alternate simulaion technology from Imperas.

Thanks Christophe

**Comment by anthony-kolesov** [comment]
You can do this on Imperas if their simulator implements GNU IO hostlink (I don't know if they do). This is a relatively simple feature, because at the high level simulator should just intercept SWI exceptions and handle them internally. All of the arguments are passed as normal function arguments via registers, as with standard syscall.

**Comment by coco21** [comment]
Who generates the .gcda, the simulator engine and/or perhaps the debugger engine I suppose?

**Comment by anthony-kolesov** [comment]
Debugger has nothing to do with debugger. File is created by the application itself. In cae of simulators that means that simulator hostlink does this on behalf of application, by interepting its syscalls.

**Comment by claziss** [comment]
Hi Chris,
You can see [here](https://github.com/foss-for-synopsys-dwc-arc-processors/newlib/blob/arc-2016.09/libgloss/arc/mcount.c#L380) how the newlib is writing the profiling info to a file.  Thus, if your simulator can read/write from/to a file, then you should be fine. Otherwise, you need to investigate how syscalls are implemented by your simulator.

A very simple experiment is to make a program that writes/reads to/from a file, and observe if it has the desired behavior. Anyhow, the providers of your simulator tech should give you more info if your sim supports GNU or not.

**Comment by anthony-kolesov** [comment]
Hi Chris,

Any more questions on this topic? Can I close this issue?
