### ISSUE TITLE
Toolchain Build fails on Arch Linux

### ISSUE THREAD

**Issue by eugenelet** [foss-for-synopsys-dwc-arc-processors/toolchain#109]
Hello,

I've used both methods to get the toolchain as proposed in the tutorial provided which are through git and through the complete tarball.

Building works fine until this part:
```
/home/gene/Documents/Si2/ARC_Contest/arc_gnu_2016.09_sources/INSTALL/arc-elf32/bin/as: unrecognized option '--64'
make[1]: *** [Makefile:2502: build/version.o] Error 1
```
It has something to do with the binary file "as" which is provided. I've got all of the prerequisite packages 
`texinfo byacc flex libncurses5-dev texlive build-essential git wget`
except
`libexpat1-dev zlib1g-dev`
which I can't find a suitable package for arch linux, not sure if has anything to do with that error.

The following is the stdout generated by ./build-all
```
Checking out GIT trees ...
	Downloading external dependencies...
START ELF32: Tue 14 Feb 17:19:00 CST 2017
Installing in /home/gene/Documents/Si2/ARC_Contest/toolchain_bak/arc_gnu/INSTALL
Building binutils ...
  configuring...
  building...
  installing...
  generating PDF documentation...
Building gcc-stage1 ...
  configuring...
  building...
ERROR: failed while building.
See `/home/gene/Documents/Si2/ARC_Contest/toolchain_bak/arc_gnu/logs/elf32-build-2017-02-14-0919.log' for details.
ERROR: arc-elf32- tool chain build failed.
```
What am I missing? 

Thanks,
Eugene

**Comment by anthony-kolesov** [comment]
Option `--64` is x86 option, not for ARC, hence build fails. I'm not sure though why would this happen though. Could you send me your `elf32-build-2017-02-14-0919.log` at Anton.Kolesov (at) synopsys.com?

**Comment by eugenelet** [comment]
Hi Anthony,

Sent you my log, thanks for helping!

Eugene

**Comment by anthony-kolesov** [comment]
Hi Eugene,

Please clean up the PATH variable: remove the `::` in the middle and `:` in the beginning - this effectively adds current working directory to the PATH, which confuses configure and make tools. Thus you get this error.

Anton

**Comment by eugenelet** [comment]
Hi Anton,

Build works perfectly now, thanks a lot! I've this new error regarding
generating tex file. I'll attach my log here. I assume there's something
wrong with the library I'm using. Thank you!

Eugene​
 all-build-2017-02-15-1408.log
<https://drive.google.com/file/d/0B_6MjOAm5IOCWFV5MDMtRGZIMk0/view?usp=drive_web>
​​
 elf32-build-2017-02-15-1408.log
<https://drive.google.com/file/d/0B_6MjOAm5IOCTWxTYXBPa1lHenc/view?usp=drive_web>
​

**Comment by anthony-kolesov** [comment]
Hi Eugene,

I cannot download those files - access to Google Drive is blocked in Synopsys for security reasons.

If you don't need GNU toolchain documentation, then you can just pass `--no-pdf` to skip the step. There are a lot of problems with Texinfo on various systems and with it's various versions. Since internally we don't test with Arch Linux, it is possible that it has some specific problem, maybe a missing font package.

Anton

**Comment by eugenelet** [comment]
Hi Anton,

Working like a charm now, thanks a lot!

Eugene
