### ISSUE TITLE
Automatic Overlay Manager (AOM), register coloring

### ISSUE THREAD

**Issue by coco21** [foss-for-synopsys-dwc-arc-processors/toolchain#110]
Hello,

AOM exists on MetaWare IDE based toolchain.
Does ARC GNU provides a similar implementation here? I was thinking about a AOM for RAM.

Second point: does ARC GNU provides support for register coloring?

Thanks Christophe

**Comment by fbedard** [comment]
Hi Chris,

Regarding AOM feature, it is not supported by GNU Toolchain.  Support is limited to MWDT.  

Thanks,

Francois

**Comment by claziss** [comment]
Hi,
I suppose the register coloring refers to ARM's iterative recompilation technique that aim to obtain better size figures. The answer is no, GNU doesn't support this feature. However, you can use lto to minimize size figure for an app.

Or, another technique, which I successfully experimented, is to profile your application using a number of option combination, then you can extract a custom optimization setting per function to obtain the minimum application size (i.e., each function will have its own unique set of option combination which will provide the minimum size settings).

Best.

**Comment by coco21** [comment]
Hi François, Claudiu,
That answers my questions, perfect, thanks.
Christophe
