### ISSUE TITLE
Error on compiling using gcc

### ISSUE THREAD

**Issue by eugenelet** [foss-for-synopsys-dwc-arc-processors/toolchain#111]
Hello,

I'm trying to compile a simple c code using arc-elf32-gcc, but I can't get it to work. Here's the command I used:
`arc-elf32-gcc -g -o simple simple.c`

and the error message I got:
```
/home/gene/Documents/Si2/ARC_Contest/arc_gnu_2016.09_sources/INSTALL/lib/gcc/arc-elf32/6.2.1/../../../../arc-elf32/lib/arc700/crt0.o: In function `__start':
crt0.S:(.text+0x34): undefined reference to `_impure_ptr'
crt0.S:(.text+0x60): undefined reference to `exit'
collect2: error: ld returned 1 exit status
```

Thanks!

Eugene

**Comment by anthony-kolesov** [comment]
This is described in [README](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain#using-nsim-simulator-to-run-bare-metal-arc-applications).

And in [FAQ](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/wiki/Frequently-Asked-Questions):

- **Q: Linker fails with error: _undefined reference to `_exit'_. Among other
  possible functions are also _sbrk, _write, _close, _lseek, _read, _fstat,
  _isatty.**

  A: Function `_exit` is not provided by the libc itself, but must be provided
  by the libgloss, which is basically a BSP (board support package). Currently
  two libgloss implementations are provided for ARC: generic libnosys and
  libnsim which implements nSIM IO hostlink. In general libnosys is more
  suitable for hardware targets that doesn't have hostlink support, however
  libnsim has a distinct advantage that on exit from application and in case of
  many errors it will halt the core, while libnosys will cause it to infinitely
  loop on one place. To use libnsim, pass option `--specs=nsim.specs` to gcc at
  link stage. If you are a chip or board developer, then it is likely that you
  would want to implement libgloss specific to your hardware.

**Comment by eugenelet** [comment]
Hi Anton,

I've 2 questions:
1. is libnsim just for simulation? As I'm planning to program the executable file into my board.
2.  

> then it is likely that you would want to implement libgloss specific to your hardware


How do I implement libgloss?

Eugene

**Comment by anthony-kolesov** [comment]
libnsim is mostly for simulation, because it implements some system calls that are handled by the simulator hostlink, but this is not handled on boards.. For boards it is better to use libnosys,specs - it provides only stub implementation of those functions.

To provide libgloss implementation specific to your board, you'd need to look at the sources of existing implementations and implementing several system calls and probably provide a linker script for specific memory map. For example see item 6 of question 6 in newlib FAQ: https://sourceware.org/newlib/faq.html#q6 . More information, probably, can be found in newlib documentation.

**Comment by eugenelet** [comment]
Hi Anton,

Thanks for the information! 
So in order to get it working for my EMSK, I'll compile it with `--specs=nosys.specs` , am I right?

Eugene

**Comment by anthony-kolesov** [comment]
Yes.

For EMSK you can also look at [embARC](https://www.embarc.org/). It includes implementation of some of the system calls.

**Comment by eugenelet** [comment]
Hi Anton,

Okay, will look into it, thanks for helping! :)

Eugene
