### ISSUE TITLE
Building ARC toolchain

### ISSUE THREAD

**Issue by ekromskoy** [foss-for-synopsys-dwc-arc-processors/toolchain#112]
Hello,

I am trying to compile toolchain from source tarball downloaded from this site. Every time I get error related to ptrace.h

/work/arc_gnu/arc_gnu_2016.03_sources/gdb/gdb/gdbserver/linux-arc-low.c:476:17: error: ‘PTRACE_GET_THREAD_AREA’ undeclared (first use in this function)

This time I have it for gdbserver because now I use --no-native-gdb option to build-all.sh script. 

Previously I got same error for native-gdb, that was reason I disabled it. 
/work/arc_gnu/arc_gnu_2016.03_sources/gdb/gdb/arc-linux-nat.c: In function ‘ps_get_thread_area’:
/work/arc_gnu/arc_gnu_2016.03_sources/gdb/gdb/arc-linux-nat.c:216:17: error: ‘PTRACE_GET_THREAD_AREA’ undeclared (first use in this function)

Should I supply any particular option to build-all.sh? What place to check?
Full command line is:

./build-all.sh --no-auto-checkout --no-auto-pull --no-native-gdb --install-dir /opt/arc --uclibc-defconfig tablo_defconfig

It build almost everything and stop at gdb. Same error either with sources 2016.03 and 2016.09; linux sources I have kernel 3.12 with some our internal modifications.  

Thank you,
Ed

**Comment by vineetgarc** [comment]
Your 3.12 kernel: arch/arc/include/uapi/asm/ptrace.h is missing 
define PTRACE_GET_THREAD_AREA	25

However even if you fix it, the system will nto likely be usable anyways. The 3.12 kernel is ABI v3, while 
the current tools are ABI v4. So you shoudl consider upgrading.

However, if you must use the old kernel, then as a a hack 

arch/arc/include/uapi/asm/elf.h
-#define EF_ARC_OSABI_CURRENT   0x00000300   /* v3 (no legacy syscalls) */
+#define EF_ARC_OSABI_CURRENT   0x00000400

Thing is current tools only support ABIv4 but you seem to be building for ARCompact where there is no functional change in v3 -> v4
For more details on topic please see : https://github.com/foss-for-synopsys-dwc-arc-processors/linux/wiki/ARC-Linux-Syscall-ABI-Compatibility

**Comment by vineetgarc** [comment]
BTW the stable 3.12 kernel (3.12.70) already has the PTRACE_GET_THREAD_AREA backported
------------->
commit 70e52877b68404f462227167ab1c4549e53865fc
Author: Anton Kolesov <Anton.Kolesov@synopsys.com>
Date:   Fri Jun 20 20:28:39 2014 +0400

    ARC: Implement ptrace(PTRACE_GET_THREAD_AREA)
    
    commit a4b6cb735b25aa84a462a1985e3e43bebaf5beb4 upstream.
    
    This patch adds implementation of GET_THREAD_AREA ptrace request type. This
    is required by GDB to debug NPTL applications.
    
    Signed-off-by: Anton Kolesov <Anton.Kolesov@synopsys.com>
    Signed-off-by: Vineet Gupta <vgupta@synopsys.com>
    Signed-off-by: Jiri Slaby <jslaby@suse.cz>

**Comment by ekromskoy** [comment]
Hi Vineet,

Do you have any link where I can download mentioned stable 3.12 kernel (3.12.70)? All I can find here is 3.18. I have 3.12 kernel which is tailored to our SoC platform. I think that was complete parallel development and not synced up with ARC stable kernel. This is one of the reasons I have to stick with this old kernel. 

Thank you for information you provided and your support.

Cheers,
Ed

**Comment by vineetgarc** [comment]
Hi Ed,
We don't do any active linux kernel development on github anymore. Everything is upstream. The stable 3.12 I was referring to is at
git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git
specifically the linux-3.12.y branch which already includes ARC support.
Please use that as baseline for your out-of-tree platform code.

We backport any relevant bug fixes to "stable" LTS kernels hence it is advisable to use the above as baseline.
-Vineet

**Comment by ekromskoy** [comment]
Hi Vineet

Thank you, downloading kernel from kernel.org. Yeah, since it's internal thing and SoC has no much interest to public, our kernel is a bit messy. I will try to line it up with stable one.

Are you saying there is a big probability that 4.10 (latest stable) kernel could be relatively easily compiled and run on ARC based system these days? 

Thank you,
Ed

**Comment by vineetgarc** [comment]
Both 3.12 and 4.10 will compile equally well and run on ARC. Newer kernel has more features and optimizations (both ARC specific and generic). e.g. 3.12 doesn't support the newer ARCv2 HS38 processors and related boards. It is in general better to work with latest kernels - but that is up to you. Vendors have various reasons to work with old kernels (lack of board support upstream, drivers not compatible with newer kernels etc - so try to upstream ur platform support if you can). 

FWIW, In your case, remember my original point that 3.12.x is not compatible with latest GNU tools release - u need to patch kernel elf.h neverthless to downgrade to ABIv3. I tried to backport ABI v4 support but that was rejected by GKH !
