### ISSUE TITLE
Metware and GCC linker compatibility 

### ISSUE THREAD

**Issue by bravindr** [foss-for-synopsys-dwc-arc-processors/toolchain#114]
When trying to link a library created by Metaware (testlib,o) with GCC, the linker shows the following error.

/nfs/site/disks/ndg_socarch_01/tools/arc-gcc/arc_gnu_2016.09-rc2_prebuilt_elf32_le_linux_install/bin/arc-elf32-gcc -mcpu=quarkse2_em -T hwconfig/example_gcc -specs=nsim.specs   -o test.out testlib.o test.c
/nfs/site/disks/ndg_socarch_01/tools/arc-gcc/arc_gnu_2016.09-rc2_prebuilt_elf32_le_linux_install/bin/../lib/gcc/arc-elf32/6.2.1/../../../../arc-elf32/bin/ld: testlib.o: uses different e_flags (0x0) fields than previous modules (0x5)

However, this error is not shown when using -mcpu=arcem. qurakse2_em was added as an extension to the arcem in 9.2016 GCC release.

**Comment by bravindr** [comment]
I need to correct this. The error occurs in both cases. -mcpu=arcem and -mcpu=quarkse2_em

**Comment by claziss** [comment]
As far as I can see, that is an warning. The final object should be never the less emitted.
Please, let me otherwise.

**Comment by claziss** [comment]
As there is no comments on this thread I'll close it.
