### ISSUE TITLE
-fplugin support on Windows host

### ISSUE THREAD

**Issue by coco21** [foss-for-synopsys-dwc-arc-processors/toolchain#115]
Hello,

Come back on an old one we attempted in the past on ARC GNU 2014.12 version to enable -fplugin option meaning we had to rebuild / x-compile ARC GNU toolchain again.

The CASE which handled that is: 8000796117 ARC GNU - Recompile toolchain/runtimes and I worked on this with Igor.

I remind we were able to rebuild the ARC GNU for a Linux host target but for Windows no chance, think there were issues with MinGW. Cygwin is not wanted since we don't want of course any Cygwin runtime dependencies here.

Perhaps for new 2017.03 version we can easier rebuild the toolchain to enable -fplugin support for Windows host target, can you please attempt this and try?

Thx Christophe

**Comment by coco21** [comment]
Update: I did open a CASE, 8001000683 "ARC GNU enable -fplugin support for Windows host target"
Thx Christophe

**Comment by coco21** [comment]
We may have found a way to enable this feature also for Windows build and could share back when ready.

**Comment by fbedard** [comment]
Hi Christophe,

I understand you guys are no longer considering using this plugin approach for your solution.  If you have anything you'd like to share on getting the general windows plugin use case please include it here otherwise let's close this issue as we don't plan to do any work on this ourselves. 

Thanks.

**Comment by iguryanov** [comment]
Hi Francois, there is a patch in the CASE, I'll forward it to Anton and Claudiu. 
Had not chance to try it myself yet. I think we can close it here.

**Comment by coco21** [comment]
Hello, I close the issues here but keep the CASE ticket open on Synopsys side. I provided a first quick patch to Synopsys folks that shall make -fplugin support also possible on Windows hosts.
