### ISSUE TITLE
ARC GNU 2017.03 RC1 - Secure MPU 

### ISSUE THREAD

**Issue by coco21** [foss-for-synopsys-dwc-arc-processors/toolchain#117]
Hello,

We now have an additional question regarding the SFLAG instruction encoding (the assembler output does not match the documentation).

The documentation of the SFLAG instruction states that the instruction encoding for both C and U6 variants has all ones in bit positions 5:0. However, the tool chain generates all zeros in these positions. For example sflag r3 generates the pattern 302f 00c0 when assembled; the documentation implies it should be 302f 00ff. I believe that the assembler is correct and the documentation is wrong - can you please confirm this?

We have the same inconsistency for 2017.03-RC1 with the documentation for the SFLAG instruction as the previous version (I think this would be expected, since the version number embedded in the name is the same). We still need Synopsys to confirm whether the assembler or the documentation is correct.

Thx Christophe

**Comment by coco21** [comment]
Additional information:

The issue reported here directly is linked to a Synopsys ticket:
https://onlinecase.synopsys.com/Home.aspx?caseNumber=8001000705.

This ticket is market **showstopper** and also further refers to a STAR:
9001177535 (Secure EM - More clarity needed wrt interrupt entry and exit).

Thanks to bring the necessary attention to my request.
Best regards Christophe

**Comment by coco21** [comment]
Hello,

Ok we redid the test regarding Q1 (SLFAG encoding).
Whereas for MWDT 2016.12 it might be correct for ARC GNU 2017.03-RC1 it's wrong then.

MWDT 2016.03:

302f003f sflag %r0
302f00ff sflag %r3

ARC GNU 2017.03-RC1 (via objdump):

302f 0000 sflag   r0
302f 00c0 sflag   r3

So we need a fix of the ARC GNU toolchain quickly please.

Thx Christophe

**Comment by fbedard** [comment]
Hello Christophe,

Just wanted to acknowledge your report here.  We will review and advise asap.

**Comment by claziss** [comment]
Hi,
As far as I can see the SFLAG encoding is this one:
```c
/* sflag c 00110RRR001011110RRRCCCCCCRRRRRR */
```
Where R is reserved and needs to be considered 0, or at least we interpret it so in GNU.

As for the u6:
```c
/* sflag u6 00110RRR011011110RRRuuuuuuRRRRRR */
```
So, it seems to me that the R bits are interpreted as 1 in the case of MWDT.

**Comment by coco21** [comment]
Hello,

Thanks for the precision, shared that further here too.
At this stage I still am not sure why interpretations differ between the GNU and the MWDT and the paper spec. Can you explain please?

Thank you & Br Christophe

**Comment by claziss** [comment]
Hi,
I've double checked the encoding with the hardware guys, GNU got the wrong encoding. Thank you for signalizing this. A patch is undertesting.

**Comment by claziss** [comment]
Fixed by [commit](https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/commit/6171bf31305b3a904318ff751cd7c984f4cc4d7c).

**Comment by coco21** [comment]
I'll feed inputs here into Synopsys (showstopper) ticket directly, there already is heavy R&D rework ongoing on spec side since there are many inconsitencies - please adivise with Synopsys folks directly to sort that out internally on your side. At this stage our reference is the EM6 spec so Synopsys side.

Thx Christophe

**Comment by fbedard** [comment]
To be clear - spec (PRM) was correct in this instance, this was just an issue with our implementation in GNU,

**Comment by coco21** [comment]
Hello,
Yep, thanks for the information. Now we know spec and GNU (with patch above) are matching, that brings us further, thanks much,
Christophe

**Comment by coco21** [comment]
Hello,

Quickly a remaining question: when do you plan to deploy the patch e.g. as a RC2 so we can use it without needing to build the toolchain? Thx Christophe

**Comment by fbedard** [comment]
Hi Christophe,

We just published RC2 at https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/releases/tag/arc-2017.03-rc2 

Please give it a try and let us know whether you run into any further issues.  

Thanks!

**Comment by coco21** [comment]
Hi François,

Very good news, ok already am downloading it. Yep we let you know back.

Thx Christophe
