### ISSUE TITLE
TCF to GCC

### ISSUE THREAD

**Issue by coco21** [foss-for-synopsys-dwc-arc-processors/toolchain#118]
Hello,

We start now to develop first baremetal code using ARC GNU and CPU HW IP .tcf file.
We are interested into getting all macros defining registers, maps, offsets etc.

Went on the doc page here: https://foss-for-synopsys-dwc-arc-processors.github.io/toolchain/baremetal/tcf.html#general-sescription

I am doing this in Windows, using Cywgin + perl + XML:LibXML package that all seems to work.

However I must do something wrong, please see below.

schmid@MOB13263 /cygdrive/c/arc_gnu/bin
$ ll arc-elf32-tcf-* ad_*
-rwxrwxr-x+ 1 schmid         Domain Users  52K May 10 14:01 ad_arc_arc_without_apex.tcf*
-rwxrwx---+ 1 Administrators Domain Users 4.1K Apr 13 00:20 arc-elf32-tcf-gcc*

schmid@MOB13263 /cygdrive/c/arc_gnu/bin
$ arc-elf32-tcf-gcc --tcf ad_arc_arc_without_apex.tcf
arc-elf32-gcc.exe: error: @/tmp/QofBpZK8RK/gcc.arg: No such file or directory

Thx Christophe

**Comment by anthony-kolesov** [comment]
I think the problem is that arc-elf32-gcc.exe is not a Cygwin executable, therefore it cannot understand the cygwin path of `/tmp/....`. You need to modify perl script to pass windows path to compiler. This will look like this:

```diff
diff --git a/extras/arc-tcf-gcc b/extras/arc-tcf-gcc
index 90c8447..c2306d0 100755
--- a/extras/arc-tcf-gcc
+++ b/extras/arc-tcf-gcc
@@ -80,7 +80,7 @@ sub parseXML
     print $fh $cnfgl[0]->textContent;
     close $fh;

-    return $filename
+    return `cygpath -w -a $filename`
 }

 # Parse input arguments, search for --tcf <filename>, and extract it.
@@ -125,7 +125,7 @@ sub processXML
     # Parse the linker file
     my $sn = '/config_list/configuration[@name="gnu_linker_command_file"]';
     parseXML ($tcf, $sn);
-    my $cmdline = " -Wl,-marcv2elfx -L" . $dirname . " ";
+    my $cmdline = " -Wl,-marcv2elfx -L" . `cygpath -w -a $dirname` . " ";


     # Parse the compiler options
@@ -151,5 +151,7 @@ parseInputArgs(@ARGV);
 $dirname = tempdir();
 my $cmd = processXML();
 $cmd = $compiler . $cmd . " " . join (" ", @gcc_args);
+$cmd =~ s/\R//g;
+$cmd =~ s/\\/\\\\/g;
 print $cmd, "\n" if ($verbose) ;
 system ($cmd);
```

**Comment by coco21** [comment]
Oh ok, gosh each time I get cought on that one, ok I've to leave but promise will try that tomorrow.
Didn't studied to script further but I expect it also may be able to not only wrap on GCC but also extract me proto headers or pieces of Makefile, command file, am I right? Because TCF has it all.

Thx Christophe

**Comment by anthony-kolesov** [comment]
It extracts compiler flags, linker script and header defines.

**Comment by coco21** [comment]
Good morning,

Ok tried it and it seems to work correctly now.
However I must misunderstand something here since compiler is tried to be invoked, but I don't want so. I simply expect feeding a TCF into that script and it throws out all the defines - it's how it's supposed to work am I correct? Sorry for my basic questions here but I am in a hurry and need quick understanding and have no time to study the script, much thanks. Christophe

schmid@MOB13263 /cygdrive/c/arc_gnu/bin
$ arc-elf32-tcf-gcc_cygwin --tcf ad_arc_arc.tcf
c:/arc_gnu/bin/../lib/gcc/arc-elf32/6.3.0/../../../../arc-elf32/bin/ld.exe: address 0x54 of a.out section `.ivt' is not within region `SYSTEM1'
c:/arc_gnu/bin/../lib/gcc/arc-elf32/6.3.0/../../../../arc-elf32/bin/ld.exe: address 0x178 of a.out section `.startup' is not within region `SYSTEM1'
c:/arc_gnu/bin/../lib/gcc/arc-elf32/6.3.0/../../../../arc-elf32/bin/ld.exe: a.out section `.jcr' will not fit in region `SYSTEM1'
c:/arc_gnu/bin/../lib/gcc/arc-elf32/6.3.0/../../../../arc-elf32/bin/ld.exe: address 0x54 of a.out section `.ivt' is not within region `SYSTEM1'
c:/arc_gnu/bin/../lib/gcc/arc-elf32/6.3.0/../../../../arc-elf32/bin/ld.exe: address 0x178 of a.out section `.startup' is not within region `SYSTEM1'
c:/arc_gnu/bin/../lib/gcc/arc-elf32/6.3.0/../../../../arc-elf32/bin/ld.exe: region `SYSTEM1' overflowed by -8387870 bytes
c:/arc_gnu/bin/../lib/gcc/arc-elf32/6.3.0/../../../../arc-elf32/lib/em4/crt0.o: In function `__start':
crt0.S:(.text.__startup+0x3e): undefined reference to `_impure_ptr'
crt0.S:(.text.__startup+0x3e): undefined reference to `_impure_ptr'
crt0.S:(.text.__startup+0x6a): undefined reference to `main'
crt0.S:(.text.__startup+0x6a): undefined reference to `main'
crt0.S:(.text.__startup+0x72): undefined reference to `exit'
crt0.S:(.text.__startup+0x72): undefined reference to `exit'
collect2.exe: error: ld returned 1 exit status

**Comment by anthony-kolesov** [comment]
This script is expected to run the compiler - it extracts contents from the TCF and passes it as arguments to compiler, otherwise there would be no purpose in this script - if one only needs the options, then he can just open the TCF in text editor and extract all of the options/defines out of it, its just an XML. The purpose of this script to automate this, so that people will not be required to manually operate with TCFs. Besides, because there is a lot of data in the TCF, it is usually not passed to compiler as options, instead it is extracted into files, then compiler is told to use those files.

**Comment by coco21** [comment]
Ok that is clear and confirms the purpose of this perl script, I understand and makes sense, thanks.
You say "extraction into files", where can I find those?
I think then I simply have to compile a fake .c file via that script and giving it --tcf option along, correct?
That way I can recuperate the files.

Thx Christophe

**Comment by anthony-kolesov** [comment]
Those files are created in temporary directory. If you only need their contents, then it is better to open TCF in text editor and extract contents manually. Alternatively you can use "tcftool"  which is provided together with GNU toolchain starting with this release:

```bash
# Compiler flags
$ tcftool -q -p gcc_compiler <TCF>

# Preprocessor defines
$ tcftool -q -p C_defines <TCF>

# Memory map for -marcv2elfx
$ tcftool -q -p gnu_linker_command_file <TCF>
```

**Comment by coco21** [comment]
Oh cool, that's exactly what I needed, thanks for pointing that out. Christophe

**Comment by coco21** [comment]
I think we can close that issue, I got the informations I needed. Best Christophe
