### ISSUE TITLE
ARC GNU roadmap for upcoming months

### ISSUE THREAD

**Issue by coco21** [foss-for-synopsys-dwc-arc-processors/toolchain#119]
Hello,

We today use 2017.03-RC2 version of the ARC GNU, mainly for the secure MPU features this toolchain has to support as well.
I was wondering if I can deploy this toolchain into teams here and maturity grade of it. Whereas I understand this is a RC version, maybe you could provide some short term roadmap you plan until let's say to rollout 2017.06 version?

Thx Christophe

**Comment by coco21** [comment]
Hi again,

I got some feedback regarding the 2017.03-rc2 assembler that does not behave as expected:

- Error: A jump/branch instruction in delay slot
- Error: unknown opcode 'ldb'  /  Error: unknown opcode 'ldw'
- Error: inappropriate arguments for opcode 'enter_s'  /  Error: inappropriate arguments for opcode 'leave_s'

This comes out of tests that run on 2014.12 ARC GNU but now fail on 2017.03-rc2 ARC GNU.

Again, we should get feedback from GNU about whether this should be valid or not, because the Architecture Reference Manual doesn't say that this is illegal.

I will also post same information and a bit more in CASE "Case 8001000705 : Poor documentation of interrupt entry and return." Please sync with Synopsys folks as well since this directly relates to that ticket too.

Thx Christophe

**Comment by coco21** [comment]
Update: you can find more details and also test assembly code in CASE "Case 8001000705 : Poor documentation of interrupt entry and return.". Didn't want to share this here, thx Christophe

**Comment by anthony-kolesov** [comment]
Hi Chris,

With respect of a roadmap, the ultimate man is Francois, but he is on vacation right now, so you might need to wait two weeks before he'll return to get a complete answer.

What I can say is that we don't plan 2017.06 as far as I know (FWIW this 2017.03 already slipped far enough to be 2017.06), instead we typically make two releases in a year, so second will be 2017.09.

**Comment by fbedard** [comment]
2017.03 release was done in May.   Next release will be 2017.09 with the following planned updates for bare metal (elf32) toolchain (reflects our current plans, subject to change): 
- Move to GCC 7.1
- Switch to LRA for register allocation
- Revamped Zero Overhead Loop (ZOL) implementation
- Support for reduced register set (RF16) configuration on ARCv1 and ARCv2 cores
- Support loop count width (LP_COUNT register values) < 32 bits 
- Support for __uncached and __aux attributes
- Builtin functions for DSP instructions

**Comment by coco21** [comment]
Thanks! Do you have a link where I can get this info updated in real-time?

**Comment by fbedard** [comment]
Best way is to periodically monitor checkins on arc-2017.09 branch of gcc repository.

**Comment by coco21** [comment]
Ok understand, thanks. Br Christophe
