### ISSUE TITLE
Assembler version 2017.03-rc2 is reporting errors, previously OK

### ISSUE THREAD

**Issue by eroom1966** [foss-for-synopsys-dwc-arc-processors/toolchain#121]
Hi
We are trying to run the assembler on a file which previously assembled correctly, now we see many issues.

Output from assembler
asmtest.S:1365: Error: A jump/branch instruction in delay slot.
asmtest.S:1365: Error: A jump/branch instruction in delay slot.
<...>
asmtest.S:1759: Error: unknown opcode 'ldb'
asmtest.S:1760: Error: unknown opcode 'ldb'
<...>
asmtest.S:1801: Error: unknown opcode 'ldw'
asmtest.S:1802: Error: unknown opcode 'ldw'
<...>
asmtest.S:4101: Error: inappropriate arguments for opcode 'enter_s'
asmtest.S:4180: Error: inappropriate arguments for opcode 'leave_s'

Error: A jump/branch instruction in delay slot
These errors are very strange: the instruction at line 1365 is a BTST instruction that is plainly neither a jump/branch instruction nor in a delay slot. Commenting the line out (and lines nearby) doesn't help - the error just moves around. The fact that the error is inappropriate and repeated many times makes me think that the assembler has got into a bad state here for some reason.

Error: unknown opcode 'ldb'  /  Error: unknown opcode 'ldw'
In this case, the assembler is failing to recognize instructions of the form:
    ldb.x.a.di
and
    ldw.x.a.di
The Architecture Reference Manual doesn't say that this is illegal, and it used to assemble correctly. We should get feedback from GNU about whether this should be valid or not.

Error: inappropriate arguments for opcode 'enter_s'  /  Error: inappropriate arguments for opcode 'leave_s'
In this case, empty register lists for enter_s and leave_s are not being accepted, when they used to be:
    enter_s     {}
    leave_s     {}
Again, we should get feedback from GNU about whether this should be valid or not, because the Architecture Reference Manual doesn't say that this is illegal.

To reproduce rename asmtest.S.txt asmtest.S, then :-
$ arc-elf32-gcc -c asmtest.S -mcpu=arcem -EL

Is the syntax incorrect ?
[asmtest.S.txt](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/1007164/asmtest.S.txt)

Regards

**Comment by claziss** [comment]
Hi,
Error: A jump/branch instruction in delay slot
The error is correct, however the location where it happens is incorrect reported. The correct message is:
```asm
asmtest.S:1550: Error: Insn j has a jump/branch instruction j in its delay slot.
asmtest.S:1551: Error: Insn j has a jump/branch instruction j in its delay slot.
asmtest.S:1554: Error: Insn j has a jump/branch instruction jeq_s in its delay slot.
asmtest.S:1564: Error: Insn j has a jump/branch instruction j in its delay slot.
asmtest.S:1565: Error: Insn j has a jump/branch instruction j in its delay slot.
asmtest.S:1566: Error: Insn j has a jump/branch instruction j in its delay slot.
asmtest.S:1569: Error: Insn j has a jump/branch instruction j_s in its delay slot.
asmtest.S:1583: Error: Insn jl has a jump/branch instruction jl in its delay slot.
asmtest.S:1584: Error: Insn jl has a jump/branch instruction jl in its delay slot.
asmtest.S:1585: Error: Insn jl has a jump/branch instruction jl in its delay slot.
asmtest.S:1588: Error: Insn jl has a jump/branch instruction jl_s in its delay slot.
asmtest.S:1598: Error: Insn jl has a jump/branch instruction jl in its delay slot.
asmtest.S:1599: Error: Insn jl has a jump/branch instruction jl in its delay slot.
```
Error: unknown opcode 'ldb' / Error: unknown opcode 'ldw'
This is an assembler issue which was set to recognize up to three flags. However, the ldb/ldh instructions are having 4 flags (i.e., 'd/h', 'x','ab', and 'di').

Error: inappropriate arguments for opcode 'enter_s' / Error: inappropriate arguments for opcode 'leave_s'
Indeed the PRM is vague here. I would assume the enter/leave requires at least an operand. However, if you like to call those function with a null argument, I would recommend using:
```asm
leave_s 0
enter_s 0
```
N.B. If you use code-density ops, you need to pass -mcode-density to the assembler, or use a .cpu pseudo/or mcpu option to point to an ARC EM with code density ops enabled by default (e.g., em4)

P.S. There may be issues with jli_s and not aligned immediate arguments. I made a patch which fixes this issue and the above reported ones.

Thank you

**Comment by claziss** [comment]
I've pushed three small patches that address the problems which you signalized. Please let me know if there are more issues.
