### ISSUE TITLE
ARC 4.8.5 toolchain (2015.12)  Error: junk at end of line: `,@.LANCHOR1@pcl'

### ISSUE THREAD

**Issue by ekromskoy** [foss-for-synopsys-dwc-arc-processors/toolchain#125]
I have some weird problem compiling zlib 1.2.11 with my toolchain based on release 2015.12. With older and with newer (2016.03, for example) tollchains I don't seems to have this problem.

Here is assembly code generated from trees.c

.L249:
	st.as r1,[r0,-81]       ;21	# s_11(D)->bi_valid, D.4920
	add r1,pcl,@.LANCHOR1@pcl		;8	# tmp732,
	add_s r1,r1,1-pcl,@.LANCHOR1@pcl	# tmp731, tmp732,

This last line is refused by GAS. Line 249 in trees.c doesn't have anything but initialization of global structure:
local const static_tree_desc  static_l_desc =
{static_ltree, extra_lbits, LITERALS+1, L_CODES, MAX_BITS};
;;;
/*L249*/    static_l_desc.extra_bits = extra_lbits;
 
I cannot find in ARC ASM guide such many operands in ADD_S instruction; so how this been generated and how to avoid it?

Thank you,
Ed

**Comment by ekromskoy** [comment]
It turned out this assembly produced by _tr_flush_block() function and not related to line 249. But anyway, below is bad assembly code
.L249:
	st.as r1,[r0,-81]       ;21	# s_11(D)->bi_valid, D.4920
	add r1,pcl,@.LANCHOR1@pcl		;8	# tmp732,
	add_s r1,r1,1-pcl,@.LANCHOR1@pcl	# tmp731, tmp732,
	add r12,pcl,@.LANCHOR1@pcl-805		;8	# ivtmp.245,
	mov_s lp_count,r3	;2	# tmp729, D.4920
	brgt r1, r3, @.L234	#, tmp731, D.4920,
	brne r3, -2147483648, @.L243	#, D.4920,,

And here is good code for the same part but produced 2016.03 (also 4.8.5 based) release

.L249:
	st.as r1,[r0,-81]       ;21	# s_11(D)->bi_valid, D.4918
	add r1,pcl,@.LANCHOR1@pcl		;8	# tmp732,
	mov_s r4,r1	;2	#, tmp732
	rsub r4,r4,1	#,,
	add_s r1,r1,r4	# tmp731, tmp732,
	add r12,pcl,@.LANCHOR1@pcl-805		;8	# ivtmp.245,
	mov_s lp_count,r3	;2	# tmp729, D.4918
	brgt r1, r3, @.L234	#, tmp731, D.4918,
	brne r3, -2147483648, @.L243	#, D.4918,,

Do you have any idea where to look at? 2016.03 release is not good for me because it produces kernel modules that I cannot insert into 3.12 kernel. Is any way to disable dwarf2 and make modules compatible with previous kernels as in 2015.12 release?

**Comment by vineetgarc** [comment]
Hi,
About 2016.03 and 3.12 kernel there was some earlier discussion here
  https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/issues/120
Did you get a chance to backport the commit and see if that enabled you to load modules in 3.12 ?

**Comment by ekromskoy** [comment]
I will try that and see if modules will work. I decided to roll back to 2015.12 release; everything seems good except this one bug discovered by compiling zlib. Kernel, modules and a few minimal rootfs went good.

**Comment by ekromskoy** [comment]
Hi Vineet,

Sorry I looked back in that discussion and remember now that you suggested to back port something to our 3.12 kernel? We decided not to and roll back toolchain. I found that 2015.12 release works and this is the only bug reported so far. I would prefer to fix  2015.12 toolchain or find workaround to compile zlib rather then change kernel.

Thank you
Ed

**Comment by vineetgarc** [comment]
It is always difficult to patch old toolchians than to patch old kernels - seems counter intuitive that is how it is. So please add that kernel patch and you should be good to go !

**Comment by ekromskoy** [comment]
Cherry-picking from kernel fix  f52e126cc74761? Hmm... will see tomorrow how big cherry tree is.

I don't seem to have this asm code bug with 4.8.4 toolchain so it's a bit unexpected. Also we had some other bugs wit 4.8.0 and earlier but not this one.

**Comment by vineetgarc** [comment]
Do note that the kernel patch only works in conjunction with GNU 2016.03 - i.e. we assume that you will be switching to 2016.03 (to workaround the possible toolchain issue reported here)

**Comment by claziss** [comment]
Hi,
This instruction is not OK:
add_s r1,r1,1-pcl,@.LANCHOR1@pcl	# tmp731, tmp732,

However, this is solved in newer version of the compiler.

**Comment by ekromskoy** [comment]
Vineet,

Could you please be more specific about
The quick fix for your 3.12.x is to over-ride this toolchian behaviour by cherry-picking upstream kernel fix f52e126cc74761 ("ARC: unwind: ensure that .debug_frame is generated (vs. .eh_frame)").

Where to find this kernel fix f52e126cc74761? And what exact changes I should take... My understanding is that 2016.03 toolchain generates .eh_frame and doesn't generate .debug_frame. Is this correct?

Thank you,
Ed

**Comment by ekromskoy** [comment]
Ok, I checked out that hash revision.

**Comment by vineetgarc** [comment]
What I meant was to apply the patch corresponding to that commit id and apply it to your kernel.
Assuming you are in an upstream tree (as your 3.12 kernel won't have that patch in it's git history)
cd {upstream-kernel}
git format-patch f52e126cc74761~1..f52e126cc74761 -o /tmp
cd {ur-3.12-kernel}
git am /tmp/0001-ARC-unwind-ensure-that-.debug_frame-is-generated-vs..patch

**Comment by vineetgarc** [comment]
And about your other point, 2016.03 by default generates .eh_frame but can be made to generate .debug_frame which the kernel patch above forces it to. You can find more details in patch's commit log

**Comment by ekromskoy** [comment]
We use Mercurial internally, so our linux kernel is under hg. OK, your patch was not too big, I applied it by hand. Now I have to rebuild 2016.03 toolchain and see if kernel and modules are OK. I let you know how it's going.

**Comment by vineetgarc** [comment]
Rebuild the toolchain - what for ? FWIW the kernel patch above doesn't warrant a toolchain rebuild !

**Comment by ekromskoy** [comment]
I have modifications to toolchain code specific to our ARC cores. No, it is completely unrelated. But now I need 2016.03 release to build our kernel and modules. It's going to be ready after lunch.

**Comment by vineetgarc** [comment]
since you are building the toolchain, suggest adding a patch to binutils referred to in issue #120 as well.
As I mentioned there, the binutils in there had a small bug in generating dwarf info which inhibits correct stack unwinding.

**Comment by ekromskoy** [comment]
OK, everything seems to work now. Thank you very much.

**Comment by vineetgarc** [comment]
Great !
So just to summarize the reported issue exists with GNU 2015.12 and goes away with GNU 2016.03.
To enable 3.12 kernel to work with latter toolchain, patch proposed in issue #120 needed to be applied as well !
