### ISSUE TITLE
Ashling Opella XD for ARC - Need --arc-reg-file XML

### ISSUE THREAD

**Issue by coco21** [foss-for-synopsys-dwc-arc-processors/toolchain#127]
Hello, 

I am about to integrate our FPGA based breadboard using an Ashling Opella XD for ARC JTAG probe. 
In the past we already used such setup and I got an XML file "arc-opella-em.xml" that embeds all register definitions. 

We now use latest ARC EM Core version ARCv2EM6 4.00A+ESP (secure MPU). 
I was told it's simply a matter of such an XML file to correctly make talk our JTAG probe to such a target. 

Therefore can you please provide me with an appropriate XML file so I can start using correctly the JTAG probe on our FPGA board? 

It's important since for the moment I am stuck. 

PS: I also opened a ticket as showstopper on support site, Case Number:	8001028376

Much thanks & Regs' Christophe

**Comment by coco21** [comment]
Found this but am not sure there is ESP / secure MPU support for the ARCv2 EM6 CPU.
URL: https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/tree/arc-staging/extras/opella-xd

Thx Christophe

**Comment by iguryanov** [comment]
Hi Christophe, 

I have the case and talking with Ashling now. 

arc-em-cpu.xml bundled with Opella software is the same. I it does not have any ESP/secure MPU registers defined, as it was not defined before for usual MPU or MMU for 700/HS. And seems worked fine.  Does it have to have _all_registers? 

For usual aux registers, if you do need them in the file, you can simply modify the file. Could you please try it? (ESP/sMPU list is relatively short). The only thing I have to check with Ashling is that for ESP registers are not always RW or RO, it depends on the protection state... 

Regards,
Igor.

**Comment by coco21** [comment]
Hi Igor,

Thanks for the information. I've to check here. Thing is our ARCv2 EM6 will be all the time in secure MPU mode and never in normal mode - so I simply ask myself if the probes/applction/XML configurations we used today still will work. We were using same probes since a moment now (on ARCv1 605 and ARCv2 EM6 3.11a and now 4.00+ESP). I was told by Synopsys worst case it's simply a matter of XML file update - I understand it's what you're about to check, I then wait on a feedback.

Thx & regs Christophe

**Comment by coco21** [comment]
Ok I start to make it working. I now get an error message telling me

"Remote 'g' packet reply is too lonng: ..."

On 2014.12 I used a GDB init file with a line like that: "set arc opella-target arcem".
But that on 2017.03 no longer works. Also followed instructions on this link but still not working: https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/wiki/AXS-SDP-and-Ashling-GDB-Server

What am I missing here? Thx for the help.
Christophe

**Comment by anthony-kolesov** [comment]
Hi Chris,

GDB target description file should be updated according to the changes done to Ashling file. Registers added to file that is passed to Ashling server also should be added in the GDB XML target description file.

**Comment by coco21** [comment]
Hello Anthony,

Thanks.

In 2014.12 GDB guide I see the command "set arc opella-target arcem" that worked until now.
I also understand that with later versions of GDB in 2017.03 (7.12 I think it is) there are XML files used to configure correct target.

I use Ashling software and drivers 1.0.5 G that already brings support for processor XML files (starting GDB 6.8). We use this since 2 years now and it worked fine in past project where we ran 2014.12 ARC GNU on a EM6 core.

On (Ashling) GDB server side I do that:

ash-arc-gdb-server.exe --arc-reg-file arc-opella-em.xml --device ARC-JTAG-TAP-R1 --jtag-frequency 10Mhz

On client side (ARC GNU 2017.04 arc-elf32-gdb.exe) I use an init file with that content

set architecture EM
set tdesc arc-em-cpu.xml ../My/Path/Something
target remote tcp:localhost:2331
load ../My/Other/Path/MyImage.elf

Also tried on second line rather use opella-arcem-tdesc.xml as normally it should be and described on your wiki page here. But that also still throws me the 'g' packet too long error.

In my understanding either I need "set arc opella-target arcem" back on GBD client side or I need to better understand which exact XML to load on each side (server and client). I certainly am missing something.
I also was told by Synopsys my Ashling probes don't need an update (firmware) here but simply an XML adaptation (I saw the new registers having been added). But the method on GBD client side changed and I need to work out that now.

Thx Christophe

**Comment by coco21** [comment]
Mmmh, went back here to re-read in detail: https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/wiki/AXS-SDP-and-Ashling-GDB-Server

I fear this comments (known issues). I use GDB 7.12 (2017.03) and have Opella 1.0.5-G.

- In Opella software version of 1.0.6 prior to 1.0.6-D it has been observed that in some cases target core may hang on application load, if target has external memory attached. This happens when P-packet is disabled, and since P-packet should be disabled when using new GDB with those versions of Opella software, effectively it is not possible to use GDB >= 7.9 with Ashling GDBserver < 1.0.6-D to debug cores that employ external memory.
- In version of 1.0.6 it has been observed that breakpoint set at "main()" function of application may be not hit on first run in HS34 core in AXS102.
- In version 1.0.6-D it has been observed that gdbserver doesn't invalidate I$ of the second ARC 600 core of AXS101 - if this core hits a software breakpoint it gets stuck at it forever.

Please advise so I understand I've a chance to make run my setup or need updates or hot fixes.
Thx Christophe

**Comment by anthony-kolesov** [comment]
> set tdesc arc-em-cpu.xml ../My/Path/Something

Here you need to use a "tdesc" file, which is an XML file that describes ARC registers in different format than the file used by Ashling gdbserver. For example for server register file `arc-em-cpu.xml` you need to use `set tdesc filename opella-arcem-tdesc.xml`, where this file comes from https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/tree/arc-releases/extras/opella-xd .  GDB should be printing you an error if you try to use Ashling XML file - it has different format.

With respect of Ashling version, I don't remember myself what problems each version has, but if says that you need at least 1.0.6-D - then it is probably so :) In that case there were real bugs in server implementation which prevented it operation with the new GDB, which started to use XML target descriptions. So for the new GDB you need a newer ashling software version.

**Comment by coco21** [comment]
Hello Anthony,

I simply went to Ashling and will test with their updated version. Will report back here when done.

Thx Christophe

**Comment by claziss** [comment]
It seems the issue is fixed (somehow). Please reopen it if you consider otherwise.
