### ISSUE TITLE
2014.12 vs. 2017.03 - Questions regarding certain changes

### ISSUE THREAD

**Issue by coco21** [foss-for-synopsys-dwc-arc-processors/toolchain#129]
Hello,

Here two questions from our teams who used 2014.12 in the past and now switched to new 2017.03.
When changed the version we were wondering why following changes have been applied (reason, effect):

1. Why was the -mshift-assist option removed from GCC, ASM, LD? Possible consequences?
2. Why are the litteral strings for [IC_CTRL], [IC_IVIC], [IC_IVIL] not accepted anymore?

Thx & Br Christophe

**Comment by claziss** [comment]
Hi,
1. -mshift-assist was a dummy option, not having any impact on the code. Basically, gcc compiler doesn't optimize for ASR16, ASR8, LSR8, LSL8, ROL8, and ROR8, when we do not have barrel shifter option.
2. The strings should be accepted, but indeed, using lower letters. I'll make a patch to accept both upper and lower case letters.

My test:
```asm
	lr r0,[ic_ctrl]
	lr r0,[ic_ivic]
	lr r0,[ic_ivil]
```

Thanks,
Claudiu

**Comment by coco21** [comment]
Hi,

Ok I take that information, much thanks.

Christophe

**Comment by claziss** [comment]
I've fixed upper/lower case issue here (2017.09):
[ARC] Update handling AUX-registers.
Update aux-registers data-base, and accept aux-registers names with
upper/lowercase names.

opcode/
2017-07-18  Claudiu Zissulescu  <claziss@synopsys.com>

	* arc-regs.h: Update aux-registers.

gas/
2017-07-18  Claudiu Zissulescu  <claziss@synopsys.com>

	* config/tc-arc.c (find_opcode_match): Accept uppercase aux-regs
	names.
	* testsuite/gas/arc/ld2.d: Update test.
	* testsuite/gas/arc/taux.d: Likewise.
	* testsuite/gas/arc/taux.s: Likewise.

include/
2017-07-18  Claudiu Zissulescu  <claziss@synopsys.com>

	* opcode/arc.h (ARC_OPCODE_ARCV1): Define.

**Comment by coco21** [comment]
Perfect, thanks much! Christophe
