### ISSUE TITLE
gcc / metaware compatibilty

### ISSUE THREAD

**Issue by Pyjong** [foss-for-synopsys-dwc-arc-processors/toolchain#130]
Sorry for opening something that has been here already, but I really have to ask or I spend rest of my life typing __attribute__(section()). In metaware compiler there was pragma Code, Data, BSS. As the name hints it worked much like section directive in NASM -> anything that comes after the directive will be put in that section in the object file (that goes separately for Code, Data and BSS). Is there by any chance something in that manner in this toolchain too? Thanks

**Comment by anthony-kolesov** [comment]
Hi,

Our main expert in this area is currently on vacation, but AFAIK there is no similar pragma for GCC. However [GCC documentation for attribute(section)](https://gcc.gnu.org/onlinedocs/gcc-7.2.0/gcc/Common-Function-Attributes.html#index-section-function-attribute) suggests that

> If you need to map the entire contents of a module to a particular section, consider using the facilities of the linker instead

It seems that the way how linker script can be changed to put the whole object file into custom section is described here: https://mcuoneclipse.com/2014/10/06/putting-code-of-files-into-special-section-with-the-gnu-linker/

**Comment by Pyjong** [comment]
Ok, thank you. It will still take a lot of work but I guess that can't be avoided here. And for future changes, linker scripts should make the project more flexible.

**Comment by claziss** [comment]
Hi,

Usually placing a data into a specific section should be done in an exceptional case. Otherwise, the compiler will emit the rightful section by default. Please can you be more specific what is your actual issue, if it is possible.

**Comment by Pyjong** [comment]
Hi,

The original reason for this linking excercise is saving RAM in our firmware. I know this can still be done with rewriting the linker script theoretically, but practically it will be a bit painful because, in my project, the C files even though functionally well grouped, their content is later split into multiple sections (meaning multiple code sections, multiple data sections), some rellocable, some fixed, some discardable. That means using linker script, being able to have 1 section per type per c file, I will have to split the C files so I can set the same memory layout in linker script (it has to be the same memory layout, for partially non-technical reasons :( ). The other option is __attribute.. at this point it actually seems easier for me but I guess others wouldn't thank me, so .ld it is. I think I have the idea how to deal with this, I just wouldn't want to spend a week working on it and then find out there actually is code_seg or something..
