### ISSUE TITLE
Makefile macros not working in assembly .inc files

### ISSUE THREAD

**Issue by coco21** [foss-for-synopsys-dwc-arc-processors/toolchain#136]
Hello,

We use macros in our Makefile (-DMyMacro) to enable / disable parts of code.

Whereas this works fine for C/C++ sources and also assembly file sources (.s) it's not working and taken into account for assembly includes (.inc).

We use arc-elf32-gcc front-end only in our Makfile to talk to compiler, assembler and linker.
We suspect GCC front-end is not passing all information to the assembler backend.

Can you please help use here and provide some guidance?

Thx Christophe

**Comment by anthony-kolesov** [comment]
Hi Chris,

Do you mean that you are using C-preprocessor in your assembly files and disable parts of code using standard `ifdef/endif`. Compiler option `-D...` sets options for the preprocessor.

Assembler files are parsed via C-preprossor if their extension is `.S`, files with extension `.s` are treated as pure assembly and are not feeded through C-preprocessor. The former behaviour can be enforced via option `-x assembler-with-cpp`.

**Comment by coco21** [comment]
Hi Anthony,

Ok, our assembly files terminate ".s" and not ".S". So we simply change the case of the file type extension to an upper case S? Let us try. 

And yes: we use C-preprocessor in our assembly (in the .inc to be precise) by using standard ".ifdef"/".else"/".endif" constructs.

Thx Christophe

**Comment by anthony-kolesov** [comment]
`.ifdef` is not a C-preprocessor define, it is actually an assembler command. I tihnk symbols are defined for it via gas option `--defsym sym=value`, when passed from the compiler driver you the should use `-Wa,--defsym sym=value`

**Comment by coco21** [comment]
Ok we changed our assembly files from .s to .S but now includes in those (now newly extended .S) files such a #include "arc_reg.h" are no longer found during build and ends with an error telling the arc_reg.h cannot be found.

Based on all that can you please tell me how in the .inc I shall process a C-preprocessor define correctly?

Thx Christophe

**Comment by anthony-kolesov** [comment]
Hi Chris,

If you had a file `.s`, then `#include "arc_reg.h"` was treated as a comment - it wasn't included at all. That means that you can simply remove it or you need to path apropriate `-I` flag to compiler.

**Comment by coco21** [comment]
Hi, yes you're right our bad. Ok I now simply replaced the #include "arc_reg.h" by .include "arc_reg.h" and also ensured in our Makefile we pathed the correct -I flags, that shall be ok on our side.
In the Makefile I defined for the assembler (used through arc-elf32-gcc) this: DBG_ASM := -Wa,--defsym MYSYMBOL=1.

I now get an error when the assembler is invoked (through gcc) telling me this in the output:

...blablabla
Compiling AFile1.c
...
Compiling AFile2.c
Assembling MyAssembly.s
arc-elf32-gcc.exe: error: MYSYMBOL=1: No such file or directory
make: *** [Some/Path/MyAssembly.o] Error 1
...

What am I missing?

**Comment by anthony-kolesov** [comment]
Should be `-Wa,--defsym,MYSYMBOL=1`

Otherwise only `--defsym` is passed to assembler, while MYSYMBOL=1 is considered as an argument to driver itself.

**Comment by coco21** [comment]
Ok when you say it this makes sense, I am reading the documentation at the same time but this are fine "tricks". Ok then I followed what you told me and seems to go a bit better, but ...

Assembler still is moaning, no longer regarding MYSYMBOL=1 that seems now to be accepted but about the .include "AnyOtherFile.h" statement inside my assembly module MyAssembly.s (lower case .s).
It says:

Assembling MyAssembly.s
./../../AnyOtherFile.h;21: Error: junk at the end of line, first unrecognized character is `/'

And so on. Analyzing a bit closer the AnyOtherFile.h it seems characters like "//" are not accepted but "/*" are passing.

So this certainly are rules of how a C-style .h file has to be written and commented when planned to be included inside a .s assembly file via .include statement. Can you please direct me here? I mean: it's possible do what I try doing here, right?

Thx Much C

**Comment by anthony-kolesov** [comment]
Since file is included inside of the assembly file, it is treated as an assembly file. So comments should follow the rules of assembly syntax: `/* */` or `;` or `#` , as described in gas documentation.

However if you include this header both in C and in asm, I'm not sure what content can be shared there - I can think of only of preprocessor defines that can be shared, but since you include file with assembler's directive `.include`, preprocessor staget has been already passed, so .h will be included as is, so it should contain only valid assembly.

**Comment by coco21** [comment]
Ok thanks.

We finally came back to #include "AnyOtherFile.h" and it passes now. Also tried to simply comment it out like ;;#include "AnyOtherFile.h" and then build didn't pass. So looks like the # is not only a comment in a .s file but still can have effect to some extend, perhaps we both say the same here.

So now the assembly stage also is passing, let's accept this as it is for the moment.
I now drive into another issue that is assembler complains 'bcc_s' being an unknown opcode.
This bcc_s indeed appears within the .ifdef MYSYMBOL construct in my .inc file - proof that the assembly switch now is working I'd say. Coming back to this unknown opcode it reminds me some past discussion we had here but am not able to find the leads, perhaps you know please?

My assembler options rougly are

-mmpy-option=0
-mcpu=em6
-mbarell-shifter
-mcode-density
-mswap
-mnorm
-nostartfiles
-mlong-calls
-specs=nosys.specs
-Wl,--no-check-sections

I'd say -mlong-calls is the candidate but your guidance is welcome

Thx C

**Comment by anthony-kolesov** [comment]
bcc_s is indeed an incorrect instruction mnemonic. You need to modify your code in such way that gas wouldn't think that this is an instruction

**Comment by coco21** [comment]
Ok but looking at the ARCv2 ISA Programme's Reference Manual, Bcc_s exists. Version of the guide is 5782-080, June 2017. So this is not supposed to be an incorrect instruction. There are some reasons why the instruction is present therefore I'd be glad if you could give me some guidance where I shall look in terms of HW platform configuration (tcf files I have) or compiler switches to use or not to use - all this in the assumption I'd like to use the Bcc_s instruction at the end. I keep searching on my side in the meantime too of course Thx Christophe

**Comment by claziss** [comment]
Hi,
My interpretation of the cc in the Bcc_s is it stands for **C**onditional **C**ode. As the PRM is listing explicitly the recognized short instructions:
```asm
BEQ_S s10 1111001sssssssss
BNE_S s10 1111010sssssssss
BGT_S s7 1111011000ssssss
BGE_S s7 1111011001ssssss
BLT_S s7 1111011010ssssss
BLE_S s7 1111011011ssssss
BHI_S s7 1111011100ssssss
BHS_S s7 1111011101ssssss
BLO_S s7 1111011110ssssss
BLS_S s7 1111011111ssssss
```

Please let me know if this explanation suits you. 


Thanks,
Claudiu

**Comment by coco21** [comment]
Hello,

Ok you're right, I didn't fully read the tables. Refering to aformentionned PRM BCC_s shall exist (it's case sensitive so upercase "C" here) but Bcc_s means "cc" represents the condition codes being accepted (Table 4-7). My bad, sorry.

The Bcc_s comes from former code we used on an ARCv1 605 target. It think whith your information we're set. Thx Christophe

**Comment by claziss** [comment]
I agree the PRM can be confusing, it is on my todo list to clarify it as much as it is possible to do :)
