### ISSUE TITLE
2017.03 - Looking for using optimization -O2 without TCO optimization

### ISSUE THREAD

**Issue by coco21** [foss-for-synopsys-dwc-arc-processors/toolchain#141]
Hello,

I try to find a way using -O2 optimization but without using the TCO (Tail Call Optimization).
Now using -O2 means TCO is on per default. Tried to read through GCC documentation but I only see switches such as -ftree-tail-merge and -max-tail-merge-xxx but don't find a way doing that.

Is there a way?

Thx Christophe

**Comment by claziss** [comment]
Hi Christophe,

Sorry for the late response, I haven't seen your post, my bad.

To disable sibling calls, you just need to pass -fno-optimize-sibling-calls. More over, our backend will not do tail call optimizations for interrupts, jli and secure calls. Obviously, we can extend the list if needed.

Please let me know if it fixes your issue, and close this thread if so.

Thank you,
Claudiu

**Comment by coco21** [comment]
Hi Claudiu,

Thanks for your answer. Teams will check this here and as soon as I get an input I update the ticket here.

Thx Christophe

**Comment by coco21** [comment]
Hello Claudiu,

A short experiment shows that indeed the TCO optimization gets disabled.
We now need to verify also if that is not breaking anything on our production code.
I will close this request and reopen it shall there be other questions. 

Thanks for your help
Christophe
