### ISSUE TITLE
Baremetal links in release area giving 404 error

### ISSUE THREAD

**Issue by puneet** [foss-for-synopsys-dwc-arc-processors/toolchain#144]
The baremetal binaries are not available in the release area.

https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/releases/download/arc-2017.09-release/arc_gnu_2017.09_prebuilt_baremetal_le_linux_install.tar.gz

**Comment by anthony-kolesov** [comment]
Hi Puneet,

Thanks for reporting this problem. I've updated Release page with valid links and fixed an issue with script that generates them in commit 64fff0e5be321fab4b9f11d6b1731a0fe78231d7.
