### ISSUE TITLE
which version of toolchain contains the workaround for ARC700 D-Cache eviction issue

### ISSUE THREAD

**Issue by emersonchi** [foss-for-synopsys-dwc-arc-processors/toolchain#149]
Hi Anton,
Last year we report an issue to synopsys, the bug number is 9001072678. It is D-Cache related issue. 
The original issue is reported to mcc compiler.

Title: Data Cache May Evict Invalid Cache Line
Impacted Configuration: ARC 700 with Data Cache

Is there a work around for this issue? and if yes which version of the gcc toolchain contains the fix. 

Thank You

**Comment by fbedard** [comment]
Hi Emerson,

As i recall you requested the workaround be implemented in GCC also and changes were implemented and can be found here:  https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commits/arc-4.8-vixs

**Comment by emersonchi** [comment]
Hi Francois,
Since the change is not included in the arc-2017.09 branch, is the changeset 91a4d164e37c8f5f70378ab35073dc562689c32e, relate to the fix? or it is different.

Thanks

**Comment by claziss** [comment]
Hi,
The patch  you refer to is not related to D-Cache issue. It detects and avoids a load instruction which operates on the same address like the previous lexicographical store. This is a ARC700 Core issue.

Best
