### ISSUE TITLE
Building toolchain for ARC700 failed on glibc

### ISSUE THREAD

**Issue by reftekhari** [foss-for-synopsys-dwc-arc-processors/toolchain#150]
Tried to build toolchain for ARC700 and using glibc instead of uclibc. The build failed on glibc and here is the error message:
msort.c:201: Error: opcode 'dmb' not supported for target arc700

**Comment by iguryanov** [comment]
Hi Reza, 

I've shared last details via case, please check if you can rebuild toolchain and the kernel now. 

Regards,
Igor.
