### ISSUE TITLE
difference between WINDOWS platform and Linux Platform

### ISSUE THREAD

**Issue by inkstone** [foss-for-synopsys-dwc-arc-processors/toolchain#155]
We found this issue when we are working with our customized embarc_osp. Same code compiled with same TOOLCHAIN version except one on windows and one on linux. Only compiled on windows works.

For our customized code, we only try to add FreeRTOS's cli into embarc. We believe there are some issue related to toolchain itself. Any tips for further investigation this issue?

Thanks

**Comment by fbedard** [comment]
Which version of the GNU Toolchain are you using?  Can you also provide the error message you are seeing when compiling on linux?
