### ISSUE TITLE
int32_t is defined as "long int" instead of "int" for arc-elf32? Any reason for this?

### ISSUE THREAD

**Issue by inkstone** [foss-for-synopsys-dwc-arc-processors/toolchain#157]
The underlying definition disagrees with my impress. See following sample code:

   #include <stdio.h>
   #include <stdint.h>
   #include <stdlib.h>
   char buff[100];
   int main() {
        uint32_t d = 5;
        sprintf(buff, " %d\n", d);
        return 0;
   }

Here is what I got:
$ arc-elf32-gcc --specs=nsim.specs -mcpu=em4_dmips test_uint32.c -o test_uint32.elf -Wall
test_uint32.c: In function ‘main’:
test_uint32.c:9:26: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘uint32_t {aka long unsigned int}’ [-Wformat=]
         sprintf(buff, " %d\n", d);
                         ~^
                         %ld

If I use gcc on my local machine, there is no warning at all. 

It is very annoying since our project is now compiling with both GCC and Metaware. The later views "uint32_t" as "unsigned int" instead of "unsigned long int". Using Macro __GNU__ can work around this, but it is also means that __GNU__ will be put everywhere. Any solution here?

**Comment by anthony-kolesov** [comment]
Hi,

For uint32_t type correct format is `printf("%" PRIu32 "\n", (uint32_t) some_number);`, because it is not defined if `uint32_t` should be long or int - it should be 32 bits. https://en.cppreference.com/w/c/types/integer

I'm adding @claziss for compiler insight, but I doubt that it would be possible to change definition for intNN_t family in GCC.

**Comment by claziss** [comment]
Hi,

The latest gcc releases are checking and throwing more warnings and error when suspicious constructions are used.

long long defines a 64 bit variable. The uint32_t is correctly placed into a 32 bit register. Please use the correct sprintf format when using uint32_t.
