### ISSUE TITLE
Add option --strip to ./build-all.sh

### ISSUE THREAD

**Issue by anthony-kolesov** [foss-for-synopsys-dwc-arc-processors/toolchain#16]
Add option --strip, that will strip **host** executables from debug symbols. It will run `strip -g` on ./arc-elf32, ./arc-linux-uclibc, ./bin, ./libexec/gcc/4.8.0. Debug symbols doesn't make a lot of sense for end users, but they occupy 2/3 of space in compiled toolchain.

I would suggest make this a default value (providing --no-strip as a negation), but would be happy even if it would be an optional choice.

**Comment by amylaar** [comment]
Quoting Anthony Kolesov notifications@github.com:

> Add option --strip, that will strip _host_ executables from debug  
> symbols. It will run `strip -g` on ./arc-elf32, ./arc-linux-uclibc,  
> ./bin, ./libexec/gcc/4.8.0. Debug symbols doesn't make a lot of  
> sense for end users,

Till something breaks.

> but they occupy 2/3 of space in compiled  toolchain.

Most of arc-elf32 / arc-linux-uclibc is source or target code,
only their bin subdirs are host binaries

[amylaar@rowan INSTALL]$ du -s bin arc-elf32/bin arc-linux-uclibc/bin
76548   bin
4056    arc-elf32/bin
4068    arc-linux-uclibc/bin
[amylaar@rowan INSTALL]$ du -s arc-elf32/ arc-linux-uclibc/
294764  arc-elf32/
57344   arc-linux-uclibc/

So, clearly most of the stuff is target code.  Plus, the debug symbols
are not loaded into memory unless required by a debugger, so you are
really talking about mere disk space savings.

amylaar@rowan gcc]$ du -s ../../INSTALL/bin
76548   ../../INSTALL/bin
[amylaar@rowan gcc]$ du -s ../../INSTALL/arc-elf32/
294764  ../../INSTALL/arc-elf32/

**Comment by anthony-kolesov** [comment]
You've forgotten about ./libexec/ which contains 3 files over 60 MiB:

```
[akolesov@ru20-arctools toolchain]$ du -sh INSTALL/
390M    INSTALL/
[akolesov@ru20-arctools toolchain]$ du -shc INSTALL/arc-elf32/bin INSTALL/bin INSTALL/libexec/gcc/arc-elf32/4.8.0/
34M INSTALL/arc-elf32/bin
74M INSTALL/bin
196M    INSTALL/libexec/gcc/arc-elf32/4.8.0/
303M    total
```

This is ELF32 toolchain without without multilibs.

```
[akolesov@ru20-arctools toolchain]$ du -sh INSTALL INSTALL-stripped/
390M    INSTALL
148M    INSTALL-stripped/
```

With multilibs share will be less, but it is still 250MiB of stuff that normal people don't need. This makes moving toolchain around more difficult.

**Comment by jeremybennett** [comment]
I'm with Joern's experience. This is good until something breaks, and then you have no data from the customer.

I would be inclined to make it an option that is off by default, with a note in the user manual that customers concerned about space on their host machines may use it to reduce the size of their host binaries, but with the concomitant risks if they do run into problems.

If you would like to propose a patch, then I'm happy to review it for inclusion.

**Comment by jeremybennett** [comment]
Anton - I've assigned the issue to you, if you wish to propose a patch.

**Comment by anthony-kolesov** [comment]
Yes, it will be OFF by default. I mainly need it for myself with all of those nightly builds taking a lot of space. Customers wanting to distribute prebuilt toolchain also might find it useful.

**Comment by amylaar** [comment]
Quoting Jeremy Bennett notifications@github.com:

> I'm with Joern's experience. This is good until something breaks,  
> and then you have no data from the customer.

FWIW - one of the things that's supposed to work is that you can
recompile the same binary and find the debug info matching
the stripped binary / its core dump.
However, this might not work because of bit rot/bugs, and even if it
works, it's a lot more trouble than just keeping the debug info in the
first place.
Likewise, if you have something to debug interactively, having to rebuild
the toolchain first is possible, but a lot of hassle.

**Comment by anthony-kolesov** [comment]
Added as described here: #23.
