### ISSUE TITLE
ARC GNU IDE toolchain usage issues

### ISSUE THREAD

**Issue by BarryWang2017** [foss-for-synopsys-dwc-arc-processors/toolchain#160]
My name is Barry. Our team is working on an embedded project based on the ARC HSDK board. I encountered some problems when I tried to generate a Hello World routine using the ARC GNU IDE.[(arc_gnu_2018.03_ide_linux_install.tar.gz)](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/releases/download/arc-2018.03-release/arc_gnu_2018.03_ide_linux_install.tar.gz)

First, I opened the eclipse executable in the arc_gnu_ide/eclipse directory. And I created a new C++ project, as shown below. In this C++ project, I selected the project type ARC Cross uClibc Target Application, the toolchain type is Linux uClibc GCC For ARC HS.
![default](https://user-images.githubusercontent.com/33621708/45672287-573f0a00-bb5a-11e8-9f28-e826938ba80c.png)

After clicking the Finish button，the Eclipse automatically generates a Hello World code. Then I clicked the Build button to compile the project, but the compilation process was not completed. Instead, the following error occurred.
![2](https://user-images.githubusercontent.com/33621708/45678469-008cfc80-bb69-11e8-9e87-0d78f1a5953a.jpg)

What should I do next? Or is it a bug?

Waiting forword for your reply.

Thanks,
Barry

**Comment by anthony-kolesov** [comment]
Hi Barry,

This is some bug in the IDE. Can you try C Hello world project instead of C++ - does it work?

**Comment by BarryWang2017** [comment]
Thank you for your reply!
I tried to build a C Hello World project, but the same error occurred.


Thanks,

Barry

**Comment by MrsSima** [comment]
Hi,
We've found a problem and the fix will be merged next week.
Thanks!

**Comment by anthony-kolesov** [comment]
Hi Barry.

I'm attaching the build of ARC plugins that fixes this problem. To install it, you need first to uninstall current ARC plugins (see image), then install plugins from attached tarball via Eclipse "Help -> Install New Software" menu. 

New build: [arc_gnu_2018.03_ide_plugins.zip](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/2434376/arc_gnu_2018.03_ide_plugins.zip)


![image](https://user-images.githubusercontent.com/602123/46296741-ba418f80-c5a3-11e8-9c8b-2cc498e665b8.png)
