### ISSUE TITLE
arc-elf32-gcc with lcf file

### ISSUE THREAD

**Issue by yossi-itach** [foss-for-synopsys-dwc-arc-processors/toolchain#165]
hi
I would like to build arc-elf32-gcc with lcf file how could I do it?
the arc-elf32-gcc support tcf by Python script arc-elf32-tcf-gcc but I didn't find for lcf?

**Comment by claziss** [comment]
Hi,

There is no support or plan to support such an extension. I propose to close this issue, if everyone agrees.

**Comment by yossi-itach** [comment]
hi,
So how you add lcf into your code?

**Comment by cupertinomiranda** [comment]
Hi yossi,

Personally I don't know what is this lcf. Google does not seem to help much either.
Can you detail what is this LCF ?

**Comment by yossi-itach** [comment]
LCF is linker command file that created by TCF compile but somehow I don't know why when you used ccac with TCF file it's generate but when you use arc-elf32-gnu it's not created.
lcf example look as follow:
# link.lcf
# Linker command file and memory map
# Memory is available as follows on this example system 

MEMORY {
    VTABLE: ORIGIN = 0x00000000, LENGTH = 0x400	  
    CODE:   ORIGIN = 0x00000400, LENGTH = 0xFF00
    DATA:   ORIGIN = 0x00100000, LENGTH = 64K	  
    }
    
SECTIONS {
   # Vector table goes here
   GROUP: {	
	  vectors? : {}
   } > VTABLE

   # All code goes here
   GROUP: {	
      * (TEXT): {}
   } > CODE

   # All data goes here
   GROUP: {
      .rodata? : {}
      .sdata?: {}
      .sbss?: { * {.sbss} }
      _SDA_BASE_ = SIZEOF(.sdata) + SIZEOF(.sbss) <= 255 ? ADDR(.sdata) : ADDR(.sdata) + 256;
      * (DATA): {}
      * (BSS): {}
      .stack ALIGN(4) SIZE(DEFINED _STACKSIZE?_STACKSIZE:1024): {}
      .heap? ALIGN(4) SIZE(DEFINED _HEAPSIZE?_HEAPSIZE:1024): {}
   } > DATA

}

**Comment by claziss** [comment]
The tcf contains an equivalent lcf file for gnu. lcf file is mwdt specific.

**Comment by yossi-itach** [comment]
Where in tcf? le's say I want to change VTABLE or DATA size?

**Comment by anthony-kolesov** [comment]
Usage of linker scripts is documented in the Toolchain User Guide: https://embarc.org/toolchain/baremetal/linker.html GNU linker commands in TCF are also described in the documentations: https://embarc.org/toolchain/baremetal/tcf.html#memory-map

TCF contains section called "gnu_linker_command_file" that is the `memory.x` file described in the documentation. If you need functionality that is not available via `memory.x` facilities, then you need to develop the complete linker script, using standard GNU linker script syntax: https://embarc.org/man-pages/ld/Scripts.html#Scripts

**Comment by claziss** [comment]
Any other questions on this thread, I would like to close it.
