### ISSUE TITLE
init_ad() function is missed when linking the application with the library precompiled with Metaware toolchain

### ISSUE THREAD

**Issue by alexeysmirnovspb** [foss-for-synopsys-dwc-arc-processors/toolchain#166]
Hi,
I found that GNU linker reports the following error when I am trying to link my application with the library produced by MWDT:

```
c:/arc/arc_gnu/bin/../lib/gcc/arc-elf32/8.2.1/../../../../arc-elf32/bin/ld.exe: ../../../../board/iotdk/libs/10/libmli/libmli.a(mli_helpers.o): in function `mli_hlp_convert_tensor':
mli_helpers.c:(.mli_lib.mli_hlp_convert_tensor+0x80): undefined reference to `_init_ad'
```

Seems like the library contains the reference to MWDT-specific call. I checked MWDT C runtime sources and found that this call disables the data access alignment checking (i.e. allows the unaligned data access).
The equivalent call implementation is:

```
#define STATUS32      0x000a
void _init_ad(void) {
    uint32_t stat32 = _arc_aux_read(STATUS32) | 0x80000;
    __builtin_arc_flag(stat32);
}
```

Please consider adding this call to the ARC GNU C runtime to provide the compatibility with the Metaware libraries.

**Comment by claziss** [comment]
Hi,
GNU toolchain provides all necessary files and libraries to achieve an executable using the ARC-GNU toolchain. If one uses a third party library, then he/she should provide all the bits to get to his goal.
Regarding the function invoked, in general we cannot add MWDT runtime functions to GNU as they are protected by copyright rules. 
The ARC-GNU is compatible with the MWDT at the level of ABI, which means relocations, function calls, elf structure. We do not provide compatibility with the MWDT binary at a higher level.
