### ISSUE TITLE
Fix for store A7 cacheline hazard issue 

### ISSUE THREAD

**Issue by avinashpqtn** [foss-for-synopsys-dwc-arc-processors/toolchain#168]
Hi,

I am looking at this commit:

https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/895b3e9aa49c42c0052ba66738f1068cbf72881b

Does latest ARCGCC toolchain release(2018_09) includes this fix?

Thanks,
Avinash

**Comment by anthony-kolesov** [comment]
Hi Avinash,

Yes, this commit is included in the arc-2018.09 branch.

**Comment by avinashpqtn** [comment]
Thanks for the confirmation, Antony!

**Comment by anthony-kolesov** [comment]
Hi Avinash,

I got a note from our engineers that while option is present and supported, it might not used by default and thus the standard library for ARC700 is not built using that option, so to ensure that this hazard is not present, you'd need to rebuilt standard library and start files usign this opion. I'll try to get info from the compiler engineer of this is indeed needed.

**Comment by avinashpqtn** [comment]
Re-opening for additional inputs from Synopsys as above.

**Comment by claziss** [comment]
Hi,

The store hazard is in and enabled by default. For example, please consider the following C-source:

```c
volatile int a;
volatile int b;

void
foo ()
{
  a = 1;
  b = a;
}
```

Compiled with the next line:
```
arc-elf32-gcc -S -mcpu=arc700 -O2 arc700-stld-hazard.c 
````

we get:

```asm
        .section        .text
        .align 4
        .global foo
        .type   foo, @function
foo:
        mov_s r2,@a     ;14
        mov_s r3,1      ;0
        st_s r3,[r2]            ;18
        nop_s
        nop_s
        ld_s r2,[r2]            ;17
        st.as r2,[gp,@b@sda]    ;28
        j_s [blink]
        .size   foo, .-foo
```

Please let me know if this is what are you searching for.

**Comment by iguryanov** [comment]
Hi Avinash,

there were two workarounds for cacheline hazard, second one simply added nop after every N loads. 
This workaround is not included in 2018.09. 

As I know you are upgrading toolchain only for your latest chip. If this is correct then you don't need these nops inserted. 

Regards,
Igor.

**Comment by claziss** [comment]
Is here any new update, shall we close this issue?

**Comment by claziss** [comment]
Updated storehazard patch https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/5f1e3021dbd5f2a2f1a435cdce246d9fb289aa09. Close this one.
