### ISSUE TITLE
uclibc-ng: RPC support

### ISSUE THREAD

**Issue by avinashpqtn** [foss-for-synopsys-dwc-arc-processors/toolchain#169]
Hi @vineetgarc , @anthony-kolesov ,

We are planning to move to the latest ARCGCC toolchain for our products.

During compilation, I discovered that uclibc-ng does not support RPC. e.g rpc/rpc.h is not present inside include directory.

I also see that for glibc there is an option to enable RPC (see link_obsolete_rpc=yes). 
Is there any such configuration option provided for uclibc. If not, what are options to add RPC support?

**Comment by vineetgarc** [comment]
uClibc doesn't support RPC. You can use external libtirpc which is what buildroot does.
