### ISSUE TITLE
Mention tags in README.md

### ISSUE THREAD

**Issue by anthony-kolesov** [foss-for-synopsys-dwc-arc-processors/toolchain#17]
Readme should point users that they need to use tags to get stable release. I also suggest that along with "arc-4.8-R1", etc tags we would have a rolling tag "arc-stable" which would point to the current latest stable tag. If we will not add such a tag, then documentation should describe how to choose the latest tag (that arc_4_8-R1.2 is fresher than arc_4_8-R1, etc).

**Comment by jeremybennett** [comment]
Good idea about documenting the tags in README.md. Would you like to propose some text.

I don't think "arc-stable" is a good idea. IMO tags should be fixed, not changing. I think with clear documentation, the user will know to select an appropriate tag!

We can then make the dev branch the default, since the user will be able to read about the release tags.

**Comment by amylaar** [comment]
Quoting Jeremy Bennett notifications@github.com:

> I don't think "arc-stable" is a good idea. IMO tags should be fixed,  
>  not changing. I think with clear documentation, the user will know  
> to select an appropriate tag!

IIRC, we said we can get rid of the stable branch by pointing to
the latest stable point in the branch.
Do you mean the tags should instead be something like arc-stable-<date> ?
I suppose you could set them after a successful regression test, and
hopefully you also have a system in place that can map the tag to the
test logs.
However, if someone just wants the latest stable sources, a moving tag
is still useful.
Well, if it is really the duplicate of a dated tag, that should make it
less hard to replicate builds?

**Comment by anthony-kolesov** [comment]
Implemented: https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/pull/19
