### ISSUE TITLE
Checkout of Linux sources is incorrect under some circumstances

### ISSUE THREAD

**Issue by anthony-kolesov** [foss-for-synopsys-dwc-arc-processors/toolchain#170]
There is a bug in the toolchain build scripts (https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/blob/ec17f7c27b3d75bc18be348636643e0b3f93364d/arc-versions.sh#L96) - the goal is to checkout Linux sources if either glibc or uclibc is selected, however condition as-it stands does exact inverse. As a result, when user is building the baremetal toolchain scripts try to checkout the Linux sources, but when user is building Linux toolchain - sources are not checked out.

However fixing this is not as trivial as just inverting an expression. It is possible for the user to pass `--no-elf32 --no-uclibc --no-glibc` options - thus not building anything but checking out the sources to correct branches/tags. However if expression will be fixed, then this combination of options will not checkout the Linux sources. As it stands, right now, expression depends only on variables which indicate if uclibc or glibc toolchain is being *built*, assuming that there is some toolchain always being built. I think that to properly fix an issue, it is needed that this expression also to check for `DO_ELF32` variable, and if all three `DO_*` variables are not set - then it reverts to checking out the Linux sources. Note that there is a second issue lurking here - currently  `--no-elf32 --no-uclibc --no-glibc` will checkout the uclibc sources, but it will not checkout the glibc sources. This is harder to address, because we don't require both uclibc and glibc soruces to be present, so perhaps script should checkout repos if directories exist, but silently skip them if they are not present? I'm not 100% sure which would be best. One option would be to actually separate `arc-versions.sh` from `build-all.sh` - so build-all.sh will not call it, user must call it explicitly, thus user may pass different options to `arc-versions.sh` from what they would pass to `build-all.sh`. 
the the condition there is wrongly inverted and it doesn’t checkout Linux sources when building the Linux toolchain, and checks out them when not building the Linux toolchain. 

FB:  How does building linux toolchain succeed in our regression env with this issue? 

Though there is an additional problem, because it seems to me that in current configuration, should I correct the condition, then Linux sources will not be checked out in some other cases, when they should, so fixing the problem is not just about adding the logical “not”.

**Comment by abrodkin** [comment]
> FB: How does building linux toolchain succeed in our regression env with this issue?

I guess we normally don't pass that a bit of a nonsense combo: `--no-elf32 --no-uclibc --no-glibc`.

And I don't really see any reason for having that implicit "source checkout" target, maybe just add a special option like `--checkout-sources` that does exactly what user expects from it?

**Comment by anthony-kolesov** [comment]
According to my latest check, `release.mk` in fact does not rely on this functionality - it uses git directly to get proper branches/tags.

**Comment by abrodkin** [comment]
> 
> 
> According to my latest check, `release.mk` in fact does not rely on this functionality - it uses git directly to get proper branches/tags.

So do we need to do something here still then?

**Comment by anthony-kolesov** [comment]
Yes, I think so, I'm just noting that changes will not have direct effect on release process. But the issue is still there.

Adding `--checkout-sources` option will not help, I think, because there is still a question of what repositories to checkout - the script needs to know if uclibc, linux, glibc and newlib should be checked out or not. Which is why I would propose that `arc-versions.sh` should be invoked separately using it's own set of options. Or you can make `--checkout-sources` cancel further build and use options only to identify what to checkout.

**Comment by abrodkin** [comment]
That behavior seems to not get in the way for current active users of this script, so I'm closing it now. If for anybody that becomes a problem later, we'll get back to it.
