### ISSUE TITLE
[dejagnu:g++]  C++11: hexfloat doesn't work

### ISSUE THREAD

**Issue by fbedard** [foss-for-synopsys-dwc-arc-processors/toolchain#173]
hexfloat seems not to work.

Failure:
FAIL: 27_io/basic_ostream/inserters_arithmetic/char/hexfloat.cc execution test

Reason:
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stod

Suspect lib issue whrere stod (strtod) doesn't support hexfloat

See:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=64054

**Comment by abrodkin** [comment]
Still happens in 2020.09. @claziss if that's a low-hanging fruit, can we mark it for 2021.03?

**Comment by claziss** [comment]
Upstream fixed
