### ISSUE TITLE
[dejagnu:g++] Dwarf2 info not accurate/missing

### ISSUE THREAD

**Issue by fbedard** [foss-for-synopsys-dwc-arc-processors/toolchain#174]
The following dwarf tests are failing:

FAIL: g++.dg/debug/dwarf2/non-virtual-thunk.C  -std=gnu++98  scan-assembler thunk.C:30
FAIL: g++.dg/debug/dwarf2/non-virtual-thunk.C  -std=gnu++11  scan-assembler thunk.C:30
FAIL: g++.dg/debug/dwarf2/non-virtual-thunk.C  -std=gnu++14  scan-assembler thunk.C:30

Suspecting this to be a mainline issue.

**Comment by abrodkin** [comment]
Still happens in 2020.09. @claziss if that's a low-hanging fruit, can we mark it for 2021.03?

**Comment by claziss** [comment]
Mainline update.
