### ISSUE TITLE
[dejagnu:gcc] Division fails in gcc tests for optimized floating point lib

### ISSUE THREAD

**Issue by fbedard** [foss-for-synopsys-dwc-arc-processors/toolchain#175]
Failures occur in gcc/testsuite/gcc.target/arc/ieee_div.c. Information in gcc.log file:

Runtime computation error @66. inf != 0
Runtime computation error @68. inf != 0
Runtime computation error @69. -inf != 0
Runtime computation error @70. -inf != 0
Runtime computation error @71. inf != 0
Runtime computation error @73. inf != 0
Runtime computation error @74. -inf != 0
Runtime computation error @75. -inf != 0
Runtime computation error @76. inf != 0
Runtime computation error @91. inf != NaN
Runtime computation error @92. inf != NaN
Runtime computation error @93. 0 != NaN
Runtime computation error @94. 0 != NaN
Runtime computation error @96. inf != NaN
Runtime computation error @97. inf != NaN
Runtime computation error @98. 0 != NaN
Runtime computation error @99. 0 != NaN

*** EXIT code 4242
FAIL: gcc.target/arc/ieee_div.c execution test

**Comment by claziss** [comment]
These errors are related to *ARC700* floating point division implementation in libgcc.

**Comment by BrunoASMauricio** [comment]
I cannot find the "ieee_div.c" test in GCC testsuite. Ran GCC tests for arcv2 and nothing popped up. Will close for the time being until issue comes up again or more information is made available.
