### ISSUE TITLE
Support programming of EMSK FPGAs from openOCD

### ISSUE THREAD

**Issue by fbedard** [foss-for-synopsys-dwc-arc-processors/toolchain#181]
Add support of programming of FPGA from OpenOCD.  Different FPGAs might require different code, EMSK's use Spartan-6 LX150 device. 

OpenOCD supports programming of Virtex-2. Code is mainly just reading a *.bit file and then a bunch of JTAG commands so it looks relatively simple assuming Spartan-6 does not differ too much from Virtex-2.

This feature will allow users to program FPGA without using proprietary software.

**Comment by abrodkin** [comment]
@fbedard do we really need this? I was under impression that EMSK's FPGA was never meant to be programmable by a end-user. Moreover the board comes bundled with a couple pre-programmed .bit-files so that customers may chose the one which matches his or her needs the best.

**Comment by fbedard** [comment]
No, no longer needed.  Closing.
