### ISSUE TITLE
Support XML target descriptions on Linux targets

### ISSUE THREAD

**Issue by fbedard** [foss-for-synopsys-dwc-arc-processors/toolchain#188]
With GDB client supporting XML target descriptions gdbservers should be updated to use that feature appropriately, instead of current "compatible" fixed register set.

In this case that feature relates to both gdbserver and native GDB. Although native GDB doesn't need to use XML descriptions directly, still register set should same for gdbserver and native GDB.

**Comment by shahab-vahedi** [comment]
[arc: Add ARCv2 XML target along with refactoring](https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=995d3a197d7)
