### ISSUE TITLE
Support Synopsys ARC development systems in libgloss

### ISSUE THREAD

**Issue by fbedard** [foss-for-synopsys-dwc-arc-processors/toolchain#189]
libgloss is intented to contain BSPs for newlib.  Support for all Synopsys ARC Dev systems should be added, with tutorial on how to use that when compiling applications.

**Comment by claziss** [comment]
Closing commit https://github.com/foss-for-synopsys-dwc-arc-processors/newlib/commit/9fd48b9881a30a124228f71f97d39ab015bc34f6
