### ISSUE TITLE
gdb fails when command "stepi" used near "llock/scond" ARC assembly instructions

### ISSUE THREAD

**Issue by fbedard** [foss-for-synopsys-dwc-arc-processors/toolchain#191]
gdb fails when command "stepi" used near "llock / scond" ARC assembly instructions.

I tried to debug userspace path of "fprintf" libcall from uClibc.

Here is part of code I tried to debug:
```
   0x2008aaa0 <__GI_vfprintf+64>:       ld         r2,[fp,-76]
   0x2008aaa4 <__GI_vfprintf+68>:       add_s      r2,r2,56
   0x2008aaa6 <__GI_vfprintf+70>:       st         r2,[fp,-16]
   0x2008aaaa <__GI_vfprintf+74>:       ld         r3,[fp,-16]
   0x2008aaae <__GI_vfprintf+78>:       mov_s      r4,1
   0x2008aab0 <__GI_vfprintf+80>:       llock      r2,[r3]
   0x2008aab4 <__GI_vfprintf+84>:       brne       r2,0,0x2008aac0 <__GI_vfprintf+96>

   0x2008aab8 <__GI_vfprintf+88>:       scond      r4,[r3]
   0x2008aabc <__GI_vfprintf+92>:       bnz        0x2008aab0 <__GI_vfprintf+80>

   0x2008aac0 <__GI_vfprintf+96>:       st         r2,[fp,-20]
   0x2008aac4 <__GI_vfprintf+100>:      ld         r2,[fp,-20]
   0x2008aac8 <__GI_vfprintf+104>:      st         r2,[fp,-24]
```

Here is gdb out, when I executed code using "stepi" command:

```
0x2008aaa0 <__GI_vfprintf+64>: ld         r2,[fp,-76]
0x2008aaa4 <__GI_vfprintf+68>: add_s      r2,r2,56
0x2008aaa6 <__GI_vfprintf+70>: st         r2,[fp,-16]
0x2008aaaa <__GI_vfprintf+74>: ld         r3,[fp,-16]
0x2008aaae <__GI_vfprintf+78>: mov_s      r4,1
0x2008aab0 <__GI_vfprintf+80>: llock      r2,[r3]
0x2008aab4 <__GI_vfprintf+84>: brne       r2,0,0x2008aac0 <__GI_vfprintf+96>
0x2008aab8 <__GI_vfprintf+88>: scond      r4,[r3]
0x2008aabc <__GI_vfprintf+92>: bnz        0x2008aab0 <__GI_vfprintf+80>
0x2008aab0 <__GI_vfprintf+80>: llock      r2,[r3]
0x2008aab4 <__GI_vfprintf+84>: brne       r2,0,0x2008aac0 <__GI_vfprintf+96>
0x2008aab8 <__GI_vfprintf+88>: scond      r4,[r3]
0x2008aabc <__GI_vfprintf+92>: bnz        0x2008aab0 <__GI_vfprintf+80>
0x2008aab0 <__GI_vfprintf+80>: llock      r2,[r3]
0x2008aab4 <__GI_vfprintf+84>: brne       r2,0,0x2008aac0 <__GI_vfprintf+96>
0x2008aab8 <__GI_vfprintf+88>: scond      r4,[r3]
0x2008aabc <__GI_vfprintf+92>: bnz        0x2008aab0 <__GI_vfprintf+80>
0x2008aab0 <__GI_vfprintf+80>: llock      r2,[r3]
```
... And so on ...

If I tried to use instruction like "next" or "step" after first time "llock / scond" loop occurred gdb hangs up (because in execute "llock / scond" loop infinitely).

This problem occurred when I used gdb as well as I used gdbserver.
Target platform is nSIM HS38 and axs103 devboard (so it isn't simulator bug).
gdb/uClibc/linux image/etc are build using buildroot.
gdb version is 2016.03
gcc-2016.03
binutils-2016.03
uclibc-1.0.15

**Comment by shahab-vahedi** [comment]
This is reproducible by the current [state](https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/tree/2dac47516529458fa1e6d69afa66ff49835517e4) of [arc-2019.09-gdb](https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/tree/arc-2019.09-gdb). I have used an `arc-2019.09` uClibc Linux image on an **HSDK board**. The example code is [attached](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/3789288/gdb-atomic-stuck.zip)


![gdb-atomic-stuck](https://user-images.githubusercontent.com/16524902/67864706-50891180-fb26-11e9-8ae3-b211fdc959da.gif)

The code of intereset is:
```
main+14: llock   r2,[r0]      ; initiate an atomic write by setting LF=1
main+18: brne.nt r2,0,main+30 ; somebody else wrote? break if so.
main+22: scond   r3,[r0]      ; only write if LF is still 1
main+26: bne     main+14      ; did we succeed? try again if not.
main+30: mov_s   r0,0         ; outside atomic write
```
The key here is that `LF` must remain set. Under 2 circumstances it gets cleared:
1. Another entity writes to the address associated (`[r0]`) --> will lead to _waiting_
2. An exception or interrupt is raised --> this is what happens when debugging with `ni`/`si`

The problem here is the *rise of exception* between `llock` and `scond`. I expect a `next` (source level), not to cause any exception in this block, but apparently it does. For now, the workaround is to use `until`  with a target outside the atomic block (or next source line).

**Comment by shahab-vahedi** [comment]
One can consider this an **anti-debugging technique** ;)

**Comment by shahab-vahedi** [comment]
Commit [[Fix] Do not interrupt atomic sequences](https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/commit/28d6f6c863299466a062cd3ff6a4572d08dab230) in [arc-2019.09-gdb](https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/tree/arc-2019.09-gdb) resolves this issue.

![gdb-atomic-solved](https://user-images.githubusercontent.com/16524902/67967973-d7adb680-fc06-11e9-9e84-029a5ed67f7f.gif)

```
[FIX] Do not interrupt atomic sequences

An atomic sequence looks something like below:
 50: llock   r2,[r0]         ; initiate an atomic write by setting LF=1
 54: brne.nt r2,0,66         ; somebody else wrote? break if so.
 58: scond   r3,[r0]         ; only write if LF is still 1
 62: bne     fwrite+50       ; did we succeed? try again if not.
 66: brne_s  r2,0,148        ; another thread won the game, go waiting
 68: st      r18,[r13,64]    ; welcome to the realm

Normally GDB sets breakpoint on evey instructions. This means that
there are exceptions raised between "llock" and "scond". When that
happens the "LF" flag is cleared and we lose the atomicity.

This patch teaches GDB the pattern of "llock .. scond" and will set
the next breakpoint _after_ scond. No matter if you use "n", "ni",
"s", "si"; they all will skip over the atomic sequence now. If you
really want to break in between you must explicitly set a breakpoint.

Signed-off-by: Shahab Vahedi <shahab@synopsys.com>
```
