### ISSUE TITLE
Missing explicit register file initialization

### ISSUE THREAD

**Issue by iguryanov** [foss-for-synopsys-dwc-arc-processors/toolchain#193]
Hi, 

Our run-time does not have explicit register file initialization. This creates problems for RTL simulation (as registers are in X state, not in 'random'), and might also hit designs with ECC-protected register file. 

At first issue was reported against startup, then it was found in exit code, and I see other potential scenarios. So instead of minor fix (like stopping use of r0/r1 in startup) we should explicitly reset core registers. As second issue is deep in libc.a, and third may happen at any time, would it make sense to have registers always initialized? Or inject initialization code at link time using weak symbols. 

Here are points of pain:

**1 - crt0.S assumes that r0 is argc and r1 are argv arguments of main().** 
      It moves them for a short time into r13/r14 so _init can be executed. Here we have first issue with non-initialized registers read. 
```asm
; Some  targets use the .init and .fini sections to create constructors and
; destructors, and for these targets we need to call the _init function and
; arrange for _fini to be called at program exit.
	mov_s	r13, r0
	mov_s	r14, r1
...
        jl	@_init
...
	mov_s	r0, r13
	mov_s	r1, r14
...	mov	fp,0			; initialize frame pointer
	jl	@main
```

**2 - __call_exitprocs() from libc.a(lib_a-__call_atexit.o)**
     This C function dumps scratch registers, and for simple applications (like SoC test suite) they might be still uninitialized. 

```asm
__call_exitprocs:
 294: c0f1                     push_s	%blink
 296: 1cfcb508                 push	%r20
 29a: 1cfcb4c8                 push	%r19
 29e: 1cfcb488                 push	%r18
 2a2: 1cfcb448                 push	%r17
 2a6: 1cfcb408                 push	%r16
 2aa: c7e1                     push_s	%r15
 2ac: c6e1                     push_s	%r14
 2ae: c5e1                     push_s	%r13
......
```

**3 - any interrupt or exception handler calling external function will dump register file onto stack.** 
     So, RTL simulation or ECC core will go wild. 

Regards,
Igor.

**Comment by claziss** [comment]
@iguryanov adding an initialization for all regs will solve the problem? looks to me like that.

**Comment by iguryanov** [comment]
should solve. But our cores are configurable and MWDT startup is not trivial on that part - 32/16 regs, 1 or more banks of registers, number of registers in secondary banks, etc...

**Comment by claziss** [comment]
aha, I need to add into crt0 a runtime checker which will choose for the right init. Probably this will not be in in the next release :(

**Comment by iguryanov** [comment]
runtime check might take space you don't want to give away. metaware startup sequence is defined with hardware options passed to buildlib utility and compile-time conditions. I guess we can skip one release - if somebody is affected again we will provide with temp workaround.

**Comment by iguryanov** [comment]
similar issue in another place - pushing r13 on the stack while it was not used before and holding 0xXXXXXXXX:

```asm
__do_global_ctors_aux:
700002e4: 16007002 80000424        ld	%r2,[0x8000_0424]		; __CTOR_LIST__
700002ec: 7754                     cmp_s	%r2,-1
700002ee: 7ce0                     jz_s	[%blink]
700002f0: c0f1                     push_s	%blink
700002f2: c5e1                     push_s	%r13 ; <==========
700002f4: 45cb 80000424            mov_s	%r13,0x8000_0424		; __CTOR_LIST__
```

**Comment by claziss** [comment]
A simple register cleanup patch here:
https://github.com/foss-for-synopsys-dwc-arc-processors/newlib/commit/56c86e63af1253a2ce52a2be3247e09d342becb7

**Comment by abrodkin** [comment]
Fixed with the commit mentioned above.
