### ISSUE TITLE
Error: invalid register number, should be pcl for instruction 'leave_s' 

### ISSUE THREAD

**Issue by abrodkin** [foss-for-synopsys-dwc-arc-processors/toolchain#197]
Built arc-2019.09-rc1 tools with our scripts in Ubuntu 18.04.3 Docker (i.e. clean environment) as simple as `./build-all.sh --no-uclibc` got a failure on newlib building which happens due to AS error:
```
./arc-elf32-as -mcpu=arcem -mcode-density test.S -v
GNU assembler version 2.33.50 (arc-elf32) using BFD version (ARCompact/ARCv2 ISA elf32 toolchain arc-2019.09-rc1) 2.33.50.20191002
test.S: Assembler messages:
test.S:4: Error: invalid register number, should be pcl for instruction 'leave_s'
```

Test-case is:
```
        enter_s {r13-r19, blink} ; sp=sp+(-32)
        mov_s   r16,r3  ;4
        mov_s   r2,r3   ;4
        leave_s {r13-r19, blink} ; sp=sp+32
```
Note it was generated by CC right before (i.e. it isn't hand-crafted something).

Also note AS from prebuilt tools (https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/releases/download/arc-2019.09-rc1/arc_gnu_2019.09-rc1_prebuilt_elf32_le_linux_install.tar.gz) happily assembles this example.

Attached is misbehaving AS: [arc-elf32-as.zip](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/3825178/arc-elf32-as.zip).

**Comment by claziss** [comment]
I cannot reproduce this issue at my end. Probably it is a miss-compilation on your setup, which I cannot control or influence. Please update your host compiler at your end or/either other support tools and libs.

**Comment by abrodkin** [comment]
@claziss for the record could you please specify which Linux distro do you use for building a toolchain on your end?

**Comment by claziss** [comment]
@abrodkin I use latest Fedora witih gcc 9.1.x. I also use a docker container to build the toolchain. Here it is :
https://github.com/claziss/arc-gnu-docker

And for windows toolchain I use:
https://github.com/claziss/arc-win-docker

And for testing ;)
https://github.com/claziss/arc-testing-docker

Unfortunately, I cannot really use travisCI with them as it take too long and travisCI jobs time out :(

**Comment by abrodkin** [comment]
As per @anthony-kolesov something similar was observed much earlier with Ubuntu 17.10 and given this problem still happens with Ubuntu 18.04 it worth looking closer at it.

**Comment by abrodkin** [comment]
Attached binary of the cross-assembler has debug info so in GDB with:
```
set substitute-path /arc_gnu/binutils __your_path_to_binutils__
b opcodes/arc-opc.c:616
```
you may stop at mentioned error message.

**Comment by jeremybennett** [comment]
If it helps as a small example, Embench (see https://github.com/embench/embench-iot) hits this when compiling `aha-mont64.c` using GCC top-of-tree (commit a9d06ea05ab). Compile command was:
```C
arc-elf32-gcc -c -ggdb3 -fdata-sections -ffunction-sections \
	      -mcpu=em4 -Os -mcode-density -I~/embench-iot/support \
	      -I~/embench-iot/config/arc/boards/generic \
	      -I~/embench-iot/config/arc/chips/em \
	      -I~/embench-iot/config/arc \
	      -DCPU_MHZ=1 -DWARMUP_HEAT=1 -o mont64.o \
	      ~/embench-iot/src/aha-mont64/mont64.c
```
Output was:
```
/tmp/ccPqPANh.s: Assembler messages:
/tmp/ccPqPANh.s:153: Error: invalid register number, should be pcl for instruction 'leave_s'
```
No problem if I compile with `-mcpu=em`, but then I can't use `-mcode-density`

**Comment by jeremybennett** [comment]
Furthermore, this example compiles fine with `-mcpu=em4_dmips`, but then the `minver` example blows up with a different message:
```C
arc-elf32-gcc -c -ggdb3 -fdata-sections -ffunction-sections -mcpu=em4_dmips \
	      -Os -mcode-density -I~/embench-iot/support \
	      -I~/embench-iot/config/arc/boards/generic \
	      -I~/embench-iot/config/arc/chips/em -I~/embench-iot/config/arc \
	      -DCPU_MHZ=1 -DWARMUP_HEAT=1 -o libminver.o \
	      ~/embench-iot/src/minver/libminver.c
```
which gives the error message:
```
/tmp/ccyAbrwn.s: Assembler messages:
/tmp/ccyAbrwn.s:795: Error: invalid register number, should be blink for instruction 'enter_s'
```

**Comment by jeremybennett** [comment]
I see the same behavior in the GCC 9.2 release code base as well.

**Comment by abrodkin** [comment]
@jeremybennett we only managed to get that problem reproduced on Ubuntu starting from 17.10. If we build ARC toolchain on other Linux distros this problem never happens. I'm wondering which distro do you use?

**Comment by claziss** [comment]
@jeremybennett @abrodkin both gcc and binutils (top of tree) correctly handles enter and leave instructions in my fedora setup. It looks to me a compilation issue of the x86 compiler in your setup. Which gcc version of the compiler do u use?

**Comment by jeremybennett** [comment]
@claziss Just done a quick check:
```
$ gcc --version
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
```
I'm not at work at the moment, but I'll dig out the exact configure line for binutils-gdb and gcc tomorrow.

**Comment by claziss** [comment]
There is a memory leak found and fixed lately in binutils. I don't know if it has any connection with observed behaviour for ARC but I let it here for reference.
https://sourceware.org/bugzilla/show_bug.cgi?id=24960

**Comment by abrodkin** [comment]
This is now fixed with https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/commit/91be564da5af9bef8f9fbbd223e76be6d2e81484.

**Comment by claziss** [comment]
Pushed to binutils mainline https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=commit;h=2a1ebfb221f5f52a743b7ea4c504a7318956c49c
