### ISSUE TITLE
Buildroot: oprofile fails to build with arc-2019.09 toolchain

### ISSUE THREAD

**Issue by EvgeniiDidin** [foss-for-synopsys-dwc-arc-processors/toolchain#199]
With recent introduction of arc-2019.09-rc1(eng002) toolchain in buildroot the "oprofile" package started to fail:
http://autobuild.buildroot.net/results/0e0/0e0d7587dc2117d7ea97571f1533d9640d227cc7//

It was tested that with upstream binutils (ver: 2.32, 2.33, 2.33.1) the error does not reproduces.
Also recent ARC-specific commits didn't cause the error - with binutils rev:
https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/commit/de4859eacb74a440d9fd61e4a0f051e3737a05dd
the error still reproduces.

Actually here is the commit which has caused the error:
https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=commit;h=fd3619828e94a24a92cddec42cbc0ab33352eeb4
and it is in master branch, but not in binutils-2_33-branch.

**Comment by claziss** [comment]
As far as I understand, there is nothing which I can do here. Please close this issue if there are no other developments.

**Comment by EvgeniiDidin** [comment]
Closing the issue do generic upstream change, nothing related with ARC.
