### ISSUE TITLE
[LD]arc-2019.09-rc2/archs:  ld with "-G" option causes change of arch to ARCompact

### ISSUE THREAD

**Issue by EvgeniiDidin** [foss-for-synopsys-dwc-arc-processors/toolchain#209]
Dmalloc package builds in Buildroot autobuilder started to fail with latest arc-2019.09-rc2 toolchain. Building package for archs fails with the message that binaries were compiled for ARCompact.

The error can be reproduced with simple application:
```
int main(){ return 0; }
```
and next sequence of commands:
```
cd ~/arc_gnu_2019.09-rc2_prebuilt_uclibc_le_archs_linux_install/bin
./arc-linux-gcc  main.c
./arc-linux-ar cr libaaa.a a.out
./arc-linux-ranlib libaaa.a
./arc-linux-readelf -h libaaa.a

File: libaaa.a(a.out)
ELF Header:
  Magic:   7f 45 4c 46 01 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF32
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           ARCv2

./arc-linux-ld -G -o libaaa.so  libaaa.a
./arc-linux-readelf -h libaaa.so
ELF Header:
  Magic:   7f 45 4c 46 01 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF32
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              DYN (Shared object file)
  Machine:                           ARCompact

```
Note! without "-G" key the target architecture remains unchanged.
The issue also reproduces on arc-2019.03-release toolchain.

**Comment by claziss** [comment]
From ld help:
`-G SIZE, --gpsize SIZE      Small data size (if no size, same as --shared)` 

thus, the same effect can be seen if we pass instead of `-G` `--shared`.

**Comment by claziss** [comment]
It is very strange the procedure which you have, it took me a while to realize it :) You want to create a dynamic library out of a static one. The linker will just throw the archive, and will create an empty library. You can easily see that from your example as the readelf command will not say a thing about `a.out` object. Hence, the empty dynamic lib is created using the default flags which in our case is ARCv1. Similar results you get also on a `x86` machine.
