### ISSUE TITLE
GCC: Some arc built-ins are not documented

### ISSUE THREAD

**Issue by abrodkin** [foss-for-synopsys-dwc-arc-processors/toolchain#213]
We do have quite some `__builtin_arc_xxx` functions documented in the official GCC documentation, see https://gcc.gnu.org/onlinedocs/gcc/ARC-Built-in-Functions.html but some which we do implement (see https://gcc.gnu.org/viewcvs/gcc/trunk/gcc/config/arc/builtins.def?view=markup) are not documented.

For example the following built-ins are missing in the documentation:
* `__builtin_arc_ffs()`
* `__builtin_arc_fls()`
* `__builtin_arc_clri()`
* `__builtin_arc_kflag()`
* `__builtin_arc_seti()`

Also none of SIMD-related built-ins is mentioned at all.

**Comment by iguryanov** [comment]
Hi Claudiu, 

could you please update with 2021.03 release? 

Regards,
Igor.

**Comment by claziss** [comment]
Updated here: https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/484bdc96a7358e64ac84954036a932df39643382
