### ISSUE TITLE
[GDB]: dejagnu tests fail because "gdb_tg.o" is not found.

### ISSUE THREAD

**Issue by shahab-vahedi** [foss-for-synopsys-dwc-arc-processors/toolchain#222]
binutils branch: `20190.09nx`

When running GDB's testsuite, many tests (~180) fail because GCC cannot compile them:
```
gdb compile failed, arc-elf32-gcc: error: gdb_tg.o: No such file or directory
```

`gdb_tg.o` does exist and it has been used by many test cases. It seems like some of the tests "cd" to other directories and then the compilation will break.

Attached you will find the necessay scripts and README to reproduce this issue for one of the tests on your system.

[gdb-no-test-glue.zip](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/3989257/gdb-no-test-glue.zip)

**Comment by shahab-vahedi** [comment]
A fix has been [proposed](https://sourceware.org/ml/gdb-patches/2020-02/msg00382.html) upstream.

**Comment by shahab-vahedi** [comment]
The fix has been [merged upstream](https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=commit;h=24ac169ac5a918cd82b7485935f0c40a094c625e) and rebased.

**Comment by abrodkin** [comment]
Fixed by https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/commit/24ac169ac5a918cd82b7485935f0c40a094c625e in `arc-2020.03`.
