### ISSUE TITLE
[GDB]: tdesc-regs.exp fails

### ISSUE THREAD

**Issue by shahab-vahedi** [foss-for-synopsys-dwc-arc-processors/toolchain#223]
binutils branch: `2019.09nx`

Test `tdesc-regs.exp` fails:
```
FAIL: gdb.xml/tdesc-regs.exp: maintenance print reggroups
```

The problem seems to be related to the fact that GDB does not recognize the "general" register groups anymore. This needs further investigations and could cause other problems (#224).

Use the attached data to reproduce the test after making the adjustments according to the README.

[gdb-target-desc.zip](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/3989296/gdb-target-desc.zip)

**Comment by shahab-vahedi** [comment]
commit [6df4907](https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/commit/6df4907808984673d7081ce8b63c15c35e6d5189) fixes this.

**Comment by abrodkin** [comment]
This is the same fix in `arc-2020.03` branch: https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/commit/64e06e5b062a911d87987a7763669a076259a861.
