### ISSUE TITLE
[GDB]: In TUI mode, if source is small, GDB crashes.

### ISSUE THREAD

**Issue by shahab-vahedi** [foss-for-synopsys-dwc-arc-processors/toolchain#225]
binutils branch: `2019.09nx`

If the number of lines to be printed in GDB's `asm` layout is not big enough to exceed over the layout, GDB will crash:
![gdb-layout-src-crash_nok_with_layout](https://user-images.githubusercontent.com/16524902/71277716-f3575280-2355-11ea-8e36-6ee27f921d80.gif)

However, if there is no layout mode, it proceeds happily:
![gdb-layout-src-crash_ok_without_layout](https://user-images.githubusercontent.com/16524902/71277641-bee39680-2355-11ea-95e6-38ff4263ec3c.gif)

Use attached data set to reproduce and even compare with another target that works fine.
[gdb-layout-src-crash.zip](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/3989448/gdb-layout-src-crash.zip)

**Comment by shahab-vahedi** [comment]
This is a problem in GDB's TUI and a [bug has been submitted](https://sourceware.org/bugzilla/show_bug.cgi?id=25345). This [patch](https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=cbfa85811792ca8e96ace40bef0aaaf507e54bcc) takes care of half of it and soon there is going to be another [one](https://sourceware.org/ml/gdb-patches/2020-01/msg00438.html) to close it for good.

**Comment by shahab-vahedi** [comment]
The issue is solved upstream:

[GDB: Fix the overflow in addr/line_is_displayed()](https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=cbfa85811792ca8e96ace40bef0aaaf507e54bcc)
[gdb/tui: Prevent exceptions from trying to cross readline](https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=2f267673f0fdee9287e6d404ecd4f2d29da0d2f2)
[gdb/tui: asm window handles invalid memory and scrolls better](https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=733d0a679536628eb1be4b4b8aa6384de24ff1f1)

Soon I will do a rebase.

**Comment by shahab-vahedi** [comment]
it has been rebased with yet one [tiny issue](https://sourceware.org/ml/gdb-patches/2020-01/msg00780.html).

**Comment by shahab-vahedi** [comment]
And this [patch](https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=42330a681af23a80d3e1f201d2a65886875e74bd) completely resolves the issue (still we need a rebase at this point to get it in).

**Comment by shahab-vahedi** [comment]
rebased.

**Comment by abrodkin** [comment]
Fixed by https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/commit/42330a681af23a80d3e1f201d2a65886875e74bd in `arc-2020.03`.
