### ISSUE TITLE
[GDB]: Registers are not updated if source file is not found.

### ISSUE THREAD

**Issue by shahab-vahedi** [foss-for-synopsys-dwc-arc-processors/toolchain#226]
binutils branch: `2019.09nx`

If GDB is in source layout:
```
gdb> layout source
```
and for whatever reason GDB cannot locate the necessary source file(s):
```
... crt0.S: No such file or directory
```
If you intiate a target remote:
```
gdb> target remote ...
```
The register information is not received from the other end. However, if you change to another layout (say `layout asm`), then it goes OK. Watch below for a demonstration of both:
![gdb-missing-src-bad-reg-neg](https://user-images.githubusercontent.com/16524902/71278394-c6a43a80-2357-11ea-814c-0206a6a90645.gif)

This behavior leads to nSIM's crash (but QEMU survives).

Use attached data to reproduce.
[gdb-missing-src-bad-reg-neg.zip](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/3989479/gdb-missing-src-bad-reg-neg.zip)

**Comment by shahab-vahedi** [comment]
This is an upstream issue and a [fix has been proposed](https://sourceware.org/ml/gdb-patches/2020-02/msg00127.html).

**Comment by shahab-vahedi** [comment]
[second revision of the fix with a test](https://sourceware.org/ml/gdb-patches/2020-01/msg00815.html).

**Comment by shahab-vahedi** [comment]
The fix is [in](https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=1d5d29e73f4b5f1af4df5b6e39ccf2fa722acead).

**Comment by abrodkin** [comment]
Fixed by https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/commit/1d5d29e73f4b5f1af4df5b6e39ccf2fa722acead in `arc-2020.03`.
