### ISSUE TITLE
[newlib/libgloss] Add support for RF16 configurations

### ISSUE THREAD

**Issue by abrodkin** [foss-for-synopsys-dwc-arc-processors/toolchain#231]
Currently we have this:
```shell
$ arc-elf32-gcc -mcpu=em_mini -Os --specs=nsim.specs test.c
.../bin/../lib/gcc/arc-elf32/9.2.1/../../../../arc-elf32/bin/ld: error: a.out: cannot mix rf16 with full register set .../bin/../lib/gcc/arc-elf32/9.2.1/../../../../arc-elf32/lib/em_mini/libnsim.a(nsim-syscalls.o)
.../bin/../lib/gcc/arc-elf32/9.2.1/../../../../arc-elf32/bin/ld: failed to merge target specific data of file .../bin/../lib/gcc/arc-elf32/9.2.1/../../../../arc-elf32/lib/em_mini/libnsim.a(nsim-syscalls.o)
```

@claziss @shahab-vahedi who's interested in getting this done at some point? :)

We need this to have an ability to add RF16 (`-mcpu=em_mini`) configuration in automated testing, i.e. have an ability to run a simple "hello world" application in nSIM similarly to what we do for other configurations.

In particular we do it in automated flow as a part of release (as well as engineering build & RCs) publishing. So that will help us to be sure stuff builds and runs on RF16 configs, instead of getting unexpected reports like https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/issues/216.

**Comment by claziss** [comment]
Not sure if we can use the nsim's gnu Host I/O for RF16. We need to investigate more.

**Comment by claziss** [comment]
Supporting RF16 with existing GNU host I/O for nsim is not possible as the syscalls are using unsupported registers. For example:

```c
#define _naked_syscall2(__res, name, a, b)			\
	__asm__ __volatile__ ("mov	r1, %3\n\t"		\
			"mov	r0, %2\n\t"			\
			"mov	r8, %1\n\t"			\
			SYSCALL					\
			"mov	%0, r0"				\
			: "=r" (__res)				\
			: "i" (SYS_##name),			\
			  "r" ((long)a),			\
			  "r" ((long)b)				\
			: "cc", "r0", "r1", "r8");		\
	if ((unsigned long)(__res) >= (unsigned long)(-125)) {	\
		errno = -__res;					\
		__res = -1;					\
	}
```

As you can see `r8` is illegal for RF16 configuration. A solution is to switch for MWDT host I/O interface. However, we lack information on its specs.

**Comment by vineetgarc** [comment]
AFAIKR, for reduced regfile configs, syscall number was in r4 - please check the ABI doc

**Comment by claziss** [comment]
Having the new mwdt hostlink libgloss may be a solution.

**Comment by abrodkin** [comment]
Indeed, https://github.com/foss-for-synopsys-dwc-arc-processors/newlib/pull/14 should fix this.

**Comment by VVIsaev** [comment]
Should be fixed in [https://github.com/foss-for-synopsys-dwc-arc-processors/newlib/tree/arc-2021.03](arc-2021.03).

```
$ cat hello.c
#include <stdio.h>

int main() {
        printf("hello \n");
}
$ arc-elf32-gcc -mcpu=em_mini --specs=hl.specs ./hello.c -o hello
$ nsimdrv -prop=nsim_isa_rgf_num_regs=16 -prop=nsim_isa_family=av2em -prop=nsim_isa_core=1 -prop=nsim_hlink_gnu_io_ext=1 ./hello
hello
```
