### ISSUE TITLE
Can't access int_vector_base in assembly files for -mcpu=arc600

### ISSUE THREAD

**Issue by petrokarashchenko** [foss-for-synopsys-dwc-arc-processors/toolchain#238]
I need to set-up base address for vector table with next instructions in assembly file
```
    mov      r0, VECTOR_TABLE_BASE_ADDR
    sr       r0, [int_vector_base]
```
Production of object file fails with 
```
arceb-elf32/bin/ld: ../../build/tmp/low_level_init.o: in function `_low_level_init':
(.text+0x28): undefined reference to `int_vector_base'
arceb-elf32/bin/ld: (.text+0x28): undefined reference to `int_vector_base'
collect2: error: ld returned 1 exit status
```
As a workaround for now I have added `.extAuxRegister int_vector_base,0x25,   r|w`, but I think this should be fixed.

**Comment by petrokarashchenko** [comment]
@abrodkin can we include this into 2020.03?

**Comment by claziss** [comment]
As far as I can see in PRM, it is called:
`Interrupt Vector Base Register, INT_VECTOR_BASE`
If you use that name it should work.

**Comment by petrokarashchenko** [comment]
I will try in uppercase.
I just got a quick look into `binutils/opcodes/arc-regs.h` and I can find only
```
DEF (0x25,  ARC_OPCODE_ARC700,  NONE, int_vector_base)
DEF (0x25,  ARC_OPCODE_ARCV2,   NONE, int_vector_base)
```
So no definition for ARC600. Could this be a reason?

**Comment by claziss** [comment]
Patch in mainline binutils. 2020.03 branch will be rebased soon to reflect it:
https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=commit;h=265b467340e5334a682e47a0e1b69a80c4428349

**Comment by petrokarashchenko** [comment]
Could you please notify in this issue when rebase is done?

**Comment by claziss** [comment]
Should be done. Please resync on 2020.03 binutils branch.
