### ISSUE TITLE
[GDB/nSIM]: Connecting to nSIM remote stub is broken

### ISSUE THREAD

**Issue by shahab-vahedi** [foss-for-synopsys-dwc-arc-processors/toolchain#239]
### Issue
For some binaries [1], when you connect GDB to nSIM's stub and then issue a "next" it will trigger an assert:
```
/gdb/inferior.c:279: internal-error: inferior* find_inferior_pid(process_stratum_target*, int): Assertion `pid != 0' failed.
A problem internal to GDB has been detected,
further debugging may prove unreliable.
```

### Tested platforms
This is a table of different configurations tried:
| GDB                     | Simulator [2] | Outcome |
--------------------------|---------------|----------
| arc-2020.03      (v10+) | nSIM          | NOK     |
| arc-2020.03      (v10+) | QEMU          | OK      |
| arc-20189.09-gdb (v8.0) | nSIM          | OK      |

### Investigation
So far, the result of my investigation is that the latest GDB, clears the global `inferior_ptid` by invoking `switch_to_inferior_no_thread()`. The old GDB never did that. As a result, GDB ends up looking for `inferior_ptid.m_pid=0` and asserts.

Since QEMU does not trigger this, there is a possibility that nSIM is misbehaving here and is not sending the inferior info as often as it is needed.

### Attachment
Attached you will find all the things you need to reproduce this issue. Consult the `README` file in there: [gdb-nsim-stub-asserts.zip](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/4288128/gdb-nsim-stub-asserts.zip)

##### Footnotes
[1]
I haven't figured out yet what the exact characteristics of such binaries is. Nevertheless, the attached zip file provides one of those.

[2]
nSIM versions tried: `bleeding-edge (Build: TIP@257fe69c)` and `2018.12-1 (Build: 003_FREE)`.

**Comment by shahab-vahedi** [comment]
The problem in current GDB (arc-2020) seems to be about `do_target_wait()` clearing a global variable `inferior_ptid` and then later looking into one of its field (`m_ptid`) without setting it to anything:
```
infrun.c:do_target_wait()
{
   ...
   // the introduced lambda that wasn't in GDB 8.0
   auto do_wait = [&] (inferior *inf)
   {
     // this will set "inferior_ptid" to "null_ptid"
     switch_to_inferior_no_thread (inf);

     // eventually, will cause the assert to be triggered
     ... do_target_wait_1 (inf, wait_ptid, &ecs->ws, options);
   };
   ...
   // the lambda in motion
   int inf_num = selected->num;
   for (inferior *inf = selected; inf != NULL; inf = inf->next)
     if (inferior_matches (inf))
       if (do_wait (inf))                   // BOOM!
   ...
}
```

From a call stack point of view, deep down in `do_target_wait_1()`:
```
do_target_wait_1()
  ...
    remote_target::wait_as()     // process "S05" packet
      process_stop_reply()       // sets "ptid" to "inferior_ptid"
        remote_notice_new_inferior()
          find_thread_ptid()     // ASSERTS
```

To put it all together:

1. `do_wait` lambda invokes `switch_to_inferior_no_thread()` that sets `inferior_ptid` to `null_ptid`.
2. `do_wait` invokes `do_target_wait_1()`
3. `process_stop_reply()` inside `do_target_wait_1()` will set `ptid` to `inferior_ptid` which holds no value.
4. `find_thread_ptid()` down the road looks into this `ptid` and asserts.

I have [asked](https://sourceware.org/ml/gdb/2020-03/msg00007.html) about this in GDB's mailing list.

Logs:
[gdb8_working.txt](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/4289765/gdb8_working.txt)
[gdb10_not_working.txt](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/4289766/gdb10_not_working.txt)

**Comment by shahab-vahedi** [comment]
patch [gdb/remote: Restore support for 'S' stop reply packet](https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=24ed6739b699f329c2c45aedee5f8c7d2f54e493) from upstream resolves this issue. `binutils: arc-2020.03` has already been rebased with this change in.

**Comment by abrodkin** [comment]
Fixed by https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/commit/24ed6739b699f329c2c45aedee5f8c7d2f54e493 in `arc-2020.03`.
