### ISSUE TITLE
uClibc-ng-test-suite failures #1 (overall)

### ISSUE THREAD

**Issue by NikitaSobolev** [foss-for-synopsys-dwc-arc-processors/toolchain#240]
```
FAIL tst-cancel16 got 1 expected 0
        thread not canceled
FAIL tst-cancel4 got 1 expected 0
        in-time cancel test of 'read' successful
        ...
        in-time cancel test of 'msgrcv' successful
        early cancel test of 'read' successful
        ...
        early cancel test of 'recvmsg' successful
        Timed out: killed the child process
FAIL tst-cancel5 got 1 expected 0
        in-time cancel test of 'read' successful
        ...
        in-time cancel test of 'msgrcv' successful
        early cancel test of 'read' successful
        ...
        early cancel test of 'recvmsg' successful
        Timed out: killed the child process
FAIL tst-cancelx16 got 1 expected 0
        thread not canceled
FAIL tst-cancelx18 got 1 expected 0
        going to cancel in-time
        cleanup handler not called
FAIL tst-cancelx20 got 1 expected 0
        sa_flags = 0 test
        called cleanups 0
FAIL tst-cancelx21 got 1 expected 0
        sa_flags = 0 test
        called cleanups 0
FAIL tst-cancelx4 got 1 expected 0
        cleanup handler not called for 'read'
        ...
        cleanup handler not called for 'msgrcv'
        early cancel test of 'read' successful
        ...
        early cancel test of 'recvmsg' successful
        Timed out: killed the child process
FAIL tst-oncex3 got 1 expected 0
        once_handler1: locked
        going to cancel
        cleanup handler not called
FAIL tst-oncex4 got 1 expected 0
        joined first thread
        cl_called = 0
FAIL tst-mallocfork got 1 expected 0
        Didn't expect signal from child: got `Segmentation fault'
```

uclibc-1.0.30
linux-4.17
gcc  arc-2018.03
buildroot 2018.05-776-gc4d2699256

**Comment by vineetgarc** [comment]
Can this be please rerun against the latest release of tools to setup a baseline. As I mentioned some of the tests originally reported failing are passing now !

**Comment by abrodkin** [comment]
As per on of the latest Linux verification executions on HSDK we're seeing 409 passed, 76 failed & 13 skipped tests.
All results are available here: http://de02-resultsdb:8080/result.php?Project=28&pkey=12027.
Not sure though if we're willing to spend resources on this one anytime soon.
@vineetgarc should we just close it now in a hope to get back to it later?

**Comment by vineetgarc** [comment]
So just for the record, per Alexey's link above the 76 failures are below
gcc: arc-2020.09-release
binutils:arc-2020.09-release
uClibc: ?
linux: 5.1-rc4
build: -mcpu=archs

Nothing seems out of ordinary and given we are de-emphasizing uClibc, we could close this.
```
FAIL bug-iconv-trans got 1 expected 0
FAIL collate-test got 1 expected 0
FAIL gen-unicode-ctype got 1 expected 0
FAIL tst-cancelx4 got 1 expected 0
FAIL tst-cancelx16 got 1 expected 0
FAIL tst-cancel18 got 1 expected 0
FAIL tst-cancelx18 got 1 expected 0
FAIL tst-cancelx20 got 1 expected 0
FAIL tst-cancelx21 got 1 expected 0
FAIL tst-digits got 1 expected 0
FAIL tst-ethers got 1 expected 0
FAIL tst-ethers-line got 1 expected 0
FAIL tst_iswalnum got 1 expected 0
FAIL tst_iswalpha got 1 expected 0
FAIL tst_iswcntrl got 1 expected 0
FAIL tst_iswctype got 1 expected 0
FAIL tst_iswdigit got 1 expected 0
FAIL tst_iswgraph got 1 expected 0
FAIL tst_iswlower got 1 expected 0
FAIL tst_iswprint got 1 expected 0
FAIL tst_iswpunct got 1 expected 0
FAIL tst_iswspace got 1 expected 0
FAIL tst_iswupper got 1 expected 0
FAIL tst_iswxdigit got 1 expected 0
FAIL tst-langinfo got 1 expected 0
FAIL tst_mblen got 1 expected 0
FAIL tst_mbrlen got 1 expected 0
FAIL tst_mbrtowc got 1 expected 0
FAIL tst_mbsrtowcs got 1 expected 0
FAIL tst_mbstowcs got 1 expected 0
FAIL tst-mbswcs1 got 1 expected 0
FAIL tst-mbswcs2 got 1 expected 0
FAIL tst-mbswcs3 got 1 expected 0
FAIL tst-mbswcs4 got 1 expected 0
FAIL tst-mbswcs5 got 1 expected 0
FAIL tst-mbswcs6 got 1 expected 0
FAIL tst_mbtowc got 1 expected 0
FAIL tst-numeric got 1 expected 0
FAIL tst-oncex3 got 1 expected 0
FAIL tst-oncex4 got 1 expected 0
FAIL tst-origin got 139 expected 0
FAIL tst-regexloc got 1 expected 0
FAIL tst-setlocale got 1 expected 0
FAIL tst-sscanf got 1 expected 0
FAIL tst_strcoll got 1 expected 0
FAIL tst-strxfrm got 1 expected 0
FAIL tst_strxfrm got 1 expected 0
FAIL tst_towctrans got 1 expected 0
FAIL tst_towlower got 1 expected 0
FAIL tst_towupper got 1 expected 0
FAIL tst-trans got 1 expected 0
FAIL tst_wcrtomb got 1 expected 0
FAIL tst_wcscat got 1 expected 0
FAIL tst_wcschr got 1 expected 0
FAIL tst_wcscmp got 1 expected 0
FAIL tst_wcscoll got 1 expected 0
FAIL tst_wcscpy got 1 expected 0
FAIL tst_wcscspn got 1 expected 0
FAIL tst_wcslen got 1 expected 0
FAIL tst_wcsncat got 1 expected 0
FAIL tst_wcsncmp got 1 expected 0
FAIL tst_wcsncpy got 1 expected 0
FAIL tst_wcspbrk got 1 expected 0
FAIL tst_wcsrtombs got 1 expected 0
FAIL tst_wcsspn got 1 expected 0
FAIL tst_wcsstr got 1 expected 0
FAIL tst_wcstok got 1 expected 0
FAIL tst_wcstombs got 1 expected 0
FAIL tst_wcswidth got 1 expected 0
FAIL tst_wcsxfrm got 1 expected 0
FAIL tst_wctob got 1 expected 0
FAIL tst_wctomb got 1 expected 0
FAIL tst_wctrans got 1 expected 0
FAIL tst-wctype got 1 expected 0
FAIL tst_wctype got 1 expected 0
FAIL tst_wcwidth got 1 expected 0
```

**Comment by abrodkin** [comment]
gcc: arc-2020.09-release (GCC 10.2 + patches)
binutils: arc-2020.09-release (Binutils 2.35 + patches)
uClibc: 1.0.36 
linux: 5.11-rc4
build: `-mcpu=archs`.

**Comment by vineetgarc** [comment]
From above my last runs we should only have following cancel related failures:

FAIL tst-cancelx4 got 1 expected 0
FAIL tst-cancelx16 got 1 expected 0
FAIL tst-cancel18 got 1 expected 0
FAIL tst-cancelx18 got 1 expected 0
FAIL tst-cancelx20 got 1 expected 0
FAIL tst-cancelx21 got 1 expected 0
FAIL tst-oncex3 got 1 expected 0
FAIL tst-oncex4 got 1 expected 0

@geomatsi can you paste your sorted list of failures here
1. baseline (no libgcc or uClibc fix - it should be similar to what we have above: note that cancel11, cancelx11 etc are passing above)
2. uClibc fix only (that should increase the failures: I expect to see cancel11, cancelx11 failing)
3. libgcc fix.

**Comment by geomatsi** [comment]
I executed uClibc  test suilte on HSDK board using up-to-date [snps buildroot](https://github.com/foss-for-synopsys-dwc-arc-processors/buildroot/commit/8b58b524956a40d287f2700b519c2b790ebcef06) images:
* gcc: arc-2020.09-release
* binutils: arc-2020.09-release
* uClibc: 1.0.39
* linux: 5.6.3

Additional patches in question:
1. [fix for uClibc sigrestorer](https://github.com/foss-for-synopsys-dwc-arc-processors/uClibc/pull/6)
2. [fix for libgcc signal handler unwinder](https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/pull/103)

Note that default HSDK buildroot configuration [snps_archs38_hsdk_defconfig](https://github.com/foss-for-synopsys-dwc-arc-processors/buildroot/blob/arc64/configs/snps_archs38_hsdk_defconfig) uses glibc. So HSDK buildroot configuration needs to be modified for uClibc build. 

1. Baseline results: no additional uClibc and libgcc fixes: [uclibc-tests-uclibc-no-fixes.log](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/7792220/uclibc-tests-uclibc-no-fixes.log)
Summary:
Total skipped: 15
Total failed: 12
Total passed: 405
Failures:
```
FAIL tst-ethers-line got 1 expected 0
FAIL tst-ethers got 1 expected 0
FAIL tst-cancel18 got 1 expected 0
FAIL tst-cancelx16 got 1 expected 0
FAIL tst-cancelx18 got 1 expected 0
FAIL tst-cancelx20 got 1 expected 0
FAIL tst-cancelx21 got 1 expected 0
FAIL tst-cancelx4 got 1 expected 0
FAIL tst-oncex3 got 1 expected 0
FAIL tst-oncex4 got 1 expected 0
FAIL tst-tls1 got 1 expected 0
FAIL tst-tls2 got 1 expected 0
```
2. Only uClibc fix: [uclibc-tests-uclibc-fix.log](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/7792250/uclibc-tests-uclibc-fix.log)
Summary:
Total skipped: 15
Total failed: 28
Total passed: 389
Failures:
```
FAIL tst-ethers-line got 1 expected 0
FAIL tst-ethers got 1 expected 0
FAIL tst-cancel11 got 1 expected 0
FAIL tst-cancel16 got 1 expected 0
FAIL tst-cancel18 got 1 expected 0
FAIL tst-cancel2 got 1 expected 0
FAIL tst-cancel21 got 1 expected 0
FAIL tst-cancel25 got 1 expected 0
FAIL tst-cancel3 got 1 expected 0
FAIL tst-cancel4 got 1 expected 0
FAIL tst-cancel5 got 1 expected 0
FAIL tst-cancel6 got 1 expected 0
FAIL tst-cancel7 got 1 expected 0
FAIL tst-cancelx11 got 1 expected 0
FAIL tst-cancelx16 got 1 expected 0
FAIL tst-cancelx18 got 1 expected 0
FAIL tst-cancelx2 got 1 expected 0
FAIL tst-cancelx20 got 1 expected 0
FAIL tst-cancelx21 got 1 expected 0
FAIL tst-cancelx3 got 1 expected 0
FAIL tst-cancelx4 got 1 expected 0
FAIL tst-cancelx6 got 1 expected 0
FAIL tst-cancelx7 got 1 expected 0
FAIL tst-cleanup4 got 1 expected 0
FAIL tst-cleanupx4 got 1 expected 0
FAIL tst-key3 got 1 expected 0
FAIL tst-tls1 got 1 expected 0
FAIL tst-tls2 got 1 expected 0
```
3. Both uClibc and libgcc fixes: [uclibc-tests-uclibc-n-libgcc-fix.log](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/7792253/uclibc-tests-uclibc-n-libgcc-fix.log)
Summary:
Total skipped: 15
Total failed: 6
Total passed: 411
Failures:
```
FAIL tst-ethers-line got 1 expected 0
FAIL tst-ethers got 1 expected 0
FAIL tst-cancel18 got 1 expected 0
FAIL tst-cancelx18 got 1 expected 0
FAIL tst-tls1 got 1 expected 0
FAIL tst-tls2 got 1 expected 0
```

I did a quick check of tst-cancel18 pair of tests. IIUC their failure is not related to stack unwind. They fail because they can not be cancelled by signal. And the reason is the issue with uClibc implementation of [clock_nanosleep](https://cgit.uclibc-ng.org/cgi/cgit/uclibc-ng.git/tree/librt/clock_nanosleep.c):

```
#if defined(SINGLE_THREAD_P)
...
#else
...
#end
```
should be replaced with
```
if (SINGLE_THREAD_P) {
...
} else {
...
}
```

**Comment by abrodkin** [comment]
`tst-ethers*` tests expectedly fail as they expect to find missing by default `/etc/ethers` file with contents of "teeth 1.2.3.4", see https://www.mail-archive.com/devel@uclibc-ng.org/msg00006.html for more details and proposed solutions.

Thus we're left with just 4 failing tests on ARC HS:
```
FAIL tst-cancel18 got 1 expected 0
FAIL tst-cancelx18 got 1 expected 0
FAIL tst-tls1 got 1 expected 0
FAIL tst-tls2 got 1 expected 0
```
If we ever want to spend time on them we're free to re-open this one or create a new issue.
