### ISSUE TITLE
GLIBC: ARC support does not seem to be in any mainline glibc release

### ISSUE THREAD

**Issue by pmgreco** [foss-for-synopsys-dwc-arc-processors/toolchain#243]
I cannot find a mainline tarball of glibc that contains sysdeps/arc (I looked in the latest glibc-2.31) -- so I am currently using one from https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_foss-2Dfor-2Dsynopsys-2Ddwc-2Darc-2Dprocessors_glibc&d=DwICaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=9nrtBsp6WoQyhjyCmxwwoz7_A-dk6r2fRPXWzx4CNO0&m=dyiyYlHd_xpdbSerrAtFSF_4KXlbYk1PgWMP8-cAZbk&s=Q1JnLKXCbLaPl-DJpX3f3pJ_6jgLI4YuXbLNKRe5fV4&e=  but would like to know when/how/where I can get a mainline glibc that includes support for ARC -- as I eventually need to be on a mainline release.

**Comment by vineetgarc** [comment]
We've already been working on upstreaming the glibc port to ARC. I posted the v3 patchset last week and v4 was posted few hours back. 
http://lists.infradead.org/pipermail/linux-snps-arc/2020-March/007127.html

So rest assured it is in works and will finish in next weeks/months as the reviews / maintainers bless it.
