### ISSUE TITLE
GDB: building gdb on Darwin fails with "error: no member named 'abs' in namespace 'std'"`

### ISSUE THREAD

**Issue by falaleevms** [foss-for-synopsys-dwc-arc-processors/toolchain#245]
Building gdb from 2020.03-eng001 on Darwin fails with:
```
/Volumes/develop/jenkins/akolesov-mac/workspace/gnu_eng_build_macos/gdb/gdb/gdbtypes.c:1254:10: error: no member named 'abs' in namespace 'std'; did you mean simply 'abs'?
            = ((std::abs (stride) * element_count) + 7) / 8;
                ^~~~~~~~
                abs
```
gcc used:
```
$ gcc --version
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

Seems the cause it this [commit](https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=commit;h=3104d9ee223133b9f5be4ec96b3f986e4fbc893e)

Possible [solution](https://github.com/isovic/racon/issues/20)

**Comment by shahab-vahedi** [comment]
I've taken a look into that file (`gdbtypes.c`) and others. There is no `#include <cpp_header_for_c>` in there (like `cstdio, cmath, etc.`). That's why I think the proposed [solution](https://github.com/isovic/racon/issues/20) might not be accepted.

@falaleevms could you submit this on [GDB's bugzilla](https://sourceware.org/bugzilla/)?

**Comment by abrodkin** [comment]
Filed bug in GDB's Bugzilla: https://sourceware.org/bugzilla/show_bug.cgi?id=25731

**Comment by abrodkin** [comment]
@shahab-vahedi the fix will be pushed to binutils-gdb shortly, could you please cherry-pick it to our `arc-2020.03` branches?

**Comment by shahab-vahedi** [comment]
Sure!

**Comment by shahab-vahedi** [comment]
@abrodkin Simon has suggested a [patch](https://sourceware.org/bugzilla/show_bug.cgi?id=25731#c4) for you to try.

**Comment by abrodkin** [comment]
The first patch posed on GDB's mailing list: https://sourceware.org/pipermail/gdb-patches/2020-April/167501.html.

**Comment by abrodkin** [comment]
At this point mailing list discussion stopped here: https://sourceware.org/pipermail/gdb-patches/2020-April/167515.html

**Comment by abrodkin** [comment]
@shahab-vahedi could you please cherry-pick the fix (https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=ff8885c3be6f42ed90a7b0ec0028fad26861cd94) from upstream to our Binutils' `arc-2020.03` branch?

**Comment by shahab-vahedi** [comment]
> @shahab-vahedi could you please cherry-pick the fix (https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=ff8885c3be6f42ed90a7b0ec0028fad26861cd94) from upstream to our Binutils' `arc-2020.03` branch?

[done](https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/commit/41dcc5f2bf440bbd782ebe0c29ad2d88eb047d93).
