### ISSUE TITLE
Eclicpse: arc plugins don't work in arc-2020.03-rc1

### ISSUE THREAD

**Issue by falaleevms** [foss-for-synopsys-dwc-arc-processors/toolchain#255]
Eclipse arc plugins bundled in arc-2020.03-rc1 are not usable:
Should be:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/28342150/78584040-4d662000-7840-11ea-8775-a9464c17ee86.png)

But in fact we have only:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/28342150/78583913-24458f80-7840-11ea-9e2b-f72e0863fdfb.png)

**Comment by anthony-kolesov** [comment]
Eclipse version is too old - 2018-12-R, should be 2019-09 at least.

**Comment by EvgeniiDidin** [comment]
Using Eclipse 2020.03 requires there are three steps required for successful installation of ARC plugins.

1) installation of **"jre"** files.
For Linux in **"eclipse"** directory run ```
tar xf OpenJDK11U-jre_x64_linux_openj9_11.0.4_11_openj9-0.15.1.tar.gz --transform=s/jdk-11.0.4+11-jre/jre/```
In Windows unzip and rename to **"jre"** contents of OpenJDK11U-jre_x64_windows_openj9_11.0.4_11_openj9-0.15.1.zip

2) Add path to arc_elf32 toolchain to $PATH environment variable or replicate IDE directory structure.
3) Put **features** and **plugins** directories from **arc_gnu_2020.03-rc1_ide_plugins.zip** archive in **eclipse/dropins** directory

**Comment by abrodkin** [comment]
Fixed now in `arc-2020.03-rc1` re-spin with update of the Eclipse and JRE.
