### ISSUE TITLE
Link failure for --specs=emsk_em9d.specs

### ISSUE THREAD

**Issue by EvgeniiDidin** [foss-for-synopsys-dwc-arc-processors/toolchain#259]
```c
#include <stdio.h>
int main(void)
{
        printf("Hello!\n\r");
        return 1;
}
```

Builds perfectly fine with `arc-2019.09`:
```
$ arc-elf32-gcc -mcpu=em4_dmips --specs=emsk_em9d.specs -O0 hello_world.c
```

Fails with `arc-2020.03`:
```
$ ~svc-arcoss_auto/gnu_builds/2020.03-rc1/elf32_le_linux/bin/arc-elf32-gcc -mcpu=em4_dmips --specs=emsk_em9d.specs hello_world.c

.../2020.03-rc1/elf32_le_linux/bin/../lib/gcc/arc-elf32/9.3.1/../../../../arc-elf32/bin/ld: .../2020.03-rc1/elf32_le_linux/bin/../lib/gcc/arc-elf32/9.3.1/../../../../arc-elf32/lib/em4_dmips/libc.a(lib_a-signalr.o): in function `_kill_r':
signalr.c:(.text+0xc): undefined reference to `_kill'
.../2020.03-rc1/elf32_le_linux/bin/../lib/gcc/arc-elf32/9.3.1/../../../../arc-elf32/bin/ld: signalr.c:(.text+0xc): undefined reference to `_kill'
.../2020.03-rc1/elf32_le_linux/bin/../lib/gcc/arc-elf32/9.3.1/../../../../arc-elf32/bin/ld: .../2020.03-rc1/elf32_le_linux/bin/../lib/gcc/arc-elf32/9.3.1/../../../../arc-elf32/lib/em4_dmips/libc.a(lib_a-signalr.o): in function `_getpid_r':
signalr.c:(.text+0x38): undefined reference to `_getpid'
.../2020.03-rc1/elf32_le_linux/bin/../lib/gcc/arc-elf32/9.3.1/../../../../arc-elf32/bin/ld: signalr.c:(.text+0x38): undefined reference to `_getpid'
collect2: error: ld returned 1 exit status
```

**Comment by abrodkin** [comment]
@shahab-vahedi could you please look at this one? Might have something to do with a newlib.

**Comment by abrodkin** [comment]
@EvgeniiDidin I guess you may reproduce that problem w/o Eclipse with only a simple test source and the same command line, right?

**Comment by EvgeniiDidin** [comment]
@abrodkin Yes, it reproduces outside Eclipse as well.

**Comment by shahab-vahedi** [comment]
What was the command used to build this toolchain?
```
build-all.sh ...
```

**Comment by abrodkin** [comment]
@falaleevms could you please comment on Shahab's question?

**Comment by shahab-vahedi** [comment]
I cannot investigate this further until #262 is resolved.

**Comment by falaleevms** [comment]
@shahab-vahedi, this command was used:

```
./build-all.sh --disable-werror                                \
               --strip                                         \
               --no-auto-pull                                  \
               --no-auto-checkout                              \
               --elf32-strip-target-libs                       \
               --config-extra '--with-python=no --with-isl=no' \
               --install-dir ../release_output/arc_gnu_2020.03-rc1_prebuilt_elf32_le_linux_install \
               --release-name "2020.03-rc1"                    \
               --no-uclibc

```

**Comment by shahab-vahedi** [comment]
> @shahab-vahedi, this command was used:
> 
> ```
> ./build-all.sh --disable-werror                                \
>                --strip                                         \
>                --no-auto-pull                                  \
>                --no-auto-checkout                              \
>                --elf32-strip-target-libs                       \
>                --config-extra '--with-python=no --with-isl=no' \
>                --install-dir ../release_output/arc_gnu_2020.03-rc1_prebuilt_elf32_le_linux_install \
>                --release-name "2020.03-rc1"                    \
>                --no-uclibc
> ```

Still with these build args, I end up with no _uart_ library and hence the error in #262 .

**Comment by abrodkin** [comment]
@shahab-vahedi  as I mentioned in #262 could you please for now build non-multilib toolchain with the following change?
```
diff --git a/libgloss/arc/Makefile.in b/libgloss/arc/Makefile.in
index 46a4a35..9439065 100644
--- a/libgloss/arc/Makefile.in
+++ b/libgloss/arc/Makefile.in
@@ -92,12 +92,7 @@ UART_DIR = uart-dir
 CFLAGS = -g
 override CFLAGS += $(UART_CFLAGS)

-CPU_FAMILY = $(findstring em,${MULTISUBDIR})
-ifeq ($(CPU_FAMILY), em)
 ALL = $(CRT0) $(NSIM_BSP) $(UART_LIB) $(QEMU_BSP)
-else
-ALL = $(CRT0) $(NSIM_BSP) $(QEMU_BSP)
-endif
 ALL_INSTALL = $(CRT0_INSTALL) $(NSIM_INSTALL) $(NANO_INSTALL) $(UART_INSTALL) $(MEMORY_MAP_INSTALL) $(QEMU_INSTALL)

 # These are roughly topologically sorted in order to make porting more
@@ -199,9 +194,8 @@ $(NANO_INSTALL):
                $(INSTALL_DATA) $(srcdir)/$$x $(DESTDIR)$(tooldir)/lib$(MULTISUBDIR)/$$x; done

 $(UART_INSTALL):
-       if [ "$(CPU_FAMILY)" == "em" ]; then \
-               $(mkinstalldirs) $(DESTDIR)${tooldir}/lib${MULTISUBDIR} ; \
-               $(INSTALL_DATA) $(UART_LIB) $(DESTDIR)$(tooldir)/lib$(MULTISUBDIR)/$(UART_LIB) ; fi
+       $(mkinstalldirs) $(DESTDIR)${tooldir}/lib${MULTISUBDIR}
+       $(INSTALL_DATA) $(UART_LIB) $(DESTDIR)$(tooldir)/lib$(MULTISUBDIR)/$(UART_LIB)
        for x in $(EMSK_SCRIPTS); do \
                $(INSTALL_DATA) $(srcdir)/$$x $(DESTDIR)$(tooldir)/lib$(MULTISUBDIR)/$$x; done
```

This way you'll be unblocked and we'll try to solve 2 orthogonal problems in parallel.

**Comment by shahab-vahedi** [comment]
@abrodkin with the changes you suggested, I don't run to #262 anymore nor this one. It just builds.

**Comment by shahab-vahedi** [comment]
I cannot reproduce this issue either with our [_rc1_](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/releases/download/arc-2020.03-rc1/arc_gnu_2020.03-rc1_prebuilt_elf32_le_linux_install.tar.gz) release.

**Comment by shahab-vahedi** [comment]
The key thing to reproduce this issue is using `\n\r` and only `\n\r` at the end of the string !!!!!!

**Comment by shahab-vahedi** [comment]
> The key thing to reproduce this issue is using `\n\r` and only `\n\r` at the end of the string !!!!!!

It bugged me why `\n\r` triggers this only. This is my analysis:
Simple `printf` with a new line at the end:
```
printf("a very simple string\n");
```
translates to:
```
puts("a very simple string")
```

However, a `printf` like:
```
printf("%d", 0)
```
actually pulls in `printf` and not the `puts`. And that opens the Pandora box.

**Comment by shahab-vahedi** [comment]
The missing stubs have been added. It works on my side now. Please confirm if it is fixed for you as well.

**Comment by abrodkin** [comment]
Seems to work fine now, thanks!

**Comment by shahab-vahedi** [comment]
> Seems to work fine now, thanks!

Credit goes to @claziss
