### ISSUE TITLE
[GDB] Add Support for the Generating & Loading Core Files on Bare-Metal Apps

### ISSUE THREAD

**Issue by robfallone** [foss-for-synopsys-dwc-arc-processors/toolchain#263]
We'd like to have the ability to load core-file dumps that are obtained from devices in service in the field and we'd like to be able to generate them when a debugger is connected. Our application is a bare-metal application, it is not running linux. We should be able to use GDB's "generate-core-file" command and feed that core file back into GDB at a later time to debug.

**Comment by claziss** [comment]
Generating core-file dumps is, usually, specific to Linux environments. Do you use OpenOCD to connect to the chip?

**Comment by craigblackmore** [comment]
I have recently implemented bare-metal core dump for RISC-V and I'm working on upstreaming it in the near future. It works using GDB's `gcore` and `gdb <binary-file> <core-dump>` commands and is suitable for any target supporting the GDB Remote Serial Protocol.

Some target-specific additions would be needed to make this work for ARC, mostly around handling the dumping and loading of ARC's registers.

**Comment by shahab-vahedi** [comment]
> We'd like to have the ability ...

Could you please provide more data? What ARC configuration(s) do you exactly use? Are you using OpenOCD? etc.?

**Comment by shahab-vahedi** [comment]
@robfallone ?

**Comment by shahab-vahedi** [comment]
> I have recently implemented bare-metal core dump for RISC-V and I'm working on upstreaming it in the near future. It works using GDB's `gcore` and `gdb <binary-file> <core-dump>` commands and is suitable for any target supporting the GDB Remote Serial Protocol.
> 
> Some target-specific additions would be needed to make this work for ARC, mostly around handling the dumping and loading of ARC's registers.

@craigblackmore Thanks for the info. I will keep an eye on this, when it is merged upstream.

**Comment by fredrikhederstierna** [comment]
I think latest gdb-11.1 now do support bare-metal core dump for RISC-V.

**Comment by shahab-vahedi** [comment]
thank you! I have extracted the necessary changes in `gdb-11.1` and noted it down in our internal tracking system.

**Comment by shahab-vahedi** [comment]
moved into internal tracking.
