### ISSUE TITLE
[gdb] single step from RTIE to userspace

### ISSUE THREAD

**Issue by vineetgarc** [foss-for-synopsys-dwc-arc-processors/toolchain#266]
when debugging qemu issue 112, was trying to single step out of exception handler to user space but it doesn't (and continues to run unless another kernel break point is hit)

**Comment by shahab-vahedi** [comment]
I have tried this with a baremetal program while using QEMU as the debug server. It seemed working:

![user_land](https://user-images.githubusercontent.com/16524902/80967491-c09a8c00-8e16-11ea-8a4e-a632a4b29e92.gif)

Could you share with me more details on how you run into this?
I've also added the codes if you want to dabble in it:
[arc-rtie-vineet.zip](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/4574722/arc-rtie-vineet.zip)

**Comment by vineetgarc** [comment]
Can u try this with a linux kernel debug session - put a break point on ret_from_exception and try single stepping all the way through rtie and see if it steps into user space. 
If the basic test works, perhaps my issue might be that I have not done add-symbol-file <user-space-dso>.

**Comment by cupertinomiranda** [comment]
@vineetgarc, I believe that is the case. Indeed I think you need to do the add-symbol-file to the userspace application in order for it to be able to perform the unwinding correctly.

I think I was able to do it when adding the object with add-symbol-file.

**Comment by shahab-vahedi** [comment]
might be related to #267

**Comment by shahab-vahedi** [comment]
@vineetgarc Could you read [the rationale mentioned for the other issue](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/issues/267#issuecomment-628512896)? If it applied to your case as well, then let's close this issue. If not, this needs an investigation of its own.

**Comment by shahab-vahedi** [comment]
I think this problem is not existing anymore. @vineetgarc feel free to re-open if you have more details.

**Comment by vineetgarc** [comment]
With latest qemu (arcv2) and gdb from arc_gnu_2021.09-eng001_prebuilt_elf32_le_linux_install I see same issue - single step from RTIE won't step into userspace instructions.

**Comment by vineetgarc** [comment]
I tried qemu unit test  **check_rtie_user.tst** which behaves as expected. However when doing this on Linux kernel the issue issue remains. So take any linux kernel image you have lying around (im attaching a new one here)

1. boot kernel
2. b @EV_TLBMiss   # make sure EFA/ERET pertain to user mode
3. once in TLB Miss handler, add another break point on @restore_regs   (this song and dance is to avoid a return from interrupts path back to kernel which uses the same @restore_regs code path). Actually single step from rtie in interrupt return path does the right thing.
4. cont
5. single step to RTIE and see if instruction after that is user mode.

[vmlinux-210615-arcv2-glibc-fb6b321a6c17-qemu-glibc-tests-falter-new.gz](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/6705052/vmlinux-210615-arcv2-glibc-fb6b321a6c17-qemu-glibc-tests-falter-new.gz)

**Comment by shahab-vahedi** [comment]
Attaching the _make recipe_ to make the debugging easier.

[gdb-rtie.tar.gz](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/6710923/gdb-rtie.tar.gz)

**Comment by shahab-vahedi** [comment]
I see the behaviour that Vineet is mentioning. See below. Most of the time _scenario 1_ happens and sometimes _scenario 2_.

What I noticed as well, is that when gdb is paused at the `rtie` instruction (`0x80fcaecc`) and I set a breakpoint to what `eret` is (`b *0x200c5fbc`), still `si` ends up in those `0x8...` addresses. It's only after the execution of those instructions, and there are lots of them, that gdb hits the breakpoint and the code ends in the userland. Therefore, I suspect this is what's supposed to happen and is what QEMU does in terms of execution, but I cannot explain why.

```
$$$$$$$$$$$$$$$$
$$ scenario 1 $$--------------------------------------------------------
$$$$$$$$$$$$$$$$

 restore_regs code
 0x80fcaecc <ret_from_exception+312>     rtie    ; eret=0x200c5fbc
                                                 ; "si" ends in 0x811a6ab4

 0x811a6ab0 <uart_write+244>     seti    r17
>0x811a6ab4 <uart_write+248>     ld_s    r2,[r15,0x8]
 0x811a6ab6 <uart_write+250>     sub_s   r2,r2,0x1
 0x811a6ab8 <uart_write+252>     st_s    r2,[r15,0x8]
 0x811a6aba <uart_write+254>     breq.nt r2,0,156        ;0x811a6b54 <uart_write+408>
 0x811a6abe <uart_write+258>     ld      r0,[r16,104]
 0x811a6ac2 <uart_write+262>     add3    r3,r0,0x18
 0x811a6ac6 <uart_write+266>     llock   r2,[r3]
 0x811a6aca <uart_write+270>     sub     r2,r2,0x1
 0x811a6ace <uart_write+274>     scond   r2,[r3]

$$$$$$$$$$$$$$$$
$$ scenario 2 $$--------------------------------------------------------
$$$$$$$$$$$$$$$$

 restore_regs code
 0x80fcaecc <ret_from_exception+312>     rtie    ; eret=0x200c5fbc
                                                 ; "si" ends in 0x81016d00

>0x81016d00 <run_timer_softirq>          push_s  blink
 0x81016d02 <run_timer_softirq+2>        mov_s   r0,0x813b2d00
 0x81016d08 <run_timer_softirq+8>        bl      -1492   ;0x81016734 <__run_timers>
 0x81016d0c <run_timer_softirq+12>       mov_s   r0,0x813b3580
 0x81016d12 <run_timer_softirq+18>       pop_s   blink
 0x81016d14 <run_timer_softirq+20>       b       -1504   ;0x81016734 <__run_timers>
```

@vineetgarc I could really pick your brain on this.

**Comment by shahab-vahedi** [comment]
Another thing I noticed is when we hit the `restore_regs` code as Vineet suggested (only enabling after a `TLBMiss`), still the code is `rtie`ing as such it is returning from an interrupt and not an exception. In other words, I've never seen the code from `.Lexcept_ret` being executed. This happens because there is always some interrupt in _active_ part of `aux_irq_act`.

```
arch/arc/kernel/entry-arcv2.S

.Lrestore_regs:
restore_regs:

	# Interrpts are actually disabled from this point on, but will get
	# reenabled after we return from interrupt/exception.
	# But irq tracer needs to be told now...
	TRACE_ASM_IRQ_ENABLE

	ld	r0, [sp, PT_status32]	; U/K mode at time of entry
	lr	r10, [AUX_IRQ_ACT]

	bmsk	r11, r10, 15		; extract AUX_IRQ_ACT.active
	breq	r11, 0, .Lexcept_ret	; No intr active, ret from Exception

;####### Return from Intr #######

.Lisr_ret:

debug_marker_l1:
	; bbit1.nt r0, STATUS_DE_BIT, .Lintr_ret_to_delay_slot
	btst	r0, STATUS_DE_BIT		; Z flag set if bit clear
	bnz	.Lintr_ret_to_delay_slot	; branch if STATUS_DE_BIT set

	; Handle special case #1: (Entry via Exception, Return via IRQ)
	;
	; Exception in U mode, preempted in kernel, Intr taken (K mode), orig
	; task now returning to U mode (riding the Intr)
	; AUX_IRQ_ACTIVE won't have U bit set (since intr in K mode), hence SP
	; won't be switched to correct U mode value (from AUX_SP)
	; So force AUX_IRQ_ACT.U for such a case

	btst	r0, STATUS_U_BIT		; Z flag set if K (Z clear for U)
	bset.nz	r11, r11, AUX_IRQ_ACT_BIT_U	; NZ means U
	sr	r11, [AUX_IRQ_ACT]

	INTERRUPT_EPILOGUE
	rtie

;####### Return from Exception / pure kernel mode #######

.Lexcept_ret:	; Expects r0 has PT_status32

debug_marker_syscall:
	EXCEPTION_EPILOGUE
	rtie
```

**Comment by shahab-vahedi** [comment]
@vineetgarc Please close this issue if the situation is clear. If not, feel free to rebut.
