### ISSUE TITLE
[gas] gas need to relax ST a, [b, off] into  ST.as a, [b, off/8]

### ISSUE THREAD

**Issue by vineetgarc** [foss-for-synopsys-dwc-arc-processors/toolchain#274]
On ARC ST encodings of form ST a, [b, off]  only take s9 offset. The workaround is to change this into ST.as (if offset is multiple of 4)

A bunch of asm code in kernel ends up longer offsets and thus needs to be fixed up by hand.
The problem is aggravated in ARCv3 (ARC64) where the offsets just double up (pertaining to storage of registers).

It would be very helpful if the assembler does this relaxation on its own (Metaware assembler does this already)

**Comment by shahab-vahedi** [comment]
To give a fresh example from ARCv3, consider the following instruction:

```asm
lddl r3, [r2,256]            ; -256 <= s9 <= 255. Therefore, 256 is limm.
```

GNU assembler produces:
```asm
22f2 0f82 0000 0100     lddl    r2,[r2,0x100]    ; 8 bytes long
```

Metaware produces:
```asm
1220 0e82               lddl.as r2,[r2,32]       ; 4 bytes long
```

It would be nice if GNU assembler would achieve the same outcome **with the trigger of a flag**. It is too intrusive to be a default behaviour.

**Comment by vineetgarc** [comment]
@shahab-vahedi what is intrusive about using address scaling ? It should be default w/o any flag whatsoever.

**Comment by shahab-vahedi** [comment]
The assembly is as close as you can get to the machine code while still keeping your sanity in check. The assembly instructions should not change on the fly, be that may for optimization reasons. Just because other tools do it, it doesn't mean we have to completely replicate their behaviour.

For what's its worth, I am not brainstorming here. This has been discussed with @claziss and what I wrote earlier is the result of that.

**Comment by vineetgarc** [comment]
> The assembly instructions should not change on the fly, be that may for optimization reasons. 

Why is that. Isn't assembler relaxation supposed to do that - transform instructions to better (shorter, faster) ones if available  A naive assembly programmer may not know that the 256 above would generate an 8 byte instruction so it is for tools to fix those things w/o being asked to. Of course if the size increases thats a bid thing, but if size reduces whats the issue.
Ironically you seem to be updating this issue as if you want this fixed, but you seem to be reasoning in the opposite direction.

> Just because other tools do it, it doesn't mean we have to completely replicate their behavior.

It is not about other tools at all. I noticed this issue several years ago and that was just from generated code inspection and not comparison. But of course we should embrace good things from others

> For what's its worth, I am not brainstorming here. This has been discussed with @claziss and what I wrote earlier is the result of that.

Is that a hint for me to shut up as well ;-)

**Comment by shahab-vahedi** [comment]
Disclaimer: I intend not to turn this into a long discussion where the points are belaboured. Therefore, I try to keep it short. We can talk it out during our next ARC64 meeting.

> Why is that. Isn't assembler relaxation supposed to do that - transform instructions to better (shorter, faster) ones if available A naive assembly programmer may not know that ...

Thinking **for** an assembly programmer is not ideal. Maybe that instruction is exactly what he wants (Think writing tests for QEMU). Then should he write the opcode with ".byte/word/etc" directives!? (rhetorical question) 
The programmer should have control over when this transformation may or may not happen.

For a comparison, I have nothing against *If GCC used to emit `lddl r0, [r1, 256]` and now it should emit `lddl.as r0, [r1, 32]`*. Compilation and transformation go hand in hand. Assembler is about giving pure control/power to the developer.

> Ironically you seem to be updating this issue as if you want this fixed, but you seem to be reasoning in the opposite direction.

I do want it fixed, but with a flag. I am not saying the optimization is not good, but only on the cue of the programmer.

> Is that a hint for me to shut up as well ;-)

Quite the contrary! I was pleasantly surprised that you well documented this issue while I also experienced it today. What I was trying to convey was that I am not going about and randomly dumping my ideas in issues as comments just to make a fuss.
