### ISSUE TITLE
[gas] gas need to relax ST a, [xxx, 0] into ST a, [xxx] 

### ISSUE THREAD

**Issue by vineetgarc** [foss-for-synopsys-dwc-arc-processors/toolchain#275]
We have some code of form 
```asm
ST a, [@global, 0]
```
gas barfs as "Error: inappropriate arguments for opcode 'st' "

It can simply relax the ST instruction and ignore the 0 offset.

**Comment by claziss** [comment]
It is just an encoding issue, GAS doesn't expect to have a symbol there. Hence, the error.

**Comment by abrodkin** [comment]
@claziss do we need to do something here?

**Comment by abrodkin** [comment]
@claziss ping!

**Comment by claziss** [comment]
This is a syntactic sugar, if anyone is in desperate need please reopen.
