### ISSUE TITLE
[gas][arc64] SUBL_S / ADDL_S with SP operand incorrect behavior 

### ISSUE THREAD

**Issue by Palmyr3** [foss-for-synopsys-dwc-arc-processors/toolchain#277]
According to ARC64 HLA v1.6, section [4.5.6 Revised 16-bit Encodings for ARC64] the two lowest bit of u9 operand are always zero for SUBL_S / ADDL_S instructions with SP-only registers as SP is always 4 byte aligned. These 2 bits are used to extend u7 operand to u9.

However ARC64 assembler allows addl_s instruction with incorrect u9 operand value, which can't be encoded: 
```
addl_s sp, sp, 1
```

The subl_s instruction with incorrect u9 operand (i.e `subl_s sp, sp, 1`) is rejected, however the error message is really misleading:
```
Error: register must be either r0-r3 or r12-r15 for instruction 'subl_s'
```

**Comment by claziss** [comment]
Encodings needed to be checked.

Encoded Instructions | I4| I3|I2|I1|I0 | b2| b1| b0 | i2| i1| i0 | u4 |u3|u2|u1|u0
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --| -- | --| --
LD_S b, [SP, u7] | 1 | 1 | 0 | 0 | 0 | b | b | b | 0 | 0 | 0 | u | u | u | u | u
LDB_S b, [SP, u7] | 1 | 1 | 0 | 0 | 0 | b | b | b | 0 | 0 | 1 | u | u | u | u | u
ST_S b, [SP, u7] | 1 | 1 | 0 | 0 | 0 | b | b | b | 0 | 1 | 0 | u | u | u | u | u
STB_S b, [SP, u7] | 1 | 1 | 0 | 0 | 0 | b | b | b | 0 | 1 | 1 | u | u | u | u | u
ADDL_S 				b, SP, u7 | 1 | 1 | 0 | 0 | 0 | b | b | b | 1 | 0 | 0 | u | u | u | u | u
ADDL_S 				SP, SP, u9 | 1 | 1 | 0 | 0 | 0 | U | U | 0 | 1 | 0 | 1 | u | u | u | u | u
SUBL_S 				SP, SP, u9 | 1 | 1 | 0 | 0 | 0 | U | U | 1 | 1 | 0 | 1 | u | u | u | u | u
POPL_S 				b | 1 | 1 | 0 | 0 | 0 | b | b | b | 1 | 1 | 0 | 0 | B | B | B | 1
POPDL_S 				b | 1 | 1 | 0 | 0 | 0 | b | b | b | 1 | 1 | 0 | 1 | B | B | B | 1
PUSHL_S 				b | 1 | 1 | 0 | 0 | 0 | b | b | b | 1 | 1 | 1 | 0 | B | B | B | 1
PUSHDL_S 				b | 1 | 1 | 0 | 0 | 0 | b | b | b | 1 | 1 | 1 | 1 | B | B | B | 1
LEAVE_S u7 | 1 | 1 | 0 | 0 | 0 | U | U | U | 1 | 1 | 0 | u | u | u | u | 0
ENTER_S u6 | 1 | 1 | 0 | 0 | 0 | 0 | U | U | 1 | 1 | 1 | u | u | u | u | 0

**Comment by claziss** [comment]
`addl_s sp,sp,1` is encoded using the `addl_s h,h,limm` format, and not `addl_s sp,sp,u9`. Thus,

```asm
   0:	719b 0000 0001      	addl_s	sp,sp,0x1
```

which is correct.

**Comment by abrodkin** [comment]
@claziss so then it seems to be an incorrect statement in the HLA, right?
Shall we file an internal Jira issue for that?

**Comment by vineetgarc** [comment]
Depends on where the issue is - is this due to assembler port picking the limm format (whereas it could have used u9) or is it indeed an issue with HLA ?

**Comment by claziss** [comment]
Doesn't look like an issue to me. It depends what the user wants. In this issue, the user explicitly wrote `addl_s sp,sp,1` which can and is encoded using `addl_s h,h,limm` format. If he will write `addl_s sp,sp,8' then it will be encoded using `addl_s sp,sp,u7` encodings.

**Comment by claziss** [comment]
Please be aware `u9` is a bit misleading name here. It is actually  encoded in 5 bits, hence, the `u9` immediate is 32-bit aligned. If it is not then, it cannot match the `addl_s sp,sp,u9` encoding. Please check the above encoding table.

**Comment by abrodkin** [comment]
@claziss I think what confused @Palmyr3 were:
1. How information if put in the HLA. I know that's not PRM yet and probably that's the real issue. Given how sparse explanations are in different sub-sections it might easily lead to such questions. If we had all encoding of `addl_s` in 1 place it would be clear that there're more options
2. `subl_s sp, sp, 1` is not accepted even though I would expect it to be completely in line with its `addl_s` counterpart. Is that a wrong assumption?

**Comment by claziss** [comment]
>     2. `subl_s sp, sp, 1` is not accepted even though I would expect it to be completely in line with its `addl_s` counterpart. Is that a wrong assumption?

Yes, HLA is clear, we have `addl_s  h,h,limm` AND `addl_s sp,sp,u9` instructions. Also we have `addl_s h,PCL,limm` variant. If `subl_s` doesn't have exactly the same  variants like `addl` is not a problem of the tools.

**Comment by abrodkin** [comment]
@claziss I didn't say it's a tool problem, instead I was asking where that problem might be and if in the documentation, it IMHO worth improvement.

**Comment by claziss** [comment]
I don't really see a problem with HLA regarding this particular problem, but if you feel it is a problem with HLA, then you should ask for improving it.
