### ISSUE TITLE
[arc64] incorrect endianness when symbol resolving for 'j' instruction 

### ISSUE THREAD

**Issue by Palmyr3** [foss-for-synopsys-dwc-arc-processors/toolchain#281]
I'm building ASM code for ARC64 with following instruction, where `_PrepC` is C function name.
```
j _PrepC
```

In final binary this instructions turns into:
```
38a0:	2020 0f80 3820 0000 	j	0x38200000
```

In final binary `_PrepC` function is located at 0x00003820 address rather than 0x38200000 which is encoded in jump instruction. Looks like the limm operand is decoded in middle endian for some reason.

<br/>

This happens only on symbol resolving, so when I define the `j` argument as a constant, like:
```
j 0x3820
```
in final binary it has correct value:
```
38a0:	2020 0f80 0000 3820 	j	0x3820
```

**Comment by cupertinomiranda** [comment]
This is hard to believe as a real problem. :-)
Please add attachments of original assembly files.

**Comment by claziss** [comment]
I have the next example:

```asm
	.global	main
	.type	main, @function
main:
	j	@foo

	.section	.text.foo
	.global	foo
	.type	foo, @function
	.org	0x3820
foo:
	nop
```

And I use `arc64-elf-gcc example.S` to get the binary.

After the assembly step I get:

```asm
000000000000000 <main>:
   0:	2020 0f80 0000 0000 	j	0
			4: R_ARC_32_ME	foo
```
In the final binary, I get:
```asm
0000000000000264 <main>:
     264:       2020 0f80 0000 3a8c     j       0x3a8c
        ...

0000000000003a8c <foo>:
    3a8c:       264a 7000               nop
```

As far as I can see, everything is fine. I am waiting for you to provide a simple example showing the issue.

**Comment by Palmyr3** [comment]
[Here](https://gist.github.com/Palmyr3/880a5c58410ffa8541c2bb31c82fe3b8) is the preprocessed ASM source file. The instruction I'm talking about is at the end of the file:

```asm
 add sp, sp, 2048

 j _PrepC
```

[Here](https://gist.github.com/Palmyr3/faed9d5a1da3a6c18a3878e17342efbb) is the file after assembly step.

```asm
000000000000004e <done_cache_invalidate>:
  ...
  54:	2400 3f9c 0000 0800 	add	sp,sp,0x800
  5c:	2020 0f80 0000 0000 	j	0
```

In final binary I have

```asm
    3890:	2400 3f9c 0000 0800 	add	sp,sp,0x800
    3898:	2020 0f80 3820 0000 	j	0x38200000
```

Additional toolchain info: toolchain was built from GCC arc64(fa04bf88) branch, binutils arc64(c580ea36) branch

**Comment by Palmyr3** [comment]
I've finally found the rootcause of this. I isn't toolchain issue but the issue with zephyr build.

The build itself was for "elf64-littlearc" but final linkage was for "elf32-littlearc" due to incorrect header include to linker script.

My fault :)
