### ISSUE TITLE
[arc64] [gcc] kernel fails to link with -mcmodel=medium

### ISSUE THREAD

**Issue by vineetgarc** [foss-for-synopsys-dwc-arc-processors/toolchain#283]
ARC64 kernel built with -mcmodel=medium fails to link.
This was due to a shorter S21W relo which was getting out of range in final link.

```
kernel/workqueue.o: in function `apply_wqattrs_prepare':
workqueue.c:(.text+0x2fa6): relocation truncated to fit: R_ARC_S21W_PCREL against symbol `memcpy' defined in .text section in lib/string.o
```

```
arc64-elf-readelf -a kernel/workqueue.o | grep memcpy
000000002fb2  012f0000000f R_ARC_S21W_PCREL  0000000000000000 memcpy + 0
000000002fc2  012f00000011 R_ARC_S25W_PCREL  0000000000000000 memcpy + 0
..
```

The S21W relos in turn was due to a conditional branch which gcc needs to avoid (in lack of linker relaxation)
```
	movl.eq	r2,r18
	movl.eq	r0,r21
	bleq	@memcpy
```

**Comment by cupertinomiranda** [comment]
This is an in-progress issue.
The relocations were there and Claudiu is looking into this.

Don't know how you have missed it in your grep. :-)

```
objdump -dr:
2f94: 1601 1e42 ldl.as r2,[r14,1]
2f98: 1100 0840 ldl r0,[r1]
2f9c: 7a08 andl_s r2,r2,r0
2f9e: 5a44 0042 andl r2,r2,0x1
2fa2: 1e01 109f stl.as r2,[r14,1]
2fa6: 5a0b 8080 tstl r2,r2
2faa: 5aca 0481 movl.eq r2,r18
2fae: 58ca 0541 movl.eq r0,r21
2fb2: 0800 0001 bleq 0 ;0 <memcpy>
2fb2: R_ARC_S21W_PCREL memcpy

readelf -a:
000000002fb2  012f0000000f R_ARC_S21W_PCREL  0000000000000000 memcpy + 0

```

**Comment by vineetgarc** [comment]
> This is an in-progress issue.
NP take your time.

> Don't know how you have missed it in your grep. :-)
yeah thats weird, the grep output was big and i likely trucate dit on copy/paste - and missed the lone S21 in the zoo of S25 - vision no longer 20/20 ;-)

**Comment by claziss** [comment]
A typo in the code was allowing predicated calls to be generated always. Fixed, please update.

**Comment by vineetgarc** [comment]
Great, kernel now links successfully with medium model and the resulting binary is 10% smaller

```
$ bloat-o-meter vmlinux ../ARC64/vmlinux-200618-arc64-mcmodel-large
add/remove: 1/16 grow/shrink: 10934/187 up/down: 540960/-5712 (535248)
...
Total: Before=4787135, After=5322383, chg +11.18%
```
