### ISSUE TITLE
Unify tab/spaces usage in scripts

### ISSUE THREAD

**Issue by anthony-kolesov** [foss-for-synopsys-dwc-arc-processors/toolchain#29]
Usage of tabs and space should be consistent in one file.

I will update scripts files after release.

**Comment by jeremybennett** [comment]
This seems reasonable. I set things up to follow emacs default formating for shell scripts. So you should be able to open in emacs and apply tabify-region to the entire file.

**Comment by anthony-kolesov** [comment]
Done in ab1edda7f7bdecc8772e6c1508c51104550b9fca.
