### ISSUE TITLE
[ARC64] gcc to enable __attribute__ ((__access__ x))

### ISSUE THREAD

**Issue by vineetgarc** [foss-for-synopsys-dwc-arc-processors/toolchain#290]
When building glibc with ARC64, there are tons of warnings for above attribute not supported (for gcc >= 10)
That generates too much noise and obscures real issues. 
I've hacked an upstream file, but consider enabling it.

**Comment by claziss** [comment]
I have update gcc to proper gcc10.1 release:
```
arc64-elf-gcc --version
arc64-elf-gcc (GCC) 10.1.1 20200701
```
Please update.
