### ISSUE TITLE
Installing Plugins

### ISSUE THREAD

**Issue by TaikunZhang** [foss-for-synopsys-dwc-arc-processors/toolchain#291]
Keep running into this error when trying to install the plugin in Eclipse.
![image](https://user-images.githubusercontent.com/35281652/86941762-50f49600-c112-11ea-8f31-dfc3cf7f97ab.png)

**Comment by abrodkin** [comment]
@TaikunZhang could you please share more details on what is your Eclipse version?

**Comment by anthony-kolesov** [comment]
Hi @TaikunZhang,

I was able to reproduce the problem and is now discussing the way to fix this with my colleagues.

As a workaround you can do the following:
1. Unzip `arc_gnu_2020.03_ide_plugins.zip`
2. Copy files `plugins/com.arc.embeddedcdt_2019.9.0.202005250525.jar` and `plugins/com.synopsys.arc.gnu.elf_2019.9.0.202005250525.jar` into the `dropins` folder in your Eclipse installation.
3. Restart Eclipse if it was already running.
4. Go to **Help** menu, **About Eclipse IDE** item.
5. In the opened window press **Installation Details** button.
6. In the opened window go to **Plug-ins** tab and type **synopsys** into the filter text box - you should see two plugins in the list. 

I have tested this with Eclipse CDT 2020-06. Let me know if that doesn't help.
