### ISSUE TITLE
ECR: in arc_legitimize_tls_address, at config/arc/arc.c:6260

### ISSUE THREAD

**Issue by falaleevms** [foss-for-synopsys-dwc-arc-processors/toolchain#292]
There are two toolchains, built from the same sources (arc-2020.03-release):

- Toolchain that was built with scripts from current repository:
`/slowfs/ru20arcgnu1/gnu_verification/builds/96_10.06.2020_scripts/arc-default-elf32/bin/arc-elf32-gcc`

- Toolchain that was built with crosstool-ng:
`/slowfs/ru20arcgnu1/arcoss_verification/arc-gnu-toolchain/workspace/builds/ct73/arc-multilib-elf32/bin/arc-multilib-elf-gcc`

Trying to compile `pr83055.c` with toolchain that was built with crosstool-ng leads to following error:
```
$ arc-multilib-elf-gcc pr83055.c -mcpu=hs -fno-diagnostics-show-caret -fno-diagnostics-show-line-numbers -fdiagnostics-color=never -O0 -fprofile-generate -S --specs=nsim.specs -mcpu=hs -o pr83055.s
during RTL pass: expand
pr83055.c: In function 'c':
pr83055.c:7:33: internal compiler error: in arc_legitimize_tls_address, at config/arc/arc.c:6260
```
While “script” toolchain compiles this file without errors.

Find .c file and script to reproduce this problem here: `/remote/ru20home1/falaleev/crosstool-ng-toolchain-ecr/`

[compiler-calls.sh.txt](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/4924442/compiler-calls.sh.txt)
[pr83055.c.txt](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/4924443/pr83055.c.txt)

**Comment by claziss** [comment]
It looks to me you configured the corss-ng tool to compile with TLS support for baremetal, which is not needed. 
You can choose to:
1. pass `--disable-tls`, `--disable-threads` when u configure ur baremetal toolchain.
2. u can use `-mtp-regno=25` or any other register number, if you want to use TLS in bare metal.

Please let me know how does it works.

**Comment by falaleevms** [comment]
@claziss, thank you! Disabling TLS support for baremetal toolchain helps. I'll close this issue once I launch verification with this change.

Asking to be on the safe side, we still need TLS support for linux toolchain, right?

**Comment by claziss** [comment]
@falaleevms right

**Comment by falaleevms** [comment]
As was written before, disabling TLS support for baremetal toolchain helps.
