### ISSUE TITLE
__builtin_arc_sr() description is incorrect

### ISSUE THREAD

**Issue by abrodkin** [foss-for-synopsys-dwc-arc-processors/toolchain#293]
According to the PRM:
```
SR r1,[r2] ;
Store contents of r1 into Aux. register pointed to by r2
```

But what we have in GCC (https://gcc.gnu.org/onlinedocs/gcc/ARC-Built-in-Functions.html) is:
```
void __builtin_arc_sr (unsigned int auxr, unsigned int val)
The first argument, auxv, is the address of an auxiliary register, the second argument, val, is a compile time constant to be written to the register. Generates:
    sr  auxr, [val]
```

Which is quite in reverse given generated ASM. Though we figured out that problem before and in places where we use `__builtin_arc_sr()` we swapped arguments ourselves. See :
1. Linux: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/soc/arc/aux.h#n14
2. U-Boot: https://gitlab.denx.de/u-boot/u-boot/-/blob/master/arch/arc/include/asm/arcregs.h#L118
3. Zephyr: https://github.com/zephyrproject-rtos/zephyr/blob/master/include/arch/arc/v2/aux_regs.h#L167

So I guess we need to update description of `__builtin_arc_sr()` so that it matches real implementation.

**Comment by claziss** [comment]
Fixed:
https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/ea1e893c35c106954539081d0d1d8a1055f9d73b
