### ISSUE TITLE
[ARC64/gcc] __builtin_set_thread_pointer() not setting thread pointer

### ISSUE THREAD

**Issue by vineetgarc** [foss-for-synopsys-dwc-arc-processors/toolchain#295]
Found this issue as part of [[ARC64] minimal glibc userspace bringup using MMUv4](https://github.com/foss-for-synopsys-dwc-arc-processors/linux/issues/27)

glibc based busybox was crashing as thread pointer r30/gp was not setup in glibc despite the __builtin_set_thread_pointer(). gcc  was not generating code to setup r30 despite the builtin.
```
# define TLS_INIT_TP(tcbp)					\
  ({                                            		\
	long result_var;					\
	__builtin_set_thread_pointer (tcbp);     		\
	result_var = INTERNAL_SYSCALL (arc_settls, 1, (tcbp));	\
	INTERNAL_SYSCALL_ERROR_P (result_var)			\
	? "settls syscall error" : NULL;			\
   })
```

small testcase
```
void set_tp(void *p)	{ 	__builtin_set_thread_pointer(p);	}
 arc64-unknown-linux-gnu-gcc -c -O2 test-tp.c -fPIC --save-temps
```

Claudiu provided a fix this morning, which cures the issue for minimal test above, but a freshly built toolchain (gcc, glibc everything) doesn't have the code generated. I'm afraid there is no simple test case here.

To reproduce: build the arc64 glibc toolchain and in the generated libc.a look for __libc_setup_tls() right before it calls trap_s for arc_settls syscall as shown above: there is no codegen for setting r30

**Comment by claziss** [comment]
Patch pushed https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/633c490a7a30fdb6a187baef76ca19243a661540.

Please retry.

**Comment by vineetgarc** [comment]
Fixed with the aforementioned commit indeed.
