### ISSUE TITLE
kernel allmodconfig build (-mbig-endian) failing due to invalid MPY instruction

### ISSUE THREAD

**Issue by vineetgarc** [foss-for-synopsys-dwc-arc-processors/toolchain#300]
This was reported @ http://lists.infradead.org/pipermail/linux-snps-arc/2020-September/004215.html
[core.i.gz](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/5295114/core.i.gz)

kernel allmodconfig build (which also enables -mbig-endian) is failing.

Confirmed with upstream gcc 9.3 as well as 2020.09 based local build.

arc-linux-gcc -c -O2 -mbig-endian sched.i

**Comment by claziss** [comment]
Patch sent to [gcc mailing list](https://gcc.gnu.org/pipermail/gcc-patches/2020-October/555695.html)

**Comment by vineetgarc** [comment]
@claziss can this be stable backported please !

**Comment by claziss** [comment]
didn't I pushed there too? let me check, otherwise, I will add it to gcc10 as well

**Comment by claziss** [comment]
Pushed to gcc10
