### ISSUE TITLE
make: ccac: Command not found

### ISSUE THREAD

**Issue by StevenWu851013** [foss-for-synopsys-dwc-arc-processors/toolchain#301]
I have some problem when I try to make the file, the terminal says that
make: ccac: Command not found
make: *** [Makefile:261: tensorflow/lite/micro/micro_interpreter.o] Error 127
Is that the Metaware ARC C/C++ Compiler not installed?
But I have already installed the arc_gnu toolchain, can anyone help me?

**Comment by claziss** [comment]
For the Metaware ARC C/C++ Compiler u need to get it through Synopsys official channels.
ARC_GNU toolchain only provides u the GNU (gcc) compiler toolchain.

**Comment by jcampbel** [comment]
Hi @StevenWu851013 
Currently, the ARC backend for TensorFlow Lite for Microcontrollers only supports the MetaWare compiler, as documented [here](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro/tools/make/targets/arc).  That page also provides instructions on how to get access to evaluation versions of MetaWare tools.
I hope this helps,
Jamie

**Comment by StevenWu851013** [comment]
Thank you guys! I understand!
