### ISSUE TITLE
GCC: allow to specify FPU during configuration with "--with-fpu"

### ISSUE THREAD

**Issue by abrodkin** [foss-for-synopsys-dwc-arc-processors/toolchain#304]
Selection of an FPU to be used by the GCC on some architectures is done with GCC's `--with-fpu` configuration option which allows for flexibility: multiple types of FPU might be supported (as opposed to binary toggle like `-mfloat-abi={soft|hard}`).

Apparently that option is not supported by GGC for ARC:
```
./configure --host=arc-linux --with-cpu=hs4x --with-fpu=fpud_all
...
Configuring in host-arc-linux/gcc
...
This target does not support --with-fpu.
Valid --with options are: cpu
make[1]: *** [configure-gcc] Error 1
```

**Comment by vineetgarc** [comment]
And while at it, please also consider supporting canonical **--with-float=hard**. 
Currently we get

```
This target does not support --with-float.
Valid --with options are: cpu
```

**Comment by claziss** [comment]
I have added `--with-fpu` configuration option. It does check if fpu option used is compatible with the selected cpu.

Patch here https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/eea22f55a64aebc63563aad41046426f12e66b74

**Comment by claziss** [comment]
> And while at it, please also consider supporting canonical **--with-float=hard**.
> Currently we get
> 
> ```
> This target does not support --with-float.
> Valid --with options are: cpu
> ```

We don't have a valid option to map if the floats are hard or not, as opposed to ARM. In the arm case a hard/soft float may change the ABI.

**Comment by abrodkin** [comment]
@claziss may we have that improvement posted upstream?

**Comment by vineetgarc** [comment]
> > And while at it, please also consider supporting canonical **--with-float=hard**.
> > Currently we get
> > ```
> > This target does not support --with-float.
> > Valid --with options are: cpu
> > ```
> 
> We don't have a valid option to map if the floats are hard or not, as opposed to ARM. In the arm case a hard/soft float may change the ABI.

I suppose this would be needed for arc64 fpu support where we could have the different ABIs ?
