### ISSUE TITLE
Error: operand is not duplicate of the previous one for instruction 'adc' [-fno-strict-overflow]

### ISSUE THREAD

**Issue by abrodkin** [foss-for-synopsys-dwc-arc-processors/toolchain#310]
Attached pre-processed file [remap_range.i.gz](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/5518168/remap_range.i.gz) (note it is compressed as GitHub refuses to accept `.i` files), then:
```
$ arc-linux-gcc -mcpu=arc700 -O3 -fno-strict-overflow -c remap_range.i

/tmp/ccsxNrDv.s: Assembler messages:
/tmp/ccsxNrDv.s:145: Error: operand is not duplicate of the previous one for instruction 'adc'
```

That problem happens with GCC 10.2 (at least we see it with pre-built arc-2020.09 toolchain and with vanilla GCC 10.2 from Buildroot-built toolchain) and Linux kernel staring from v5.10-rc1, i.e. not on anything earlier like v5.9.y.

**Comment by claziss** [comment]
fixed by this commit: https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/09944fba5bfb8e5543ce043c70d08222cf2f97ff

**Comment by vineetgarc** [comment]
FWIW this issue is relevant for both -mcpu=arc700 and -mcpu=hs38 but not for -mcpu=hs4x likely due to scheduling of instructions

```
arc-linux-gcc -O3 remap_range.i -c -fno-strict-overflow -mcpu=arc700
/tmp/ccixkkvg.s: Assembler messages:
/tmp/ccixkkvg.s:145: Error: operand is not duplicate of the previous one for instruction 'adc'
```
```
arc-linux-gcc -O3 remap_range.i -c -fno-strict-overflow -mcpu=hs38_linux
/tmp/ccdLrfed.s: Assembler messages:
/tmp/ccdLrfed.s:135: Error: operand is not duplicate of the previous one for instruction 'adc'
```
```
 arc-linux-gcc -O3 remap_range.i -c -fno-strict-overflow -mcpu=hs4x 
```

**Comment by abrodkin** [comment]
@claziss may we get this one into upstream GCC 10.x as it is affected as well and I guess there will be at least 10.3 release before we switch to 11?

**Comment by claziss** [comment]
After I see the results of the testing, I'll start pushing it :)

**Comment by abrodkin** [comment]
For the record, the fix is now in upstream `master` brach (to become 11.x): https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=dfbe642c97f7f430926cb6b33cd5c20b42c85573

@claziss may we have it cherry-picked into `releases/gcc-10` branch so that we get it in v10.3 whenever it happens?

**Comment by vineetgarc** [comment]
@claziss - can thi sbe backported to gcc-10 - which is broken ATM due to this.

**Comment by claziss** [comment]
5aeabae7f0c (HEAD -> releases/gcc-10, origin/releases/gcc-10) arc: Refurbish adc/sbc patterns [Claudiu Zissulescu]
