### ISSUE TITLE
Some libstdc++ DejaGNU tests fail if libstdc++ built w/o optimization

### ISSUE THREAD

**Issue by abrodkin** [foss-for-synopsys-dwc-arc-processors/toolchain#313]
Toolchain: arc-2020.09, Elf32.

Test body:
```c++
#include <iostream>

int main()
{
        std::error_code e1;
        std::error_code e2(std::make_error_code(std::errc::operation_not_supported));


        if (!std::is_neq(e1 <=> e2))
                std::cout << "0: Assert!" << '\n';
        else
                std::cout << "0: Success!" << '\n';

        if (!std::is_neq(e1.value() <=> e2.value()))
                std::cout << "1: Assert!" << '\n';
        else
                std::cout << "1: Success!" << '\n';

        if (!((e1 <=> e2) == e1.value() <=> e2.value()))
                std::cout << "2: Assert!" << '\n';
        else
                std::cout << "2: Success!" << '\n';
}
```
Build it with pre-built arc-2020.09 elf32 toolchain: `arc-elf32-g++ -mcpu=archs -std=gnu++2a --specs=nsim.specs`
Execute with nSIM:
```shell
$ nsimdrv -on nsim_emt -p nsim_isa_family=av2hs -p nsim_isa_div_rem_option=2 -p nsim_isa_ll6
4_option=1 -p nsim_isa_mpy_option=2 a.out

0: Success!
1: Success!
2: Success!
```

Now re-build libstdc++ with `-O0` like that (in gcc's top-level source folder):
```
CXXFLAGS_FOR_TARGET="-O0 -g" ../configure --target=arc-elf32 --with-cpu=archs --disable-multilib --disable-werror --enable-languages=c,c++ --disable-shared --disable-tls --disable-threads --with-python=no --with-newlib --with-headers=__path_to_headers__ --prefix=__path_to_install_location__
```

Re-build the test pointing to newly built `libstdc++.a` location like that: `arc-elf32-g++ -mcpu=archs -std=gnu++2a --specs=nsim.specs -L__path_to_libstdc++.a_folder__`, and execute it:
```shell
$ nsimdrv -on nsim_emt -p nsim_isa_family=av2hs -p nsim_isa_div_rem_option=2 -p nsim_isa_ll6
4_option=1 -p nsim_isa_mpy_option=2 a.out

0: Success!
1: Success!
2: Assert!
```

Note if we once again re-buil libstdc++ with enabled optimization via `CXXFLAGS_FOR_TARGET="-O2 -g"`, the failure will be gone again.

Found while looking at extra libstdc++ DejaGNU failures in case of Croostool-NG built toolchain.
Above test was modelled after `libstdc++-v3/testsuite/19_diagnostics/error_code/operators/three_way.cc` with all external dependencies removed.

**Comment by claziss** [comment]
The test boils down to the following function calls and return value comparison:

```asm
	bl @_ZNSt3_V215system_categoryEv;1
	bl.d @_ZNSt3_V216generic_categoryEv;1
	mov_s	r13,r0	;4
	cmp_s r13,r0
```

The above functions are located in `system_error.cc` file part of the `libstdc++-v3` library, and they return a pointer:

```asm
	.align 4
	.global	_ZNSt3_V215system_categoryEv
	.type	_ZNSt3_V215system_categoryEv, @function
_ZNSt3_V215system_categoryEv:
	mov_s	r0,@_ZN12_GLOBAL__N_1L24system_category_instanceE	;13
	j_s	[blink]
	.size	_ZNSt3_V215system_categoryEv, .-_ZNSt3_V215system_categoryEv

	.align 4
	.global	_ZNSt3_V216generic_categoryEv
	.type	_ZNSt3_V216generic_categoryEv, @function
_ZNSt3_V216generic_categoryEv:
	mov_s	r0,@_ZN12_GLOBAL__N_1L25generic_category_instanceE	;13
	j_s	[blink]
	.size	_ZNSt3_V216generic_categoryEv, .-_ZNSt3_V216generic_categoryEv
```
Each pointer refers to distinct instances in the data memory:

```asm
	.section	.data
	.align 4
	.type	_ZN12_GLOBAL__N_1L24system_category_instanceE, @object
	.size	_ZN12_GLOBAL__N_1L24system_category_instanceE, 4
_ZN12_GLOBAL__N_1L24system_category_instanceE:
	.word	@_ZTVN12_GLOBAL__N_121system_error_categoryE+8

	.align 4
	.type	_ZN12_GLOBAL__N_1L25generic_category_instanceE, @object
	.size	_ZN12_GLOBAL__N_1L25generic_category_instanceE, 4
_ZN12_GLOBAL__N_1L25generic_category_instanceE:
	.word	@_ZTVN12_GLOBAL__N_122generic_error_categoryE+8
```

Hence, the initial comparison is checking two pointers if they are equal/less than or not. In the case of `O0` the order of the above snip is reversed. Thus, the error.

In my opinion, this error can be due to a defective test or defective c++ front-end, but, by all means, I do not see any issue related to ARC backend.

More about [three way compare](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1614r2.html)

**Comment by abrodkin** [comment]
@claziss thanks for looking into it! If ARC is out of the question here, maybe it worth filing as an upstream bug vs GCC?

**Comment by claziss** [comment]
I've sent an email to the responsible person, but, it is your finding, you can fill it as a bug.

**Comment by claziss** [comment]
I've sent an email to the responsible person, but, it is your finding, you can submit it as a bug.

**Comment by claziss** [comment]
Per test creator, the test is wrong and it will be fixed upstream. Closing it.
