### ISSUE TITLE
Unable to copy value from uncached struct with -O1/2/3

### ISSUE THREAD

**Issue by VVIsaev** [foss-for-synopsys-dwc-arc-processors/toolchain#315]
Following code prints `FAIL` when executed using nsim:
```
#include <stdio.h>

struct uncached_st {
        int value;
} __attribute__((uncached));

struct cached_st {
        int value;
};

struct uncached_st g_uncached_st = {
        .value = 17
};

struct cached_st g_cached_st = {
        .value = 4
};

void __attribute__((noinline)) test_struct_copy()
{
        g_cached_st.value = g_uncached_st.value;
}

int main(int argc, char **argv)
{
        test_struct_copy();

        if (g_cached_st.value == g_uncached_st.value)
                fprintf(stderr, "PASS\n");
        else
                fprintf(stderr, "FAIL\n");

        return 0;
}
```
Compilation string:
`arc-elf32-gcc -mcpu=hs -O1 --specs=nsim.specs main.c -o main`
Nsim string:
`nsimdrv -prop=nsim_isa_family=av2hs -prop=nsim_isa_core=1 -prop=nsim_emt=1 ./main`

Failure is reproducible with ARC GNU Toolchains 2020.09-1, 2020.09, 2020.03.
ARC GNU Toolchain 2019.09 works correct.

Disassembly of `test_struct_copy()` for 2020.09-1:
```
000002c8 <test_struct_copy>:
     2c8:       1600 7802 0000 4e08     ld.di   r2,[0x4e08]
     2d0:       7ee0                    j_s     [blink]
     2d2:       78e0                    nop_s
```
For 2019.09:
```
00000270 <test_struct_copy>:
     270:       1600 7802 0000 4dac     ld.di   r2,[0x4dac]
     278:       1ac1 b098               st.as   r2,[gp,-63]
     27c:       7ee0                    j_s     [blink]
     27e:       78e0                    nop_s
```
Marking `struct uncached_st g_uncached_st` as `volatile` fixes the issue.

**Comment by claziss** [comment]
I have a proposed fix here:
https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/46a1bdf5c54bfd4159c8257da73e603271b0370c

Please let me know if you have extra issues, otherwise, please close this thread.

**Comment by VVIsaev** [comment]
I've checked dev build and issue is fixed. Thank you!
