### ISSUE TITLE
How to use 4GB memory of HS38 board?

### ISSUE THREAD

**Issue by L-leopold** [foss-for-synopsys-dwc-arc-processors/toolchain#316]
**Well, here is the new issue.**
The reason why I did not  use release 2020  is that  something wrong in compiling Openmp.

  I originally planned to report this bug to you after running a YOLO version. Since you asked, I will tell you about this problem. I use the following steps:

git clone https://github.com/lapesd/libgomp.git
cd libgomp/src/libgomp/build
../configure -host=arc-linux CC=arc-linux-gcc CXX=arc-linux-g++ -disable-multilib
make
When I was running make step, it prompts like this:
![image](https://user-images.githubusercontent.com/64076445/102486274-c0988500-40a3-11eb-9873-f565154d8050.png)

Even I substitute CXX=arc-linux-g++ with CPP=arc-linux-g++ , because I check the makefile ,it does not contain CXX ,but it contains CPP.
But it still can not work.
But when I use the 2018 release , it works . And I do not know the reason.

**And sir,could you please tell me how to use all the memory? Because when I run the YOLO network, which is a CNN, PC can run perfectly with 2GB memory. That means my code is not fault. I guess it is very likely that the memory is not enough**

**Comment by abrodkin** [comment]
@L-leopold why do you use this repo https://github.com/lapesd/libgomp which contains some "enhanced implementation of LibGOMP" which is basically a fork from the original GCC's libgomp made 4 years ago and with some questionable "improvements" on top... with last change done almost 3 years ago?

If you try to build original GGC's libgomp from here: https://github.com/gcc-mirror/gcc/tree/master/libgomp it builds perfectly fine with both `arc-2020.09` & `arc-2019.09`.

**Comment by abrodkin** [comment]
And see my explanation of memory-related questions here: https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/issues/314#issuecomment-747409973

**Comment by L-leopold** [comment]
@abrodkin  Thank you for your patient reception.

I saw the https://github.com/gcc-mirror/gcc/tree/master/libgomp 
why I use the old version of libgomp is I found a Blog here:(if you can visit Chinese website)
https://blog.csdn.net/ACMore_Xiong/article/details/79533658

and  the website you give  is a little complex , I still can not figure out how to compile openmp with  arc-linux-gcc or something
hahahahaha.....
sorry  I am just a master , my major is digital integrated circuit design, still very struggling for embedded development.
Anyway ,thank you for  your explanation . I will research  and study it.

**Comment by abrodkin** [comment]
So do we need to do anything else here or this one might be closed as well?

**Comment by L-leopold** [comment]
@abrodkin  Thank you sir.
**I really wish to know how to change the kernel to extend to 1.5 GB .**
Because though I can not give you a bug report, my teacher and I unanimously believed that the compiler put some variables in a space other than 1GB when compiling, resulting in some variables not being found when loading the program.
Because when I ran YOLOv3 network, which is a CNN, segmentation fault happened when running at the fourteenth conv layer.
When I  ran YOLOv3 tiny network, which is  smaller than YOLOv3,   segmentation fault happened when loading the weight into the network.
When I  ran  YOLOv2 tiny network , which is really smaller than YOLOv3 tiny , it can run perfectly.
So  my teacher and I think it is because some varibales are stored in other 1GB, as I can not  give you a specific report.
And thank you anyway.
I will close  this  issue.
