### ISSUE TITLE
gcc.target/arc/loop-3.c fails

### ISSUE THREAD

**Issue by abrodkin** [foss-for-synopsys-dwc-arc-processors/toolchain#318]
The following DejaGnu test (https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/blob/arc-2020.09/gcc/testsuite/gcc.target/arc/loop-3.c) of GCC fails with arc-2020.09 toolchain this way:
```
FAIL: gcc.target/arc/loop-3.c scan-assembler bne_s @.L2
```

In the test we expect to find `bne.d @.L2` for ARC600 & ARC700 while  `bne_s @.L2` for al lthe rest:
```
/* { dg-final { scan-assembler "bne_s @.L2" { target { ! { arc700 || arc6xx } } } } } */
/* { dg-final { scan-assembler "bne.d @.L2" { target { arc700 || arc6xx } } } } */
```

But what we get is quite the reverse:
```
$ arc-elf32-gcc -v
...
gcc version 10.2.0 (ARCompact/ARCv2 ISA elf32 toolchain 2020.09)

$ arc-elf32-gcc loop-3.c -O2 -mno-sdata -S -mcpu=archs
$ cat loop-3.s | grep bne
        bne.d @.L2

$ arc-elf32-gcc loop-3.c -O2 -mno-sdata -S -mcpu=arc700
$ cat loop-3.s | grep bne
        bne_s @.L2
```

**Comment by claziss** [comment]
Fixed: https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/3564aaf "arc: Update test pattern."
