### ISSUE TITLE
[NEWLIB] Incomplete gettimeofday() in MW hostlink

### ISSUE THREAD

**Issue by shahab-vahedi** [foss-for-synopsys-dwc-arc-processors/toolchain#325]
The `gettimeofday()` function in `libgloss/arc/hl/hl_gettimeofday.c` silently returns an error if the 2nd argument (`tz`) is provided by the caller. Instead this function should be fully implemented or makes sure no caller calls it with `tz != NULL`.

**Comment by shahab-vahedi** [comment]
@abrodkin

**Comment by abrodkin** [comment]
@shahab-vahedi with that moved to the separate issue, can we merge https://github.com/foss-for-synopsys-dwc-arc-processors/newlib/pull/14?

**Comment by shahab-vahedi** [comment]
That is merged.

**Comment by VVIsaev** [comment]
We do not have a way to provide timezone via Metaware hostlink as I know.

What we have right now:
```
/* gettimeofday() implementation.  timezone and usec are not supported.  */
int
_gettimeofday (struct timeval *tv, struct timezone *tz)
{
  int ret;
  uint32_t host_timer;

  if (tz != NULL)
    {
      errno = ENOSYS;
      return -1;
    }
```

POSIX (https://pubs.opengroup.org/onlinepubs/9699919799/functions/gettimeofday.html) says:
```
int gettimeofday(struct timeval *restrict tp, void *restrict tzp);

...
If tzp is not a null pointer, the behavior is unspecified.

RETURN VALUE
    The gettimeofday() function shall return 0 and no value shall be reserved to indicate an error.
```

So I think we can just ignore `tz` argument and always set `tv` and return 0.

**Comment by VVIsaev** [comment]
Please find PR here: https://github.com/foss-for-synopsys-dwc-arc-processors/newlib/pull/15 .

**Comment by shahab-vahedi** [comment]
[ [ARC] [libgloss] Fix hostlink gettimeofday()](https://github.com/foss-for-synopsys-dwc-arc-processors/newlib/pull/15) is merged.
