### ISSUE TITLE
Bump Binutils to the most recent version 2.36.1

### ISSUE THREAD

**Issue by abrodkin** [foss-for-synopsys-dwc-arc-processors/toolchain#329]
There's a subtle update of Binutils 2.36 series with a couple of minor fixes, see https://sourceware.org/pipermail/binutils/2021-February/115240.html.

We may want to re-base on top of that as that's what seems to be used by other projects.

**Comment by claziss** [comment]
Updated: 
https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/commit/f35674005e609660f5f45005a9e095541ca4c5fe
