### ISSUE TITLE
Bump Newlib to the most recent version 4.1.0

### ISSUE THREAD

**Issue by abrodkin** [foss-for-synopsys-dwc-arc-processors/toolchain#330]
Currently our Newlib fork is based on upstream v3.3.0 (to be more precise we're on https://www.sourceware.org/git/?p=newlib-cygwin.git;a=commit;h=a1c7e920845ab21185f18950be3d84f4312222de in our `arc-2021.03` branch as of today), but since then major v4.0.0 (http://sourceware-org.1504.n7.nabble.com/newlib-4-0-0-snapshot-created-td654302.html) and its soonish re-spin v4.1.0 were released (http://sourceware-org.1504.n7.nabble.com/newlib-4-1-0-yearly-snapshot-created-td657366.html).

So let's re-base on that newer version.

## Major changes in newlib version 4.0.0:

- additional out-of-bounds checking for malloc/nano-malloc family
- various fixes to makedocbook for python 3.8
- multiple standard/accuracy fixes to libm math routines
- C-SKY port
- support for Armv8-R aarch64 added
- move of __tzrules_struct from time.h to internal header
- math additions/improvements for RISC-V and arm
- all arm code converted to use unified syntax for Thumb1
- fenv support added for multiple platforms
- hard float support for PowerPC taken from FreeBSD
- advertising clause removed from BSD licenses
- various other fixes

**Comment by claziss** [comment]
Local head moved beyond the indicated point
