### ISSUE TITLE
Do we have C++ exception handling in arc_gnu_2014.08_sources arcgcc?

### ISSUE THREAD

**Issue by pyangqtn** [foss-for-synopsys-dwc-arc-processors/toolchain#333]
Hi,
    I'm from Quantenna, we're using "arc_gnu_2014.08_sources" (arcgcc 4.8.0) for one of our products. Our customer is wondering, if the C++ exception handling is included and enabled by default or not, Would you mind henlp on this? The options we're using to genertate the compiler is "--cpu arc700 --disable-werror --no-multilib --no-elf32 --strip". And if C++ exception handling is included but not enabled, how can we enbale it?
    Many thanks.
BR,
pyang

**Comment by claziss** [comment]
HI, C++ exception should be supported by our toolchain. However, you use a very old release which is known to have problems with proper handling of those concepts. I would suggest using our latest release for full support.

**Comment by pyangqtn** [comment]
Thank you for the information. Let me deliver this info to the project manager first.

**Comment by claziss** [comment]
No feedback in this, if anyone feels to re-open it please do.
