### ISSUE TITLE
[ARC64] [gcc] generate 64-bit DIVL / REML instructions

### ISSUE THREAD

**Issue by vineetgarc** [foss-for-synopsys-dwc-arc-processors/toolchain#336]
Gcc currently doesn't generate 64-bit DIVL, DIVUL, REML, REMUL instructions (unlike mpy64 these are not codegen at all).
These instructions are baseline so can be supported unconditionally.

Excerpt from HLA:
```
-div64
Indicates if 64/64 divide and remainder instructions are
included. The instructions supported by this option are:
DIVL, DIVUL, REML, REMUL
This is a deprecated option; all ARC64 cores will support
64/64 divide instructions. The option will remain active
during core development, to permit staged
implementation and testing of 64-bit divider operations,
but this will not be exposed as an option in customer IP
libraries.
```

**Comment by claziss** [comment]
Please use `-mdiv-rem` to generate those instructions. 
@shahab-vahedi  we need support for them in qemu.

**Comment by cupertinomiranda** [comment]
Those instructions are alreadyy in ARC64 port of QEMU as well as in ARCv2 implementation.
Are they not correct ?

**Comment by vineetgarc** [comment]
Thx for the quick fix !

**Comment by vineetgarc** [comment]
closed by mistake

**Comment by vineetgarc** [comment]
Indeed those are implemented in qemu as well - verified that kernel boots.

**Comment by claziss** [comment]
@cupertinomiranda please close this issue when QEMU fully supports DIVL/REML.
