### ISSUE TITLE
[newlib] Use nano libraries when possible

### ISSUE THREAD

**Issue by shahab-vahedi** [foss-for-synopsys-dwc-arc-processors/toolchain#338]
The linker specs files should allow building against nano libraries. For instance, `libgloss/arc64/qemu.specs` should change from:
```
*qemu_libc:
-lc
```
to
```
*qemu_libc:
%{!specs=nano.specs:-lc} %{specs=nano.specs:-lc_nano} 
```

Some of the specs files:
```
libgloss/arc64/hl.specs
libgloss/arc64/nsim.specs
libgloss/arc64/qemu.specs
```

**Comment by claziss** [comment]
@kolerov I think this is already fixed by using cross-ng.

**Comment by kolerov** [comment]
@claziss Yes, Crosstool-NG handles `nano.specs` in conjunction with another specs well. However, as @shahab-vahedi said earlier, all our specs files (`hl.specs`, `nsim.specs`, `qemu.specs`) must contain this section:

```
*<board>_libc:
%{!specs=nano.specs:-lc} %{specs=nano.specs:-lc_nano} 
```

Crosstool-NG always builds Newlib Nano in a separate directory and generates its own `nano.specs`. If `CT_NEWLIB_NANO_INSTALL_IN_TARGET=n` then `nano.specs` forces GCC to look up libraries in that separate directory (https://github.com/crosstool-ng/crosstool-ng/blob/ce6467faa1d6e977f45596c57832b91e526358c7/scripts/build/companion_libs/350-newlib_nano.sh#L226). Crosstool-NG creates symbolic links for all original libraries there (e.g., `libc.a -> libc_nano.a`) and everything works fine in any case.

If `CT_NEWLIB_NANO_INSTALL_IN_TARGET=y` then Crosstool-NG installs copies of `_nano.a` libraries to the original target's directory. Generated `nano.specs` forces GCC to look up libraries in that directory: `libc.a` and `libc_nano.a` are different libraries there. In this case a program may be linked incorrectly depending on the order of passed specs files. E.g.:

```
$ arc64-elf-gcc -specs=nano.specs -specs=nsim.specs simple.c -o simple.elf -v
--start-group -lgcc -lc_nano --end-group --start-group -lgcc -lc -lnsim --end-group
$ du -b simple.elf 
84152   simple.elf

$ arc64-elf-gcc -specs=nsim.specs -specs=nano.specs simple.c -o simple.elf -v
--start-group -lgcc -lc -lnsim --end-group --start-group -lgcc -lc_nano --end-group
$ du -b simple.elf 
25344   simple.elf
```

You can see there that the same set of options generates different binaries. However, it doesn't happen only when `CT_NEWLIB_NANO_INSTALL_IN_TARGET=n`. I've prepared a patch for specs file to fix it. I am going to create PR when it's tested by me soon: https://github.com/foss-for-synopsys-dwc-arc-processors/newlib/commit/f61284776cf9755967dc279fc570d71757e7ab71.

**Comment by kolerov** [comment]
A corresponding PR was merged: https://github.com/foss-for-synopsys-dwc-arc-processors/newlib/pull/43. @claziss, may I push it to `arc-2023.03` now?

**Comment by claziss** [comment]
@kolerov please do.
