### ISSUE TITLE
ARC64 switch for big unsigned char doesn't always work

### ISSUE THREAD

**Issue by VVIsaev** [foss-for-synopsys-dwc-arc-processors/toolchain#347]
I faced an issue with busybox built by buildroot. In the recent build I see that variables can not be evaluated by shell:
```
$ echo $$
$=
```

I found that `argstr()` function from https://elixir.bootlin.com/busybox/1.32.0/source/shell/ash.c#L6709 does not go to case `case CTLVAR:` and does not do `evalvar()`.

I simplified this function and reproduced similar issue with baremetal toolchain:
```c
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

int pass;

void
passfunc ()
{
  pass = 1;
}

void
failfunc ()
{
  fprintf (stderr, "FAIL\n");
  exit(1);
}

static __attribute__ ((noinline)) void
argstr (char *p)
{
  size_t length;

  length = 0;
  for (;;)
    {

      unsigned char c;

      c = p[length++];

      if (c == '\0')
        break;

      fprintf (stderr, "0x%x == 0x%x\n", c, (unsigned char)'\202');

      switch (c)
        {
        case '=':
        case ':':
          failfunc();
          continue;
        case (unsigned char)'\210':
          failfunc();
          break;
        case (unsigned char)'\201':
          failfunc();
          break;
        case (unsigned char)'\202':
          passfunc();
          break;
        case (unsigned char)'\204':
          failfunc();
          break;
        }
    }
}

int
main ()
{
        char p[3] = {'\202', 'a', '\0'};
        argstr (p);

        if (pass)
                fprintf (stderr, "PASS\n");
        else
                fprintf (stderr, "FAIL\n");

        return !pass;
}
```

```
$ arc64-elf-gcc -O1 -specs hl.specs -o test test.c
$ nsimdrv -prop=nsim_isa_family=arc64  -p nsim_isa_div_rem_option=2 -p nsim_isa_mpy_option=3 -prop=nsim_isa_mpy64=1 -prop=nsim_isa_div64_option=1 -prop=nsim_hlink_gnu_io_ext=1 test
0x82 == 0x82
0x61 == 0x82
FAIL
```
Issue can be reproduced with `-O1/2/3/s`. `-mno-unaligned-access` does not help.
Issue cannot be reproduced with `-O0`

Versions used:
gcc: arc64, 28e017d4fa8d3d571452787794dfd0b4e09cf0a8
newlib: arc64, 2b97ded2d0e32dffda87028ed2e28c69b26987ed
binutils-gdb: arc64,38f913d8337c9cda0637cff92a313678bc2c508e

Also reproduced with arc64 toolchain build 509.

Please find temp files here: [test.zip](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/6082657/test.zip)

**Comment by VVIsaev** [comment]
Just tried with recent x86_64 gcc:
```
$ gcc --version
gcc (Debian 10.2.1-6) 10.2.1 20210110
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ gcc -O3 ./test.c -o test
$ ./test 
0x82 == 0x82
0x61 == 0x82
PASS
```

**Comment by claziss** [comment]
This is one of the SNAFU situations. The error is due to a wrong number extension. Thank you for finding it. Fix here:
7f9789e arc64: Fix casesi snafu: https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/7f9789ed3af8b837f8cf66afdbc5a740863dc4d7
