### ISSUE TITLE
gcc: make hs38 as default

### ISSUE THREAD

**Issue by vineetgarc** [foss-for-synopsys-dwc-arc-processors/toolchain#348]
In lack of -mcpu toggle, current gcc driver builds for arc700.
We are no longer actively working on arc700 - any ARC700 customers use old stuff anyways.
So I propose to make -mcpu=hs38 as default (hs38_linux might be too aggressive given floating point connotations and hs4x similarly) - anyhow anything in hs family would be better than 700.

1. The change is straight fwd https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/bfa7ede2450c281926c1d54b76f1b4e3611bb954  but per discussion with @claziss
2.  We need to make sure there are no regression in dejagnu (vs. current runs)
3.  Complementary changes are needed in binutils as well.

This issue is a placeholder to make sure we address all of that as part of GNU verification and update here so once @claziss is happy this patch can be pushed upstream.

**Comment by vineetgarc** [comment]
CC @claziss @shahab-vahedi @cupertinomiranda @VVIsaev

**Comment by vineetgarc** [comment]
ping !

**Comment by falaleevms** [comment]
@vineetgarc, action requested is to launch gnu toolchain verification against topic-vineet-gcc10-hs38-default branch, right?

**Comment by vineetgarc** [comment]
That I think was already done by @abrodkin - we need to see if there are any additional failures (dejagnu etc) to be able to do this.

**Comment by vineetgarc** [comment]
This is fixed in mainline now  (and backported to gcc 11) - and even better it is hs38_linux (so hard-float is default).

upsteam/master                : 2021-06-02 46d04271a498 ARC: gcc driver default to hs38_linux  
upstream/releases/gcc-11: 2021-06-02 67a457824e1c ARC: gcc driver default to hs38_linux
