### ISSUE TITLE
[N.B.] QEMU's gdbserver compatibility

### ISSUE THREAD

**Issue by shahab-vahedi** [foss-for-synopsys-dwc-arc-processors/toolchain#353]
The **new** QEMU's gdbserver can only be used in conjunction with GDB release `arc-2021.03+`. The **old** one can be used freely.

What does **new** QEMU mean?
Since there is no tags in QEMU yet, I cannot refer to a release/date. **New** QEMU comes with the following code:

```
gdb-xml/arc-v2-core.xml:
...
<feature name="org.gnu.gdb.arc.core">
...
```

While the **old** QEMU has the following content:
```
gdb-xml/arc-core-v2.xml:
...
<feature name="org.gnu.gdb.arc.core.v2">
...
```

Notice the difference between both the file paths and the feature name.

**Comment by abrodkin** [comment]
Not a bug, but a known behavior.

**Comment by jthampan** [comment]
Hi, I am facing this issue with latest Zephyr SDK since the GDB version is old
How to resolve it, as i don't know how to generate Zephyr SDK with a new version of GDB

**Comment by abrodkin** [comment]
@joetham there're 2 options I guess:
1. Use GDB client from our pre-built toolchain. For example from here: https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/releases/download/arc-2021.09-release/arc_gnu_2021.09_prebuilt_elf32_le_linux_install.tar.gz
   That could be done easily and right now. Please try it and let me know if it works.
2. Update GDB version in Zephyr's SDK.
    That will require additional work and I think we'll do that as a part of ARC tools update in the Zephyr's SDK. Which we'll do via https://github.com/zephyrproject-rtos/sdk-ng/issues/455 as a part of the upcoming Zephyr SDK update.

**Comment by shahab-vahedi** [comment]
@joetham this is just an example for ARCv2 (hs) target:

```
INST=${HOME}/arc-gdb

#REPO=https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb.git
REPO=https://sourceware.org/git/binutils-gdb.git

#git clone --single-branch --branch arc-2021.09-gdb "${REPO}"
git clone "${REPO}"

cd binutils-gdb
./configure --target=arc-elf          \
            --with-cpu=archs          \
            --disable-shared          \
            --disable-threads         \
            --disable-tls             \
            --prefix=${INST}          \
            --disable-ld              \
            --disable-gas             \
            --disable-binutils

make -j $(nproc) all-gdb
make             install-gdb
```

If you do have further questions, please kindly open a new issue.

**Comment by jthampan** [comment]
Thanks this way i can debug
