### ISSUE TITLE
reduced register set runtime incorrectly calculates modulo with __umodsi3

### ISSUE THREAD

**Issue by iguryanov** [foss-for-synopsys-dwc-arc-processors/toolchain#355]
Hi, 

I was running some tests with em_mini 16registers target, took libgcc.a from 2021.03 release candidate. 

At least em_mini has issues with calculating unsinged int modulo with __umodsi3(). 
for unsigned int X bigger than 0xa000_0000   "x % 10" is always equals x. 

I tested only em_mini, only unsigned integers and only 10 on right side. 
And to make test faster I checked only for results bigger than 9, not for absolute correctness. 

Regards,
Igor.

**Comment by claziss** [comment]
Thanks for this one. The mask used in `udivmodsi4` was wrong. Fixed by this commit:

https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/55a92c96f870063ff100a0abb936e6c2b773d15f
