### ISSUE TITLE
Add links in toolchain documentation to embARC web-site & toolchain downloads

### ISSUE THREAD

**Issue by abrodkin** [foss-for-synopsys-dwc-arc-processors/toolchain#357]
From toolchain docs https://foss-for-synopsys-dwc-arc-processors.github.io/toolchain:
1. To toolchain downloads (releases): https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/releases
2. To https://embarc.org

**Comment by kolerov** [comment]
I added links to the main documentation page:

https://foss-for-synopsys-dwc-arc-processors.github.io/experimental-documentation/2023.09/
