### ISSUE TITLE
Error: inappropriate arguments for opcode 'stl'

### ISSUE THREAD

**Issue by abrodkin** [foss-for-synopsys-dwc-arc-processors/toolchain#359]
On attempt to build native toolchain for ARC64 bumped into this:
```
# arc64-linux-g++ -c -O2 loop-init.ii
/tmp/ccH7lpkL.s: Assembler messages:
/tmp/ccH7lpkL.s:1717: Error: inappropriate arguments for opcode 'stl'
```

Components used (tips of `arc64` branches as of today):
* Binutils: https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/commit/3fc58dcb8641724c3bd0cc45a7dd17ce3039627d
* GCC: https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/251a7e99a619248f6c0fb27be420d009a7e81125
* Glibc: https://github.com/foss-for-synopsys-dwc-arc-processors/glibc/commit/5754a6aa79d8e990cdabcc3baffa454e1e666677

Archive with pre-processed input: [loop-init.ii.gz](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/6195044/loop-init.ii.gz).

**Comment by claziss** [comment]
The faulty instruction is this one:
```asm
stl.as r0,[8,r1]
```
The address is valid for a `ld` instruction but not for `st`.

Simplified example:

```c
 struct a {
  typedef int b;
};
template <typename, typename c, typename = typename c::b> struct d;
template <typename e, typename c> struct d<e, c, int> {
  e &operator[](unsigned);
  int f;
  e g[];
};
template <typename e, typename c> e &d<e, c, int>::operator[](unsigned h) {
  return g[h];
}
d<int, a> *i;
int j;
void k() {
  if (i == __null) {
    d<int, a> *l;
    (*l)[j] = __null;
  }
}
```

**Comment by claziss** [comment]
Fixed by this commit: https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/ad0e5817359bb262ac35a4722294d1f86b81b72a "arc64: Fix matching scalled address".
