### ISSUE TITLE
Change year on IDE starting screen

### ISSUE THREAD

**Issue by vkremneva** [foss-for-synopsys-dwc-arc-processors/toolchain#364]
While going through [release testing](https://gitsnps.internal.synopsys.com/arc_oss/gnu-test-plan/-/blob/master/release-tests.rst) for the ARC GNU 2021.03-rc1 I saw an odd window (see the picture below):

![VirtualBox_Ubuntu 18 04 for Release Tests_01_04_2021_15_05_19](https://user-images.githubusercontent.com/11376479/113291574-e61c6800-92fb-11eb-87d8-559ba080f41e.png)

As you can see, at opening window we have year '2020' instead of current '2021'. From the terminal window above you can see that I've used "fresh" version of eclipse.

**Comment by abrodkin** [comment]
That's an Eclipse version `2020-03` 4.15.0 which is being displayed.
And we're not going to change that.
