### ISSUE TITLE
[ARC_GDB][FT2232] Unexpected program stop, and incorrect data read via JTAG.

### ISSUE THREAD

**Issue by daliu6126** [foss-for-synopsys-dwc-arc-processors/toolchain#371]
Hi Guys,

I`m using ARC GDB and FT2232 to do the debug on EM22fs dual-core chip. Real chip, not FPGA.

As attached picture,
when I ran the program by arc gdb, I observed that the program was ran yet (Because I checked the output from UART), 
but on the gdb command line window, the program was stopped, and command input was possible.

Then I type below command to try to read the SRAM 0x50000000 (which is the beginning of the SRAM): 
    >  "x /32xw 0x50000000"
the fetched data was not correct, and the data was left-shift one bit.

I also attached the full ARC script folder. I suspect that there is something wrong in the cfg file also.

Could anyone help to this issue?

Thanks so much!

Best regards,
Tao.

**Comment by daliu6126** [comment]
![ARC_GNU_FT2232_Unexpect_stop_and_incorrect_data_read_20210416111053](https://user-images.githubusercontent.com/16330813/116185010-5bd8ef80-a753-11eb-8c47-98e01c757400.png)

[scripts.zip](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/6381816/scripts.zip)

**Comment by shahab-vahedi** [comment]
@EvgeniiDidin could you double check the OpenOCD part?

**Comment by shahab-vahedi** [comment]
@daliu6126 I don't see a shift left on `0x5000_0000`:

```
0x5000_0000 << 1 will be 0xa000_0000
```

You have a trailing `8` in `0xa000_0008`. Even if there was 1 bit leaking from the next "word" it should have become `0xa000_0001`.

**Comment by shahab-vahedi** [comment]
closing due to lack of response.
