### ISSUE TITLE
[ARC64] assembler error: "operand out of range (-516 is not between -512 and 511)"  when building glibc at -O2

### ISSUE THREAD

**Issue by vineetgarc** [foss-for-synopsys-dwc-arc-processors/toolchain#374]
arc64-linux-gcc -c -O2 utmp_file.i
/tmp/ccyQRimW.s: Assembler messages:
/tmp/ccyQRimW.s:1658: Error: operand out of range (-516 is not between -512 and 511)
/tmp/ccyQRimW.s:1668: Error: operand out of range (-514 is not between -512 and 511

Issue happens with latest gcc/binutils from arc64 branches, but not say from gcc/binutils of say gcc commit  1af4ddc4b17b
[utmp_file.i.gz](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/6418253/utmp_file.i.gz)

**Comment by claziss** [comment]
STL doesn't accept `w6` encoding, hence all the direct immediate stores are using limm. Fix here:  https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/2cc78980e263bcac97bd3c5ed9525a40b8d1315e
