### ISSUE TITLE
libgloss: hl.specs missing functions

### ISSUE THREAD

**Issue by claziss** [foss-for-synopsys-dwc-arc-processors/toolchain#379]
The next functions are missing from `hl.specs`:

* `_stat`
* `_link`

**Comment by VVIsaev** [comment]
Hi @claziss ,

As I can remember we don't have these functions in Metaware hostlink (at least in the nsim implementation). Does it block you?

I can add stubs if needed.

**Comment by claziss** [comment]
We need some dummy ones. Here it is my implementation:
```c
int __attribute__((weak))
_stat (const char *fname, void *st)
{
  errno = ENOSYS;
  return -1;
}

int __attribute__((weak))
_link (const char *__path1 __attribute__ ((unused)), const char *__path2 __attribute__ ((unused)))
{
  errno = ENOSYS;
  return -1;
}
```

**Comment by VVIsaev** [comment]
Please find MR for ARCv2 here: https://github.com/foss-for-synopsys-dwc-arc-processors/newlib/pull/21.

**Comment by VVIsaev** [comment]
Thank you @claziss for merging it to arc64!

I think we can close the issue.
