### ISSUE TITLE
[GCC 11] Error: operand out of range (0x0000000000001030 is not between 0xfffffffffffff000 and 0x0000000000000fff)

### ISSUE THREAD

**Issue by abrodkin** [foss-for-synopsys-dwc-arc-processors/toolchain#382]
Trying to build OpenEmbedded for HSDK with vanilla GCC 11.1 see this:
```
$ arc-oe-linux-g++ -c -mcpu=hs38_linux -O2 hb-ot-shape-complex-use.cc.ii --save-temps
hb-ot-shape-complex-use.cc.s: Assembler messages:
hb-ot-shape-complex-use.cc.s:2914: Error: operand out of range (0x0000000000001030 is not between 0xfffffffffffff000 and 0x0000000000000fff)
```

Attached are `.ii` & `.s` files. GCC version is:
```
$ arc-oe-linux-g++ -v
...
Supported LTO compression algorithms: zlib
gcc version 11.1.1 20210523 (GCC)
```

A couple of notes:
1. I cannot reproduce that with pre-built `arc-2021.03` Glibc toolchain for ARC HS
2. Both `-O2` & `-mcpu=hs38_linux` are required for reproduction

[hb-ot-shape-complex-use.cc.zip](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/6559486/hb-ot-shape-complex-use.cc.zip)

**Comment by claziss** [comment]
The ZOL contains a number of instructions which needs to be split at a later time than the ZOL generation. However, the split instruction sizes are too optimistic leading to a wrong computation of ZOL size.

**Comment by claziss** [comment]
Patch: https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/afe89aaa3cf1214900a86b766d7ee9484e99484b

**Comment by vineetgarc** [comment]
@claziss can this be pushed upstream and also backported for gcc 11 ?

**Comment by claziss** [comment]
@vineetgarc sure, but I was waiting for the nightly build and testing....

**Comment by claziss** [comment]
pushed to master and gcc11 branch

**Comment by abrodkin** [comment]
It's https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/0061fabeb9393c362601486105202cfe837a5a68 in `arc-2021.09` branch.

**Comment by abrodkin** [comment]
And that's a part of GCC 11.2 release, see https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=0061fabeb93.
