### ISSUE TITLE
arc64: hard-float: libgcc/gcc missing __truncdfhf2

### ISSUE THREAD

**Issue by vineetgarc** [foss-for-synopsys-dwc-arc-processors/toolchain#387]
arc64 glibc hard-float currently fails when linking test cases since libgcc has missing __truncdfhf2 (and would not have been noticed if we didn't have #334  (which causes all calls to be resolved eagerly).

This is related to half-precision codegen.  It seems there is pattern in gcc but that code seems commented / not-ready. The fix is to enable that or provide a fallback in libgcc or disable HF in gcc (which currently is auto-enabled correctly, --with-fpu=fpud).

I currently carry a hack to force HP in gcc

```diff
diff --git a/gcc/config/arc64/arc64.h b/gcc/config/arc64/arc64.h

 /* FP options.  */
 #define ARC64_HAS_FP_BASE (arc64_fp_model > 0)
-#define ARC64_HAS_FPUH    (arc64_fp_model > 0)
+#define ARC64_HAS_FPUH    (0)

```

**Comment by vineetgarc** [comment]
Please be aware that glibc HF support is gated on this being fixed. My local builds are currently carrying the hack described above.

**Comment by claziss** [comment]
Added related missing patterns here:
https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/b737e3212d4e24d63c2d38a1f8322ebbab681916

**Comment by vineetgarc** [comment]
Fixed.
