### ISSUE TITLE
[ARC64] dynamic link busybox crash

### ISSUE THREAD

**Issue by vineetgarc** [foss-for-synopsys-dwc-arc-processors/toolchain#388]
glibc bits for dynamic linker have been pushed and with this I'm trying to bringup a dynamic linked system 
In test setup I have both static busybox (as default) which boots to shell and a dynamic linked busybox which is seg faulting in dynamic loader.

I'm still at gcc commit 2020-07-29 f470b90af0b3 arc64: fix tls detection in assemble to avoid any possible issues due to recent dbnz commits).

The issue manifests in _dl_start() and an inline function called elf_get_dynamic_info()
This code is writing to _rtld_local._dl_rtld_map.   which is accessed in pc relative way

The initial accesses in dl_start are good

```
    addl    r18,pcl,@_rtld_local@pcl             
    addl    r1,r18,2568            <-- PC relative base address of  _rtld_local._dl_rtld_map.l_addr
    stl    r19,[r1]

    addl    r1,r18,2584            <-- PC relative base address of  _rtld_local._dl_rtld_map.l_ld
    stl    r0,[r1]
```
However a subsequent access to _rtld_local._dl_rtld_map.l_info[ ] is done via an compiler generated intermediate pointer (const pool like)

```
    addl    r3,pcl,@.LC25@pcl     <-- gcc generated pointer which contains l_info address
...
    ldl    r2,[r3]            <--  loads from LC25
    add3l    r1,r2,r1     <-- this address is bad
    stl    r0,[r1]    #, dyn  <-- this ST falters

    .align    8
.LC25:
    .xword    @_rtld_local+2632    # _rtld_local._dl_rtld_map.l_info
```

The address however is build time and not runtime (this is loader startup code so it can't be dynamically fixedup)

```
0000000000001500 <_dl_start>:
...
    1582:	5f00 7f03 0001 e0a8 	addl	r3,pcl,123048@s32	;1f628 
...
    15d0:	1300 0842           	ldl	r2,[r3]	<-- loads 0x2_0a60   (needs to be runtime value)
    15d4:	5a16 0041           	add3l r1,r2,r1	<--- 0x2_0ad0
    15d8:	1900 0007           	stl	r0,[r1]       <-- segv
```

The LC25 ends up in data.rel.ro section, however it contains build time address of _rtld_local

```
Disassembly of section .data.rel.ro:
000000000001f618 <any_debug-0x128>:
...
   1f628:	60 0a 02 00             	.word	0x00020a60     <-- this is the address which points to inside rtld_global below

Disassembly of section .data:
0000000000020018 <_rtld_global>:
...
   20a60:	00 00 00 00             	.word	0x00000000	<-- start of rtld_local->l_info 
...
```

So what we really need to avoid is this extra const pool like pointer generated by compiler.

**Comment by cupertinomiranda** [comment]
Can we close this ?

**Comment by vineetgarc** [comment]
Yeah this is long fixed and the workaround to use -fPIC for executable builds is not needed either.
