### ISSUE TITLE
ARC64 gcc ICE triggered with -mdiv-rem

### ISSUE THREAD

**Issue by vineetgarc** [foss-for-synopsys-dwc-arc-processors/toolchain#393]
arc64-linux-gcc -O2 -mdiv-rem -c tcp_cubic.i

arc64-unknown-linux-gnu-gcc -O2 -mdiv-rem -c tcp_cubic.i -fdump-rtl-all
../net/ipv4/tcp_cubic.c: In function 'hystart_ack_delay':
../net/ipv4/tcp_cubic.c:393:1: error: unrecognizable insn:
(insn 11 10 14 4 (set (reg:DI 78)
        (udiv:DI (const_int 262144000000 [0x3d09000000])
            (reg:DI 74 [ _6 ]))) "../include/linux/math64.h":67:18 -1
     (nil))
during RTL pass: vregs
dump file: tcp_cubic.i.237r.vregs
../net/ipv4/tcp_cubic.c:393:1: internal compiler error: in extract_insn, at recog.c:2294

**Comment by claziss** [comment]
Ups, a big constant not split to LO/HI construct. I'll take care of it thanks!

**Comment by claziss** [comment]
Done, please update:
https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/08452076debd6ee6014503167b1eb1b38875caa7

**Comment by vineetgarc** [comment]
Thx for the quick fix !
