### ISSUE TITLE
arc64: gcc: ICE with -m128 -msimd -ftree-vectorize

### ISSUE THREAD

**Issue by vineetgarc** [foss-for-synopsys-dwc-arc-processors/toolchain#394]
With latest gcc on arc64 branch

```
(insn 525 457 122 17 (parallel [
            (set (reg/v:SI 14 r14 [orig:232 <retval> ] [232])
                (plus:DI (mult:DI (sign_extend:DI (reg/v:SI 8 r8 [orig:155 i ] [155]))
                        (sign_extend:DI (reg:SI 0 r0 [274])))
                    (reg:DI 58 r58)))
            (clobber (reg:DI 58 r58))
        ]) "mm/percpu.c":295:42 -1
     (nil))
during RTL pass: shorten
mm/percpu.c:1080:1: internal compiler error: in insn_min_length, at config/arc64/arc64.md:558
```
[ice.tar.gz](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/6711704/ice.tar.gz)

**Comment by claziss** [comment]
Reduced test:
```c
d(int *f) {
  long e = a * (1UL << 12) + b;
  *f = e;
}
g() {
  for (d(&c);;)
    h(c);
}
```

Command line: `arc64-elf-gcc percpu.i -msimd -S -w -O3 `

**Comment by claziss** [comment]
The special procedure which I made to merge a mov and a mac instruction doesn't check for the output mode of each of the involved instructions. For example, it allows to merge a 32bit register into the 64bit output mac instruction. 
Fix this issue by commit: 
https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/f5534497f15bbfe0d68495fad67988333d50a82a

**Comment by vineetgarc** [comment]
Builds fine now. Thx for the quick fix.
