### ISSUE TITLE
"apt" fails to compile: ICE: in trunc_int_for_mode, at explow.c:59

### ISSUE THREAD

**Issue by abrodkin** [foss-for-synopsys-dwc-arc-processors/toolchain#398]
[edsp.tar.gz](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/6755669/edsp.tar.gz)

Compile with `arc-2021.03`: 
```
$ arc-linux-g++ -mcpu=hs -mll64 -O2 -g -c edsp.ii

during RTL pass: vartrack
.../apt-2.2.4/apt-pkg/edsp.cc: In function 'bool EDSP::WriteScenario(pkgDepCache&, FileFd&, OpProgress*)':
.../apt-2.2.4/apt-pkg/edsp.cc:288:1: internal compiler error: in trunc_int_for_mode, at explow.c:59
```

**Comment by abrodkin** [comment]
Seems to not happen with vanilla GCC 11.1 though.

**Comment by claziss** [comment]
Reduced case:

```c
typedef int a;
class d {
  struct {};
  int ae;
  int c;

public:
  d() { ae = c; }
};
class e {
  a af;

public:
  operator a() { return af; }
};
class f {
public:
  struct h;
  template <typename> class ag;
  class i;
  class j;
  int *aj;
};
struct f::h {
  e ak;
};
template <typename al> class f::ag {
protected:
  al *am;
  f *an;
  ag(f, a *) {}
};
class f::i : ag<h> {
public:
  j k() const;
};
class f::j : ag<int> {
  int *ao;

public:
  void operator++();
  f g;
  j(int *l) : ag(g, l), ao(l) {}
};
f::j f::i::k() const { return an->aj + am->ak; }
template <int aq> struct m { typedef d as[aq]; };
template <int aq> struct n { typename m<aq>::as at; };
void o(f::i &l) {
  n<sizeof &o> a;
  for (f::j b = l.k();; ++b)
    ;
}
```

**Comment by claziss** [comment]
Strange enough, the issue doesn't manifest using the latest `2021.03` branch. Please can you retry at ur end.

**Comment by abrodkin** [comment]
@claziss it fails with `arc-2021.03-eng0014` & works normally with `arc-2021.03-eng0015`. The only difference between them is https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/16fb463660ee9ce37915f92eca0e7f4eb5bcd43b ("arc: Update ZOL pattern"). Does that make any sense to you?

**Comment by claziss** [comment]
yes, that is the patch fixing this issue.

**Comment by abrodkin** [comment]
Fix in upstream GCC `master` branch (to become GCC 12): https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=9bb20299ba1d1cc3bbd83a07a777fcc5a93cfeb0

**Comment by abrodkin** [comment]
Needs back-porting to https://github.com/foss-for-synopsys-dwc-arc-processors/crosstool-ng for the release. Once done, could be closed.
