### ISSUE TITLE
Bump Binutils to the most recent version 2.37

### ISSUE THREAD

**Issue by abrodkin** [foss-for-synopsys-dwc-arc-processors/toolchain#404]
There's a new Binutils v2.37 released, see https://www.mail-archive.com/info-gnu@gnu.org/msg02923.html.
In particular it contains a fix for Windows (which we previously cherry-picked in `arc-2021.03`), see https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/issues/376.

**Comment by claziss** [comment]
Please use upstream binutils for release. There is no reason why not to use it.
