### ISSUE TITLE
[arc64] Trouble debugging user application with qemu

### ISSUE THREAD

**Issue by vineetgarc** [foss-for-synopsys-dwc-arc-processors/toolchain#407]
qemu: 2021-07-22 0468a2d222af gdb: Consider the whole 8 bytes when writing to GPRs  
gcc/binutils: latest arc6 4branches

`$ qemu-system-arc64 -cpu hs6x -nographic -no-reboot -monitor none -global cpu.freq_hz=5000000 -serial stdio -kernel  vmlinux-210803-arc64 -s -S`

```
$ elf-210803-binutils-d4ca2f3f215f/bin/arc64-elf-gdb -q vmlinux-210803-arc64
add-symbol-file busybox-static-glibc-2.34 0x10380
Reading symbols from busybox-static-glibc-2.34...
Cannot access memory at address 0x145f80
```

[busybox-static-glibc-2.34.gz](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/6927328/busybox-static-glibc-2.34.gz)
[vmlinux-210803-arc64.gz](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/6927338/vmlinux-210803-arc64.gz)

**Comment by shahab-vahedi** [comment]
Can you try your steps like this:

```
# terminal 1
$ qemu-system-arc64 -cpu hs6x                    \
                    -nographic                   \
                    -no-reboot                   \
                    -monitor none                \
                    -global cpu.freq_hz=5000000  \
                    -serial stdio                \
                    -kernel vmlinux-210803-arc64 \
                    -s -S


# terminal 2
$ gdb -q vmlinux-210803-arc64
(gdb) tar rem :1234
(gdb) cont

# let the linux boot completely

# terminal 2
(gdb) <ctrl-c>
(gdb) add-symbol-file busybox-static-glibc-2.34 0x10380
(gdb) ...
```

The idea is that QEMU should know about those _virtual_ addresses before they're introduced to your gdb commands. QEMU will know about them only after such TLB entries exist.

**Comment by vineetgarc** [comment]
Makes sense, but despite doing that I see exact same result.
I waited for kernel to boot and then did the add symbol which spews out the same error msg.
Can you try at your end with the binary artifacts added to issue !

```
add-symbol-file busybox-static-glibc-2.34 0x10380
warning: A handler for the OS ABI "GNU/Linux" is not built into this configuration
of GDB.  Attempting to continue with the default arc64 settings.

Reading symbols from busybox-static-glibc-2.34...
Cannot access memory at address 0x145f80
```

**Comment by vineetgarc** [comment]
There's more weirdness. The symbol information in gdb seems to be wrong too:
The elf entry point is 0x10380, however gdb symbol lookup maps it to abort() at different address, but which happens to be the symbol at numerically lowest address in the elf file.

```
info symbol 0x10380
abort in section .text of busybox-static-glibc-2.34
```

00000000000101e8:  abort:
0000000000010380: __start:

**Comment by shahab-vahedi** [comment]
@cupertinomiranda and I have investigated this a bit more and here's the upshot:

### Cannot access memory at address 0x145f80
This is the address of `_Unwind_DebugHook` that GDB will be [looking for](https://sourceware.org/git/?p=binutils-gdb.git;a=blob;f=gdb/breakpoint.c;h=89af44ee4c6b8dfdca3d07c61fc4e73b2cc04f01;hb=HEAD#l3533). Nevertheless, this error is benign. You can still continue debugging and setting breakpoints as illustrated by the GIF image in the end.

### The text address
The address for loading the symbol file is the text address:
```
$ readelf -WS busybox-static-glibc-2.34 | grep text | awk '{ print "0x"$5 }'
0x101e8

(gdb) add-symbol-file busybox-static-glibc-2.34 0x101e8
```
It should not be confused with the entry address:
```
$ readelf -h busybox-static-glibc-2.34 | grep Entry
  Entry point address:               0x10380
```

### How it works on another system
A sample demo of how it is working on my system with the files provided.
![407](https://user-images.githubusercontent.com/16524902/128264526-cc92c3ac-8436-42e0-b46e-0d65fbd5c2f3.gif)

**Comment by vineetgarc** [comment]
> The address for loading the symbol file is the text address:
> It should not be confused with the entry address:

Hmm that's the issue - I was giving elf entry point as load address (as thats what I remeber always doing) - but I can see why the first symbol address makes sense. In prev runs perhaps first symbol was entry point, which is not any more.
