### ISSUE TITLE
[arc64] -mcmodel=large not working in gcc11

### ISSUE THREAD

**Issue by vineetgarc** [foss-for-synopsys-dwc-arc-processors/toolchain#412]
Trying to link kernel at high address 0xFFFF_0000_0000 is failing (it was working with gcc10 back in december).

```
unsigned int reset_devices;

int __attribute__((__section__(".init.text"))) __attribute__((__cold__)) set_reset_devices(char *str)
{
 reset_devices = 1;
 return 1;
}
```

arc64-linux-gcc  -O3 -c -mcmodel=large --save-temps init-main.c

**gcc11 codegen (NOK)**
```
	st	1,[@reset_devices]	# reset_devices,
	j_s.d	[blink]
	mov_s	r0,1	
```

**vs. gcc10 (OK)**
```
	movhl_s	r0,@reset_devices	# tmp108,
	orl_s	r0,r0,@reset_devices@u32
	st	1,[r0]	# reset_devices,
	mov_s	r0,1
	j_s	[blink]
```

**Comment by vineetgarc** [comment]
There's another issue: if we add static to function, the whole body gets optimized out. Is that expected ?

**Comment by claziss** [comment]
At `O3` the compiler may decide to inline the function body. To make sure your function remains, you can use the attribute `noinline`. Using 32bit addresses when asking for 64bit is not ok.

**Comment by claziss** [comment]
Fix here: https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/d675a5a2790f49dbf14123526a50e5fed5d4eecd

**Comment by VVIsaev** [comment]
Hi @claziss !

I've got similar problem with latest compiler and `elf64arc.x` moved to high address (checked two: build 744 and manually built toolchain):
```c
#include <stdio.h>
#include <stdint.h>

int *to_move;

int main(int argc, char **argv) {
	printf ("0x%lx\n", (unsigned long)to_move);

	return 0;
}
```
```
$ arc64-elf-gcc --save-temps -mcmodel=large -T ./elf64arc.x ./1.c
/slowfs/ru20arcgnu1/arcoss_verification/arc-gnu-toolchain/gnu_builds/arc64/744/arc64-unknown-elf/bin/../lib/gcc/arc64-snps-elf/11.1.1/crtbegin.o: in function `deregister_tm_clones':
crtstuff.c:(.text.deregister_tm_clones+0x4): relocation truncated to fit: R_ARC_32_ME against `no symbol'
collect2: error: ld returned 1 exit status
```
Please find temp files here:
[link-issue.tar.gz](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/6982460/link-issue.tar.gz)

For lower addresses it works fine.

**Comment by claziss** [comment]
`crtbegin.o` is probably compiled for a small/medium memory, and it can be the source of ur issue.  Have you got the chance to compile all the compiler libraries with large memory model?

**Comment by VVIsaev** [comment]
Oh, you're right, that can be an issue for C example.

I reduced example:
```
$ LANG=C arc64-elf-gcc -nostartfiles -nolibc -mcmodel=large -T ./elf64arc.x ./1.s -save-temps
a-1.o: in function `__start':
(.text+0xc): relocation truncated to fit: R_ARC_32_ME against `no symbol'
collect2: error: ld returned 1 exit status
$ cat 1.s
	.section	.bss
	.align	8
	.type	to_move, @object
	.size	to_move, 8
to_move:
	.zero	8
	.section	.rodata
	.align	8

	.section	.text
	.align	4
	.global	__start
	.type	__start, @function
__start:
	movhl	r0,@to_move
	orl	r0,r0,@to_move
```

[linux-issue-asm.tar.gz](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/6982550/linux-issue-asm.tar.gz)
Still small addresses work.

**Comment by claziss** [comment]
`ORL` is missing the `LO32` reloc. Add it here; https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/commit/b3ebe1f81a2b1c26e94b02a6ad07274bd52a6169

**Comment by VVIsaev** [comment]
Thank you, @claziss ! Now I'm able to link the kernel with gcc11 and libgcc built with mcmodel set to large.

Now I see runtime issue with initialized data and function pointer, see:
```c
#include <stdio.h>
#include <stdint.h>


static uint64_t __attribute__((noinline)) test (void) {
	//printf("test\n");

	return 42;
}

struct data {
	uint64_t (*test)(void);
} d = {
	.test = test
};

int __start(int argc, char **argv) {
	d.test();

	return 0;
}
```

```
$ arc64-elf-gcc -nostartfiles   -T ./0x80000000.ld ./1.c -save-temps -o 1-medium
$ objdump -s -j .data ./1-medium
 
./1-medium:     file format elf64-little

Contents of section .data:
 80002038 00000080 00000000                    ........        

$ arc64-elf-gcc -nostartfiles  -mcmodel=large -T ./0xffff0000000.ld ./1.c -save-temps -o 1-large
$ objdump -s -j .data ./1-large

./1-large:     file format elf64-little

Contents of section .data:
 ffff00002040 00000000 00000000                    ........        

$ LANG=C objdump -t ./1-large

./1-large:     file format elf64-little

SYMBOL TABLE:
...
0000ffff00000000 l     F .text	000000000000000c test
...
```

So for `medium` case I see proper address, when for `large` case I see that high bytes are truncated.

Compiler is build from arc64 branches, temp files can be found here:
[struct-ptr-issue.tar.gz](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/6993270/struct-ptr-issue.tar.gz)

**Comment by claziss** [comment]
It looks like `R_ARC_64` reloc doesn't do its job.

**Comment by claziss** [comment]
Fix here: https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/commit/2a6feccb60aefc794278cd16d03182c2d19cd18d

**Comment by VVIsaev** [comment]
Hi @claziss ,

I checked your fix and it works, thank you!

But I faced one new issue (looks similar to #413):
```c
#include <stdio.h>
#include <stdint.h>

#define RAM_BASE 0xffff00000000
#define PAGE_SHIFT 12
#define virt_to_pfn(kaddr) (((unsigned long)(kaddr)) >> PAGE_SHIFT)

#define pfn_shift(kaddr) (virt_to_pfn(kaddr) - virt_to_pfn(RAM_BASE))

struct page {
	int a;
};

struct page *mem_map;

static unsigned long __attribute__((noinline)) test (void * addr) {
	unsigned long r = (mem_map + pfn_shift(addr))->a;

	return (unsigned long)r;
}

int main() {
	struct page l1[8];

	for (unsigned long i = 0; i < 8; i++) {
		l1[0].a = 0xabcd;
	}

	mem_map = l1;
	mem_map -= pfn_shift(l1);
	printf("0x%lx\n", test(l1));

	return 0;
}

int __start() {
	return main();
}

void _exit_halt() {

}
```

This is example based on kernel code, here we are trying to get page descriptor from `mem_map` based on some offset. In this example we subtract some shift from `mem_map` and then in function `test()` we should add it back. So expected output is `0xabcd.

```
$ gcc -O3 2.c
$ ./a.out 
0xabcd

$ arc64-elf-gcc --save-temps -nostartfiles ./2.c -O2  -mcmodel=large -T ./0xffff00000000.ld -specs hl.specs
$ nsimdrv -prop=nsim_fast=0 -prop=nsim_isa_dual_issue_option=1 -prop=nsim_isa_has_hw_pf=1 -prop=nsim_isa_m128_option=1 -prop=nsim_isa_has_hw_pf=1 -prop=nsim_isa_vec64=1 -prop=nsim_isa_family=arc64 -prop=nsim_isa_enable_timer_0=1 -prop=nsim_isa_enable_timer_1=1 -prop=nsim_isa_addr_size=64 -prop=nsim_isa_pc_size=64 -prop=nsim_isa_mpy_option=9 -prop=nsim_isa_mpy64=1 -prop=nsim_isa_div64_option=1 -prop=nsim_isa_div_rem_option=2 -prop=nsim_isa_atomic_option=1 ./a.out 
0x0
```

Function `test()`disasm:
```
0000ffff00000000 <test>:                                                        
    ffff00000000:       7028 0000 ffff          movhl_s r1,0xffff    ; r0 = 0x3fd8; this address we expect to have after shift
    ffff00000006:       5861 0300               lsrl    r0,r0,0xc    ; r0 = 0x3
    ffff0000000a:       7038 0000 e600          orl_s   r1,r1,0xe600    ; r1 = 0xffff0000e600 = &mem_map
    ffff00000010:       1100 0841               ldl     r1,[r1]    ; load mem_map value to r1 = 0x3fffc03fcc;
    ffff00000014:       5915 0000               add2l   r0,r1,r0    ; r0 = 0x3fffc03fd8
    ffff00000018:       2031 0f80 0040 0000     ld.x    r0,[r0,0x400000]    ; r0 = load from [0x3fffc03fd8 + 0x400000 = 0x4000003fd8] = 0 instead of 0xabcd from 0x3fd8
    ffff00000020:       7ee0                    j_s     [blink]
    ffff00000022:       78e0                    nop_s
```
versions are current arc64, temp files:
[array-ptr-issue.tar.gz](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/7034646/array-ptr-issue.tar.gz)

**Comment by claziss** [comment]
The compiler was accepting a constant int in the `LD` 's `LIMM` field larger than 32bit.
Fix here: https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/567f3f5feb9600265ee00d5a202bd8d0398c1452

**Comment by VVIsaev** [comment]
Will file separate issues if any. Thank you!
