### ISSUE TITLE
be linux toolchain build fail: ar: linux.o: No such file or directory

### ISSUE THREAD

**Issue by falaleevms** [foss-for-synopsys-dwc-arc-processors/toolchain#415]
Gcc sources: https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/9256d481edc

`arceb-arc700-linux-uclibc`, `arceb-archs-linux-uclibc`, `arceb-archs-linux-gnu` are failed with the same error during `gcc-stage1` building :
```
ar rcT …………………… linux.o host-linux.o
ar: linux.o: No such file or directory
```
Find full build log in attachment.

Command that was use to build toolchain:
```
./build-all.sh --no-pdf --no-system-expat --strip     --no-auto-pull --no-auto-checkout --no-native-gdb     --no-optsize-newlib --no-optsize-libstdc++     --external-download  --uclibc-build-in-src-tree             --release-name "nightly build 506"             --install-dir "/slowfs/ru20arcgnu1/arcoss_verification/arc-gnu-toolchain/workspace/builds/742/arceb-archs-linux-uclibc" --big-endian --no-elf32 --uclibc --no-multilib --cpu archs --config-extra --with-python=no --target-cflags "-O2 -g -mcpu=hs38"
```

Build log: [uclibc-build-2021-08-12-2134.log](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/6992932/uclibc-build-2021-08-12-2134.log)

**Comment by claziss** [comment]
The arceb triplet was wrong, fix here https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/99179702c27a41edfe1f740a704668707b9b1d35
