### ISSUE TITLE
Assembler error: operand out of range

### ISSUE THREAD

**Issue by vkremneva** [foss-for-synopsys-dwc-arc-processors/toolchain#416]
Build of babeltrace2 fails with error:

> /tmp/cc2UJb4Y.s: Assembler messages:
> /tmp/cc2UJb4Y.s:6468: Error: operand out of range (0xffffffffffffefa4 is not between 0xfffffffffffff000 and 0x0000000000000fff)
> /tmp/cc2UJb4Y.s:8855: Error: operand out of range (0xffffffffffffef96 is not between 0xfffffffffffff000 and 0x0000000000000fff)

You can observe builds [here](http://ru20arcgnu1:8080/?reason=babeltrace2-2.0.3).

This build fails when attempting to compile test_bitfield.c.

Compiler command:
`arc64-buildroot-linux-gnu-gcc -DHAVE_CONFIG_H -I../../include -I../../src -I../../src -include common/config.h -I../../tests/utils -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -pthread -Iglib-2.0 -Iglib-2.0/include -pthread  -Wall -Wextra -Wmissing-prototypes -Wmissing-declarations -Wnull-dereference -Wundef -Wredundant-decls -Wshadow -Wjump-misses-init -Wnested-externs -Wwrite-strings -Wformat=2 -Wno-format-nonliteral -Wstrict-aliasing -Wmissing-noreturn -Winit-self -Wduplicated-cond -Wduplicated-branches -Wlogical-op -Wno-unused-parameter -Wno-sign-compare -Wno-cast-function-type -Wno-missing-field-initializers -Wold-style-definition -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -Os  -D_FORTIFY_SOURCE=1 -c -o test_bitfield.o test_bitfield.c`

Attaching test_bitfield.c and test_bitfield.i 
[babeltrace2-test_bitfield.zip](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/7048606/babeltrace2-test_bitfield.zip)

**Comment by claziss** [comment]
Two `DBNZ` instructions are having their targets out of bounds.

**Comment by vkremneva** [comment]
### Similar error can be observed when building **vlc**:

> {standard input}: Assembler messages:
> {standard input}:10847: Error: operand out of range (0x000000000000106c is not between 0xfffffffffffff000 and 0x0000000000000fff)

vlc builds are [here](http://ru20arcgnu1:8080/?reason=vlc-3.0.11).

Compiler command:
`arc64-buildroot-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I.. -D__PLUGIN__ -I./access -I./codec -I../include -I../include -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -Os    -Wall -Wextra -Wsign-compare -Wundef -Wpointer-arith -Wvolatile-register-var -Wformat -Wformat-security -Wbad-function-cast -Wwrite-strings -Wmissing-prototypes -Werror-implicit-function-declaration -Winit-self -Wlogical-op -Wshadow=local -pipe -fvisibility=hidden -O3 -fno-math-errno -funsafe-math-optimizations -fno-rounding-math -fno-signaling-nans -fcx-limited-range -funroll-loops -fomit-frame-pointer -fstack-protector-strong -c -o packetizer/h264_nal.o packetizer/h264_nal.c`

Attaching .c and .i files
[vlc-h264_nal.zip](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/7048797/vlc-h264_nal.zip)

### Also similar error is present for **pcre**:

> /tmp/ccsMym56.s: Assembler messages:
> /tmp/ccsMym56.s:5429: Error: operand out of range (0x0000000000001096 is not between 0xfffffffffffff000 and 0x0000000000000fff)

pcre [builds](http://ru20arcgnu1:8080/?reason=pcre-8.44)

Compiler command:
`arc64-buildroot-linux-gnu-gcc -DHAVE_CONFIG_H -I. -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -O2  -D_FORTIFY_SOURCE=2 -c -o libpcre_la-pcre_exec.o pcre_exec.c`

Files: [pcre.zip](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/7048881/pcre.zip)

**Comment by claziss** [comment]
Simplified test:

```c
a, b, f, g, k, m, n, c, o, aa, ab, ac, ad, ae, w, af, ag, ah, ai, aj, ak, al, y,
    am, an;
long d, e, h, p, v, ao, ap, aq, ar, as;
short j;
unsigned long at;
static au(int av) {
  int q;
  struct {
    char c[8];
    int i
  } s;
  unsigned r, l;
  r = 0;
  for (; r < 128; r++)
    for (; l <= -r; l++) {
      __typeof__(av) t;
      char *u = s.c;
      long z = v = r / 8, aw;
      t = sizeof({}) << l;
      a = u[v] = a;
      long ax = t;
      for (; ax; ax--)
        t = v;
      for (; v < b; v++)
        u[v] = v;
      __typeof__(q) *ay;
      e = r;
      long az = e % (sizeof(0) * 8 - 1);
      aw = sizeof(0) << aw ? w == sizeof(char) ?: w ?: w : af--;
      for (; af;) {
        d = sizeof(0) << r % ao;
        w = u[af] ?: sizeof({}) << r;
      }
      if (({
            if (q != av) {
              for (; f; f++)
                ;
              ba("");
            }
            q != av;
          }))
        return;
      {
        for (; a; ag++) {
          m = n = sizeof(0) << r;
          u[v] = v = n;
        }
        u[n] = g;
        a = h / v;
        for (; a;)
          t = 1;
        for (; n < 1; n++)
          u[n] = n;
        *ay = &q;
        __typeof__(*ay) t;
        ao = sizeof 8;
        long bb = a - 1;
        if (u[e] & sizeof(char) << (a % ao ?: ao))
          if (c) {
            a = j &= (ap - r) % (sizeof(t) * 8 - 1);
            for (; r;)
              t = sizeof({}) << az;
          }
        az = t;
        for (; a;)
          t = sizeof({}) << t;
        t = t ?: sizeof({});
        for (; bb >= 1; bb--)
          ap = a = sizeof(0) << r % ao;
        u[bb] = j &= *ay = t;
      }
      if (({
            if (q != av) {
              bc(av);
              long i = 0;
              for (; i < 8; i++)
                if (i)
                  ba();
            }
            q != av;
          }))
        return;
      for (; aq < 8; aq++)
        if (d)
          aj = r;
      aj |= 8;
      if (r) {
        n = u[c] = a;
        for (; a;)
          ;
      }
      for (; ak < b - 1; ak++)
        u[c] = av;
      if (z % 8)
        u[b] |= av;
      {
        __typeof__(*ay) t;
        p = l;
        if (u[ah] << l % -1)
          if (o) {
            if (r % ar)
              d &= aj / 8 - 1;
            az = -r % -1;
            for (; a;)
              t = sizeof({}) << az;
          }
        ai = l % e % (sizeof(t) * 8 - 1);
        for (; a;)
          t = sizeof({}) << az;
        for (; ah;)
          t = t ? u[e] ?: sizeof({}) : sizeof({});
        if (r)
          aj = sizeof({}) << ar;
        al &= a = (ar - r) / t;
        az = r % ar % (t - 1);
        for (; a;)
          t = sizeof(int) << az ?: sizeof({});
        *ay = t;
      }
      if (({
            if (q != av) {
              bc("");
              for (; aa; aa++)
                ba(s);
            }
            q != av;
          }))
        return;
      for (; aq < 8; aq++)
        if (d) {
          d = ao;
          if (z)
            y = 0;
          w = k = y;
        }
      if (r)
        w &= u[k] |= k;
      for (; k < 1; k++)
        u[k] = av;
      if (z % ao) {
        d = sizeof(0) << d;
        u[k] |= w;
      }
      do {
        long x = sizeof(long);
        e = a;
        if (u[a] ? f : n) {
          f = f % x;
          d = ~sizeof({}) << r;
          f &= an;
          az = (at - r) % (8 - 1);
          t = sizeof({}) << az;
          *ay = t;
          break;
        }
        az = h % (8 - 1);
        for (; a;)
          t = t ?: sizeof({}) << az;
        t |= t ?: sizeof({});
        for (; ah;)
          if (r % x)
            e = sizeof({}) << r;
        a = az = (x - r % x) % (8 - 1);
        for (; a;)
          t = sizeof({}) << az;
      } while (0);
      if (q) {
        bd("");
        for (;;)
          ba("", s);
      }
      aq = 0;
      for (; a; aq++)
        s.c[a] = 0;
      if (ah) {
        d = sizeof(0) << r;
        if (z % 8)
          d |= sizeof(0);
        u[n] &= v = d;
        for (; t;)
          t = ab;
      }
      for (; ah - 1; d++)
        u = ab;
      if (z % 8)
        d &= u[d] |= d;
      u[ad] &= d;
      a = ao / (8 - 1);
      for (; a;)
        t = ap = ad;
      for (; ad >= c; ad--)
        if (r) {
          d = (__typeof__(0))sizeof 0 << r;
          as &= a = r % (sizeof(t) - 1);
          ae = r % ac;
          for (; a;)
            t = t ? sizeof(long) : sizeof({});
        }
      *ay = t;
      if (av)
        for (;; am++)
          ba(s.c[a]);
    }
}
be() { au(be); }
```

Compiler invoke line:
`arc64-elf-gcc -Os example.i -c`

**Comment by claziss** [comment]
The compiler computes the size of a loop body (which is suitable for dbnz) before delay slot filler. The delay slot filler can speculatively fill in the delay slot leading to a possible increase of the loop total size. Hence, the issue observed.

**Comment by claziss** [comment]
I have disabled the speculation during delay slot filler which will fix your issue as well.
https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/dd10b2f45be3eb604279a4e6c27d78f9e702bf8d

**Comment by vkremneva** [comment]
### bearssl also has similar error

(checked just now)

> /tmp/ccEPbq6v.s: Assembler messages:
> /tmp/ccEPbq6v.s:406: Error: operand out of range (0x0000000000001016 is not between 0xfffffffffffff000 and 0x0000000000000fff)
> make[1]: *** [build/obj/ssl_hs_server.o] Error 1

[builds](http://ru20arcgnu1:8080/?reason=bearssl-0.6)

Compiler line: 
`arc64-buildroot-linux-gnu-gcc -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -Os  -D_FORTIFY_SOURCE=1 -fPIC -Isrc -Iinc -c -o build/obj/ssl_hs_server.o src/ssl/ssl_hs_server.c`

.i file: [ssl_hs_server.zip](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/7066773/ssl_hs_server.zip)

**Comment by vkremneva** [comment]
**vlc** and **pcre** are building fine

**Comment by vkremneva** [comment]
error is still present for **babeltrace2**

> /tmp/ccRoxY2k.s: Assembler messages:
> /tmp/ccRoxY2k.s:6432: Error: operand out of range (0xffffffffffffefd8 is not between 0xfffffffffffff000 and 0x0000000000000fff)
> /tmp/ccRoxY2k.s:8804: Error: operand out of range (0xffffffffffffefd8 is not between 0xfffffffffffff000 and 0x0000000000000fff)
> make[3]: *** [test_bitfield.o] Error 1

**Comment by vkremneva** [comment]
both **babeltrace2** and **bearssl** are building fine
