### ISSUE TITLE
Fail to build mac and win toolchains with gcc 11: This file requires compiler and library support for the ISO C++ 2011 standard 

### ISSUE THREAD

**Issue by falaleevms** [foss-for-synopsys-dwc-arc-processors/toolchain#418]
Building mac and win toolchains with gcc 11 fails with following error:

```
[ERROR]    /usr/include/c++/4.8.2/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
```

Examples:
Win: [resultsdb](http://de02-resultsdb:8080/result.php?Project=30&pkey=26810), [defconfig](http://de02-resultsdb:8080/attachment.php?Project=30&attach_id=52888), [build log](http://de02-resultsdb:8080/attachment.php?Project=30&attach_id=52889)
Mac: [resultsdb](http://de02-resultsdb:8080/result.php?Project=30&pkey=26810), [defconfig](http://de02-resultsdb:8080/attachment.php?Project=30&attach_id=52888), [build log](http://de02-resultsdb:8080/attachment.php?Project=30&attach_id=52889)

**Comment by abrodkin** [comment]
Fix posed upstream https://github.com/crosstool-ng/crosstool-ng/pull/1593, needs to be cherry-picked or rebased-on in our CT-NG for for `arc-2021.09` release.

@temap once we get that fix in our CT-NG tree, this issue could be closed.

**Comment by abrodkin** [comment]
Got merged upstream (https://github.com/crosstool-ng/crosstool-ng/commit/5c5b4df6d33118b2df6cc4aea2564fccb9d53104) & we're now have it via re-base, see https://github.com/foss-for-synopsys-dwc-arc-processors/crosstool-ng/commit/5c5b4df6d33118b2df6cc4aea2564fccb9d53104.
