### ISSUE TITLE
Building archs native toolchain fails with: DWARF error: can't find .debug_ranges section. 

### ISSUE THREAD

**Issue by falaleevms** [foss-for-synopsys-dwc-arc-processors/toolchain#419]
Building archs native toolchain fails with following error:

```
[ERROR]    .../arc-snps-linux-gnu/bin/ld: DWARF error: can't find .debug_ranges section.
```

[ResultsDB](http://de02-resultsdb:8080/result.php?Project=30&pkey=26815), [defconfig](http://de02-resultsdb:8080/attachment.php?Project=30&attach_id=52894), [build log](http://de02-resultsdb:8080/attachment.php?Project=30&attach_id=52893)

**Comment by abrodkin** [comment]
Looks similar to the upstream bug https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100346.

**Comment by temap** [comment]
The toolchain was built with the wrong Binutils version (2.34). Updating Binutils to 2.37 fixed the issue.
