### ISSUE TITLE
GCC: Assume GNU AS & GNU LD to be used for ARC Elf & Linux toolchains by default

### ISSUE THREAD

**Issue by abrodkin** [foss-for-synopsys-dwc-arc-processors/toolchain#421]
It's possible to configure GCC driver with some assumption on which assembler and linker it's going to deal with.  Which will allow GCC driver to use specific features of a certain [at least GNU versions] tools.

Note, those are external components and so GCC has no idea what use is going to use. For example typical GNU toolchain would use assembler and linker which come from Binutils package, while a toolchain for Mac most probably will use those of LLVM.

In case of ARC default are AS and LD from Binutils and so let's make it really enabled by default with something like that:
```diff
diff --git a/gcc/config.gcc b/gcc/config.gcc
index cecf640a645..1e54eb8cf4e 100644
--- a/gcc/config.gcc
+++ b/gcc/config.gcc
@@ -1201,6 +1201,8 @@ arc-*-elf* | arc[eb]*-*-*)
        if test "x$with_cpu" != x; then
                tm_defines="${tm_defines} TARGET_CPU_BUILD=PROCESSOR_$with_cpu"
        fi
+       gas=yes
+       gnu_ld=yes
        if test x${with_endian} = x; then
                case ${target} in
                arc*be-*-* | arc*eb-*-*)        with_endian=big ;;
@@ -1222,6 +1224,8 @@ arc-*-linux* | arc[eb]*-*linux*)
        if test "x$with_cpu" != x; then
                tm_defines="${tm_defines} TARGET_CPU_BUILD=PROCESSOR_$with_cpu"
        fi
+       gas=yes
+       gnu_ld=yes
        if test x${with_endian} = x; then
                case ${target} in
                arc*be-*-* | arc*eb-*-*)        with_endian=big ;;
```

**Comment by luismgsilva** [comment]
This feature has been successfully integrated into branch `arc64` and `arc-2023.09`

https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/4305c12c1252b1764293e482ca125355ce61e1b0
https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/d9ee4f051c34261d60725a787839f8f2c49304ff
