### ISSUE TITLE
Document "interrupt" attribute

### ISSUE THREAD

**Issue by abrodkin** [foss-for-synopsys-dwc-arc-processors/toolchain#423]
There's a simple way to declare an interrupt handler with `__attribute__ ((interrupt("ilink")))` which acts similarly to MWDT's `_Interrupt` attribute. And though this attribute is mentioned in the official GCC documentation, it might make sense to add it and its usage example in our user docs for the toolchain.

Note for ARC600 & ARC700 it's `__attribute__ ((interrupt("ilink1")))`.

**Comment by kolerov** [comment]
@abrodkin Here is an article: https://foss-for-synopsys-dwc-arc-processors.github.io/experimental-documentation/2023.09/baremetal/general/interrupts/. Can you review, please? [A corresponding `.md` file](https://github.com/foss-for-synopsys-dwc-arc-processors/experimental-documentation/blob/main/docs/baremetal/general/interrupts.md).

**Comment by abrodkin** [comment]
@kolerov that looks awesome, thanks! With that in place we may close this issue.
