### ISSUE TITLE
native GDB fails to run the application

### ISSUE THREAD

**Issue by EvgeniiDidin** [foss-for-synopsys-dwc-arc-processors/toolchain#428]
Trying to run application with native-built gdb fails with message 
```
Don't know how to run.  Try "help target".
```
The full log is next:
```
# ./bin/gdb /root/hw.exe
GNU gdb (ARC HS GNU/Linux glibc toolchain - build 836) 10.2
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "--host=arc-host_snps-linux-gnu --target=arc-snps-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /root/hw.exe...
(gdb) b main
Breakpoint 1 at 0x10376: file ./hw.c, line 5.
(gdb) r
Don't know how to run.  Try "help target".
```

**Comment by abrodkin** [comment]
IIRC we saw that before and the reason is mismatch of `--host=arc-host_snps-linux-gnu` & `--target=arc-snps-linux-gnu`.
@shahab-vahedi to me that looks at least interesting, why on Earth we really depend on complete match of `--host` & `--target`?

**Comment by abrodkin** [comment]
See https://sourceware.org/git/?p=binutils-gdb.git;a=blob;f=gdb/configure.ac;h=0d91be59cd6159fba8c1e961bac231c48055c583;hb=HEAD#l181:
```
if test "${target}" = "${host}"; then
  gdb_native=yes
else
  gdb_native=no
fi
```
So either in upstream sources some more fancy filtering should be done in that comparison, or we have to accommodate this peculiarity in the build-system (in that particular case - Crosstool-NG).

**Comment by shahab-vahedi** [comment]
The host was not set correctly: `--host=arc-host_snps-linux-gnu`, it should have been `--host=arc-snps-linux-gnu `.

**Comment by shahab-vahedi** [comment]
> IIRC we saw that before and the reason is mismatch of `--host=arc-host_snps-linux-gnu` & `--target=arc-snps-linux-gnu`. @shahab-vahedi to me that looks at least interesting, why on Earth we really depend on complete match of `--host` & `--target`?

Isn't that the definition of a **native** debugger!? Anything else would be a *cross* debugger. A cross debugger relies on GDBservers (GDBstubs) to do its job, while a native one can directly use the OS's ptrace.

**Comment by abrodkin** [comment]
Ok the mystery is busted now.
It was a "cross GDB" built in a canadian cross manner. So technically it was a normal target executable, thus it started w/o problems. But it was indeed configured in a special way, let's put it like that. For the record that binary could be used for "remote" or even local debugging while being connected to the `gdbserver` :)

So for Crosstool-NG we need to disable cross GDB and enable true native GDB and all works then:
```
# CT_GDB_CROSS is not set
CT_GDB_NATIVE=y
```
