### ISSUE TITLE
"ar" on windows in cmd.exe throws a warning message about liblto_plugin.so

### ISSUE THREAD

**Issue by abrodkin** [foss-for-synopsys-dwc-arc-processors/toolchain#431]
In Windows' `cmd.exe` prompt run the following commands (inspired by https://github.com/msys2/MINGW-packages/issues/7890#issue-801698972):
```bash
touch empty.c
arc-elf32-gcc -c -o empty.o empty.c
arc-elf32-ar -rc libempty.a empty.o
```
And see the following window pop-up:
![image](https://user-images.githubusercontent.com/1618098/136060294-4d33f58c-04f1-4550-bd17-efb20a1c187d.png)

Similar to https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/issues/376

**Comment by abrodkin** [comment]
As with the previous one (https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/issues/376#issuecomment-832675820), there's a work-around with removal of `lib\bfd-plugins\liblto_plugin.so`.

**Comment by kolerov** [comment]
This error does not occur in the latest release for Windows.
