### ISSUE TITLE
Issues building emstarter kit examples

### ISSUE THREAD

**Issue by eroom1966** [foss-for-synopsys-dwc-arc-processors/toolchain#44]
Hi

I am trying to build the em starter examples (fibonacci) and I have hit two issues
1. The Makefiles for gnu reference MAKE=gmake, but the ide only contains make and not gmake
2. The crt0.s fails to compile 

do you have access to these examples, I am not sure if I am able to provide them directly

Thx
Lee

**Comment by anthony-kolesov** [comment]
Hi Lee,

I've checked EMSK project and indeed it uses gmake. I cannot fix this myself, because EMSK software is developed in a different team, but I have created a bug report for them.

Same is for crt0.s.

Thanks!

**Comment by eroom1966** [comment]
Thanks
