### ISSUE TITLE
GCC hangs when building gsl with -Os

### ISSUE THREAD

**Issue by vkremneva** [foss-for-synopsys-dwc-arc-processors/toolchain#440]
When building gsl for ARC64 we get a timeout (>300 mins).

Leads to hang:
`arc64-buildroot-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I..  -I.. -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -Os -g0 -D_FORTIFY_SOURCE=1 -c -o invtri_complex.lo invtri_complex.c`

If I remove _-Os_ flag it compiles with warning:
`arc64-buildroot-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I..  -I.. -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -g0 -D_FORTIFY_SOURCE=1 -c -o invtri_compliex.lo invtri_complex.c`

> In file included from arc64-buildroot-linux-gnu/sysroot/usr/include/bits/libc-header-start.h:33,
                 from arc64-buildroot-linux-gnu/sysroot/usr/include/math.h:27,
                 from ../gsl/gsl_math.h:22,
                 from invtri_complex.c:24:
arc64-buildroot-linux-gnu/sysroot/usr/include/features.h:412:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
  412 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      |    ^~~~~~~

Attaching  _invtri_complex.i_ file: [invtri_complex.tar.gz](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/7364924/invtri_complex.tar.gz)

**Comment by claziss** [comment]
I have updated the compiler [costs,](https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/0e665dcf70cfbb99c3ebbc0742d6d402a82d8e59) please retry.

**Comment by vkremneva** [comment]
Builds fine, thank you!
