### ISSUE TITLE
GCC fails to compile access to pointer in volatile struct when -mvolatile-di is set

### ISSUE THREAD

**Issue by VVIsaev** [foss-for-synopsys-dwc-arc-processors/toolchain#441]
For hostlink ver. 2 we have to call some function from hostlink structure. The pointer is set by debugger, so structure must be uncached and the only way to have uncached access to structure for arc64 is using volatile+mvolatile-di flag.

Here is an issue:
```
$ cat 1.c 
#include <stddef.h>

struct _hl {                                                            
	int *ptr;
};

volatile struct _hl HL;

int main() {
	if (HL.ptr) {
		return 1;
	}

	return 0;
}
$ arc64-elf-gcc -mvolatile-di --save-temps ./1.c 
a-1.s: Assembler messages:
a-1.s:26: Error: flag mismatch for instruction 'ldl'
```
Compiler build used is 913, temp files can be found here: [hl-broken.tar.gz](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/7418783/hl-broken.tar.gz).

**Comment by claziss** [comment]
Per ARC64 ISA, there is no `ldl.di` instruction. I'll just throw a more meaningful error in this case.

**Comment by claziss** [comment]
Fixed in this commit:
[e54a551489c](https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/e54a551489c) "arc64: Don't use .di flag for ldl/stl instructions"

A compiler warning (`-Waddress`) is emitted when one is trying to use `ldl/stl` with `.di` flag.
