### ISSUE TITLE
EM Starter Kit

### ISSUE THREAD

**Issue by eroom1966** [foss-for-synopsys-dwc-arc-processors/toolchain#45]
I have recently started to try to use an em starter kit,
I am trying to folow the instructions here
https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/wiki/EM-Starter-Kit

Here are my issues
1. I have installed 
https://github.com/foss-for-synopsys-dwc-arc-processors/arc_gnu_eclipse/releases/download/arc-2014.08/ARC_GNU_IDE_2014.08_win_install.exe
1. I tried to look for the directory extras/em_starter_kit - but cannot find this in the installation tree ?
   where are the linker scripts such as em5.lds ?
2. I then compiled an app using the instructions here
   https://github.com/foss-for-synopsys-dwc-arc-processors/arc_gnu_eclipse/wiki/Building-a-C-Project
   but when I try to debug following these instructions
   
   > openocd -s C:\arc_gnu\share\openocd\scripts -f C:\arc_gnu\share\openocd\scripts\target\snps_em_sk.cfg
   > I get a mesage that the file C:\arc_gnu\share\openocd\scripts\target\snps_em_sk.cfg does not exist, which is correct, but there is a file called  C:\arc_gnu\share\openocd\scripts\target\snps_em_sk_fpga.cfg
   > so I presume this is a typo
   > so next I try
   > openocd -s C:\arc_gnu\share\openocd\scripts -f C:\arc_gnu\share\openocd\scripts\target\snps_em_sk_fpga.cfg
   > and now I get 

C:\Users\moore>openocd -s c:\arc_gnu\share\openocd\scripts -f c:\arc_gnu\share\o
penocd\scripts\target\snps_em_sk_fpga.cfg
Open On-Chip Debugger 0.9.0-dev-g8be39d0-dirty (2014-12-15-17:16)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.sourceforge.net/doc/doxygen/bugs.html
Error: session's transport is not selected.
Info : session transport was not selected, defaulting to JTAG
Error: Debug adapter doesn't support any transports?
Runtime Error: embedded:startup.tcl:20:
in procedure 'script'
at file "embedded:startup.tcl", line 58
in procedure 'jtag' called at file "c:\arc_gnu\share\openocd\scripts\target\snps
_em_sk_fpga.cfg", line 13
in procedure 'default_to_jtag' called at file "embedded:startup.tcl", line 165
in procedure 'transport' called at file "embedded:startup.tcl", line 157
in procedure 'ocd_bouncer'
at file "embedded:startup.tcl", line 20

I am completely lost how to get a simple hello world compiled, linked and running in a debugger.
is anybody able to guve guidance ?

I would much prefer command line tools rather than an IDE

Thx
Lee

**Comment by anthony-kolesov** [comment]
1. `extras/em_starter_kit` is in this repository: https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/tree/arc-4.8-dev/extras/em_starter_kit . I've edited text so it will be more clear where to search for those files.
2. File should be `board\snps_em_sk.cfg` not `target\snps_em_sk.cfg`. I see that screenshots are outdated, as on them there is an older file, but in theory you don't need to change this configuration at all - `board\snps_em_sk.cfg` is a default path for OpenOCD configuration file when you create new Debug Configuration in Eclipse and select OpenOCD as a target GDB server.

With linker script and crt0.s the [first guide](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/wiki/EM-Starter-Kit) should be enough to get command line tools working. If there are still problems - please update this issue.

Note that things like "printf()" will not work with GNU tools and EM SK, so "hello world" is more complex than that. In the Eclipse IDE there is a such a template (although for the older EM4...), but with command line tools you can just grab those two important files directly:
- https://github.com/foss-for-synopsys-dwc-arc-processors/arc_gnu_eclipse/blob/master/org.eclipse.cdt.cross.arc.gnu/templates/projecttemplates/EMSK_HelloWorld_C_Project/src/Basename.c
- https://github.com/foss-for-synopsys-dwc-arc-processors/arc_gnu_eclipse/blob/master/org.eclipse.cdt.cross.arc.gnu/templates/projecttemplates/EMSK_HelloWorld_C_Project/src/starterkit.h

And then use Putty to connect to the UART port of EMSK, that should be described in the EM SK User Guide.

**Comment by eroom1966** [comment]
Thanks for the update
