### ISSUE TITLE
Bare metal ARC600 project failing to find floating point libraries at link time

### ISSUE THREAD

**Issue by rmbusy** [foss-for-synopsys-dwc-arc-processors/toolchain#451]
This may be something fundamental that I'm missing, but when trying to link a rather large project built with arc_gnu_2021.09-rc1_prebuilt_elf32_le_linux_install, it's failing to find the floating point libraries, and I'm not seeing them in the pre-built tool chain package.  The processor we're using doesn't have hardware floating point support, so we're using the -msoft-float option.  Are the libraries there and I'm just not seeing them, or do I need to rebuild the tool chain and force it to include them?  I was expecting everything to be there already. The link stage fails with unresolved symbols, like __extendsfdf2, __divdf3, __truncdfsf2, pow, etc.

**Comment by claziss** [comment]
Hi,
I am using the following test program:
```c
volatile double b = 1.341;

float main (double a)
{
  a /= b;

  return (float)a;
}
```
which is using some of the functions which you mentioned:
```asm
main:
	push_s	blink
	ld	r2,[@b]	;23
	ld	r3,[@b+4]	;23
	bl @__divdf3;1
	bl @__truncdfsf2;1
	pop_s	blink
	j_s	[blink]
	.size	main, .-main
```
I've used this compilation line `arc-elf32-gcc -mcpu=arc600 -O1  t01.c` without any issue. For the test, I've used the [`2021.09`  release.](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/releases/download/arc-2021.09-release/arc_gnu_2021.09_prebuilt_elf32_le_linux_install.tar.gz)
To help you further, please provide a simple test like the one which I've shown, with the commands used.
Thank you.
[t01.tar.gz](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/7725534/t01.tar.gz)

**Comment by rmbusy** [comment]
Hmm, I tried your exact test, and it links fine.  Next, I copied the first failing function from my build that used float into the test file, and it failed to compile because I didn't include <math.h>.  Added that, and it failed to link with undefined reference to "pow" (used in this code).  Added -lm to the end of the cmd line, and it links clean.

Looked at the first failing source file, and the person had "math.h", which Metaware never complained about.  However, I still had a link failure with "pow", even though I had -lm in the linker options.  I moved the -lm to the very end of the linker options line, and then it no longer complains.

I wasn't aware the location of -lm in the linker options was critical.  To confirm this, I moved -lm earlier in the test file command line, and it also fails.

Works  :
`arc-elf32-gcc -mcpu=arc600 -O1 testfloat.c -o testfloat.out -lm`
Doesn't work :
`arc-elf32-gcc -mcpu=arc600 -O1 -lm testfloat.c -o testfloat.out`

The function I'm testing looks like this :
```c
uint16_t db2int(float param)
{
    uint16_t result;

    float fw = pow((double)10.0, (double)(param/20.0));
    result = (uint16_t) (0x8000 * fw);
    return (result);
}
```
Thanks for the help.  I think I can close this issue, although I'm still not sure why the position of -lm is important.

**Comment by claziss** [comment]
`-lm` is signalizing to linker that you want to link the math library (home of the `pow` function). Please be aware, linking order counts.  Maybe this [link](https://eli.thegreenplace.net/2013/07/09/library-order-in-static-linking) may help you.
