### ISSUE TITLE
gcc: hs5x: crash on accessing members of a structure using pointer

### ISSUE THREAD

**Issue by geomatsi** [foss-for-synopsys-dwc-arc-processors/toolchain#457]
gcc version: branch arc64, commit db631d1a440265f0718d17baab33230823de604c
glibc toolchain built using [arc-gnu-toolchain](https://github.com/foss-for-synopsys-dwc-arc-processors/arc-gnu-toolchain), commit  acea2ee0111850b27f38cbf9c7809c6fa2fa9c03, configured as follows:

```
$ ./configure --target=arc32 --enable-linux
```

Example:

```
#include <stdint.h>

struct test_struct {
        uint8_t data[1017];
        uint64_t test;
};

void test(struct test_struct *tp)
{
        tp->test = 0;
}
```

Failure:
```
arc32-linux-gnu-gcc -nostdlib -mcpu=hs5x -c test.c -o test
during RTL pass: split5
test.c: In function 'test':
test.c:12:1: internal compiler error: in gen_reg_rtx, at emit-rtl.c:1168
   12 | }
      | ^
0x55f192 gen_reg_rtx(machine_mode)
        /home/matsi/code/arc-gnu-toolchain/gcc/gcc/emit-rtl.c:1168
0xdcec88 arc64_prepare_move_operands(rtx_def*, rtx_def*, machine_mode)
        /home/matsi/code/arc-gnu-toolchain/gcc/gcc/config/arc64/arc64.c:4356
0x1061a02 gen_movsi(rtx_def*, rtx_def*)
        /home/matsi/code/arc-gnu-toolchain/gcc/gcc/config/arc64/arc64.md:610
0x7bf61b rtx_insn* insn_gen_fn::operator()<rtx_def*, rtx_def*>(rtx_def*, rtx_def*) const
        /home/matsi/code/arc-gnu-toolchain/gcc/gcc/recog.h:407
0x7bf61b emit_move_insn_1(rtx_def*, rtx_def*)
        /home/matsi/code/arc-gnu-toolchain/gcc/gcc/expr.c:3766
0x7bfb05 emit_move_insn(rtx_def*, rtx_def*)
        /home/matsi/code/arc-gnu-toolchain/gcc/gcc/expr.c:3936
0x106be6f gen_split_35(rtx_insn*, rtx_def**)
        /home/matsi/code/arc-gnu-toolchain/gcc/gcc/config/arc64/arc32.md:16
0x795bb5 try_split(rtx_def*, rtx_insn*, int)
        /home/matsi/code/arc-gnu-toolchain/gcc/gcc/emit-rtl.c:3834
0xa37c31 split_insn
        /home/matsi/code/arc-gnu-toolchain/gcc/gcc/recog.c:3363
0xa3cd97 split_all_insns_noflow()
        /home/matsi/code/arc-gnu-toolchain/gcc/gcc/recog.c:3525
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
```

The problem can be observed for the following `data` field sizes: 1017, 1018, 1019, 1020

**Comment by claziss** [comment]
Thank you for signaling this issue. It unveiled two problems:
1. The double store addresses can be split thus the offset needs to be smaller than the one in the address to accommodate the extra arithmetic needed by split operation. 
2. The 64bit move should only be available when LL64 option is available.

**Comment by claziss** [comment]
For the second issue, I have pushed a patch to `arc64` as it is standalone:
88f3e6aebd7 arc32: Allow 64b moves only when we have LL64

For the first issue, the patch is in `arc32_wip` and it will be merged latter on this week into main `arc64` branch.

@geomatsi  please let me know how does it work for you the current `arc64` branch.

**Comment by geomatsi** [comment]
Hi @claziss 

Thanks, the second part of the fix helps us with HS5x kernel build.
