### ISSUE TITLE
[GCC] Build fails because of ">=0" of unsigneds

### ISSUE THREAD

**Issue by shahab-vahedi** [foss-for-synopsys-dwc-arc-processors/toolchain#459]
My x86_64 GCC version: `gcc (GCC) 10.2.1 20201203`
ARC64 GCC commit: [80711e9378 arc64: Add Vectorizer cost hook.](https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/80711e9378)

```
$ cd arc-gnu-toolchain
$ autoconf
$ ./configure --prefix=/path/to/install
$ make -j $(nproc)
...
ctype_members.cc: In member function 'virtual char std::ctype<wchar_t>::do_narrow(wchar_t, char) const':
ctype_members.cc:216:14: error: comparison of unsigned expression in '>= 0' is always true [-Werror=type-limits]
  216 |     if (__wc >= 0 && __wc < 128 && _M_narrow_ok)
      |         ~~~~~^~~~
ctype_members.cc: In member function 'virtual const wchar_t* std::ctype<wchar_t>::do_narrow(const wchar_t*, const wchar_t*, char, char*) const':
ctype_members.cc:230:14: error: comparison of unsigned expression in '>= 0' is always true [-Werror=type-limits]
  230 |    if (*__lo >= 0 && *__lo < 128)
      |        ~~~~~~^~~~
cc1plus: all warnings being treated as errors
make[6]: *** [Makefile:643: ctype_members.lo] Error 1

**Comment by shahab-vahedi** [comment]
```
$ ./configure --disable-werror ...
```
works around this.

**Comment by abrodkin** [comment]
Label `arc64`?

**Comment by shahab-vahedi** [comment]
For ARCv3, this file is copied from `src/gcc/libstdc++-v3/config/locale/newlib/ctype_members.cc` into the build dir (`build-gcc-newlib-stage2/arc64-elf/libstdc++-v3/src/c++11/ctype_members.cc`) and then is built. For ARCv2, although this file does exist in the source gcc, it never is copied into the build dir (and compiled?). @claziss a few questions:

1) Do we really need this for arc64?
2) Is the `wchar_t` type target dependent? If yes, maybe we can fix it from our side.
3) If the answer to (2) is "no", then I will fix this upstream.

**Comment by claziss** [comment]
> For ARCv3, this file is copied from `src/gcc/libstdc++-v3/config/locale/newlib/ctype_members.cc` into the build dir (`build-gcc-newlib-stage2/arc64-elf/libstdc++-v3/src/c++11/ctype_members.cc`) and then is built. For ARCv2, although this file does exist in 
the source gcc, it never is copied into the build dir (and compiled?). @claziss a few questions:
> 
>     1. Do we really need this for arc64?
> 
>     2. Is the `wchar_t` type target dependent? If yes, maybe we can fix it from our side.
> 
>     3. If the answer to (2) is "no", then I will fix this upstream.

AFAIK this file is compiled for ARCv2 too.

**Comment by shahab-vahedi** [comment]
Then it is not copied to build dir like the arc64 build that I had. Maybe it has something to do with "multilib" building. Nevertheless, you skipped answering the questions.

**Comment by shahab-vahedi** [comment]
Through personal communication, @claziss 's response:
```
1. Do we really need this for arc64?
Yes. ctype_members.cc is part of wchar_t (wide chars) support.

2. Is the `wchar_t` type target dependent?
Yes. It is "int" for ARCv2 and "unsigned int" for ARCv3.
```

**Comment by claziss** [comment]
1. ctype_members.cc is part of `wchar_t` support, so we do need it if we support wide chars.
2. it is target dependent.

**Comment by claziss** [comment]
I've changed the ABI to reflect what we were doing in ARCv2. Fix here: 
https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/9aa6ae66c99ea77a0d3bed00db498e38ddc594f4

**Comment by abrodkin** [comment]
@claziss do we want it in `arc-2021.09` branch as well?
