### ISSUE TITLE
[HS5x] Error: immediate is out of bounds for instruction 'std'

### ISSUE THREAD

**Issue by abrodkin** [foss-for-synopsys-dwc-arc-processors/toolchain#464]
```
$ arc32-buildroot-linux-uclibc-gcc -mcpu=hs58 -O6 -fno-omit-frame-pointer -c builtin-timechart.i
/tmp/cc2oHNI8.s: Assembler messages:
/tmp/cc2oHNI8.s:5119: Error: immediate is out of bounds for instruction 'std'
```

GCC is built from today's `arc64` branch.

[builtin-timechart.zip](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/8688344/builtin-timechart.zip)

**Comment by claziss** [comment]
The offset of a store instruction is adjusted for compensating any split operation which may happen on the store address. However, this adjustment needs to happen only when the offset is positive. Fix in: https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/489941db78b183beaa8d17c384296af2f401e67e

@abrodkin  Please retry

**Comment by abrodkin** [comment]
Indeed, https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/489941db78b183beaa8d17c384296af2f401e67e fixes the problem!
