### ISSUE TITLE
[ARCv3] Configuring the ARC64 GNU tools using "--with-cpu"​ is not yet supported

### ISSUE THREAD

**Issue by abrodkin** [foss-for-synopsys-dwc-arc-processors/toolchain#465]
GCC for ARC32 (i.e. when used `--target=arc32-*`) is by default configured for a simpler "HS5x", which among other things is lacking support of double loads/stores. So I decided to configure it to emit code for "hs58" by default, but it doesn't work as expected:
```
$ ./configure --with-cpu=hs58 --target=arc32-linux-gnu
...

$ make
checking for struct tms... yes
checking for clock_t... yes
checking for F_SETLKW... yes
checking for O_CLOEXEC... yes
checking for AF_UNIX... yes
checking for AF_INET6... yes
checking if mkdir takes one argument... no
This target does not support --with-cpu.
Valid --with options are: fpu
make[1]: *** [Makefile:4374: configure-gcc] Error 1
make[1]: Leaving directory '/home/abrodkin/Projects/sources/git/gcc'
make: *** [Makefile:960: all] Error 2
```

**Comment by claziss** [comment]
I have added the configure support for `--with-cpu` option: https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/47518cf6707d2eb65ee970ec685563ecc0d865f6
@abrodkin please retry
