### ISSUE TITLE
Wrong Dwarf Information associated to enter instruction

### ISSUE THREAD

**Issue by claziss** [foss-for-synopsys-dwc-arc-processors/toolchain#471]
ARCv2: The Dwarf information associated to enter instruction is wrong, namely the register offsets in relation to CFA are positive and they need to be negative.
This issue has been discovered in Zephyr project. More:
https://github.com/zephyrproject-rtos/zephyr/issues/47985

**Comment by claziss** [comment]
Patch added here:
https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/7af69aabd1c39efdcaf18ff99c75da57f936562e

@abrodkin please take the necessary steps to propagate this patch to Zephyr project.

**Comment by abrodkin** [comment]
Will be fixed once https://github.com/zephyrproject-rtos/gcc/pull/9 gets merged in Zephyr SDK-ng.

**Comment by userid0x0** [comment]
Hi guys,
just a question. Will this fix make it into the GCC mainline? Starting from which GCC-Version is the problem solved?

**Comment by abrodkin** [comment]
@userid0x0 I'm sure @claziss will push it to upstream GCC repo once he's back from FTO.
I guess it's well qualified for both upstream "master" (i.e. what's going to be v13 release) as well as v12.2.
