### ISSUE TITLE
do you have plan to optimize leaky_relu op for tflm?

### ISSUE THREAD

**Issue by nyadla-sys** [foss-for-synopsys-dwc-arc-processors/toolchain#474]
do you have plan to optimize leaky_relu op for tflm?

**Comment by fbedard** [comment]
HI @nyadla-sys  - did you mean to file this issue against MLI here  https://github.com/foss-for-synopsys-dwc-arc-processors/embarc_mli/issues  ?

**Comment by claziss** [comment]
MLI issue, closing it.
