### ISSUE TITLE
[ARCv3] arc32: gcc code generation issue, incorrect insertion of inline asm code

### ISSUE THREAD

**Issue by pavelvkozlov** [foss-for-synopsys-dwc-arc-processors/toolchain#475]
Toolchain, kernel, and all packages are built with Buildroot - https://github.com/foss-for-synopsys-dwc-arc-processors/buildroot/tree/abrodkin-mcpu-hs58
uclibc-ng package from: https://github.com/foss-for-synopsys-dwc-arc-processors/uClibc/tree/kozlov-arc32-rebase
uslibc-ng-test package from:  https://github.com/foss-for-synopsys-dwc-arc-processors/uclibc-ng-test/tree/uclibc-arc32-wip

I am running **uclibc-ng-tests** on HS5x

The uclibc test **tst-tls7** fails. 
For some reason, the arc32 gcc compiler generates bad code for the **in_dso2()** function.
Function code:
``` c
#define TLS_GD(x)					\
  ({ int *__result;					\
     __asm__ ("add r0, pcl, @" #x "@tlsgd      \n"     	\
	  ".tls_gd_ld " #x "`bl __tls_get_addr@plt \n"	\
	  "mov %0, r0                    \n"		\
	  : "=&r" (__result)				\
	  ::"r0","r1","r2","r3","r4","r5","r6","r7",	\
	    "r8","r9","r10","r11","r12");		\
     __result; })

int
in_dso2 (void)
{
  int *foop;
  int result = 0;
  static int n;
  int *np;

  puts ("foo");			/* Make sure PLT is used before macros.  */
  __asm__ ("" ::: "memory");

  foop = TLS_GD (foo);
  np = TLS_GD (comm_n);
  
  if (n != *np)
    {
      printf ("n = %d != comm_n = %d\n", n, *np);
      result = 1;
    }

  result |= in_dso (*foop = 42 + n++, foop);

  *foop = 16;

  return result;
}
```
Generated code:

``` objdump
 694: 2700 7f80 0000 195c   add   r0,pcl,0x195c   ;1ff0 <comm_n+0x1ff0>   
 69c: 0ea6 ffcf             bl      -348     ;540 <_init+0x6c>
 6a0: 250a 1000             mov     r13,r0
 6a4: 1500 1010             ld      r16,[r13]
 6a8: 87a0                  ld_s    r13,[r15,0]
 6aa: 200c a340             cmp     r16,r13
 6ae: 2700 7f80 0000 194c   add     r0,pcl,0x194c<->;1ff8 <foo>                      
 6b6: 0e8e ffcf             bl      -372    ;540 <_init+0x6c>
 6ba: 260a 1000             mov     r14,r0
 6be: 001e 0021             beq.d   30    ;6da <in_dso2+0x66>
 6c2: 20ca 2021             mov.eq  r16,0
 6c6: 41a1                  mov_s   r1,r13
 6c8: 4202                  mov_s   r2,r16
```
The compiler sets the inline asm code in the incorrect place between **cmp** and  **beq.d** instructions, as a result check for n  != *np (both zeroes) doesn't pass.

Build command (under buildroot):
```
~/build-linux/output_hs5x_uclibc/host/bin/arc32-buildroot-linux-uclibc-gcc \
        -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g0 -Wl,-z,max-page-size=4096 -I../../test -D_GNU_SOURCE -Wno-missing-field-initializers -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g0 -Wl,-z,max-page-size=4096 -DUSE_TLS=1 -DHAVE___THREAD=1 -I. -DHAVE_TLS_MODEL_ATTRIBUTE=1  \
        -fPIC -DSHARED -shared \
        -fPIC -shared tst-tlsmod3.c -o tst-tlsmod3.so -Wl,-soname,tst-tlsmod3.so \
          \
        -shared -static-libgcc -L../../lib tst-tlsmod2.so
```

At the same time, the ARCv2 gcc compiler generates correct code:

``` objdump
 6f4: 2700 7f80 0000 38fc     add     r0,pcl,0x38fc   ;3ff0 <comm_n+0x3ff0>   
 6fc: 0ed2 ffcf               bl      -304    ;5cc <_init+0x58>
 700: 270a 1000               mov    r15,r0
 704: 2700 7f80 0000 38f4     add    r0,pcl,0x38f4<->;3ff8 <foo>                       
 70c: 0ec2 ffcf               bl     -320    ;5cc <_init+0x58>
 710: 250a 1000               mov     r13,r0
 714: 43e5                    ld_s    r3,[r15,0]
 716: 42c5                    ld_s    r2,[r14,0]
 718: 7350                    cmp_s   r3,r2
 71a: 002e 0021               beq.d   46      ;746 <in_dso2+0x6e>
 71e: 27ca 1021               mov.eq  r15,0
 722: 42a5                    ld_s    r2,[r13,0]
```

Build command (under buildroot):
```
~/build-linux/output-arc-hs4x-uclibc/host/bin/arc-buildroot-linux-uclibc-gcc \
        -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g0 -Wl,-z,max-page-size=8192 -I../../test -D_GNU_SOURCE -Wno-missing-field-initializers -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g0 -Wl,-z,max-page-size=8192 -DUSE_TLS=1 -DHAVE___THREAD=1 -I. -DHAVE_TLS_MODEL_ATTRIBUTE=1  \
        -fPIC -DSHARED -shared \
        -fPIC -shared tst-tlsmod3.c -o tst-tlsmod3.so -Wl,-soname,tst-tlsmod3.so \
          \
        -shared -static-libgcc -L../../lib tst-tlsmod2.so
```

**Comment by claziss** [comment]
Hi @pavelvkozlov,
I think the assembly in TLS_GD macro is not correct. See: https://github.com/foss-for-synopsys-dwc-arc-processors/glibc/commit/7a07121ddcd247dd1962d428b859a21757475078

Also, I do not really understand what is allegedly wrong in the ARC32 case. The `cmp` instruction needs to compare between one TLS variable (i.e., `r16[r13]` ) and the local static variable (i.e., `r13`).  As far as I can see, both registers are read before comparison operation. The `foop` variable is needed latter on, hence, the compiler moves it closer to the place where it is used.

**Comment by pavelvkozlov** [comment]
Hi @claziss,

I agree this problem can be solved by many ways, but is it correct that compiler insert a call for the  ```__tls_get_addr()``` function between the ```cmp```  instruction and  condition branch instruction ```beq.d```? What about status flags? I suspect the  ```__tls_get_addr()``` function changes this flags, and as a result ```beq.d``` uses bad flags and ```0 == 0``` check` returns ```false```.

**Comment by claziss** [comment]
The call to `__tls_get_addr()` is inside of the inline assembly code. The compiler doesn't parse this code, and if the asm code is clobbering the CFLAGS or any register then those ones need to be present in the clobbering list. Please refer to https://gcc.gnu.org/onlinedocs/gcc/Extended-Asm.html
However, if you have any other example which is not using inline assembly and you get a call between the `cmp` and `bCC` instruction, then that may be interesting.

**Comment by pavelvkozlov** [comment]
@claziss, thanks for the clarification, I've really missed that CFLAGS should be in clobber list, thought that cc clobber is implicit in every asm(). I'll fix inline asm code in test.
