### ISSUE TITLE
Wrong BL instruction offset if the callee address is not word-aligned

### ISSUE THREAD

**Issue by luchezarg** [foss-for-synopsys-dwc-arc-processors/toolchain#478]
The attached file illustrates the issue. Two assembly language files (f1.s and f2.s) are linked with a C file. The code size of f1.s isn't a multiple of 4, so the start address of f2.s, which is linked after f1.s, isn't word-aligned. When the C code (at 1036c) tries to call a function at the start of this file (f2, at 1038e), it in fact calls the code at an address less by 2, which is the last instruction in f1.s at 1038c. That's because the BL instruction offset is by 2 less than it should be. As the addresses become known only at link time, I think that the bug is in the linker. (If f2.s is linked before f1.s, the bug doesn't reveal, since the code size of f2.s, unlike f1.s, is a multiple of 4.)

[bug.txt](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/9600873/bug.txt)

**Comment by claziss** [comment]
Hi, it is required to use `.align` keyword when developing and using inline assembly at the start of a function, like your `f2` function. Adding this, will result in aligned code. More info about `align` here: https://sourceware.org/binutils/docs/as/Align.html
