### ISSUE TITLE
__builtin_sqrt and __builtin_sqrtf don't unfold to FPU instructions for ARC HS

### ISSUE THREAD

**Issue by pavelvkozlov** [foss-for-synopsys-dwc-arc-processors/toolchain#484]
I've noticed that on ARC HS the compiler replaces the ```__builtin_sqrt``` and ```__builtin_sqrtf``` by the ```sqrt()``` and ```sqrtf()``` function calls, even if ```-mfpu=fpud``` and ```-fno-math-errno``` options are specified.

``` c
float my_sqrtf(float v)
{
      return  __builtin_sqrtf(v);
}

int main(int argc, char *argv[])
{
      return 0;
}
```
If I compile this code for arc64 by the following line:
```
arc64-linux-gnu-gcc -mfpu=fpud -fno-math-errno  ./sqrt.c -o sqrt
````
I will receive something like:
```
000000000001044c <my_sqrtf>:
   1044c:            7fe0                j_s.d     [blink]
   1044e:            e040 4020           fssqrt   f0,f0
   10452:            78e0                nop_s
```
But for ARC HS if I compile this code by the following line (I also have to add the libm library):
```
arc-linux-gnu-gcc -mfpu=fpud -fno-math-errno -lm  ./sqrt.c -o sqrt
```
I will receive code with ```sqrtf()``` call from libm, not the FPU instruction.

This causes a problem while I try to use glibc with HW FPU support. If glibc configured for use of FPU it relies to the compiler's ```__builtin_sqrt``` and ```__builtin_sqrtf``` and uses them in ```sqrt()``` and ```sqrtf()``` functions and I receive the following code in libm:

```
0001c4b4 <__ieee754_sqrtf>:
   1c4b4:       0001 0000           b     0                     ;1c4b4 <__ieee754_sqrtf>
```
Is it possible from compiler side to change behavior of ```__builtin_sqrt``` and ```__builtin_sqrtf``` and use FPU instructions for ARC HS?
Otherwise some changes and software implementation inside glibc is required for this case.

**Comment by claziss** [comment]
I suppose you need to use `-mfpu=fpud_div`. Please see the public gcc [manual](https://gcc.gnu.org/onlinedocs/gcc-12.2.0/gcc/ARC-Options.html#ARC-Optionsl)

**Comment by pavelvkozlov** [comment]
@claziss, you are right. Adding extra -mfpu option (I've used ```-mfpu=fpud_all```) solved my problem. Thanks.
