### ISSUE TITLE
ARC32: loop optimization causes Infinite loop and memory fault

### ISSUE THREAD

**Issue by pavelvkozlov** [foss-for-synopsys-dwc-arc-processors/toolchain#489]
I was debugging a fault of a test from glibc test suit and found strange code generated by compiler for glibc. My single step debug shows that, after some loop optimizations generated code ignores check of exit condition for a loop, and instead of exit after a first iteration, loops until stack corruption and fault.

Original C code is in glibc funcfion ```group_number()```. Based on this code I've prepared a small test that reproduce described problem. Build command for test:
```
arc32-linux-gnu-gcc -mcpu=hs5x -O2 -g3 bad_loop.c -o bad_loop
````
Expected result - one loop iteration and exit with some output. In fact, memory fault.
Test source is in attach. 
This issue and test fault occurs only for ARC32 variant. Reproduced with compiler and binutils from current [arc-2022.09 branch](https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/tree/arc-2022.09).
Option ```-fno-tree-loop-optimize``` allows to generate code with expected behavior and without fault.
[bad_loop.zip](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/10082131/bad_loop.zip)

**Comment by claziss** [comment]
Fixed by this commit https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/0c24472336abba9722108945e06968ad84a993dd

**Comment by pavelvkozlov** [comment]
I've rebuilt toolchain with this fix https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/0c24472336abba9722108945e06968ad84a993dd and can confirm that the issue with bad loop in the ```group_number()``` function inside glibc has gone.
I will run all glibc test suit for regression and will back with report later.

**Comment by pavelvkozlov** [comment]
With commits:
https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/9ff963a9bd60ed6f1ac00ea265b76bcedda31f13
https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/018f99d8a444bbe6fe20e8e0ea21cb4940be37de
The described issue has gone, and no regressions found.

**Comment by shahab-vahedi** [comment]
For the record, there was a 2nd patch created for this that was meant to be upstreamed

[Dataflow: Update df_analyze_loop to take into account](https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/82275a384b7896c2f6d46dbe6baaa9a905667981)

However, that patch is rendered unapplicable after the latest GCC rebase. I had to drop it. but I archive it here.

[0492-MAINLINE-Dataflow-Update-df_analyze_loop-to-take-int.patch.tar.gz](https://github.com/user-attachments/files/15879348/0492-MAINLINE-Dataflow-Update-df_analyze_loop-to-take-int.patch.tar.gz)

Nonetheless, the original fix which is a bit slow, is still in.
