### ISSUE TITLE
ST instruction with large offset issue on ARC GNU assembler

### ISSUE THREAD

**Issue by SiyuanCheng-CN** [foss-for-synopsys-dwc-arc-processors/toolchain#490]
Found building error: immediate is out of bounds for instruction 'st', while using offset size (s9 value) greater than 0xff with ARC GNU. I tested in mwdt with same offset, but it doesn't throw such error.

test code:
```
.global _start
.type _start, @function
_start:
    ld r13, [sp, 0x104]
    st r13, [sp, 0xff]
    flag 1
```
ccac disassembly:
```
1441360d                 ld	%r13,[%sp,0x104]
1cff3340                 st	%r13,[%sp,255]
```
gnu disassembly:
```
2430 3f8d 0000 0104 	ld	r13,[sp,0x104]
1cff 3340           	st	r13,[sp,255]
```
LD is working fine with offset larger than 0xff. ST only works well in mwdt.

Reproduce error:
toolchain: arc_gnu/2021.09-elf32
change the offset for st from 0xff to 0x104 and `arc-elf32-gcc -o test.o test.S`
```
.global main
.type main, @function
main:
    ld r13, [sp, 0x104]
    st r13, [sp, 0x104]
    flag 1
```
Error message:
```
test.S: Assembler messages:
test.S:5: Error: immediate is out of bounds for instruction 'st'
```

**Comment by claziss** [comment]
Accordingly to ARC's Programmer Reference Manual for ST instructions we have:
```asm
ST<zz><.aa><.di> c,[b,s9]    00011bbbssssssssSBBBCCCCCCDaaZZ0
```
As we can see, the index can be `s9` only.  Thus, we can fit a value between _-256_ and _255_. For fitting a larger immediate, you should use the `.as` flag (i.e., address scaling). Please be aware the address scaling flag scales an immediate in function of the type of data access. Please refer to ARC PRM document for more information. 

So, to fit the `0x104` in an `ST` instruction we should do:

```asm
.global main
.type main,@function
main:
      ld r13, [sp, 0x104]
      st.as r13,[sp, 0x104 >> 2]
```

More code memory friendly:

```asm
.global main
.type main,@function
main:
      ld.as r13,[sp, 0x104 >> 2]
      st.as r13,[sp, 0x104 >> 2]
```

which will lead to:

```asm
00000000 <_start>:
   0:	1441 360d           	ld.as	r13,[sp,65]
   4:	1c41 3358           	st.as	r13,[sp,65]
   8:	2069 0040           	flag	0x1
```

**Comment by SiyuanCheng-CN** [comment]
Thank you for the answer, close this one now.
