### ISSUE TITLE
Compatibility  between ARC gnu chain and Synopsys MetaWare C/C++ compiler 

### ISSUE THREAD

**Issue by oraikhma** [foss-for-synopsys-dwc-arc-processors/toolchain#50]
I am wondering if I can use the ARC  gdb to debug the code been generated by MetaWare compiler , I made a first try and had  a failure in DWARF parsing 
arc_gnu_2014.08_sources/unisrc-4.8/gdb/dwarf2-frame.c:683: internal-error: Unknown CFI encountered.
Any idea how to proceed with this issue 

Thanks , Oleg Raikhman

**Comment by anthony-kolesov** [comment]
Hi Oleg,

Compatibility between GNU tools and MetaWare is not something we verify right now, however we have plans to introduce compatibility in next releases. Can you specify which MetaWare C flags has been used to compile your application. It is likely that metaware generates some special DWARF info to describe some of ARC exntesions and that cuases problem in GDB. If it is an open-source project, then of course link to source would be more useful to reproduce this issue :)

Anton

**Comment by oraikhma** [comment]
Hi Anton , 
I am working for Intel, so i can't share the code , Not sure if it can help but 
switch (insn) : dwarf2-frame.c:442 , insn has a value equals to 4 which goes to 
         default :  internal_error (**FILE**, **LINE**, : dwarf2-frame.c:683: internal-error: 
                      _("Unknown CFI encountered."));
Thanks, Oleg

**Comment by anthony-kolesov** [comment]
Hi Oleg,

We will investigate and try to develop a test case for your problem since you can’t share the code. However for now we don't have a schedule for MetaWare-GDB compatibility. In the meantime, can you use MDB to debug MetaWare compiled code?

**Comment by bwxz** [comment]
er,how can slove it? I have the same consideration.

**Comment by claziss** [comment]
If u are Synopsys clients, you can make a CASE and put ur code in. It should be alright as u sign with Synopsys a non-disclosure agreement. 
In all cases, we need a piece of code that reproduces the issue observed.
Thanks!

**Comment by bwxz** [comment]
I have been question，does the metaware complie tools“ mcc” same with ARC GNU IDE  complie tools “arc-glf32-gcc”?? and when the metaware prj open with GNU IDE, like this picture
![eclipsearc600](https://cloud.githubusercontent.com/assets/16777578/12601086/4d26ae80-c4d9-11e5-903a-498f5062d315.png) ,er,some  compatibility ,different?

**Comment by anthony-kolesov** [comment]
MIDE and GNU IDE are not compatible with each other. Metaware tools can be used only with MIDE, and GNU tools can be used only with GNU IDE.

**Comment by bwxz** [comment]
i know,thanks, and when MIDE ?and when GNU?for example ARC 600~

**Comment by anthony-kolesov** [comment]
Sorry, I don't understand your question. You mean with which core to use which IDE? They both support ARC 600, although in GNU IDE support is minimal, but the decision of IDE depends on which toolchain is used.
