### ISSUE TITLE
GDB for Windows does not work correctly in Eclipse plugin

### ISSUE THREAD

**Issue by kolerov** [foss-for-synopsys-dwc-arc-processors/toolchain#501]
On Windows 10 hosts Eclipse plugin for ARC cannot connect to any GDB server correctly. To reproduce it you can create a simple debug configuration for nSIM and try to debug an application. The problem is that Eclipse plugin sends to GDB this string:

    arget remote ...

instead of this:

    target remote ...

I've created a pull request with temporary fix (https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/pull/66). This pull request reverts commit [d08cbc5d3203118da5583296e49273cf82378042 ](https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/commit/d08cbc5d3203118da5583296e49273cf82378042) which introduced that bug. This revert is temporary since it's not clear what exactly leads to this error.

Note, on Linux hosts that problem is not happening.

**Comment by kolerov** [comment]
Seems like the problem is in GDB itself. Compare `gdb/even-top.c` in our repository and in upstream:

https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/blob/arc64/gdb/event-top.c
https://github.com/bminor/binutils-gdb/commits/master/gdb/event-top.c

You will see that after https://github.com/bminor/binutils-gdb/commit/d08cbc5d3203118da5583296e49273cf82378042 commit there is a series of other commits which related to input/output and buffering. I tried to cherry-pick some of them, build GDB and try to use it with Eclipse on Windows. Then everything worked fine. There is a list of commits which I got:
 
    $ git log --oneline -n 10 gdb/event-top.c
    3e6f0b82f9d (HEAD -> ykolerov-fix-win-rebase) gdb: remove static buffer in command_line_input
    48df998111d [gdb] Handle pending ^C after rl_callback_read_char
    974c80a52be gdb: move setbuf calls out of gdb_readline_no_editing_callback
    1b991eb9d81 gdb: handle bracketed-paste-mode and EOF correctly
    4a52ae68069 gdb: improved EOF handling when using readline 7
    fa121beb516 gdb: work around prompt corruption caused by bracketed-paste-mode
    d08cbc5d320 gdb: unbuffer all input streams when not using readline

Picking some of these commits to our current source tree leads to conflict thus it's necessary to do it carefully.

**Comment by shahab-vahedi** [comment]
Thank you Yuriy for the  inputs. I will make sure that the next cut out release of GDB will either have these commits naturally or cherry-picked.

**Comment by kolerov** [comment]
I confirm that all those commits are presented in our `binutils-gdb` repository now. The latest `arc-2023.03-rc1` release is built without this issue.
