### ISSUE TITLE
[ARCv3] HS5x - absence of support for atomic llockd/scondd instructions

### ISSUE THREAD

**Issue by pavelvkozlov** [foss-for-synopsys-dwc-arc-processors/toolchain#505]
According to the PRM for 32-bit ARCv3 processors (ARC HS5x) atomic instructions ```llockd``` and ```scondd``` for 64-bit data are available and it would be great to have a support in the tools.
We need this to add optimized set of ```atomic64_*``` functions to the Linux kernel for the HS5x.

Now, code like the following returns assembler error:
```c
  __asm__ __volatile__ (
  	"1:\n"
  	"llockd %0, %1\n"
  	"add.f %L0, %L0, %L2\n"
  	"adc %H0, %H0, %H2\n"
  	"scondd %0, %1\n"
  	"bnz 1b\n"
  	: "=&r"(a64), "+ATOMC"(counter)
  	: "ir"(b64)
  	:"cc", "memory");
...
Error: unknown opcode 'llockd' 
Error: unknown opcode 'scondd'
```

**Comment by abrodkin** [comment]
Temporary work-around for the Linux kernel for ARC HS58 is available here: https://github.com/foss-for-synopsys-dwc-arc-processors/linux/commit/71455c65c044ffe506d4bfea3fd954b0ce30c61c.

**Comment by claziss** [comment]
Fix in https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/commit/7ae0445c604c0a9cae3bf6a1c8fd68f63cb55cd2

**Comment by abrodkin** [comment]
Fix back-ported to `arc-2022.09` - https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/commit/c89aa1cf76eab8c6a67ac405b04f8df175a1e229.
@pavelvkozlov once new engineering build is out with that fix, please re-try and close this issue.

**Comment by claziss** [comment]
@BrunoASMauricio  Please implement them in QEMU

**Comment by abrodkin** [comment]
Is a part of `arc-2022.09-rc2` available here https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/releases/tag/arc-2022.09-rc2
