### ISSUE TITLE
ARCv2: -mno-millicode option fails to suppress usage of libgcc millicode in Linux kernel

### ISSUE THREAD

**Issue by pavelvkozlov** [foss-for-synopsys-dwc-arc-processors/toolchain#509]
I've faced a problem with build of one configuration of Linux kernel. This configuration is used in Linux CI.
In this configuration the kernel built with option -Os. For all kernel modules the option ```-mno-millicode``` is used to suppress use of millicodes from the libgcc. But in module zstd_decompress (in obj file ```lib/zstd/decompress/zstd_decompress_block.o```) I see symbols for libgcc and kernel link stage fails with:
```
MODPOST modules-only.symvers
ERROR: modpost: "__st_r13_to_r20" [lib/zstd/zstd_decompress.ko] undefined!
ERROR: modpost: "__ld_r13_to_r20_ret" [lib/zstd/zstd_decompress.ko] undefined!
ERROR: modpost: "__ld_r13_to_r24_ret" [lib/zstd/zstd_decompress.ko] undefined!
ERROR: modpost: "__st_r13_to_r23" [lib/zstd/zstd_decompress.ko] undefined!
ERROR: modpost: "__st_r13_to_r19" [lib/zstd/zstd_decompress.ko] undefined!
ERROR: modpost: "__st_r13_to_r21" [lib/zstd/zstd_decompress.ko] undefined!
ERROR: modpost: "__ld_r13_to_r17_ret" [lib/zstd/zstd_decompress.ko] undefined!
ERROR: modpost: "__st_r13_to_r24" [lib/zstd/zstd_decompress.ko] undefined!
ERROR: modpost: "__ld_r13_to_r24" [lib/zstd/zstd_decompress.ko] undefined!
ERROR: modpost: "__ld_r13_to_r19_ret" [lib/zstd/zstd_decompress.ko] undefined!
WARNING: modpost: suppressed 3 unresolved symbol warnings because there were too many)
```
Another report from the build robot for this issue: https://lore.kernel.org/lkml/202206060104.EfejFWJu-lkp@intel.com/
With -O2 issue does not appear.
The kernel config (based on our haps default config): [linux-config.zip](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/10466958/linux-config.zip)

To reproduce:
```
1. Get linux kernel.
2. cd linux && mkdir build
3. copy .config to build dir
4. make O=./build ARCH=arc CROSS_COMPILE=arc-linux-gnu- olddefconfig
5. make O=./build ARCH=arc CROSS_COMPILE=arc-linux-gnu-
```
Can we do something with this?

**Comment by pavelvkozlov** [comment]
Additional information: archive with compile time intermediate outputs: [zstd-decompress.zip](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/10499471/zstd-decompress.zip).
Archive contains:
```
zstd_decompress_block.i  - prepcocessed source
zstd_decompress_block.s  - intermediate asm
zstd_decompress_block.o  - object file with __st_r*/__ld_r* symbols
also, 
zstd_decompress_block.c - initial source
zstd_decompress_block.o.cmd - initial build command
```
In most cases combination of options ```-Os -mno-millicode``` works correctly and suppress use of millicodes from the libgcc, but in this particular case I see object file with references for millicodes from the libgcc:
```
arc-linux-gnu-gcc -Os -mno-millicode -c zstd_decompress_block.i 
arc-linux-gnu-nm zstd_decompress_block.o | grep st_r*
         U __st_r13_to_r17
         U __st_r13_to_r18
         U __st_r13_to_r19
         U __st_r13_to_r21
         U __st_r13_to_r22
         U __st_r13_to_r24
```
Any ideas? It looks like a compiler issue.

**Comment by claziss** [comment]
I have pushed this commit: https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/3a6a3a713f0cc6618fb9f9e15cb58294e97802cd
Please retry.

**Comment by pavelvkozlov** [comment]
I can confirm, with this change described issue has gone. Thank you.
Do you plan to provide this fix to the gcc mainstream?

**Comment by claziss** [comment]
... done: https://gcc.gnu.org/pipermail/gcc-patches/2023-February/611863.html
