### ISSUE TITLE
ARC GDB client tries to load unloadable sections in .elf file

### ISSUE THREAD

**Issue by noammeir** [foss-for-synopsys-dwc-arc-processors/toolchain#51]
hi

we try to work with GDB for connecting to an Ashling GDB server connected by JTAG to our ARC core. 

in the code we have a section marked by "SECTIONS" as "NOLOAD". 

the mcc generated .elf file has this section marked as loadable with filesz 0, which as far as I understand indeed marks this 
section as not loadable. 
the .elf file works fine with metaware debugger and similar cases were ok also with Lauterbach. 

when we use the GDB and run "load" command, we see that it tries to load this section, causing corruption and disables us 
from working with it. 
this happens both from eclipse toolchain and from a stand-alone GDB client by synopsys, both windows or unix. 

I also opened a solvenet case with synopsys on that (number 8000784130) and they confirmed on their side that it seems like a GDB issue after running a small test case they created, they are working on a fix for that.

how can we confirm and fix it on the toolchain here as well?

thanks, 
Noam

**Comment by anthony-kolesov** [comment]
I close this one, since it is handled via Solvnet.
