### ISSUE TITLE
ARC 2022.09-rc2: fail to build simple program

### ISSUE THREAD

**Issue by pavelvkozlov** [foss-for-synopsys-dwc-arc-processors/toolchain#510]
Something wrong with ARC 2022.09-rc2 release:
[Linux/glibc ARC HS](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/releases/download/arc-2022.09-rc2/arc_gnu_2022.09-rc2_prebuilt_glibc_le_archs_linux_install.tar.gz)

```c
test.c
int main()
{
   return 0;
}
---
arc-linux-gnu-gcc test.c -o test
arc-linux-gnu-gcc: internal compiler error: Segmentation fault signal terminated program cc1
Please submit a full bug report, with preprocessed source (by using -freport-bug).
See <https://gcc.gnu.org/bugs/> for instructions.
```

**Comment by abrodkin** [comment]
@pavelvkozlov could you please reproduce the same problem with `arc-linux-gnu-gcc` executed under host's GDB and at least post a back-trace (`bt` command output in the GDB)?

**Comment by pavelvkozlov** [comment]
It seems it was something on my side. For some reason, ```cc1``` was corrupted after unpacking of the archive with toolchain. I downloaded and unpacked it again and issue has gone. With correct cc1(with correct chsum) I can build executables.
