### ISSUE TITLE
The F16_SP_OPS should be enabled for all ARCv3 processor family

### ISSUE THREAD

**Issue by kolerov** [foss-for-synopsys-dwc-arc-processors/toolchain#513]
`push_s blink` is a valid opcode for HS 4x and HS 5x. Moreover, ccac generates it and nSIM understands it. However, GCC does not recognize it. Consider this example:

Consider this example `main.c`:

```c
#include <stdio.h>

int f(int a, int b)
{
    return a + b;
}

int main()
{
    int c = f(4, 5);
    printf("%d", c);
    return 0;
}
```

Compile this code for HS 4x and HS 5x using MWDT:

```
ccac -av3hs -g -c main.c -o main-ccac-hs5x.o
```

Then you can find that objdump cannot recognize it:

```
$ arc64-elf-objdump -d main-ccac-hs5x.o

main-ccac-hs5x.o:     file format elf32-littlearc64
…
00000004 <main>:
   4:   c0f1                    .shor   0xc0f1
   6:   740c                    mov_s   r0,4
   8:   752c                    mov_s   r1,5
```

`c0f1` is exactly `push_s blink`. Also, `qemu-system-arc64` crashes on this opcode. GDB does not recognize this opcode too.

**Comment by claziss** [comment]
Binutils patch pushed here: https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/commit/9a0d6303cff2806d582d2e007c14bb5eb9e672b0

Need to update the following tools:

- [x] GCC when in ARC32 mode. Assignee @claziss 
- [x] QEMU when in ARC32 mode. Assignee @BrunoASMauricio 

Optional:

- [ ]  Check libraries assembly routines for conformity. Assignee @luiss-synopsys

**Comment by kolerov** [comment]
Seems like the same issue is applicable for `enter_s` and `leave_s`. Just checked it by the same way. They are not recognized by the toolchain and QEMU for HS 5x and HS 6x.

P.S. I've found that I have an outdated toolchain thus it's not recognized by GDB. However, the lates build of QEMU crashed on them.

**Comment by abrodkin** [comment]
@kolerov how come `enter_s` & `leave_s` are not yet recognized by the tools from `arc-2022.09` release after this fix https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/commit/1978763a15dc0397788b4500e899734ac47d8a83 which is a part of the aforementioned release?

**Comment by kolerov** [comment]
> @kolerov how come `enter_s` & `leave_s` are not yet recognized by the tools from `arc-2022.09` release after this fix [foss-for-synopsys-dwc-arc-processors/binutils-gdb@1978763](https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/commit/1978763a15dc0397788b4500e899734ac47d8a83) which is a part of the aforementioned release?

As I said in update for the previous comment, I had an outdated toolchain thus it was not recognized by GDB. However, the latest build of QEMU crashed on them.

**Comment by claziss** [comment]
GCC patch: https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/2e73d7f579378ccd8e9266b2d944f316a2c1e74f
