### ISSUE TITLE
make: *** No rule to make target `install-pdf-{binutils,ld,gas}'.  Stop.

### ISSUE THREAD

**Issue by ltqusst** [foss-for-synopsys-dwc-arc-processors/toolchain#52]
I following the every detail toolchain/README.md 
build with:
    ./build-all.sh --no-uclibc --install-dir ~/arc_bin --cpu arcem --no-multilib 
gives this error
     make: **\* No rule to make target `install-pdf-{binutils,ld,gas}'.  Stop.

I read the ./build-all.sh and append --no-pdf option, build is success.

**Comment by anthony-kolesov** [comment]
Hi,

You are using `arc-releases` branch, right? I have realized that recent commits to this branch hasn't been really fully tested, and looks like they are not compatible with your shell. What is you Linux distribution? Ubuntu?

I've reverted wrong changes, so you can do:

```
git fetch
git reset --hard origin/arc-releases
```

That will do the trick.

**Comment by ltqusst** [comment]
Hi, thank you very much, that solved my problem.

my OS is Ubuntu 12.04 with upgraded kernel 3.14.35-031435-generic
