### ISSUE TITLE
Need additional description for assets that are available for download

### ISSUE THREAD

**Issue by alexanderpisarevskiy** [foss-for-synopsys-dwc-arc-processors/toolchain#520]
We have 19 different assets for downloading ARC GNU tools on GitHub.
For a new user, it is hard to figure out what package needs to be downloaded.
We need to update documentation on this (https://foss-for-synopsys-dwc-arc-processors.github.io/toolchain/ide/index.html) with answers to the following questions:
1. Description of package naming, especially the meaning of: "arc32", "arc64", "archs", "elf32", "native", "linux". For example, it is not clear if "arc32" version can be used for HS3x/4x.
2. What version is included in the IDE package? I guess, it is "prebuilt_elf32_le".
3. Why do we have an installer for the Windows IDE version, but not have it for the Linux IDE version? Also I did not find a path-setting script in the Linux version.

P.S. It is not clear, why the Linux IDE package is twice bigger size compared to the Windows IDE package.

**Comment by kolerov** [comment]
@alexanderpisarevskiy The main documentation page is https://foss-for-synopsys-dwc-arc-processors.github.io/documentation/. I've added a detailed descriptions of distributed packages here: https://foss-for-synopsys-dwc-arc-processors.github.io/documentation/2024.06/toolchain/.
