### ISSUE TITLE
[GDB] hangs on parsing symbols from ELF-file generated by MWDT

### ISSUE THREAD

**Issue by kokas-a** [foss-for-synopsys-dwc-arc-processors/toolchain#521]
Hi colleagues,
I was working with zephyr rtos and faced with the problem.
If zephyr elf generated with recent versions of MWDT (2022.09 and .12), debug information can not be parsed by GDB - it just hangs.

###How to reproduce
Start recent version of qemu (https://github.com/foss-for-synopsys-dwc-arc-processors/qemu)
```
qemu-system-arc -cpu archs -m 8M -nographic -no-reboot -monitor none -global cpu.firq=false -global cpu.num-irqlevels=15 -global cpu.num-irq=25 -global cpu.ext-irq=20 -global cpu.freq_hz=10000000 -global cpu.timer0=true -global cpu.timer1=true -global cpu.has-mpu=true -global cpu.mpu-numreg=16 -net none -pidfile qemu.pid -chardev stdio,id=con,mux=on -serial chardev:con -mon chardev=con,mode=readline -icount shift=6,align=off,sleep=off -rtc clock=vm -kernel  zephyr_202212.elf -s -S
```

Start gdb (I used set of versions and the recent was arc_gnu_2022.09-rc3)
```
target remote  localhost:1234
symbol-file <path_to_zephyr_202212.elf>
//get hang
```

[zephyr_for _tests.zip](https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/files/10579822/zephyr_for._tests.zip)

**Comment by shahab-vahedi** [comment]
For the record, a simple reading of the file hangs GDB:

```
$ arc-elf32-gdb -q
(gdb) set debug symbol-lookup 1
(gdb) set debug symfile 1
(gdb) set debug arc 1

(gdb) symbol-file zephyr_202212.elf
      [arc-newlib] arc_newlib_osabi_sniffer: OS/ABI sniffer.
      [arc] arc_gdbarch_init: Architecture initialization.
      [arc] arc_tdesc_init: Target description initialization.
      [arc] arc_tdesc_init: Have got a target description

      Reading symbols from zephyr_202212.elf...
      sf->sym_new_init (zephyr_202212.elf)
      sf->sym_init (zephyr_202212.elf)
      sf->sym_offsets (zephyr_202212.elf, 0x7ffe99669610)
      sf->sym_read (zephyr_202212.elf, 0xe)
      qf->has_symbols (zephyr_202212.elf) = 1
      [ GDB starts spinning ]
```

**Comment by shahab-vahedi** [comment]
This probably is because of an extension that MetaWare has added to the DWARF information. I suggest submitting the issue with the MetaWare team and get an answer on what has changed from `2022.06` to `2022.12` in that regard.

If that happens to be the case, there should be a way to turn off such emissions.

**Comment by kokas-a** [comment]
As I was told by MDB Team, there is circle reference in the "broken" ELF-file. It looks like a bug while generating the DWARF.

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/57702304/216982216-a268ee8c-d895-4f1a-80c4-44cad8d7cf64.png)

From another point of view, debugger supposed to be able to handle such situation to avoid malfunction because of infinite recursion.

**Comment by shahab-vahedi** [comment]
Thanks @kokas-a I will look into it later and discuss it with upstream if necessary.

**Comment by abrodkin** [comment]
@shahab-vahedi do you mind if I move that issue to the toolchain repo (https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/issues) so that we may track it for one of the upcoming ARC GNU toolchain releases?

**Comment by shahab-vahedi** [comment]
sure, please do!

**Comment by abrodkin** [comment]
@claziss @shahab-vahedi is it critical to be solved in 2023.03 or we may postpone it to 2023.09?

**Comment by shahab-vahedi** [comment]
There is nothing to be solved here. MWDT should fix it. There is an internal issue submitted and assigned.

**Comment by pickensd** [comment]
I cannot reproduce this issue with the 09.2022 MetaWare toolchain nor the current one. Here is the Dwarf that I'm seeing for the same function:
```
0x168c4:        TAG_subprogram, Acode #30, DIE=0x168c4, aoff=0x4af1
                  AT_low_pc addr 0x0
                  AT_high_pc addr 0x10
                  AT_frame_base block1 1 bytes:  register 28;
                  AT_name strp "z_thread_essential_clear"
                  AT_decl_file data1 1 (0x1)
                  AT_decl_line data1 116 (0x74)
                  AT_prototyped flag 1
                  AT_external flag 1
```

Please attach the exact command-line that was used to compile "zephyr/kernel/thread.c". And display the compiler version ("ccac --version")
