### ISSUE TITLE
LD segfault: assertion fail .../.build/arc-snps-linux-uclibc/src/binutils/bfd/arc-got.h:382

### ISSUE THREAD

**Issue by yaroslavsadin** [foss-for-synopsys-dwc-arc-processors/toolchain#523]
Hi,

Recent builds of uClibc toolchains fail with the following error:

```
[ALL  ]        LD ld-uClibc-1.0.42.so
[ALL  ]      .../.build/arc-snps-linux-uclibc/buildtools/lib/gcc/arc-snps-linux-uclibc/12.2.1/../../../../arc-snps-linux-uclibc/bin/ld: BFD (ARCompact ISA Linux uClibc toolchain - build 1337) 2.40.50.20230314 assertion fail .../.build/arc-snps-linux-uclibc/src/binutils/bfd/arc-got.h:382
[ERROR]      collect2: fatal error: ld terminated with signal 11 [Segmentation fault]
[ALL  ]      compilation terminated.
[ERROR]      make[1]: *** [lib/ld-uClibc.so] Error 1
```

CC @abrodkin

**Comment by shahab-vahedi** [comment]
Same [comment](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/issues/524#issuecomment-1534452312) should apply here.

**Comment by yaroslavsadin** [comment]
@abrodkin @shahab-vahedi 

Not fixed by https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/commit/8f3606631dbd5c03dbb860548b3c6a40db0c16a7

**Comment by yaroslavsadin** [comment]
Just to verify myself, from the logs:

`'binutils-git-8f360663' (git https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb.git, branch arc-2023.03)`

**Comment by claziss** [comment]
@yaroslavsadin please prepare a show case for this issue, in the same style like @pavelvkozlov  [did](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/issues/524#issuecomment-1527519402). Thanks.

**Comment by yaroslavsadin** [comment]
@claziss I emailed you instructions on how to reproduce yesterday, please check. Attaching full log here also.
[build.log](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/11405358/build.log)

**Comment by shahab-vahedi** [comment]
@yaroslavsadin Once again, please kindly look into **all** the comments in #524 and provide your inputs like that.

**Comment by pavelvkozlov** [comment]
I've reproduced the same issue manually, but for _ARCv3 32-bit_ variant.
Archive with object files and Makefile to reproduce this ld fault issue:  [ld-fault-uclibc.zip](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/11406286/ld-fault-uclibc.zip)
Hope this will be helpful.
The sequence is the same as in #524:
```
Configure, build, install buinutils:
$ ../configure --target=arc32-linux-gnu --prefix=/tmp/install/arc32 --disable-multilib --disable-werror --disable-nls --with-expat=yes --disable-sim
$ make -j8 && make install

Link example object files:
$ cd /tmp/ls-fault-uclibc
$ make LD_PATH=/tmp/install/arc32/bin/
/tmp/install/arc32/bin/arc32-linux-gnu-ld --eh-frame-hdr -shared -X -o ./ld-uClibc-1.0.43.so -v \
 -z combreloc -z relro -z now -O2 -z defs -e _start -z now -Bsymbolic --export-dynamic --sort-common \
 --no-undefined --discard-locals --discard-all -soname=ld-uClibc.so.1 --whole-archive ./ld-uClibc_so.a \
 --no-whole-archive ./libgcc.a
GNU ld (GNU Binutils) 2.40.50.20230314
/tmp/install/arc32/bin/arc32-linux-gnu-ld: BFD (GNU Binutils) 2.40.50.20230314 assertion fail ../../bfd/arc-got.h:382
make: *** [Makefile:5: ld-uClibc-1.0.43.so] Segmentation fault
make: *** Deleting file 'ld-uClibc-1.0.43.so'
```

**Comment by claziss** [comment]
The linker is fixing a local symbol, namely `_dl_start`  which is triggering the BFD_ASSERT statement. Remove it and make the following if-stmt safe. Fix here: https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/commit/e16f66cf42196793c5d02e66f285eb419a47111b

**Comment by yaroslavsadin** [comment]
This one's fixed now, thanks.

**Comment by abrodkin** [comment]
Confirmed as fixed with https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/commit/e16f66cf42196793c5d02e66f285eb419a47111b
