### ISSUE TITLE
fdadd present without fpud flag

### ISSUE THREAD

**Issue by BrunoASMauricio** [foss-for-synopsys-dwc-arc-processors/toolchain#530]
I am observing a behavior that I believe is not expected, where fpu instructions are inserted by GCC, without there being an FPU flag in the invoking command.

```
#include <stdio.h>
double trunc (double x) {
	return x + x;
}

int main() {
    double normal_double = 1;
    printf("%lf\n", trunc(normal_double));
    return 0;
}
```

Compiling the above code with `arc-elf32-gcc -mcpu=archs trunc.c -fno-inline -o ./out`  generates a binary that contains fdadd as seen below:

![image](https://user-images.githubusercontent.com/113055161/235925817-ef408c68-e75a-41c9-a083-ea841fe0d7d5.png)

If the operation changes from `return x + x;` to `return x / x;`, __divdf3 softfloat is used instead of fddiv, but `return x * x;` once again uses an fpu instruction (fdmul).

Is this expected behaviour?

**Comment by claziss** [comment]
I think you configured the toolchain for a particular `mcpu` configuration, which has `fpud` enabled. We may do a better job here.

**Comment by shahab-vahedi** [comment]
@BrunoASMauricio To test @claziss 's theory, could you paste the result of the following command here:

```
$ arc-elf32-gcc -###
```

**Comment by BrunoASMauricio** [comment]
You are correct, my toolchain is built with `--with-fpu=fpud_all --with-cpu=archs`:
```
$ arc-elf32-gcc -###
Using built-in specs.
COLLECT_GCC=arc-elf32-gcc
COLLECT_LTO_WRAPPER=/scratch/brunoam/toolchain/latest/inst/arc/baremetal/libexec/gcc/arc-elf32/12.2.1/lto-wrapper
Target: arc-elf32
Configured with: /scratch/brunoam/toolchain/latest/bld/arc/baremetal/../../../src/arc/arc-gnu-toolchain/gcc/configure --target=arc-elf32 --host= --prefix=/scratch/brunoam/toolchain/latest/inst/arc/baremetal --disable-shared --disable-threads --enable-languages=c,c++ --with-system-zlib --disable-tls --with-newlib --with-headers=/scratch/brunoam/toolchain/latest/inst/arc/baremetal/arc-elf32/include --disable-libmudflap --disable-libssp --disable-libquadmath --disable-libgomp --disable-nls --enable-checking=release --disable-multilib --disable-werror --with-cpu=archs --with-fpu=fpud_all --with-gnu-as --with-gnu-ld 'CFLAGS_FOR_TARGET=-O2   ' 'CXXFLAGS_FOR_TARGET=-O2   '
Thread model: single
Supported LTO compression algorithms: zlib
gcc version 12.2.1 20220829 (GCC) 
```
After discussing out-of-band I now understand that in the configure step, using `with-c/fpu` doesn't just setup the toolchain with those parameters, but also sets them as default for GCC.

This explains the fdadd as the compilation above defaulted to fpud_all.

Thank you for the clarification.
Closing issue
