### ISSUE TITLE
-O2 flag breaks functionality when returning double

### ISSUE THREAD

**Issue by BrunoASMauricio** [foss-for-synopsys-dwc-arc-processors/toolchain#531]
### Description of the problem
When using the -O2 flag, gcc isn't preserving one of the two return registers (r0, r1) required when returning a double value from a function.

In the following example (couldnt be made smaller otherwise the outcome was different) we have two binaries, "none" on the left and "o2" on the right, compiled with no optimization flag and -O2 respectively:

Input to custom `double trunc(double)` function:

![image](https://user-images.githubusercontent.com/113055161/235884934-75165011-0628-45b6-bb70-506797f40c4a.png)

Output:

![image](https://user-images.githubusercontent.com/113055161/235885184-2592b8f8-4408-4ce7-9f65-c9d43a365e10.png)

As we can see, after the call to trunc and right before the call to printf, the values in r0 and r1 are different between the two binaries. This is because in "o2",  r0 isn't restored inside trunc after clobbering:

![image](https://user-images.githubusercontent.com/113055161/235885629-88483e0d-536f-45e1-aec2-50100c1d747f.png)

Restoration or r0 and r1 at `0x3a8` and `0x3aa` for "none" but nothing for "o2", even though r0 is clobbered at `0x28c <trunc+28>        neg.f   r0,r14`

### How to reproduce:

Use the attached [trunc.c.txt](https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/files/11381465/trunc.c.txt) (rename to trunc.c)

```
$ arc-elf32-gcc -mcpu=archs trunc.c -fno-inline -g3 -fno-builtin -o none
$ arc-elf32-gcc -mcpu=archs trunc.c -fno-inline -g3 -fno-builtin -O2 -o o2

And in separate shells, using the latest QEMU:

$ qemu qystem-arc -S -gdb tcp::1234 -M arc-sim -m 3G -nographic -no-reboot -serial stdio -monitor none -display none -cpu archs -kernel ./o2
$ qemu qystem-arc -S -gdb tcp::4321 -M arc-sim -m 3G -nographic -no-reboot -serial stdio -monitor none -display none -cpu archs -kernel ./none
```

Launch GDB and run something similar to

```
(gdb) target remote :1234 OR :4321
(gdb) b trunc
(gdb) la asm
(gdb) set disassembler-options cpu=hs38_linux
(gdb) c
(gdb) fin
(gdb) i r r1 r0
```

**Comment by BrunoASMauricio** [comment]
Duplicate of https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/issues/503, moving relevant information there and closing this.

**Comment by claziss** [comment]
This is a different issue from #503

**Comment by claziss** [comment]
The issue is related to the wrong encoding of `neg.f 0,r14` which was recognized as `neg.f r0,r14` by the assembler. Fix here: https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/commit/c928b26e0006a47cb3aca1c9bfbb8bffd365f0ab

**Comment by abrodkin** [comment]
@claziss can we have it backported to the upstream GCC 12 & 13 branches?

**Comment by claziss** [comment]
@abrodkin it doesn't have anything to do with GCC :)

**Comment by abrodkin** [comment]
@claziss oops, indeed. What about Binutils? Getting it in the upstream development branch and possibly backporting to some stable branch?
