### ISSUE TITLE
Some static PIE executables can hang in __libc_start_main  because of bad GOT relocation

### ISSUE THREAD

**Issue by pavelvkozlov** [foss-for-synopsys-dwc-arc-processors/toolchain#533]
By running glibc tests I've found that with latest binutils from arc-2023.03 branch some static PIE executables can hang in the ```__libc_start_main()``` func. 
This happens when glibc tries to check presence of ```__pthread_initialize_minimal()```. It reads value from GOT and if the value is not NULL, calls this function (in our case it is NULL, libpthread is not linked):
``` asm
000104e8 <__libc_start_main>:
   ...
   1054c:	2730 7f81 0006 b8c0 	ld	r1,[pcl,0x6b8c0]	;7be0c <.got>
   10554:	1200 2000           	ld	r0,[r18]
   10558:	792b                	tst_s	r1,r1
   1055a:	2700 7f81 0006 aaf8 	add	r1,pcl,0x6aaf8	;7b050 <__stack_chk_guard>
   10562:	8000                	ld_s	r0,[r0,0]
   10564:	2084 003c           	and	r0,r0,-256
   10568:	000a 0021           	beq.d	10	;10572 <__libc_start_main+0x8a>
   1056c:	a100                	st_s	r0,[r1,0]
   1056e:	0802 0000           	bl	0	;1056c <__libc_start_main+0x84>
   10572:	1200 2000           	ld	r0,[r18]

GOT 
Hex dump of section '.got':
  0x0007be0c 18f70700 00000000 14000000 48c50700 ............H...
  0x0007be1c c0f70700 c4f70700 00000000 ccd40700 ................
  0x0007be2c 14960300 10000000 10c00700 08000000 ................
  0x0007be3c 0c000000 d4c40700 c8fa0200 2cc50700 ............,...
  0x0007be4c 20000000 18c80700 4cf70700 0cc00700  .......L.......
  ...

```
The linker incorrectly points to the beginning of GOT and if the first value in GOT is not zero then check passes and ```bl 0``` instruction is executed.
The relocation for ```__pthread_initialize_minimal()``` in static libc.a looks like:
```
00000134  0002ff11 R_ARC_S25W_PCREL  00000000   __libc_setup_tls + 0
0000013c  00030033 R_ARC_GOTPC32     00000000   __pthread_initial[...] + 0
0000014a  00030232 R_ARC_PC32        00000004   __stack_chk_guard + 0
0000015a  0003004c R_ARC_S25W_PCREL_ 00000000   __pthread_initial[...] + 0
0000016c  00030332 R_ARC_PC32        00000000   __pointer_chk_gua[...] + 0
0000017a  00030411 R_ARC_S25W_PCREL  00000000   __cxa_atexit + 0 
```

I've reproduced this issue with ARCv3 and ARCv2 toolchains.
To reproduce, build small test with latest 2023.03 toolchain with glibc (I used arc-gnu-toolchain environment):
```c
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>

int main(int argc, char *argv[])
{
	int c;
	int val32;

	while ((c = getopt(argc, argv, "n:")) != -1) {
		switch (c) {
			case 'n':
				val32 = atoi(optarg);
				break;
			default:
				printf("Unknown option(%c)\n", c);
		}
	}
	printf("32-bit val: 0x%x\n", val32);

	return 0;
}

$ arc32-linux-gnu-gcc -fPIE -static test.c -o test
$ ./test
```
Binutils from 2022.09 branch handles this situation correctly.

**Comment by claziss** [comment]
@pavelvkozlov plz can u tell what glibc branch you use.  Somehow, I cannot reproduce your issue.

**Comment by pavelvkozlov** [comment]
I used arc-gnu-toolchain environment and built gcc, binutils and glibc from arc-2023.03 branches.
```
Commits:
glibc -6549a0c9
gcc - c805c9b4
binutils - 8f360663
```

**Comment by claziss** [comment]
Fix here: https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/commit/e3abaa2eb6dd1bd8fb91d180f4179f7c1d2cafe0

**Comment by pavelvkozlov** [comment]
I can confirm, issue has gone. Thanks.
Fixed with https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/commit/e3abaa2eb6dd1bd8fb91d180f4179f7c1d2cafe0

**Comment by pavelvkozlov** [comment]
I again see this issue, but this time with toolchain from the new arc-2023.09 branch.
It seems that the commit added to the arc-2023.03 branch https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/commit/e3abaa2eb6dd1bd8fb91d180f4179f7c1d2cafe0 is missing in arc-2023.09.

**Comment by claziss** [comment]
@pavelvkozlov thanks for finding this. Cheery picked into latest release branch.

**Comment by pavelvkozlov** [comment]
Thank you, 
Checked and closed as resolved.
