### ISSUE TITLE
GDB cannot step through DBNZ

### ISSUE THREAD

**Issue by shahab-vahedi** [foss-for-synopsys-dwc-arc-processors/toolchain#546]
If you step over the DBNZ instruction, the debugee will crash. Probably because the debugger inserts the wrong breakpoint at the wrong place.

Affects all HS4/5/6 targets.

![gdb-dbnz](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/assets/16524902/aaae68c8-5a0f-4e85-a91d-79ce64b7aadb)

sample: [gdb-dbnz-lnx.tgz](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/11551488/gdb-dbnz-lnx.tgz)

**Comment by shahab-vahedi** [comment]
The fix from @kolerov is upstream:

[arc: Put DBNZ instruction to a separate class](https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=c0852af0565c7a83e17f1358fac52a68e7047002)
[arc: Determine a branch target of DBNZ correctly](https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=33283d91d94e205ba34306cd1c253b9faceb4dd9)

@kolerov Please cherry-pick your patches from upstream for the relevant (release) branches and then close this issue.

**Comment by kolerov** [comment]
There are no next release branches for ARC classic. Thus, I reverted old version of those patches in `arc64` and pushed upstream versions (they are slightly different).
