### ISSUE TITLE
ARCv3: Faild to build XFS and BTRFS kernel modules

### ISSUE THREAD

**Issue by pavelvkozlov** [foss-for-synopsys-dwc-arc-processors/toolchain#555]
Faild to build XFS and BTRFS modules for ARCv3 32-bit variant.
```
ERROR: modpost: "__lshrdi3" [lib/test_scanf.ko] undefined!
ERROR: modpost: "__ucmpdi2" [fs/btrfs/btrfs.ko] undefined!
ERROR: modpost: "__lshrdi3" [fs/btrfs/btrfs.ko] undefined!
ERROR: modpost: "__ashldi3" [fs/btrfs/btrfs.ko] undefined!
ERROR: modpost: "__ashldi3" [fs/xfs/xfs.ko] undefined!
ERROR: modpost: "__ashrdi3" [fs/xfs/xfs.ko] undefined!
ERROR: modpost: "__ucmpdi2" [fs/xfs/xfs.ko] undefined!
ERROR: modpost: "__lshrdi3" [fs/xfs/xfs.ko] undefined!
```
It seems that the ARCv3 compiler adds calls for integer arithmetic routines and relies on libgcc as a provider of these functions. But for ARCv3 libgcc doesn't have such functions. The commit 88b0c1c1 also pointed to this.

**Comment by pavelvkozlov** [comment]
The kernel has configuration options to use generic implementations for such routines from the kernel lib.
I've created PR with fix https://github.com/foss-for-synopsys-dwc-arc-processors/linux/pull/130

**Comment by pavelvkozlov** [comment]
@claziss, what do you think, is it correct way? 
do you have plans to extend libgcc for ARCv3 with extra integer arithmetic routines?

**Comment by claziss** [comment]
I think all those functions are inlined by our gcc version. Hence, no need to have them in the libgcc.

**Comment by claziss** [comment]
For example:
```c
long long foo (long long x, int y)
{
  return x << y;
}
```
will result in:
```asm
foo:
	# args = 0, pretend = 0, frame = 0
	# frame_needed = 0, uses_anonymous_args = 0
	# size = 0 bytes
	# + outargs = 0 bytes
	# + locals  = 0 bytes
	# + regs    = 0 bytes
	# + varargs = 0 bytes
	# Parameters:
	#  x                    =`r1r0`                	(8)
	#  y                    =`r2`                  	(4)
	lsr	r4,r0,1
	not	r5,r2
	xbfu.f	0,r2,5
	asl	r3,r1,r2
	asl	r1,r0,r2
	lsr	r2,r4,r5
	mov_s	r0,r1
	or_s	r3,r3,r2
	mov.ne	r0,0
	j_s.d	[blink]
	mov.eq	r1,r3
	.size	foo, .-foo
```

**Comment by pavelvkozlov** [comment]
Then I don't understand why I see these unresolved symbols in kernel modules.

**Comment by claziss** [comment]
I am also curios. Please keep in the loop.

**Comment by pavelvkozlov** [comment]
@claziss, plz check attached archive [test_scanf.zip](https://github.com/foss-for-synopsys-dwc-arc-processors/linux/files/11614040/test_scanf.zip):
It contains compile time output for a small kernel test module (test_scanf):
```
test_scanf.i  - prepcocessed source
test_scanf.s  - intermediate asm
test_scanf.o.cmd - initial build command
```
Compiling with options -O1, -Og, -Os, -O2 or -O3 cause to appearance of __lshrdi3 call.
```
arc32-linux-gnu-gcc -O2 -c test_scanf.i 
arc32-linux-gnu-nm test_scanf.o | grep lshrdi3
         U __lshrdi3
```
With -O0 or without any, not:
```
arc32-linux-gnu-gcc -c test_scanf.i 
arc32-linux-gnu-nm test_scanf.o | grep lshrdi3
```

**Comment by claziss** [comment]
Simplified version:
```c
int a;

__attribute__((__cold__))
long long b(void)
{
  return ~0ULL >> a;
}
```

**Comment by abrodkin** [comment]
@claziss should we move that to the toolchain repo now?

**Comment by pavelvkozlov** [comment]
Required functions ```__ucmpdi2, __lshrdi3, __ashldi3, __ashrdi3``, are in libgcc  (finally I've found them).  Explicit symbol export allows to use them in kernel modules. I've update kernel patch to export required symbols https://github.com/foss-for-synopsys-dwc-arc-processors/linux/pull/130.
So, there is no issue from the libgcc or the compiler side. 
Closed, resolved in kernel.
