### ISSUE TITLE
EM SDP is not supported in OpenOCD and Eclipse

### ISSUE THREAD

**Issue by kolerov** [foss-for-synopsys-dwc-arc-processors/toolchain#562]
For EM SDP there is an options for choosing `emsdp.specs` but it doesn't exist anywhere. Also, there is no an options for specs for HSDK. This issue must be fixed after fixing this one https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/issues/544, which introduces a lot of changes to support of UART and specs files.

- [x] https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/issues/544
- [x] https://github.com/foss-for-synopsys-dwc-arc-processors/newlib/pull/49
- [x] https://github.com/foss-for-synopsys-dwc-arc-processors/newlib/pull/50
- [x] https://github.com/foss-for-synopsys-dwc-arc-processors/arc_gnu_eclipse/pull/72
- [x] Add support of EM SDP to OpenOCD.
- [x] Build the latest OpenOCD with support of OpenOCD and try to use it with Eclipse plugin.
- [x] Integrate the latest OpenOCD in Eclipse plugin.

**Comment by kolerov** [comment]
@abrodkin It turned out that not only support of EM SDP is not presented in Newlib, but OpenOCD does not support EM SDP. Is it worth keeping EM SDP projects in Eclipse?

**Comment by abrodkin** [comment]
@kolerov yes, EM SDP is our current development platforms for ARC EM processors (which is meant to replace obsolete EM StarterKit board) and so it would be really good to support EM SDP in our current tools.

**Comment by kolerov** [comment]
Fixed here:

https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/issues/583
