### ISSUE TITLE
GDB fix for PR remote/17028

### ISSUE THREAD

**Issue by eroom1966** [foss-for-synopsys-dwc-arc-processors/toolchain#58]
Hi Support

There was a fix to a bug in gdb 2014-06-11, PR remote/17028
How can I see if this is incorporated into your stream ?

I tried building off the gdb head configuring for target arc-elf32, but the configure/make fails, so I presume I need to take the GDB from here.

Thx
Lee

**Comment by anthony-kolesov** [comment]
Hi Lee,

[This patch](https://sourceware.org/ml/gdb-patches/2014-06/msg00424.html) was done for upstream 7.8 release, therefore it is in our arc-7.9-dev branch:

```
$ git log --oneline arc-7.9-dev   | grep 17028
364fe1f PR remote/17028: GDB+GDBserver hangs on Windows
$ git log --oneline arc-7.5-dev   | grep 17028
$
```

**Comment by eroom1966** [comment]
Thanks Anthony

Lee

**Comment by eroom1966** [comment]
Hi Anthony,
(reopening issue)
I cannot seem to gain access to the arc-7.9-dev branch, or maybe that is intentional ?

If I am supposed to have access can you tell me how I can do that, in the web interface the only branches I see are 
7.5 dev/stable
6.8 dev/stable

Thx
Lee

**Comment by anthony-kolesov** [comment]
Hi Lee,

Because you are looking at the old "gdb" repository. Modern GDB is in https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb repository.

To avoid confusion, I guess, we should close that old repository after we will sort out the multi-address space Q you've raised.

**Comment by eroom1966** [comment]
Thanks for the clarification
