### ISSUE TITLE
IDE: Add support for debugging EMSDP with openocd

### ISSUE THREAD

**Issue by artemiy-volkov** [foss-for-synopsys-dwc-arc-processors/toolchain#583]
![debu_configs](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/assets/137805134/a438443f-17ba-441d-8cee-96c265abddce)

In the Debugger tab of the Debug Configurations menu dialog, there is no way to set the EMSDP board as Development system. Please add a menu item for this board. You can use snps_em_sk_v2.3.cfg as the backing config file for this board, because according to this piece of documentation: https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/commit/1fd4183e3198f3bdd316f4968c87ee6be9e1a0fc#diff-57e5baf9fead8dcc75755dfce4b3c553b5e16aa8c41b718e8989c9e4005d47d5, from openocd's point of view it is functionally equivalent to EM Starter Kit v2.3.

**Comment by kolerov** [comment]
This issue if fixed with this commit:

https://github.com/foss-for-synopsys-dwc-arc-processors/arc_gnu_eclipse/commit/fb2140b79f89c1c79f8fb171a7fea46aaf1b1838
