### ISSUE TITLE
binutils objcopy does not understand my elf file created with the metaware toolkit

### ISSUE THREAD

**Issue by joolzg** [foss-for-synopsys-dwc-arc-processors/toolchain#590]
a.out: ELF 32-bit LSB executable, Synopsys ARCv2/HS3x/HS4x cores, version 1 (SYSV), statically linked, not stripped

Is there a workaround as I need to do some section manipulation on this output file.

**Comment by abrodkin** [comment]
@joolzg you may use `arc-elf32-objcopy` from our prebuilt ARC GNU toolchain. You may get it here: https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/releases/download/arc-2023.09-release/arc_gnu_2023.09_prebuilt_elf32_le_linux_install.tar.bz2

**Comment by joolzg** [comment]
Thanks that works.
