### ISSUE TITLE
Newlib for ARC-V uses wrong file-descriptor on write to semihosting

### ISSUE THREAD

**Issue by abrodkin** [foss-for-synopsys-dwc-arc-processors/toolchain#593]
This leads to a funny behavior: `write()` to `stdout` from the simulated target (be it QEMU or nSIM) ends-up being sent to host's `stdin`. And we never noticed that because on Linux hosts it's apparently possible to write to `stdin` and these messages even end-up being printed in the console. On Windows hosts though writes to `stdin` end-up being omitted by the OS and so nothing get printed.

Luckily, solution to that problem is already available, see [RISC-V: fix setting up std streams in init_semihosting()](https://sourceware.org/git/?p=newlib-cygwin.git;a=commit;h=c419bbb341528a97d2de88539caf200c9dec1ffb). And so we do need to get that fix in our Binutils sources used for ARC-V toolchain building.

**Comment by shahab-vahedi** [comment]
[cherry-picked](https://github.com/foss-for-synopsys-dwc-arc-processors/newlib/commit/c64ef7c7b6de25ef1ebd6738a877a685632b106f) onto [arcvx](https://github.com/foss-for-synopsys-dwc-arc-processors/newlib/tree/arcvx) branch.
