### ISSUE TITLE
Add coredump support for ARCv3 HS5x targets

### ISSUE THREAD

**Issue by gmazurki** [foss-for-synopsys-dwc-arc-processors/toolchain#602]
When a process crashes it is often helpful to have its core dumped. The data gathered this way could be useful in a further investigation on the reason of the crash.

Currently we are unable to gather core dumps; only a simple stack trace is printed on the console. We have a HS58-based system.
This BUG is created to find out what prevents core dumps from functioning and to enable them, possibly as an option on demand.

We enabled:

In Linux:
CONFIG_COREDUMP
ELF_CORE

In busybox:
CONFIG_FEATURE_INIT_COREDUMPS

We checked that `ulimit -a` is unlimited.

What else is needed?

**Comment by kolerov** [comment]
Corresponding PR:

- [x] https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/pull/83

**Comment by kolerov** [comment]
I am closing this issue since there is another one related to native GDB support for HS5x: https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/issues/605
