### ISSUE TITLE
Add native GDB client support for ARCv3 HS5x targets

### ISSUE THREAD

**Issue by jzbydniewski** [foss-for-synopsys-dwc-arc-processors/toolchain#605]
Using ARCv3, in release 2023.09 I cannot enable option "BR2_PACKAGE_GDB_DEBUGGER". In Config.in I can see this line

```
config BR2_PACKAGE_GDB_DEBUGGER
	bool "full debugger"
	depends on BR2_USE_WCHAR
	depends on !BR2_sh && !(BR2_arc64 || BR2_arc32)
	select BR2_PACKAGE_GMP if !BR2_GDB_VERSION_10
	select BR2_PACKAGE_NCURSES
	select BR2_PACKAGE_ZLIB
```

Is this really not supported for arc32 or just leftover ? For comparison, branch arc64 doesn't have this limitations

```
config BR2_PACKAGE_GDB_DEBUGGER
	bool "full debugger"
	depends on BR2_USE_WCHAR
	depends on !BR2_sh
	select BR2_PACKAGE_GMP if !BR2_GDB_VERSION_10 && !BR2_arc
	select BR2_PACKAGE_NCURSES
	select BR2_PACKAGE_ZLIB
```
If really not supported, can you please add support ?

**Comment by shahab-vahedi** [comment]
There's no native GDB client support in ARCv3 (yet).

**Comment by kolerov** [comment]
Corresponding PR:

- [x] https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/pull/83

**Comment by kolerov** [comment]
Hi @jzbydniewski. With the latest GDB patches not it's possible to build native GDB for HS5x targets with core dumps support. You can build Linux images using this Buildroot branch:

https://github.com/foss-for-synopsys-dwc-arc-processors/buildroot/tree/arc-2024.12

Note that now `arc-2024.12` is a current development branch for the next release and `arc64` branch is abandoned.

**Comment by kolerov** [comment]
As I said in the previous comment, it's possible now to build native GDB for HS5x targets. I am removing `2024.12` milestone but I am leaving this issue opened for further discussion.

**Comment by abrodkin** [comment]
@jzbydniewski we're going to close this issue now assuming that work on your side. If not or there're more or other issues related to GDB on ARC HS58 please feel free to reopen this issue or file a new one. Marry Christmas!
