### ISSUE TITLE
Bump GCC to the most recent version 14.1

### ISSUE THREAD

**Issue by abrodkin** [foss-for-synopsys-dwc-arc-processors/toolchain#607]
GCC v14 brings a host of new features and improvements of many areas. Of our special interest is implementation of the long list of RISC-V extensions, including code-size reduction instructions (`Zc`, `Zca`, `Zcb`, `Zcmp`, `Zcmt`, etc.), vector instructions (RVV) and many others.

See announce here: https://lists.gnu.org/archive/html/info-gnu/2024-05/msg00002.html and the changelog here: https://gcc.gnu.org/gcc-14/changes.html.

**Comment by kolerov** [comment]
The latest GCC 14 is stored in [GCC](https://github.com/foss-for-synopsys-dwc-arc-processors/gcc) repository in [arc-2024.06](https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/tree/arc-2024.06) branch. Release commit: https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/cd0059a1976303638cea95f216de129334fc04d1.
