### ISSUE TITLE
Bump Binutils to the most recent version 2.42

### ISSUE THREAD

**Issue by abrodkin** [foss-for-synopsys-dwc-arc-processors/toolchain#608]
There's a new Binutils v2.42 released, see https://sourceware.org/pipermail/binutils/2024-January/132213.html.

**Comment by shahab-vahedi** [comment]
This is [done](https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/tree/arc-2024.06) for ARC-V. The [ARCv3](https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/tree/arc64) still needs to be rebased and merged into [it](https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/tree/arc-2024.06) though.

**Comment by kolerov** [comment]
Binutils 2.42 release is stored in [Binutils](https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb) repository in [arc-2024.06](https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/tree/arc-2024.06) branch.  Release commit: https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/commit/299b91cd85540b4bfa94124364572f6a51b816fe.
