### ISSUE TITLE
Bump Newlib to the most recent version 4.4

### ISSUE THREAD

**Issue by abrodkin** [foss-for-synopsys-dwc-arc-processors/toolchain#609]
There's a new Newlib v4.4 release, see https://sourceware.org/pipermail/newlib/2023/020873.html.

**Comment by kolerov** [comment]
The latest Newlib is stored in [Newlib](https://github.com/foss-for-synopsys-dwc-arc-processors/newlib) repository in [arc-2024.06](https://github.com/foss-for-synopsys-dwc-arc-processors/newlib/commits/arc-2024.06/) branch. Release commit: https://github.com/foss-for-synopsys-dwc-arc-processors/newlib/commit/26f7004bf73c421c3fd5e5a6ccf470d05337b435.
