### ISSUE TITLE
Bump GDB to the most recent version 14.2

### ISSUE THREAD

**Issue by abrodkin** [foss-for-synopsys-dwc-arc-processors/toolchain#611]
The most recent GDB v14.2 was released on March 3rd, 2024 (see https://lists.gnu.org/archive/html/info-gnu/2024-03/msg00000.html). It brings a number of minor improvements and fixes on top of the major v14.1 release (see https://lists.gnu.org/archive/html/info-gnu/2023-12/msg00001.html).

**Comment by kolerov** [comment]
GDB 14.2 is available in `arc-2024.06-gdb` branch: https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/tree/arc-2024.06-gdb. Release commit: https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/commit/02c10eaecb63e5dbb99cbfdd1c5385e53ed031ff.
