### ISSUE TITLE
How to build gdb without python?

### ISSUE THREAD

**Issue by Imperas** [foss-for-synopsys-dwc-arc-processors/toolchain#62]
Can anyone tell me how to build the arc_gnu 2015.06 toolchain without python in the gdb?

In version 2014.12 I simply added --with-python=no to the configure command in build-elf32.sh at line 201, but I cannot figure out how to get the same result in 2015.06.

I see that toolchain/Makefile.release calls build-all.sh with `--config-extra '--with-python=no'` but when I add that to my build-all.sh command I get this error:

```
START ELF32: Fri Aug  7 01:45:50 BST 2015
Installing in /scratch/arc-elf32/Linux32/arc-elf32/
Building binutils ...
configure: error: invalid variable name: `'--with-python'
```

Any help would be appreciated.

Thanks

Jim Straus

**Comment by anthony-kolesov** [comment]
Hi Jim,

I cannot reproduce this this problem on my machine. I assume that cause of issue could be shell. What Linux distribution your are building on and what is the shell in /bin/sh? Can you also attach all-build and elf32-build log files from "logs" directory?

Anton

**Comment by Imperas** [comment]
Hi Anton,

Thanks for looking into this and the prompt response!

While simplifying my script to provide an example I have discovered the problem is an issue with quoting arguments in my script. I haven't quite figured out exactly what the problem is but it I can get `--with-python=no` to work when I invoke build-all.sh directly from the command line, so it is my problem.

Sorry for the trouble and thanks again.

Jim Straus
