### ISSUE TITLE
GCC corrupting arc HS66 store instruction by adding unexpected trap_s instruction

### ISSUE THREAD

**Issue by marklh0** [foss-for-synopsys-dwc-arc-processors/toolchain#634]
Given the following file:

``` C++
#include <cstdint>

extern "C" {
struct A {
  uint8_t reserved[1 << 30];
  uint32_t reset;
};

void __start() { reinterpret_cast<A*>(0)->reset = 0; }
}
```

And the following compile script:

``` sh
#!/bin/bash
set -o pipefail
set -o errexit
external/_main~arc64_none~arc64_gcc_toolchain_linux_x86_64/bin/arc64-elf-gcc '-mcpu=hs6x' -g -O2 -c f.cc -o f.o &&   external/_main~arc64_none~arc64_gcc_toolchain_linux_x86_64/bin/arc64-elf-objdump -SD f.o | head -n 20
```

You will see the following output:

```
f.o:     file format elf64-littlearc64


Disassembly of section .text:

0000000000000000 <__start>:
struct A {
  uint8_t reserved[1 << 30];
  uint32_t reset;
};

void __start() { reinterpret_cast<A*>(0)->reset = 0; }
   0:	1e00 7001 4000 0000 	st	0,[0x40000000,0]
   8:	78be                	trap_s	0x5
   a:	78e0                	nop_s
```

The `trap_s` instruction should not be there.

This happens at `-O2` and `-O3` levels.

I've used both of these compilers (arc-v3, HS66, little-endian bare-metal) and can reproduce the issue:
1. https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/releases/tag/arc-2024.06-rc1
2. https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/releases/tag/arc-2023.09-release

**Comment by marklh0** [comment]
At least part of the issue appears to be `-fisolate-erroneous-paths-dereference`. When I use `-fno-isolate-erroneous-paths-dereference` then this specific issue goes away. But I suspect that's not a perfect workaround.

**Comment by marklh0** [comment]
After looking up that arg, this is actually expected behavior. There is no bug.

**Comment by abrodkin** [comment]
@marklh0 thanks for your report and subsequent analysis. I'm wondering which problem you're trying to solve.

**Comment by marklh0** [comment]
> @marklh0 thanks for your report and subsequent analysis. I'm wondering which problem you're trying to solve.

I had code similar to what I showed in the test case and was getting trap_s instructions inserted in my code, even though the actual addresses I was accessing were not null pointers. This is just due to a quirk in how our autogenerated register file defines structs and fields relative to a 0 address. We can either fix our internal tooling to not do that, or provide `-fno-isolate-erroneous-paths-dereference` to the compiler.

Either way it’s not an issue with your toolchain, just something I didn’t realize was happening.

**Comment by abrodkin** [comment]
@marklh0 thanks for the explanation.
