### ISSUE TITLE
ARC toolchain questions 

### ISSUE THREAD

**Issue by schechea** [foss-for-synopsys-dwc-arc-processors/toolchain#77]
My name is Sharon and I am working at intel R&D center in Haifa Israel.

Our goal is to run a SW testing applications on bare metal system with ARCHS38 CPU.
I downloaded and installed your windows version of GNU toolchain for ARC processors (“arc_gnu_2016.03_ide_win_install.exe”).

We managed to create a project under Eclipse of type ARCcross ELF32 target application, most of the things works as expected.
However we have some questions that we still didn’t manage to resolve:
1.  How can we “replace” the malloc function that is defined in libg.a or alternatively provide malloc with our custom address range (e.g 0x3000000 => 0x4000000)
2.  How can we control the executable start address, currently is 0x100 by default and it’s not suitable for our system memory map.
3.  Currently Eclipse creates only ELF file, but we would like to create also bin file, can it be added as an artifact?

Note: our Makefile is currently auto generated by eclipse.

Waiting forward for your reply.

Thanks,
Sharon.

**Comment by anthony-kolesov** [comment]
Hi Sharon,
1. To learn how to override any function, see documentation for ld, option `--wrap`.
2. See option `--entry` in ld documentation.
3. Create `makefile.targets` file in the root of project source tree. This file is automatically included by the makefile generated by Eclipse.
   Contents of this file should be like (where `PROJECT_NAME` is set to your project name):

``` makefile
PROJECT_NAME := c

secondary-outputs: $(PROJECT_NAME).bin

$(PROJECT_NAME).bin: $(PROJECT_NAME).elf
    arc-elf32-objcopy -O binary $< $@
```

**Comment by schechea** [comment]
hi Anthony 
thanks for your support
