### ISSUE TITLE
Problem with nSIM simulator

### ISSUE THREAD

**Issue by ManuelAlfonso** [foss-for-synopsys-dwc-arc-processors/toolchain#80]
I am going to explain you exactly what I have done, and you say me If everything is correct:

I downloaded the simulator nSIM (but I cannot use it because I didn't knew that I needed more things).

so, I saw this website: "https://github.com/foss-for-synopsys-dwc-arc-processors/arc_gnu_eclipse/wiki" and then botton of the website I clicked in "Installation" and took me to another page, this website: "https://github.com/foss-for-synopsys-dwc-arc-processors/arc_gnu_eclipse/wiki/Installation", and like I use ubuntu (linux) I followed the steps, I downloaded Eclipse and then the CDT, and then I downloaded the plugins for eclipse in this website "https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/releases/tag/arc-2016.03" (arc_gnu_2016.03_ide_plugins.zip) and I installed the plugins through eclipse with the options "Install new Software", so I followed the steps of the this website, except the last paragraph where says "5. Installing plugin on Linux Host".

So do you think the step I have followed are correct?
Could you explain me how  I can install "arc_gnu_2016.03_prebuilt_elf32_be_linux_install.tar.gz"?

Thank you for everything. I hope I explained well.

**Comment by anthony-kolesov** [comment]
Hi Manuel Alfonso,

`arc_gnu_2016.03_prebuilt_elf32_be_linux_install.tar.gz` is a binary package, so you should just untar it and add it's `bin` folder to the PATH environment variable - it's not a source distribution, so it doesn't have "configure" script in it. Then run Eclipse and it will find this toolchain in the PATH.

**Comment by ManuelAlfonso** [comment]
Hello Anton, I have untared it,  but Where is the bin folder? what is bin folder? I have to add the untar in this folder? Sorry for the misinformation.
The steps that I have followed, are right?

Thank you very much.

**Comment by anthony-kolesov** [comment]
Bin folder is right in the root of the untarred directory:

```
$ tar xaf arc_gnu_2016.03_prebuilt_elf32_be_linux_install.tar.gz

$ ls arc_gnu_2016.03_prebuilt_elf32_be_linux_install/
arceb-elf32  bin  include  lib  libexec  share  Synopsys_FOSS_Notices.pdf

$ ls arc_gnu_2016.03_prebuilt_elf32_be_linux_install/bin
arceb-elf32-addr2line  arceb-elf32-g++         arceb-elf32-gdb      arceb-elf32-readelf
arceb-elf32-ar         arceb-elf32-gcc         arceb-elf32-ld       arceb-elf32-run
arceb-elf32-as         arceb-elf32-gcc-4.8.5   arceb-elf32-ld.bfd   arceb-elf32-size
arceb-elf32-c++        arceb-elf32-gcc-ar      arceb-elf32-nm       arceb-elf32-strings
arceb-elf32-c++filt    arceb-elf32-gcc-nm      arceb-elf32-objcopy  arceb-elf32-strip
arceb-elf32-cpp        arceb-elf32-gcc-ranlib  arceb-elf32-objdump  arceb-elf32-tcf-gcc
arceb-elf32-elfedit    arceb-elf32-gcov        arceb-elf32-ranlib
```

**Comment by ManuelAlfonso** [comment]
Yes, I am in eclipse, so , I do window ->  Preferences -> C/C++ -> Build -> Environment -> and I add the PATH.
is it right?
Now, Eclipse say me, "arc-elf32-g++" NOT FOUND in path, but I have done the same, in this tar "arc_gnu_2016.03_ide_linux_install.tar.gz" I have untared and then the bin folder I have done the same.

I don't know why I have a lot of problem.
Sorry for misinformation and thank you very much.

**Comment by anthony-kolesov** [comment]
No, you should add bin to the PATH before starting the Eclipse itself, for example in the bashrc or in command line, before running eclipse. `arc_gnu_2016.03_ide_linux_install` doesnt need any manipulations with PATH - it should find compiler binary in the location relative to eclipse executable, that's why it is a prefered way of running IDE, because it has a proper directory structure.

**Comment by ManuelAlfonso** [comment]
![image1](https://cloud.githubusercontent.com/assets/20947994/17570007/f7907228-5f4a-11e6-9111-9ecfeea5fdac.png)
![image2](https://cloud.githubusercontent.com/assets/20947994/17570022/0363dbda-5f4b-11e6-8f80-265e229bf657.png)
![image3](https://cloud.githubusercontent.com/assets/20947994/17570039/15b742c2-5f4b-11e6-8c59-3d350d30b246.png)

 Ok, I have done this:
In the terminal I have put : "export PATH=$PATH:theBINfolder" but still When I want to create C proyect the "ARC Cross ELF32" is not supported.

And the variable PATH say this: bash: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/leunamosnofla/Documentos/philips/arc_gnu_2016.03_prebuilt_elf32_be_linux_install/bin

so it's added good. And I have added it to ./bashrc too.

You can see in the images that If I unclick the box I can see the ARC Cross ELF32 but If I click this I can't see because really it's not supported.

The last image say that the GNU toolchain for ARC 600 is unsupported.

Thank you very much for everything.

**Comment by ManuelAlfonso** [comment]
Thank you very much. I have resolved the problem. I had to add the contents bin folder in the bin folder system.

**Comment by fbedard** [comment]
Resolved - closing.
