### ISSUE TITLE
ARC toolchain gcc 4.8 issues

### ISSUE THREAD

**Issue by emersonchi** [foss-for-synopsys-dwc-arc-processors/toolchain#81]
Dear Synopsys open source sw support team,
I got issues with the arc uclibc 4.8 toolchain:
1. version 4.8.0 does not support c++ exception handling. I compile a simple throw and catch test code with 4.8.0 uclibc toolchain. the code can't caught the exception and aborted.
2. version 4.8.4 support the exception handling, but when compile the code with optimization -O2 flag, code below isWhitespace is optimized out 
    while ((idxStart < idxEnd) && (isWhitespace(mBuf.get()[idxStart])))
    {
        ++idxStart;
    }

My platform is ARC750 V1. 

Thank You

**Comment by iguryanov** [comment]
Hi Emerson, 

I tried very small several lines test for exception using 4.8.0 compiler from our 2014.08 release. Then I compared results with 4.8.4 from 2015.06. I used "-mcpu=arc700 -O2" options. 
In both cases I see that exceptions were thrown. More over, code part of resulting assembly were completely identical. 

I also created small example for the second problem - wrote small class for mBuf which returns pointer to array and used standard isspace(). In resulting assembly I still see that isspace is called - only mBuf.get() was optimized away in the loop. 

could you please share some example for both problems? source code, build log, resulting binaries? 
Otherwise it is quite difficult to hit the same scenario you got. 

Regards,
Igor.

**Comment by emersonchi** [comment]
Igor, 
Thank  you for your reply, I attached a eh_test.cpp, which was compiled with v4.8.0  arc-linux-uclibc-g++ eh_test.cpp -o eh_test, when traced with gdb it shows the application received SIGABRT as soon as "throw a"

(gdb) n

[eh_test.zip](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/425682/eh_test.zip)

Program received signal SIGABRT, Aborted.
0x00080648 in kill ()

**Comment by emersonchi** [comment]
with 4.8.4 version 
below code 
The optimization can generate incorrect code. For example, this code segment is from our firmware code:

CString CString::trim() const
{
    int idxStart = 0;
    int idxEnd = ::strlen(mBuf.get()) - 1;

```
while ((idxStart < idxEnd) && (isWhitespace(mBuf.get()[idxStart])))
{
    ++idxStart;
}

while ((idxStart <= idxEnd) && (isWhitespace(mBuf.get()[idxEnd])))
{
    --idxEnd;
}

return subStr(idxStart, idxEnd - idxStart + 1);
```

}

The optimization will sometimes miss whitespace chars and trim strings incorrectly.
below is the compile flags 

arc-linux-uclibc-g++ -c -fno-strict-aliasing  -ftree-dce -ftree-dse -ftree-fre -ftree-sra -ftree-ter -fomit-frame-pointer -finline-functions -finline-functions-called-once -ffast-math -Werror  -mno-cond-exec  -mlong-calls  -Wall -static -O2 

Thank You

**Comment by iguryanov** [comment]
Hi Emerson, 

for your second exception example I see different assembly for the compilers, but both are working for me. But it does not proof anything as I don't have arc700 platform around today and I had to build for archs. Plus my 4.8.0 toolchain has only 700 libs and I linked object file against hs libraries - the problem can be in libraries...  If you try to link your example statically, would id still break? 

And about your optimizing away problem - you saying that it _sometimes_ misses whitespaces. Should it miss always if it is optimized away? Can you ass some logging to isWhitespace()? maybe you can disassemble CString::trim()  and upload it? I'll run experiments on my side but it may take time. 

Regards,
Igor.

**Comment by claziss** [comment]
Hi,

ARC's gcc4.8.0 has some issues with exception handling. The problem is in libgcc, unwinding procedure.

Best

**Comment by ekromskoy** [comment]
To clarify on Emerson's C++ optimization issue above it was classified as a bug and generated code mess up with first while loop cycle. Work around would be to add compilation option '-fno-tree-ch'.

Cheers,
Ed

**Comment by claziss** [comment]
gcc 4.x.x is no longer supported, please use newest arc's gcc. Please react if you don't like this issue close.
