### ISSUE TITLE
 64bit division support in toolchain

### ISSUE THREAD

**Issue by avinashpqtn** [foss-for-synopsys-dwc-arc-processors/toolchain#82]
Hi,

I am using ARC GNU 2016.03 toolchain. Toolchain has been compiled locally for Linux 4.6.3 kernel. Target platform is ARC770D.

I am seeing following warning while linking our code:
4.6.3/../linux/modules/lib/modules/4.6.3/extra/XXX.ko needs unknown symbol __udivdi3

I suspect this is originating from div_u64() in our code. Same sources work fine with older toolchain.
Also quick grep inside toolchain directory shows __udivdi3 maybe part of toolchain already:

share/info/gccint.info -
 -- Runtime Function: unsigned long __udivdi3 (unsigned long A, unsigned                                                                                                                                    long B)

Are we missing linking any(math?) library or so?

Thanks,
Avinash

**Comment by vineetgarc** [comment]
kernel link includes libgcc which is part of toolchain and has these symbols for math emulation. However to make these symbols includable for modules these are exported as well arch/arc/kernel/arcksyms.c - e.g. it has __udivsi3
maybe 2016.03 libgcc sources define a new function - __udivdi3 which needs to be exported as well in arcsyms.c  can u give tha a quick try ?

**Comment by vineetgarc** [comment]
And indeed __udivdi3 comes in from libgcc for 64-bit divide so must be triggered by your usage of div_u64. Does the kernel module from old tools have that symbol (you can use nm to chk that). Likely it doesn't due to the way gcc code gen etc.... But anyways as suggested before - try the export and see if that works for you.

**Comment by avinashpqtn** [comment]
This indeed seems to be case.
command nm on module compiled with newer toolchain results into this:
$ nm XXX.ko | grep udiv
         U __udivdi3
         U __udivsi3
while on older modules I see following output:
$ nm XXX.ko | grep udiv
         U __udivsi3

I modified arcksyms.c as per your suggestions and this seems to fix undefined symbol warning.
Attaching patch for your reference. Thanks!

[arcksysm_add_udivdi3_sym_patch.txt](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/427843/arcksysm_add_udivdi3_sym_patch.txt)

**Comment by vineetgarc** [comment]
If you care (to have a patch with ur name in upstream kernel.org) please post a git formatted patch to linux kernel mailing list and linux-snps-arc@lists.infradead.org.
If not let me know and I will create one myself and add it for sending Linus's way

**Comment by avinashpqtn** [comment]
Emails from my account have confidentiality footer and are not accepted by opensource community. 
I would request you to submit patch.

-Avinash

**Comment by vineetgarc** [comment]
Is there an email address I can add in Reported-by tag ?

**Comment by avinashpqtn** [comment]
avinashp@quantenna.com

**Comment by vineetgarc** [comment]
alright fix pushed to my kernel.org repo #for-curr branch
http://git.kernel.org/cgit/linux/kernel/git/vgupta/arc.git
will be Linus' way soon - also marked for stable backport.

Thx for the fix.
-Vineet
