### ISSUE TITLE
Linux 4.7 kernel support

### ISSUE THREAD

**Issue by avinashpqtn** [foss-for-synopsys-dwc-arc-processors/toolchain#84]
Dear Synopsys open source sw support team,

We are planning to port one of our platforms to Linux 4.7 kernel.
We would like to confirm that GCC toolchain for ARC platform supports/is compatible with Linux 4.7 kernel before diving into. Also if answer to this is affirmative,  I would like to know latest stable toolchain release which supports this kernel.

Thanks,
Avinash Patil

**Comment by vineetgarc** [comment]
Hi Avinash,

We are in transition w.r.t tools compatibility - the last GNU tools release 2016.03 was ABI v3. However with the upcoming 2016.09 tools (with gcc 6.x) we are moving to a ABI v4 (which is not compatible with ABI v3). The pairing change to kernel went into 4.8-rc1 and it has not yet hit the backports - so you will need to cherry-pick  commit 840c054fd0ef ("ARC: Support syscall ABI v4") if you are using 4.7.2

You can find more details about ABI change on wiki @
https://github.com/foss-for-synopsys-dwc-arc-processors/linux/wiki/ARC-Linux-Syscall-ABI-Compatibility

HTH,
-Vineet

**Comment by avinashpqtn** [comment]
Hi Vineet,

Thanks for information.

We are planning to use Linux 4.7/4.7.1 from linux-stable git and GCC 4.8(GNU tools 2016.03). 
Also it looks like 2016.09 GNU toolchain is yet to be released.
So we think ABI v3 suffices our requirements. 

Do you still recommend moving to 2016.09 release and GCC 6.x toolchain?

Thanks,
Avinash

**Comment by vineetgarc** [comment]
So I discussed this internally - it seems gcc 6.x still needs to go thru our formal verification so is not recommended for production as of now. You can indeed start off with GNU 2016.03 and any kernel. As long as kernel is built with any gcc 4.8.x based tools - it will act as ABI v3. FWIW there is a good chance that we will do a maintenance release of gcc 4.8.x based tools in few months (that will remain ABI v3)

ABI v4 is not a hard requirement for anyone. It just locks you to gcc 4.8.x (vs. upgrading to 6.x and beyond). 

HTH,
-Vineet
