### ISSUE TITLE
GCC arc-2016.09-eng010 accessing bitfields

### ISSUE THREAD

**Issue by danielmentzgoogle** [foss-for-synopsys-dwc-arc-processors/toolchain#85]
I copied a small example program below that demonstrates the issue. I basically get different outputs depending on whether I compile it with "-O0" vs "-O".

``` C
struct ubifs_budget_req {
    unsigned int fast:7;
    unsigned int new_ino_d:13;
};

    if (req->new_ino_d & 7) {
        printf("new_ino_d & 7\n");
    }
```

If I compile the example with optimizations turned off ("-O0"), it generates the following good code:

```
       if (req->new_ino_d & 7) {
   103ec:       13fc b002               ld      r2,[fp,-4]
   103f0:       8240                    ld_s    r2,[r2,0]
   103f2:       ba27                    lsr_s   r2,r2,0x7
   103f4:       bacc                    bmsk_s  r2,r2,0xc
   103f6:       7a50                    extw_s  r2,r2
   103f8:       bac2                    bmsk_s  r2,r2,0x2
   103fa:       7a4b                    tst_s   r2,r2
   103fc:       f207                    beq_s   1040a <fff+0x3a>
```

It right shifts the value by 7 bits to get rid of the value of "fast" and to align new_ino_d with the LSB of r2. It then masks the least significant 13 bits and finally tests the least significant 3 bits.

If I compile the same code with "-O", it generates different code:

```
        if (req->new_ino_d & 7) {
   103e4:       8540                    ld_s    r2,[r13,0]
   103e6:       228b 823e               tst     r2,-120
```

-120 is equivalent to 0xffffff88, which I think is the incorrect bitmask to test for. If I'm not mistaken, 0x380 would be the correct bitmask i.e. ignore the lower 7 bits (".fast") and test the next 3 bits.

The example code has been lifted from the Linux kernel from fs/ubifs/budget.c: ubifs_assert(!(req->new_ino_d & 7));

``` C
struct ubifs_budget_req {
    unsigned int fast:7;
    unsigned int new_ino_d:13;
};

int printf(const char *format, ...);

void fff(struct ubifs_budget_req *req) {
    printf("Entering\n");
    if (req->new_ino_d & 7) {
        /* It should not print the following line because .new_ino_d is
         * 0 but it does so on ARC when compiling with "-O" */
        printf("new_ino_d & 7\n");
    }
}

int main(int argc, char *argv[]) {
    struct ubifs_budget_req req = {
        .fast = 8,
        .new_ino_d = 0,
    };
    fff(&req);
    return 0;
}
```

**Comment by fbedard** [comment]
Thanks Daniel.  Assigned Claudiu to take a look at this.

**Comment by claziss** [comment]
I confirm this is an issue. Making a patch + test. Thank you for bringing up this issue.

**Comment by claziss** [comment]
Fixed by commit:
[arc-6.x-dev 479c87] [ARC] Fix tst_bitfield_tst pattern.

N.B. the HASH number may change due to git rebase commands.
