### ISSUE TITLE
ARC GNU 2014.12 - GDB visbility vs. MPU

### ISSUE THREAD

**Issue by coco21** [foss-for-synopsys-dwc-arc-processors/toolchain#88]
Hi all,

I post my question following suggestion by one of my Synopsys support contacts (Igor).
No CASE or STAR has been filed yet.

We use ARC GNU 2014.12 for the moment (toolchain and debugger).
We use ARC EM6 CPU w/ MPU option.
We don't use secure shield option.
We run an OpenRTOS on top, for the moment we stay supervisor mode the whole time.

I’d like to know if there may be possible issues with the native ARC GDB that the latter has not full visibility on the code or is able to circumvent e.g. MPU enforcements (that would be natural I’d say).

Indeed my very concrete problem is that in Eclipse IDE I can see ASM/C intermixed code in disassembly window until I join our main() function, follows some configurations and disassembly starts to behave differently just after MPU has been configured.
Differently means: disassembly code remains empty, I only see C lines but address/position link seem being preserved.

Below two samples (two projects but exactly same toolchain, debugger, IDE etc. versions) – one project I can properly disassemble, the other not.
You can observe when OK inst=”…” string is not empty, when not then it’s empty.

Disassemble OK

(gdb) 
292-data-disassemble -s 0x1004c8 -e 0x1004e8 -- 0
292^done,asm_insns=[{address="0x001004c8",func-name="Reset",offset="8",inst="sub_s      sp,sp,4"},{address="0x001004ca",func-name="Reset",offset="10",inst="ld         r2,[0x00801800]"},{address="0x001004d2",func-name="Reset",offset="18",inst="st         r2,[fp,-4]"},{address="0x001004d6",func-name="Reset",offset="22",inst="bl         0x10040c <EnableInterrupt>\n"},{address="0x001004da",func-name="Reset",offset="26",inst="bl         0x107174 <g_InitLogUart>\n"},{address="0x001004de",func-name="Reset",offset="30",inst="bl         0x1007b0 <A_Test>\n"},{address="0x001004e2",func-name="Reset",offset="34",inst="bl         0x101f54 <B_Test>\n"},{address="0x001004e6",func-name="Reset",offset="38",inst="bl         0x103398 <C_Test>\n"}](gdb)

Disassemble KO

(gdb) 
850-data-disassemble -s 0x11cb54 -e 0x11cb74 -- 0
850^done,asm_insns=[{address="0x0011cb54",func-name="prvIdleTask",offset="12",inst="           "},{address="0x0011cb58",func-name="prvIdleTask",offset="16",inst="           "},{address="0x0011cb5c",func-name="prvIdleTask",offset="20",inst="           "},{address="0x0011cb60",func-name="prvIdleTask",offset="24",inst="           "},{address="0x0011cb64",func-name="prvIdleTask",offset="28",inst="           "},{address="0x0011cb68",func-name="prvIdleTask",offset="32",inst="           "},{address="0x0011cb6c",func-name="prvIdleTask",offset="36",inst="           "},{address="0x0011cb70",func-name="prvResetNextTaskUnblockTime",offset="0",inst="           "}](gdb)

Thanks & Br Christophe

**Comment by anthony-kolesov** [comment]
Hi Christopher,

Could you send me a code that sets up MPU in your system? I cannot reproduce that on AXS103 with HS36.

Have you tried to lower JTAG frequency? Maybe to even some extreme values in the order of tens or hundreds of KHz? In general MPU shouldn't affect ability of Debug interface to read targets's memory - MPU protects only from Kernel and User accesses. Code protection feature, however may protect memory from Debug interface.

**Comment by coco21** [comment]
Hello Anthony,

Great you reply so fast, thanks!
Understand your statements regarding what and how MPU protects, sure.
When you say code protection, can you please give me an example of such a code protection just to align our minds (since there are many ways of doing this). Thanks.

Ok, my target is not en emulator/FPGA breadboard hence I am not using a Ashling Opella XD JTAG gdbserver backend. My target is a simulator target from Imperas itself using a GDB front-end to debug latter. That said let me check if it's ok to bring in an Imperas guy here - ideally that would be the fastest way of getting all of us out this request I pulled.

Thanks Christophe

**Comment by anthony-kolesov** [comment]
"Code protection" is a feature of ARC EM, that disables read/write access to memory regions even through a Debug interface. You can just search for "code protection" in the Databook or PRM - there is no special name of that feature. Unfortunately there is little detail about what is the "region" in this code protection mechanism, so I can only assume that memory is divided in 16 equally-sized regions, hence in your case you would either not get disassembly at all or will get it for both functions.

If you are using Imperas simulator, then apparantly it implements MPU in such way that Debugger also doesn't get read access on instruction memory - when GDB client asks gdbserver to read memory, gdbserver returns error code or something like that, so GDB client cannot disassemble it. I don't have access to this simulator, so cannot check its behaviour right now.

**Comment by coco21** [comment]
Indeed code protection is enabled in our case, both for the HW IP and the Imperas simulator (that simulates this too). MPU configurations is ok and well understood for me, code protection I need to go through specs to be sure to understand the little details. On Imperas side the idea is to simply ignore the RWX flags from a debugger POV so latter can simply see it all independently on which configuration we run, makes sense to you as well? Thx Christophe

**Comment by anthony-kolesov** [comment]
You need to try with disabled code protection to see if there is any difference.

For the MPU - simulator/gdbserver should ignore MPU RWX flags. One of the things you can do is to run this without IDE - right from the GDB. In GDB run to `prvIdleTask` or whatever is the function that runs after MPU is enabled. Do "set debug remote 1", then "disas". That would print out what exactly is the response of gdbserver to the query to read memory.

**Comment by coco21** [comment]
I get a fix by tomorrow from Imperas and it seems it's more on their side than on yours. I keep in touch but thanks already so far for your reactivity, very appreciable! Christophe

**Comment by coco21** [comment]
Hello,

To properly close my request here I confirm fix from Imperas was helping, so no link to the ARC GNU here.
Problem was that MPU RWX bits were considered by the simulation engine and created sort of an auto-lock out of the debugger being no longer able to access the memory addresses in order th fetch and disassemble instructions.

Thanks much for your support. Christophe
