### ISSUE TITLE
What is the compiler pragma to disable hardware loop within a C subroutine or within a few statements?

### ISSUE THREAD

**Issue by bravindr** [foss-for-synopsys-dwc-arc-processors/toolchain#93]

**Comment by claziss** [comment]
You can use:

``` c
__attribute__ ((optimize("no-branch-count-reg")))    
```

on a function.
More about function attributes:
https://gcc.gnu.org/onlinedocs/gcc/Function-Attributes.html
https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html

**Comment by claziss** [comment]
Closing, no further questions as far as I can see.
