### ISSUE TITLE
"_Uncached" keyword not support

### ISSUE THREAD

**Issue by yiwuzihui** [foss-for-synopsys-dwc-arc-processors/toolchain#94]
I use following definition with Metaware compiler to access hardware register
`#define read_reg(addr)   (*(_Uncached volatile unsigned int *)(addr))`

But I can't find **_Uncached** keywork under GCC.
**-mno-volatile-cache** doesn't help because **volatile** are used somewhere such as

```
struct {
    int a;
    volatile int flag;
}
```

bypass cache operation will cause memory consistency problem.
How can I define cache bypass operation without insert asm code?

**Comment by claziss** [comment]
GCC doesn't have _Uncached attribute. Maybe a solution is [here](https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/issues/58).

**Comment by yiwuzihui** [comment]
The solusion above do work, But It is really hard to replace all the register operation.
For some reason, I have a lot of driver written in follow style. 

``` c
typedef _Uncached volatile unsigned int    RwReg;
typedef struct {
    RwReg UART_THR;
   // ...
} UART

void uart_putc(UART *port, u8 c)
{
    port->UART_THR = c;
}
```

**Comment by claziss** [comment]
Sorry, I do not see an easy way out of this issue.

**Comment by claziss** [comment]
This is a planned feature for the upcoming 2017.09 release.

**Comment by claziss** [comment]
Feature added by this commit:

[ARC] Add 'uncached' attribute.
The _Uncached type qualifier can be used to bypass the cache without
resorting to declaring variables as volatile.

gcc/
2017-07-12  Claudiu Zissulescu  <claziss@synopsys.com>

	* config/arc/arc-protos.h (arc_is_uncached_mem_p): Function proto.
	* config/arc/arc.c (arc_handle_uncached_attribute): New function.
	(arc_attribute_table): Add 'uncached' attribute.
	(arc_print_operand): Print '.di' flag for uncached memory
	accesses.
	(arc_in_small_data_p): Do not consider for small data the uncached
	types.
	(arc_is_uncached_mem_p): New function.
	* config/arc/predicates.md (compact_store_memory_operand): Check
	for uncached memory accesses.
	(nonvol_nonimm_operand): Likewise.

gcc/testsuite
2017-07-12  Claudiu Zissulescu  <claziss@synopsys.com>

	* gcc.target/arc/uncached.c: New test.

**Comment by claziss** [comment]
To be metaware compatible, you need to define _Uncached:

```c
#define _Uncached __attribute__((uncached))
```

**Comment by inkstone** [comment]
How to open this feature? I did that with latest release. But I still got warning as "warning" from GCC saying it ignored the attribute

**Comment by iguryanov** [comment]
Hi Yan, as I replied in the CASE, this works as expected. 
volatile TYPE __attribute__ ((uncached)) VARNAME; 
If you having problem please paste exact piece of code to the CASE. 

But I need to check with Claudiu why this construct treats pointers to volatile differently from mwdt:

volatile  __attribute__ ((uncached)) int *status = (__attribute__ ((uncached)) int *) 0x4;
...
return *status;


Regards,
Igor.
