### ISSUE TITLE
ARC GNU 2014.12 - When optimizing (-O1,2,s) getting Assembler message of bad instruction

### ISSUE THREAD

**Issue by coco21** [foss-for-synopsys-dwc-arc-processors/toolchain#95]
Hello Anthony,

I've today a strange behavior when we compile our code.
We are using ARC GNU 2014.12 on a Windows 7.1-SP1-x64 host machine.
We use a ARCv2 EM6 CPU.

We compile code with no optimisation at all for the moment in order to  have best debug experience.
Now  we try to simply switch on optimisation switches (e.g. -O1, -O2, -Os) and some files build with no pain but suddenly build stops with the message:

Build/obj/MyFile.s: Assembler messages:
Build/obj/MyFile.s:163: Error: bad instruction `add1 r24,@__MyLinkerSymbol@sda,gp`
Build/obj/MyFile.s:163: Error: bad instruction `add1 r1,@__MyLinkerSymbol@sda,gp`
Build/obj/MyFile.s:163: Error: bad instruction `add_s r1,r1,@__MyLinkerSymbol@sda`
make: **\* [Build/obj/MyFile.s] Error 1
make: **\* Waiting for unfinished jobs....

Error is same independently if I do -O anything. I already am looking to GNU and ARC documentation to understand but prefer to ask here as well too.

Thanks for a quick answer if possible.

Best regards Christophe

**Comment by claziss** [comment]
Hi,
The listed mnemonics are not accepting the @sda relocations for the given tools version used. Please upgrade to the latest binutils and let us know if you still see the issue.

Thanks

**Comment by coco21** [comment]
Hi,
Thanks for your quick answer.

You basically tell me I've to  switcht the complete ARC GNU toolchain suite, correct?
But that is not really an option here for various reasons, let's take that just as a constraint.

@sda relocation is supported since which ARC GNU version exactly please?

Thanks Christophe

**Comment by claziss** [comment]
U can switch only the binutils, not the compiler.

@sda is supported for a while now, but not all the mnemonics are accepting it. In the newest binutils, we fix a part of those shortcomings.

As far as I can see those instructions are in a custom .s file and not generated by the compiler. So, you can use [.reloc](https://sourceware.org/binutils/docs/as/Reloc.html#Reloc) if you cannot use a newer version.

**Comment by coco21** [comment]
Ok, i downloaded the latest Eclipse installer (we also use the IDE) to get just the complete toolchain.
I took 2015.06 and installed it in parallel to my existing one 2014.12.

Then I simply replaced the complete folder C:\arc_gnu\arc-elf32 by the new version.
Assembler and linker exec have different hashes (of course this are new builds) but doing a as -v or ld -v I get same versions for both installations. gcc -v however goes from 4.8.3 toward 4.8.4 but also has different configurations.

With all that I do a rebuild but problem remains. What am I missing here?

Thanks Christophe

**Comment by coco21** [comment]
Hello,

Coming back on one of your statements above that the .s file is not generated by the compiler, that is not true in our case, input file is a .c and .h one.

I think I owe you some more details. Below assembler, compiler and linker options we use. The module in question here also is using SSP, but not all modules are using it overall in our code.

Hope that helps. Best regards Christophe

# -------------------

# Assembler flags

# -------------------

ASMFLAGS :=             \
  -x assembler-with-cpp \
  -c                    \
  $(DBG)                \
  $(OPTIM)              \
  -Wall                 \
  -mlittle-endian       \
  -mcpu=arcem           \
  -mbarrel-shifter      \
  -mshift-assist        \
  -mmpy-option=0        \
  -mcode-density        \
  -mswap                \
  -mnorm                \
  -fmessage-length=0    \
  -mlong-calls

# -------------------

# SSP

# -------------------

CC_SSP_FLAG+=-fstack-protector-all

# -------------------

# Linker flags

# -------------------

LNKFLAGS :=               \
  -Wl,-Map,$(EXENAME).map \
  -e __start              \
  $(DBG)                  \
  $(OPTIM)                \
  -mmpy-option=0          \
  -mcpu=arcem             \
  -mbarrel-shifter        \
  -mshift-assist          \
  -mcode-density          \
  -mswap                  \
  -mnorm                  \
  -nostartfiles           \
  -mlong-calls            \
  -Wl,--no-check-sections   

# -------------------

# Compiler flags

# -------------------

CCFLAGS :=           \
  -c                 \
  $(DBG)             \
  $(OPTIM)           \
  -Wall              \
  -mlittle-endian    \
  -mcpu=arcem        \
  -mbarrel-shifter   \
  -mshift-assist     \
  -mmpy-option=0     \
  -mcode-density     \
  -mswap             \
  -mnorm             \
  -fno-jump-tables   \
  -mlong-calls       \
  -save-temps=obj

**Comment by coco21** [comment]
Hello,

Update here. Using -mno_sdata helped in our case. Will try to correctly understand what's going on behind the curtain, maybe you can give a quick explanation here?

Thanks much Christophe

**Comment by claziss** [comment]
Please provide the comiler's preprocessed files which shows your problem.

Thank you

**Comment by coco21** [comment]
Not sure we can share any code details here, need to discuss this internally first on how addressing your request.

Thank you

**Comment by coco21** [comment]
Update from our side: -O (aka -O1)  seems to work and already brings a ~30% gain in place which is satisfactory so far. We had to do some small adaptations. Shall we need higher level of optimizations we let you know. I don't think we can share the .i files here, this is all classified information we cannot share here, sorry.

Thanks Christophe

**Comment by claziss** [comment]
It is not needed to share the whole project, but a small test case that shows the issue. You can do it also via official Synopsys channels, hence, you are protected by a NDA.
Anyhow, I do not see this assembler issue, with the latest binutils (the one which you can also download it from binutils website).

**Comment by fbedard** [comment]
Bonjour Christophe,

I'm going to go ahead and close this one based on your last comment.  Feel free to come back and comment further if anything else is needed from our side. 

Thanks.

**Comment by claziss** [comment]
Just for completeness:

The input ASM file:

``` asm
    .cpu EM
    add1    r24,@__MyLinkerSymbol@sda,gp
    add1    r1,@__MyLinkerSymbol@sda,gp
    add_s   r1,r1,@__MyLinkerSymbol@sda
```

Options:
arc-elf32-as t01.s -o t01.o
arc-elf32-objdump -dr t01.o

Result:

``` asm
t01.o:     file format elf32-littlearc


Disassembly of section .text:

00000000 <.text>:
   0:   2614 7698 0000 0000     add1    r24,0,gp
                        4: R_ARC_SDA32_ME       __MyLinkerSymbol
   8:   2614 7681 0000 0000     add1    r1,0,gp
                        c: R_ARC_SDA32_ME       __MyLinkerSymbol
  10:   71c3 0000 0000          add_s   r1,r1,0
                        12: R_ARC_SDA32_ME      __MyLinkerSymbol
```

Assembler version:
arc-elf32-as -version
GNU assembler (ARCompact/ARCv2 ISA elf32 toolchain arc-2016.09-eng015-3-gb9672e3) 2.27.51.20160929
Copyright (C) 2016 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or later.
This program has absolutely no warranty.
This assembler was configured for a target of `arc-elf32' and default,
cpu type`archs'.
