### ISSUE TITLE
lp_count register width

### ISSUE THREAD

**Issue by mrrosen** [foss-for-synopsys-dwc-arc-processors/toolchain#96]
It has been found that on compilations for the Intel Quark SE C1000 Sensor Core (ARC) that while the lp_count register is only 16-bits (ie, LPC_SIZE = 16), the compiler seems to assume the register is always 32-bits (assumes LPC_SIZE = 32). As such, some loops are being incorrectly compiled to use the lp_count register for loops of greater than 65535 iterations long. It would be good if the ARC GCC compiler could account for the parameterizable nature of the width of lp_count register, allowing for proper compilations to not use the register when the loop iterates more than the size of the register can account for.

**Comment by fbedard** [comment]
We will add this to our list of enhancements to consider for future release.  Thanks.

**Comment by claziss** [comment]
Feature added to our 2017.09 branch. Still we need to check if quarkse cpu needs this optimization in.

**Comment by claziss** [comment]
QuarkSE has lp_count width set to 16. Fixed by this patch:

[ARC][QuarkSE] Update
QuarkSE has lp_count width set to 16 bits. Update the compiler to
consider it.

gcc/
2017-07-11  Claudiu Zissulescu  <claziss@synopsys.com>

	* config/arc/arc-arch.h (arc_extras): New enum.
	(arc_cpu_t): Add field extra.
	(arc_cpu_types): Consider the extras.
	* config/arc/arc-cpus.def: Add extras info.
	* config/arc/arc-opts.h (processor_type): Consider extra field.
	* config/arc/arc.c (arc_override_options): Handle extra field.
