### ISSUE TITLE
AS .extAuxRegister with 32bit addresses crash

### ISSUE THREAD

**Issue by yaep** [foss-for-synopsys-dwc-arc-processors/toolchain#98]
When trying to create auxiliary register with 32bit address the arc-elf32-as.exe crashes:
.extAuxRegister myreg, 0x80018000, r|w

this works:
.extAuxRegister myreg, 0x18000, r|w

**Comment by claziss** [comment]
The 32-bit address is interpreted as a negative number, which leads to an error.

**Comment by claziss** [comment]
I'll come back to you with a patch asap.

Thank you for signalizing this.

**Comment by claziss** [comment]
A fix can be found [here](https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/commit/5500683025f05c93b3162e117ee5dfafe513b8bf).

Thank you
