### ISSUE TITLE
Relocation error with offset +/-2

### ISSUE THREAD

**Issue by calandoa** [foss-for-synopsys-dwc-arc-processors/toolchain#99]
Hi,

In some point in my code, I get a crash because of an illegal instruction (ECR=0x020000).

After investigating I found out that the linker was incorrectly calculating a relocation.
I could strip out my code to the bare minimum and still get the error.

I am using (compiled from the github sources):
GNU assembler (ARCompact/ARCv2 ISA elf32 toolchain arc-2016.09-rc1) 2.27.51.20161017

Here is the minimal code (not making any sense but clearly showing what is wrong):

file arc1:
```
	.text
	.global	__start
	.extAuxRegister AUX_DCCM, 0x18, r|w
__start:
	mov_s r0, 0x90000000
	sr r0, [AUX_DCCM]
	mov_s    r0,16
	mov_s    r1,0
	mov_s    r2,1
loop:
	add_s    r0,r0,1
	brlo r0,52,loop
```

file arc2:
```
	.text
	.global func
func:
	breq    r5, 0, bug
	st      r5, [r0, 24]
	;nop_s                    ; <- THIS IS MY WORKAROUND
bug:
	st      r3, [gp, mysda@sda]

.section .sdata, "ax"
mysda:
```

I compile with:
```
arc-elf32-as -c -mcpu=arcem -mcode-density -o arc1.o arc1.s
arc-elf32-as -c -mcpu=arcem -mcode-density -o arc2.o arc2.s
arc-elf32-ld -o out.elf arc1.o arc2.o
```

Here is the object file:
`arc-elf32-objdump -d arc2.o | grep -B 4 -A 1 bug\>:
`
```
00000000 <func>:
   0:   0d09 0010               breq.nt r5,0,8 <bug>
   4:   1818 0140               st      r5,[r0,24]
00000008 <bug>:
   8:   1a00 30c0               st      r3,[gp]
```
In the object file, everything looks fine. The `breq` jump to `bug` is using the right offset (but maybe the decoding is wrong).

The linked elf is:
`arc-elf32-objdump -d out.elf | grep -B 4 -A 1 bug\>:
`
```
00000116 <func>:
 116:   0d09 0010               breq.nt r5,0,11c <func+0x6>
 11a:   1818 0140               st      r5,[r0,24]
0000011e <bug>:
 11e:   1a00 b0c0               st      r3,[gp,-256]
```
Here the bug is showing up: the jump is targeting the address 2 bytes before `bug` (though binary code is the same). Note that I have not run this code, but in my original program, I can correct the problem by inserting a `nop_s` just before.

I also see that there is an incorrect `-256` data offset in the last instruction.

If you remove some instructions in the file arc1.s, the bad offset may disappear... and actually in my real code, the problem seems to appear or disappear randomly depending on unrelated modifications.

This is a big problem for me, even if I have a local workaround, as I do not want to put `nop_s` everywhere in my code to prevent all possible problems. The `nop_s` is also not correcting the `-256` problem above, though I have not seen this yet in my program.

**Comment by claziss** [comment]
Hi,

From PRM, on brcc instruction:

> The branch target is computed as the sum of the branch’s 32-bit word-aligned PC plus the 16-bit  halfword aligned displacement value given by the signed 9-bit literal operand (rd).

Thus, you need to align your branch targets by using .align pseudo-op:
```asm
	.text
	.global	__start
	.extAuxRegister AUX_DCCM, 0x18, r|w
	.align 4
__start:
	mov_s r0, 0x90000000
	sr r0, [AUX_DCCM]
	mov_s    r0,16
	mov_s    r1,0
	mov_s    r2,1
	.align 4
loop:
	add_s    r0,r0,1
	brlo r0,52,loop
```
and
```asm
	.text
	.global func
	.align 4
func:
	breq    r5, 0, bug
	st      r5, [r0, 24]
	.align 4
bug:
	st      r3, [gp, mysda@sda]
```

Thanks

**Comment by calandoa** [comment]
Thanks for your explanation, I understand now better  what is going on.

However, I still think this is a problem in the tools: not in the linker, but actually in the assembler.

Here the assembler is computing the displacement offset based on the address and its 32bit alignement 
of the BRxx instruction. But it is assuming that the 32bit alignement in the object file will be the same that the one after linking. This assumption is false.

The assembler should here force the alignment of the current file to be on 32bit when it is processing this kind of instruction ; or issue a warning if no ".align 4" was found, saying it cannot compute the offset in a reliable way.

I am currently compiling code working fine on MetaWare, and I guess this is the default behavior on this tool as there is no "align" in the source file.

**Comment by claziss** [comment]
Thank you for the suggestion, I'll see what can be done with the respect to that warning.

**Comment by calandoa** [comment]
While trying to find for a workaround, the problem is actually simpler than what I expected:
the assembler is not setting any alignment for .text in object files (`2**0` as reported by objdump -h). 
This is not the behavior I would expect (e.g. arc-elf32-gcc or arm-xxx-as are setting it to `2**2`).

For instance, adding one ".byte" in some .text section will force the linker to totally unalign the following code, making it impossible to run.
